begin;
select plan(45);

select has_table('public','households','households are first-class CRM records');
select has_table('public','household_members','household membership is persisted');
select has_table('public','students','students reuse person identity');
select has_table('public','student_guardian_relationships','guardian relationships are explicit');
select has_table('public','student_academic_records','academic history is effective-dated');
select has_table('public','progression_batches','progression batches are durable');
select has_table('public','progression_batch_items','progression preview items are durable');
select has_table('public','leads','leads are first-class');
select has_table('public','lead_conversions','lead conversion evidence is durable');
select has_table('public','privacy_requests','data-subject requests are durable');
select has_table('public','import_mapping_profiles','import mappings can be reused');
select has_table('public','ai_suggestion_runs','suggestion runs preserve versions');
select has_table('public','ai_suggestions','suggestions preserve evidence');
select has_table('public','ai_suggestion_decisions','human decisions are immutable records');
select ok((select relrowsecurity from pg_class where oid='public.students'::regclass),'students enforce RLS');
select ok((select relrowsecurity from pg_class where oid='public.privacy_requests'::regclass),'privacy requests enforce RLS');
select ok((select relrowsecurity from pg_class where oid='public.ai_suggestions'::regclass),'suggestions enforce RLS');
select ok(has_function_privilege('authenticated','public.product_catalog_snapshot()','EXECUTE'),'staff can use exact product aggregates');
select ok(not has_function_privilege('anon','public.product_catalog_snapshot()','EXECUTE'),'anonymous users cannot read product aggregates');
select ok(has_function_privilege('authenticated','public.preview_student_progression(text,text,text)','EXECUTE'),'leaders can invoke progression preview');
select ok(not has_function_privilege('anon','public.apply_student_progression(uuid,text)','EXECUTE'),'anonymous users cannot apply progression');
select ok(has_function_privilege('authenticated','public.convert_lead_to_opportunity(uuid,text,text,numeric,text,text)','EXECUTE'),'sales can use guarded lead conversion');
select ok(has_function_privilege('authenticated','public.generate_rule_suggestions()','EXECUTE'),'staff can run the local rules engine');
select ok(not has_function_privilege('anon','public.decide_ai_suggestion(uuid,text,text,text,text,boolean,text)','EXECUTE'),'anonymous users cannot decide suggestions');
select ok(has_function_privilege('authenticated','public.manage_privacy_request(uuid,text,text,text)','EXECUTE'),'privacy leaders can invoke the guarded request workflow');
select ok(not has_function_privilege('anon','public.manage_privacy_request(uuid,text,text,text)','EXECUTE'),'anonymous users cannot manage privacy requests');
select ok(has_function_privilege('authenticated','public.list_students_page(text,integer,integer,text)','EXECUTE'),'student search uses an exact server-side page');
select ok(not has_function_privilege('anon','public.update_student_record(uuid,timestamptz,text,text,uuid,text)','EXECUTE'),'anonymous users cannot update student records');
select ok(has_function_privilege('authenticated','public.repair_import_row(uuid,jsonb)','EXECUTE'),'staff can repair their invalid import rows');
select ok(not has_function_privilege('anon','public.repair_import_row(uuid,jsonb)','EXECUTE'),'anonymous users cannot repair import rows');
select ok(pg_get_functiondef('public.current_crm_role()'::regprocedure) like '%SALES_DIRECTOR%','director sessions are included in the privileged MFA gate');
select ok(pg_get_functiondef('public.current_crm_role()'::regprocedure) like '%SALES_MANAGER%','manager sessions are included in the privileged MFA gate');
select ok(pg_get_functiondef('public.product_catalog_snapshot()'::regprocedure) like '%group by pay.currency%','product revenue remains separated by currency');
select ok(pg_get_functiondef('public.apply_student_progression(uuid,text)'::regprocedure) like '%idempotency_key%','progression application verifies its idempotency key');
select ok(pg_get_functiondef('public.convert_lead_to_opportunity(uuid,text,text,numeric,text,text)'::regprocedure) like '%lead_conversions%','lead conversion records its evidence and idempotency');
select ok(pg_get_functiondef('public.generate_rule_suggestions()'::regprocedure) like '%external_data_sent%','rule suggestions record whether external data was sent');
select ok(pg_get_functiondef('public.decide_ai_suggestion(uuid,text,text,text,text,boolean,text)'::regprocedure) like '%create_task%','task creation requires an explicit human decision flag');
select ok(pg_get_functiondef('public.manage_privacy_request(uuid,text,text,text)'::regprocedure) like '%privacy_second_reviewer_required%','high-risk privacy actions enforce dual review');
select ok(pg_get_functiondef('public.manage_privacy_request(uuid,text,text,text)'::regprocedure) like '%WAITING_APPROVAL%','privacy export and deletion create an asynchronous approval task');
select ok(pg_get_functiondef('public.create_crm_export_approval(text,text,text,text,text,text,text)'::regprocedure) like '%students%','report approvals include education resources');
select ok((select allowed_mime_types @> array['application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] from storage.buckets where id='crm-exports'),'private export storage accepts PDF and XLSX artifacts');
select ok(pg_get_functiondef('public.list_students_page(text,integer,integer,text)'::regprocedure) like '%count(*) over()%','student pagination carries an exact filtered count');
select ok(pg_get_functiondef('public.update_student_record(uuid,timestamp with time zone,text,text,uuid,text)'::regprocedure) like '%education_version_conflict%','student updates use optimistic concurrency');
select ok(pg_get_functiondef('public.update_household_record(uuid,timestamp with time zone,text,text,text,text)'::regprocedure) like '%education_version_conflict%','household updates use optimistic concurrency');
select ok(pg_get_functiondef('public.repair_import_row(uuid,jsonb)'::regprocedure) like '%import_row_not_repairable%','row repair is restricted to failed validation rows');

select * from finish();
rollback;
