project_id = "lumina-crm"

[api]
enabled = true
port = 56321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 56322
major_version = 17

[studio]
enabled = true
port = 56323

[local_smtp]
enabled = true
port = 56324

[auth]
enabled = true
site_url = "http://localhost:3200"
additional_redirect_urls = ["http://localhost:3200/reset-password"]
enable_signup = false
minimum_password_length = 10

[auth.email]
enable_signup = false
enable_confirmations = true

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
file_size_limit = "10MiB"

[analytics]
enabled = false
