import { NextResponse } from "next/server";
import { z } from "zod";
import { ApiError,apiRoute,requireApiCapability } from "@/lib/api";
import { mutationIsTrusted } from "@/lib/request-security";
import { communicationRecipient,completeCommunication,createCommunicationThread,failCommunication,loadCommunications,queueCommunicationMessage,recordInboundCommunication,retryCommunicationMessage } from "@/lib/v220-repository";

const schema=z.discriminatedUnion("operation",[
  z.object({operation:z.literal("thread"),contactId:z.uuid(),subject:z.string().trim().min(2).max(200),channel:z.literal("EMAIL"),purpose:z.enum(["SERVICE","TRANSACTIONAL","EVENT","MARKETING"])}),
  z.object({operation:z.literal("send"),threadId:z.uuid(),body:z.string().trim().min(1).max(10000),idempotencyKey:z.string().trim().min(8).max(160)}),
  z.object({operation:z.literal("inbound"),threadId:z.uuid(),body:z.string().trim().min(1).max(10000),idempotencyKey:z.string().trim().min(8).max(160)}),
  z.object({operation:z.literal("retry"),messageId:z.uuid()}),
]);
async function get(request:Request){await requireApiCapability("messages.view");const query=new URL(request.url).searchParams.get("q")?.trim().slice(0,160)??"";return NextResponse.json({items:await loadCommunications(query)});}
async function deliver(message:{id:string;threadId:string;body:string}){try{const recipient=await communicationRecipient(message.threadId);const url=process.env.EMAIL_DELIVERY_WEBHOOK_URL?.trim();if(!url||!recipient?.contacts?.email)throw new Error(url?"RECIPIENT_EMAIL_UNAVAILABLE":"DELIVERY_NOT_CONFIGURED");const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...(process.env.EMAIL_DELIVERY_WEBHOOK_TOKEN?{authorization:`Bearer ${process.env.EMAIL_DELIVERY_WEBHOOK_TOKEN}`}:{})},body:JSON.stringify({id:message.id,to:recipient.contacts.email,template:"communication-message",payload:{subject:recipient.subject,body:message.body,recipientName:recipient.contacts.name_en||recipient.contacts.name_zh}}),signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`DELIVERY_${response.status}`);const receipt=await response.json().catch(()=>({})) as {id?:string;messageId?:string};await completeCommunication(message.id,String(receipt.id??receipt.messageId??""));}catch(error){const failure=error instanceof Error?error.message:"DELIVERY_FAILED";await failCommunication(message.id,failure);throw new ApiError(failure==="DELIVERY_NOT_CONFIGURED"?"COMMUNICATION_DELIVERY_NOT_CONFIGURED":"COMMUNICATION_DELIVERY_FAILED",failure==="DELIVERY_NOT_CONFIGURED"?503:502);}}
async function post(request:Request){if(!mutationIsTrusted(request))throw new ApiError("UNTRUSTED_ORIGIN",403);await requireApiCapability("messages.manage");const parsed=schema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)throw new ApiError("INVALID_COMMUNICATION_INPUT",400,"INVALID_COMMUNICATION_INPUT",{field:String(parsed.error.issues[0]?.path[0]??"form")});if(parsed.data.operation==="thread")await createCommunicationThread(parsed.data);else if(parsed.data.operation==="inbound")await recordInboundCommunication(parsed.data.threadId,parsed.data.body,parsed.data.idempotencyKey);else if(parsed.data.operation==="retry"){const message=await retryCommunicationMessage(parsed.data.messageId);await deliver({id:message.id,threadId:message.thread_id,body:message.body});}else{const message=await queueCommunicationMessage(parsed.data.threadId,parsed.data.body,parsed.data.idempotencyKey);await deliver({id:message.id,threadId:parsed.data.threadId,body:parsed.data.body});}return NextResponse.json({items:await loadCommunications()});}
export const GET=apiRoute(get,"COMMUNICATION_LOAD_FAILED");
export const POST=apiRoute(post,"COMMUNICATION_OPERATION_FAILED");
