import {NextResponse} from "next/server";
import {z} from "zod";
import {ApiError,apiRoute,requireApiCapability} from "@/lib/api";
import {mutationIsTrusted} from "@/lib/request-security";
import {workflowTemplateSaveSchema,workflowTemplateActionSchema,workflowTemplateStatuses} from "@/lib/workflow-input";
import {listWorkflowTemplates,getWorkflowTemplate,saveWorkflowTemplate,changeWorkflowTemplate} from "@/lib/workflow-template-repository";
import {workflowApiError} from "@/lib/workflow-api-error";
async function get(request:Request){await requireApiCapability("education.view");const params=new URL(request.url).searchParams;try{if(params.has("id")){const id=z.uuid().safeParse(params.get("id"));if(!id.success)throw new ApiError("WORKFLOW_INPUT_INVALID",400);const item=await getWorkflowTemplate(id.data);if(!item)throw new ApiError("WORKFLOW_NOT_FOUND",404);return NextResponse.json({item});}const parsed=z.object({page:z.coerce.number().int().min(1).max(100000).default(1),status:z.enum(workflowTemplateStatuses).optional(),productId:z.uuid().optional()}).safeParse(Object.fromEntries(params));if(!parsed.success)throw new ApiError("WORKFLOW_INPUT_INVALID",400);return NextResponse.json(await listWorkflowTemplates(parsed.data));}catch(error){return workflowApiError(error);}}
async function save(request:Request){if(!mutationIsTrusted(request))throw new ApiError("UNTRUSTED_ORIGIN",403);await requireApiCapability("catalog.manage");const body=await request.json().catch(()=>({}));try{if(body.operation){const parsed=workflowTemplateActionSchema.safeParse(body);if(!parsed.success)throw new ApiError("WORKFLOW_INPUT_INVALID",400);return NextResponse.json({item:await changeWorkflowTemplate(parsed.data)});}const parsed=workflowTemplateSaveSchema.safeParse(body);if(!parsed.success||request.method==="PATCH"&&parsed.data.expectedRevision===null)throw new ApiError("WORKFLOW_INPUT_INVALID",400);return NextResponse.json({item:await saveWorkflowTemplate(parsed.data)});}catch(error){return workflowApiError(error);}}
export const GET=apiRoute(get,"WORKFLOW_LOAD_FAILED");export const POST=apiRoute(save,"WORKFLOW_SAVE_FAILED");export const PATCH=apiRoute(save,"WORKFLOW_SAVE_FAILED");
