import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PDFDocument,StandardFonts,PDFName,PDFHexString,PDFNumber} from 'pdf-lib';
import {zipDocx,docxMime,digest} from '../lib/contract-document-engine.mjs';
import {docxChunks,uploadFormat,normalizeCandidate,extractCandidates,compareCandidate,pdfChunks,safeUploadName} from '../lib/contract-extraction-engine.mjs';
import {parseContractEvidence} from '../lib/contract-extraction-parser.mjs';
import {boundedUploadForm} from '../lib/contract-upload-input.mjs';
export function syntheticDocx(lines,extra=[]){const xml=lines.map(t=>`<w:p><w:r><w:t>${t.replaceAll('&','&amp;').replaceAll('<','&lt;')}</w:t></w:r></w:p>`).join('');return zipDocx([{name:'[Content_Types].xml',data:Buffer.from('<Types/>')},{name:'word/document.xml',data:Buffer.from(`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${xml}</w:body></w:document>`)},...extra]);}
const fields=[{key:'contract.amount',type:'money',category:'CANONICAL'},{key:'contract.currency',type:'currency',category:'CANONICAL'},{key:'buyer.signing_name',type:'text',category:'USER_CONFIRMED',sensitive:true},{key:'contract.signing_date',type:'date',category:'USER_CONFIRMED'},{key:'guardian.required',type:'boolean',category:'USER_CONFIRMED'},{key:'commission.eligibility_clause',type:'text',category:'UNSUPPORTED'}];
test('DOCX real package extraction preserves location and raw versus normalized evidence',()=>{const b=syntheticDocx(['合同金额：人民币 15,980.00','币种：RMB','购买人：合成甲方','签署日期：2026年10月05日','是否需要监护人：是']);const chunks=docxChunks(b),c=extractCandidates(chunks,fields,'CUSTOMER_CONTRACT');assert.equal(c[0].normalizedValue,'15980.00');assert.equal(c[0].rawValue,'人民币 15,980.00');assert.equal(c[0].sourceLocation.part,'word/document.xml');assert.equal(c[0].sourceLocation.page,undefined);assert.equal(c[1].normalizedValue,'CNY');assert.equal(c[2].confirmationTarget,'DOCUMENT_ONLY');assert.equal(c[3].normalizedValue,'2026-10-05');assert.equal(c[4].normalizedValue,true);assert.equal(compareCandidate(c[0],'20000.00'),'CONFLICT');assert.equal(compareCandidate(c[0],'15980.00'),'MATCH');assert.equal(compareCandidate(c[5],null),'UNSUPPORTED');assert.equal(digest(b),digest(b));});
test('ambiguity remains explicit and names never resolve identities',()=>{const c=extractCandidates(docxChunks(syntheticDocx(['合同金额：20,000','合同金额：15,980','签署日期：01/02/2026','购买人：ZHANG SAN'])),fields,'CUSTOMER_CONTRACT');assert.equal(c[0].confidenceState,'AMBIGUOUS');assert.equal(c.find(f=>f.fieldKey==='contract.signing_date').validationState,'AMBIGUOUS');assert.equal(normalizeCandidate('2026-99-99',{type:'date'}).state,'INVALID');assert.equal(normalizeCandidate('2026-02-30',{type:'date'}).state,'INVALID');assert.equal(c.find(f=>f.fieldKey==='buyer.signing_name').rawValue,'ZHANG SAN');});
test('cross-run tables headers and footers carry real structure without fake pages',()=>{const b=zipDocx([{name:'[Content_Types].xml',data:Buffer.from('<Types/>')},{name:'word/document.xml',data:Buffer.from('<w:document><w:body><w:tbl><w:tr><w:tc><w:p><w:r><w:t>合同金</w:t></w:r><w:r><w:t>额：20000</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:body></w:document>')},{name:'word/header1.xml',data:Buffer.from('<w:hdr><w:p><w:r><w:t>币种：CNY</w:t></w:r></w:p></w:hdr>')},{name:'word/footer1.xml',data:Buffer.from('<w:ftr><w:p><w:r><w:t>购买人：合成</w:t></w:r></w:p></w:ftr>')}]);const c=docxChunks(b);assert.equal(c[0].location.cell,0);assert.equal(c.length,3);assert.equal(extractCandidates(c,fields,'CUSTOMER_CONTRACT')[0].normalizedValue,'20000.00');});
test('allowlist magic size traversal malformed XML and external links fail safely',()=>{assert.equal(uploadFormat(syntheticDocx(['test']),'t.docx',docxMime),'DOCX');assert.throws(()=>uploadFormat(Buffer.from('%PDF-1.7'),'t.docx',docxMime),/UPLOAD_FORMAT/);assert.throws(()=>uploadFormat(Buffer.alloc(8_000_001),'t.pdf','application/pdf'),/UPLOAD_SIZE/);assert.throws(()=>docxChunks(Buffer.from('broken')),/DOCX/);assert.throws(()=>docxChunks(syntheticDocx(['test'],[{name:'word/_rels/document.xml.rels',data:Buffer.from('<Relationships><Relationship TargetMode="External" Target="https://example.test"/></Relationships>')}])) ,/EXTERNAL/);assert.ok(!safeUploadName('../../signed\u0000.pdf').includes('/'));});
test('actual text PDF yields page evidence; image-only PDF requires OCR without fallback',async()=>{const doc=await PDFDocument.create(),page=doc.addPage(),font=await doc.embedFont(StandardFonts.Helvetica);page.drawText('Contract amount: 15,980.00',{font,x:30,y:500});const bytes=await doc.save();const chunks=await pdfChunks(bytes);assert.equal(chunks[0].location.page,1);assert.equal(extractCandidates(chunks,fields,'CUSTOMER_CONTRACT')[0].normalizedValue,'15980.00');const blank=await PDFDocument.create();blank.addPage();await assert.rejects(pdfChunks(await blank.save()),/OCR_REQUIRED_NOT_SUPPORTED/);await assert.rejects(pdfChunks(Buffer.from('%PDF-1.7 invalid')),/PDF_INVALID/);});
test('bounded isolated production parser handles real masters and Word text PDF',async()=>{const catalog=JSON.parse(await readFile('templates/contracts/catalog.json','utf8'));for(const v of catalog.versions){const b=await readFile(v.template_path);const r=await parseContractEvidence(b,'DOCX',v.fields,v.contract_type==='CHANNEL_RECRUITMENT_AGREEMENT'?'CHANNEL_AGREEMENT_VERSION':'CUSTOMER_CONTRACT');assert.equal(r.extractorVersion,'LABELS_V1');assert.ok(r.chunks.length>0);assert.ok(r.candidates.length>=v.fields.length);}const pdf=await readFile('work/v324-phase2/render-qa/pages/student-generated/document.pdf').catch(()=>null);if(pdf){const r=await parseContractEvidence(pdf,'PDF',fields,'CUSTOMER_CONTRACT');assert.ok(r.chunks.some(c=>c.location.page>1));}});
test('multipart streaming limit does not trust Content-Length',async()=>{const request=new Request('http://localhost/upload',{method:'POST',headers:{'content-type':'multipart/form-data; boundary=test'},body:Buffer.alloc(8_200_001)});await assert.rejects(boundedUploadForm(request),/UPLOAD_SIZE_INVALID/);});
test('password-protected PDF is rejected without accepting or storing a password',async()=>{const doc=await PDFDocument.create();doc.addPage();const encrypt=doc.context.obj({Filter:PDFName.of('Standard'),V:PDFNumber.of(1),R:PDFNumber.of(2),Length:PDFNumber.of(40),O:PDFHexString.of('12'.repeat(32)),U:PDFHexString.of('34'.repeat(32)),P:PDFNumber.of(-4)});doc.context.trailerInfo.Encrypt=doc.context.register(encrypt);doc.context.trailerInfo.ID=doc.context.obj([PDFHexString.of('56'.repeat(16)),PDFHexString.of('56'.repeat(16))]);await assert.rejects(pdfChunks(await doc.save({useObjectStreams:false})),/PDF_PASSWORD_UNSUPPORTED/);});
test('invalid grouping and inferred identity equivalence are never silently accepted',()=>{assert.equal(normalizeCandidate('1,59,80',{type:'money'}).state,'AMBIGUOUS');assert.equal(compareCandidate({confirmationTarget:'CANONICAL_READ_ONLY',validationState:'VALID',confidenceState:'EXACT',type:'text',normalizedValue:'ZHANG SAN'},'张三'),'CONFLICT');assert.equal(compareCandidate({confirmationTarget:'CANONICAL_READ_ONLY',validationState:'VALID',confidenceState:'EXACT',type:'money',normalizedValue:'15980.00'},'15980.0000'),'MATCH');});
test('macro payloads and invalid XML entities are rejected; text/page limits are bounded',async()=>{assert.throws(()=>docxChunks(syntheticDocx(['safe'],[{name:'word/vbaProject.bin',data:Buffer.from('macro')}])),/MACRO_UNSUPPORTED/);const b=syntheticDocx(['safe']);const entries=(await import('../lib/contract-document-engine.mjs')).unzipDocx(b);entries.find(e=>e.name==='word/document.xml').data=Buffer.from('<w:document><w:p><w:t>&unknown;</w:t></w:p></w:document>');assert.throws(()=>docxChunks(zipDocx(entries)),/XML_INVALID/);assert.throws(()=>docxChunks(syntheticDocx(['X'.repeat(300001)])),/EXTRACTION_LIMIT/);const doc=await PDFDocument.create();for(let i=0;i<101;i++)doc.addPage();await assert.rejects(pdfChunks(await doc.save()),/PDF_PAGE_LIMIT/);});
test('a labeled table cell resolves only its adjacent value cell with both locations',()=>{const loc={part:'word/document.xml',table:0,row:0},chunks=[{index:0,location:{...loc,cell:0},text:'合同金额'},{index:1,location:{...loc,cell:1},text:'人民币 15,980.00'}];const c=extractCandidates(chunks,fields,'CUSTOMER_CONTRACT')[0];assert.equal(c.extractionMethod,'STRUCTURED_TABLE_MATCH');assert.equal(c.normalizedValue,'15980.00');assert.equal(c.sourceLocation.cell,1);assert.equal(c.sourceLocation.labelChunk,0);assert.ok(c.sourceExcerpt.includes('合同金额'));});

test('XML predefined entities are case-sensitive and hexadecimal digits remain valid',()=>{const packageWith=entity=>zipDocx([{name:'[Content_Types].xml',data:Buffer.from('<Types/>')},{name:'word/document.xml',data:Buffer.from(`<w:document><w:p><w:t>Buyer: ${entity}</w:t></w:p></w:document>`)}]);assert.throws(()=>docxChunks(packageWith('&AMP;')),/DOCX_XML_INVALID/);assert.equal(docxChunks(packageWith('A &amp; B &#x4E2D;'))[0].text,'Buyer: A & B 中');});
