import { z } from "zod";
import { createScimDirectoryUser, listScimDirectoryUsers, scimEnterpriseSchema, scimUserSchema, toScimUser } from "@/lib/scim";
import { requireScim, scimFailure, scimJson } from "@/lib/scim-http";

const roles=["SALES_DIRECTOR","SALES_MANAGER","SALES_SPECIALIST","SALES_SUPPORT"] as const;
const createSchema=z.object({schemas:z.array(z.string()).refine(items=>items.includes(scimUserSchema)),externalId:z.string().trim().min(1).max(255),userName:z.email().max(320),displayName:z.string().trim().max(160).optional(),name:z.object({formatted:z.string().trim().max(160).optional(),givenName:z.string().trim().max(80).optional(),familyName:z.string().trim().max(80).optional()}).optional(),active:z.boolean().default(true),[scimEnterpriseSchema]:z.object({displayNameZh:z.string().trim().max(80).default(""),displayNameEn:z.string().trim().max(80).optional(),role:z.enum(roles).default("SALES_SUPPORT"),team:z.string().trim().min(1).max(80).default("Enterprise directory")}).optional()});

export async function GET(request:Request){try{await requireScim(request);const url=new URL(request.url);const startIndex=Math.max(1,Number(url.searchParams.get("startIndex")??1));const count=Math.max(1,Math.min(100,Number(url.searchParams.get("count")??20)));if(!Number.isInteger(startIndex)||!Number.isInteger(count))return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"400",detail:"Invalid pagination"},400);const {rows,total}=await listScimDirectoryUsers(url.searchParams.get("filter")??undefined,startIndex,count);const base=url.origin;return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:ListResponse"],totalResults:total,startIndex,itemsPerPage:rows.length,Resources:rows.map(row=>toScimUser(row,base))});}catch(error){return scimFailure(error);}}

export async function POST(request:Request){try{await requireScim(request);const parsed=createSchema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"400",scimType:"invalidValue",detail:parsed.error.issues[0]?.message},400);const extension=parsed.data[scimEnterpriseSchema];const english=extension?.displayNameEn??parsed.data.displayName??parsed.data.name?.formatted??[parsed.data.name?.givenName,parsed.data.name?.familyName].filter(Boolean).join(" ")??parsed.data.userName.split("@")[0];const row=await createScimDirectoryUser({externalId:parsed.data.externalId,userName:parsed.data.userName,displayNameZh:extension?.displayNameZh??"",displayNameEn:english||parsed.data.userName.split("@")[0],role:extension?.role??"SALES_SUPPORT",team:extension?.team??"Enterprise directory",active:parsed.data.active});const resource=toScimUser(row,new URL(request.url).origin);return scimJson(resource,201,{location:resource.meta.location,etag:resource.meta.version});}catch(error){return scimFailure(error);}}
