"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {apiFetch} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {interviewResults,visaResults} from "@/lib/admission-milestone-input";
import type {MilestoneRecord,MilestonePage,MilestoneHistory,AdmissionsTimelinePage} from "@/lib/admission-milestone-repository";
import {AdmissionMilestoneEditor} from "./admission-milestone-editor";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {InlineMessage,StatusBadge} from "./ui";
export function AdmissionMilestonesSection({enrollmentId,studentId,applicationId,ownerId,canEdit,onLock,onChanged}:{enrollmentId:string;studentId:string;applicationId?:string;ownerId?:string|null;canEdit:boolean;onLock:(locked:boolean)=>void;onChanged?:()=>void}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),[page,setPage]=useState(1),[data,setData]=useState<MilestonePage>({items:[],total:0,page:1,pageSize:20}),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[editing,setEditing]=useState<{record?:MilestoneRecord}|null>(null),[locked,setLocked]=useState(false),[historyId,setHistoryId]=useState<string|null>(null),[history,setHistory]=useState<MilestoneHistory[]>([]),[historyPage,setHistoryPage]=useState(1);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{if(historyId){const result=await apiFetch<{items:MilestoneHistory[]}>(`/api/admission-milestones?id=${historyId}&resource=history&page=${historyPage}`,{signal});if(!signal?.aborted)setHistory(result.items);}else{const result=await apiFetch<MilestonePage>(`/api/admission-milestones?enrollmentId=${enrollmentId}${applicationId?`&applicationId=${applicationId}`:""}&page=${page}`,{signal});if(!signal?.aborted)setData(result);}}catch(error){if(!signal?.aborted){setError(presentApiError(error,t,"milestones.loadFailed").message);throw error;}}finally{if(!signal?.aborted)setLoading(false);}},[enrollmentId,applicationId,page,historyId,historyPage,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal).catch(()=>{}),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const lock=(value:boolean)=>{setLocked(value);onLock(value);};
 const outcome=(row:MilestoneRecord)=>{const value=row.outcome??row.metadata.result;return typeof value==="string"?([...interviewResults,...visaResults] as string[]).includes(value)?t(`milestones.result.${value}`):value:"—";};
 return <section className="detail-section" aria-label={t("milestones.title")}><h3>{t(historyId?"milestones.history":"milestones.title")}</h3>
 {notice&&<InlineMessage type="success">{notice}</InlineMessage>}{error&&<InlineMessage type="error">{error}<button type="button" className="secondary-button" onClick={()=>void load().catch(()=>{})}>{t("common.retry")}</button></InlineMessage>}{loading&&<p role="status">{t("common.loading")}</p>}
 {editing?<AdmissionMilestoneEditor key={editing.record?.id??"new"} enrollmentId={enrollmentId} studentId={studentId} applicationId={applicationId} defaultOwner={ownerId} record={editing.record} onLock={lock} onCancel={()=>setEditing(null)} onSaved={async()=>{setEditing(null);setNotice(t("milestones.saved"));onChanged?.();try{await load();}catch{setNotice(t("milestones.refreshFailed"));}}}/>:historyId?<><button type="button" className="secondary-button" onClick={()=>setHistoryId(null)}>{t("milestones.title")}</button><div className="detail-record-list">{!error&&history.map(row=><article key={row.id}><div><b>{row.from_status?t(`milestones.status.${row.from_status}`):t("enrollments.created")} → {t(`milestones.status.${row.to_status}`)}</b><small>{formatDate(row.changed_at,{includeTime:true})} · {t("enrollments.revision",{revision:row.milestone_revision})}</small>{row.reason&&<p>{row.reason}</p>}</div></article>)}</div><div className="detail-actions"><button className="secondary-button" disabled={loading||historyPage===1} onClick={()=>setHistoryPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{historyPage}</span><button className="secondary-button" disabled={loading||history.length<50} onClick={()=>setHistoryPage(value=>value+1)}>{t("cohorts.next")}</button></div></>:<>
 {canEdit&&<button type="button" className="secondary-button" onClick={()=>{setNotice("");setEditing({});}}>{t("milestones.create")}</button>}
 {!error&&!loading&&!data.items.length&&<p>{t("milestones.empty")}</p>}
 <div className="detail-record-list">{!error&&data.items.map(row=><article key={row.id}><div><b>{t(`milestones.type.${row.milestone_type}`)} · {row.sequence}</b><p><StatusBadge tone={row.status==="COMPLETED"?"green":row.status==="BLOCKED"?"red":"gray"}>{t(`milestones.status.${row.status}`)}</StatusBadge> {row.overdue&&<StatusBadge tone="amber">{t("milestones.overdue")}</StatusBadge>}</p><small>{t("milestones.owner")}: {(locale==="en"?row.owner_name_en:row.owner_name_zh)||"—"} · {t("milestones.outcome")}: {outcome(row)}</small>{(["due_at","scheduled_at","completed_at"] as const).map(key=><small key={key}>{t(`milestones.${key}`)}: {row[key]?formatDate(row[key],{includeTime:true}):"—"}</small>)}{row.application_id?<Link href={`/applications?focus=${row.application_id}`}>{t("applications.title")}</Link>:<small>{t("milestones.enrollmentContext")}</small>}</div><div className="detail-actions">{row.can_edit&&<button type="button" className="secondary-button" disabled={locked} onClick={()=>{setNotice("");setEditing({record:row});}}>{t("milestones.edit")}</button>}<button type="button" className="secondary-button" onClick={()=>{setHistoryId(row.id);setHistoryPage(1);setHistory([]);}}>{t("milestones.history")}</button></div></article>)}</div>
 <div className="detail-actions"><button className="secondary-button" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button className="secondary-button" disabled={loading||page*20>=data.total} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div></>}
 </section>;
}
export function AdmissionsTimeline({enrollmentId,refreshToken}:{enrollmentId:string;refreshToken:number}){
 const {t}=useI18n(),{formatDate}=useUserPreferences(),[page,setPage]=useState(1),[data,setData]=useState<AdmissionsTimelinePage>({items:[],page:1,pageSize:20,total:0}),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const result=await apiFetch<AdmissionsTimelinePage>(`/api/enrollments/${enrollmentId}/admissions-timeline?page=${page}`,{signal});if(!signal?.aborted)setData(result);}catch(error){if(!signal?.aborted)setError(presentApiError(error,t,"milestones.loadFailed").message);}finally{if(!signal?.aborted)setLoading(false);}},[enrollmentId,page,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load,refreshToken]);
 return <section className="detail-section" aria-label={t("milestones.timeline")}><h3>{t("milestones.timeline")}</h3><p className="field-help">{t("milestones.timelineHelp")}</p>{error&&<InlineMessage type="error">{error}<button className="secondary-button" onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>}{loading&&<p role="status">{t("common.loading")}</p>}{!error&&!loading&&!data.items.length&&<p>{t("milestones.noTimeline")}</p>}<div className="detail-record-list">{!error&&data.items.map(row=><article key={row.id}><div><StatusBadge tone={row.sourceType==="APPLICATION"?"blue":"gray"}>{t(`milestones.source.${row.sourceType}`)}</StatusBadge><p><b>{row.sourceType==="APPLICATION"?t(`milestones.event.${row.eventType}`):row.sourceType==="WORKFLOW"?t(`workflow.event.${row.eventType}`):t(`milestones.type.${row.milestoneType}`)}</b></p><small>{formatDate(row.eventAt,{includeTime:true})} · {t(`${row.sourceType==="APPLICATION"?"applications":row.sourceType==="WORKFLOW"?"workflow":"milestones"}.status.${row.status}`)}</small>{row.outcome&&<p>{row.sourceType==="APPLICATION"?t(`applications.decision.${row.outcome}`):([...interviewResults,...visaResults] as string[]).includes(row.outcome)?t(`milestones.result.${row.outcome}`):row.outcome}</p>}{row.applicationId&&<Link href={`/applications?focus=${row.applicationId}`}>{t("applications.title")}</Link>}</div></article>)}</div><div className="detail-actions"><button className="secondary-button" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button className="secondary-button" disabled={loading||page*20>=data.total} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div></section>;
}
