"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, ChevronRight, FileCheck2, KeyRound, ShieldAlert, ShieldCheck, Users } from "lucide-react";
import { EmptyState } from "@/components/data-state";
import { useI18n } from "@/components/i18n-provider";
import { InlineMessage, Pagination, ProgressBar, SearchField, StatusBadge } from "@/components/ui";
import type { AdminAuditEvent, AdminAuditPage, AdminDashboardData } from "@/lib/admin-dashboard-repository";

function Metric({icon:Icon,tone,value,label,note,href}:{icon:React.ElementType;tone:string;value:string;label:string;note:string;href:string}){return <Link className="admin-metric" href={href}><span className={tone}><Icon size={20}/></span><div><b>{value}</b><span>{label}</span><small>{note}</small></div><ChevronRight size={16}/></Link>;}
function AuditRow({event}:{event:AdminAuditEvent}){const {locale,t}=useI18n();const actor=event.actorZh&&event.actorEn?`${event.actorZh} / ${event.actorEn}`:t("admin.systemActor");const date=new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.createdAt));return <div className="event-row"><i className="blue"/><span><b>{event.action}</b><small>{actor} · {event.entityType}{event.entityId?` · ${event.entityId.slice(0,8)}`:""} · {date}</small></span></div>;}

export function AdminPortalPage({data}:{data:AdminDashboardData}){const {t}=useI18n();const items=[{count:data.pendingApprovals,href:"/admin/approvals",title:"admin.realTask.approvals",meta:"admin.realTask.approvalsHelp"},{count:data.mfaMissing,href:"/admin/users",title:"admin.realTask.mfa",meta:"admin.realTask.mfaHelp"},{count:data.failedJobs,href:"/messages",title:"admin.realTask.jobs",meta:"admin.realTask.jobsHelp"},{count:data.unreadNotifications,href:"/messages",title:"admin.realTask.messages",meta:"admin.realTask.messagesHelp"}];return <div className="page-stack admin-portal"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.operationsCenter")}</p><h1>{t("admin.portal.title")}</h1><p>{t("admin.portal.description")}</p></div><Link className="primary-button" href="/admin/users">{t("admin.inviteUser")}</Link></section>{data.mfaMissing>0&&<section className="admin-alert"><span><ShieldAlert size={21}/></span><div><b>{t("admin.securityAlert",{count:data.mfaMissing})}</b><p>{t("admin.mfaMissingHelp",{count:data.mfaMissing})}</p></div><Link href="/admin/security">{t("admin.handleNow")}</Link></section>}
    <section className="admin-metric-grid"><Metric icon={CheckCircle2} tone="purple" value={String(data.pendingApprovals)} label={t("admin.metric.approvals")} note={t("admin.metric.pendingReal")} href="/admin/approvals"/><Metric icon={Users} tone="blue" value={String(data.staffTotal)} label={t("admin.metric.members")} note={t("admin.activeCount",{count:data.activeStaff})} href="/admin/users"/><Metric icon={KeyRound} tone="amber" value={String(data.mfaMissing)} label={t("admin.metric.mfa")} note={t("admin.metric.mfaReal")} href="/admin/security"/><Metric icon={FileCheck2} tone="green" value={String(data.failedJobs)} label={t("admin.failedJobs")} note={t("admin.failedJobsHelp")} href="/messages"/></section>
    <section className="admin-grid"><article className="surface admin-work"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.priorityQueue")}</p><h2>{t("admin.todo")}</h2></div></div>{items.map(item=><div className="admin-task" key={item.title}><span className={item.count?"amber":"green"}>{item.count? <ShieldAlert size={18}/>:<CheckCircle2 size={18}/>}</span><div><b>{t(item.title,{count:item.count})}</b><small>{t(item.meta)}</small></div><Link href={item.href}>{t("admin.view")}</Link></div>)}</article><article className="surface launch-progress"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.readiness")}</p><h2>{t("admin.securityCoverage")}</h2></div></div><ProgressBar value={data.privilegedTotal?data.privilegedMfa/data.privilegedTotal*100:100} label={t("admin.mfaCoverage",{enabled:data.privilegedMfa,total:data.privilegedTotal})}/><p>{t("admin.securityCoverageHelp")}</p><Link className="card-link" href="/admin/security">{t("admin.fullChecklist")}<ChevronRight size={15}/></Link></article></section>
    <section className="surface audit-stream"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.auditTrail")}</p><h2>{t("admin.auditTrail")}</h2></div><Link href="/admin/security">{t("admin.all")}</Link></div>{data.audits.slice(0,8).map(event=><AuditRow event={event} key={event.id}/>)}</section></div>;}

export function SecurityAdminPage({data,initialAudits}:{data:AdminDashboardData;initialAudits:AdminAuditPage}){const {t}=useI18n();const coverage=data.privilegedTotal?Math.round(data.privilegedMfa/data.privilegedTotal*100):100;return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.securityAudit")}</p><h1>{t("admin.security.title")}</h1><p>{t("admin.security.description")}</p></div><StatusBadge tone={data.mfaMissing?"amber":"green"}><ShieldCheck size={14}/>{t(data.mfaMissing?"admin.actionRequired":"admin.protectionRunning")}</StatusBadge></section><section className="security-grid"><article className="surface"><span className={`security-hero ${data.mfaMissing?"amber":"green"}`}><ShieldCheck size={28}/></span><h2>{t(data.mfaMissing?"admin.securityNeedsAction":"admin.overallGood")}</h2><p>{t("admin.securityMeasuredHelp")}</p></article><article className="surface"><div className="surface-heading"><h2>{t("admin.privilegedAccounts")}</h2><b>{coverage}%</b></div><ProgressBar value={coverage} label={t("admin.mfaCoverage",{enabled:data.privilegedMfa,total:data.privilegedTotal})}/></article><article className="surface"><div className="surface-heading"><h2>{t("admin.securityQueue")}</h2></div><p>{t("admin.mfaMissingHelp",{count:data.mfaMissing})}</p><p>{t("admin.failedJobsCount",{count:data.failedJobs})}</p></article></section><SecurityAuditList initialPage={initialAudits}/></div>;}

function SecurityAuditList({initialPage}:{initialPage:AdminAuditPage}){const {t}=useI18n();const [items,setItems]=useState(initialPage.items);const [total,setTotal]=useState(initialPage.total);const [page,setPage]=useState(1);const [query,setQuery]=useState("");const [error,setError]=useState("");const pageSize=20;const load=useCallback(async(nextPage:number)=>{try{const params=new URLSearchParams({q:query,page:String(nextPage),pageSize:String(pageSize)});const response=await fetch(`/api/admin/audit?${params}`);const result=await response.json() as AdminAuditPage;if(!response.ok||!result.items)throw new Error();setItems(result.items);setTotal(result.total);setError("");}catch{setError(t("admin.auditLoadFailed"));}},[query,t]);useEffect(()=>{const timer=window.setTimeout(()=>void load(page),query?250:0);return()=>window.clearTimeout(timer);},[load,page,query]);const pages=Math.max(1,Math.ceil(total/pageSize));return <section className="surface audit-stream"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.auditTrail")}</p><h2>{t("admin.auditTrail")}</h2></div></div><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("admin.auditSearch")}/>{error&&<InlineMessage type="error">{error}</InlineMessage>}{items.length?items.map(event=><AuditRow event={event} key={event.id}/>):<EmptyState messageKey="admin.noAuditEvents"/>}<Pagination page={Math.min(page,pages)} totalPages={pages} total={total} pageSize={pageSize} onPage={setPage}/></section>;}
