"use client";
import {useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {milestoneSaveSchema,milestoneStatuses,milestoneTypes,interviewResults,visaResults,type MilestoneData} from "@/lib/admission-milestone-input";
import type {MilestoneRecord} from "@/lib/admission-milestone-repository";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {DateInput} from "./structured-inputs";
import {enrollmentTimestamp} from "@/lib/enrollment-input";
import {EnrollmentRelation} from "./enrollment-relation";
import {ApplicationSelector} from "./application-selector";
import {InlineMessage} from "./ui";
export function AdmissionMilestoneEditor({enrollmentId,studentId,applicationId,defaultOwner,record,onLock,onCancel,onSaved}:{enrollmentId:string;studentId:string;applicationId?:string;defaultOwner?:string|null;record?:MilestoneRecord;onLock:(locked:boolean)=>void;onCancel:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),preferences=useUserPreferences(),[id]=useState(()=>record?.id??crypto.randomUUID()),[data,setData]=useState<MilestoneData>(()=>({enrollment_id:enrollmentId,application_id:record?.application_id??applicationId??null,milestone_type:record?.milestone_type??"INTERVIEW",status:record?.status??"PENDING",due_at:record?.due_at??null,scheduled_at:record?.scheduled_at??null,completed_at:record?.completed_at??null,outcome:record?.outcome??null,owner_id:record?record.owner_id:defaultOwner??null,external_reference:record?.external_reference??null,note:record?.note??null,sequence:record?.sequence??1,metadata:record?.metadata??{}})),[reason,setReason]=useState(""),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState("");
 const attempt=useRef<ReturnType<typeof milestoneSaveSchema.parse>|null>(null),busy=useRef(false);
 const change=<K extends keyof MilestoneData>(key:K,value:MilestoneData[K])=>setData(previous=>({...previous,[key]:value}));
 const metadata=(key:string,value:string|number|null)=>setData(previous=>{const next={...previous.metadata};if(value===null||value==="")delete next[key];else next[key]=value;return{...previous,metadata:next};});
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy.current)return;if(!attempt.current){const parsed=milestoneSaveSchema.safeParse({id,expectedRevision:record?.revision??null,requestKey:crypto.randomUUID(),statusReason:reason,data});if(!parsed.success){setError(t("milestones.invalid"));return;}attempt.current=parsed.data;}busy.current=true;setPending(true);onLock(true);setError("");try{await apiFetch("/api/admission-milestones",{method:record?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;onLock(unknown);setError(presentApiError(error,t,"milestones.saveFailed").message);busy.current=false;setPending(false);return;}attempt.current=null;setUncertain(false);onLock(false);await onSaved();busy.current=false;setPending(false);};
 const keys=data.milestone_type==="INTERVIEW"?["interviewer","result","summary"]:data.milestone_type==="PLACEMENT_TEST"?["score","scale","result"]:data.milestone_type==="VISA_RESULT"?["result","reason"]:data.milestone_type==="OTHER"?["label"]:[];
 return <form onSubmit={submit}><h3>{t(record?"milestones.edit":"milestones.create")}</h3><p className="field-help">{t("milestones.contextHelp")}</p><fieldset className="follow-up-fields" disabled={pending||uncertain}>
 {!applicationId&&<ApplicationSelector studentId={studentId} enrollmentId={enrollmentId} value={data.application_id??""} onChange={value=>change("application_id",value||null)}/>}
 <div className="form-grid two-column"><label className="field"><span>{t("milestones.type")}</span><select name="milestone_type" value={data.milestone_type} onChange={event=>setData(previous=>({...previous,milestone_type:event.target.value as MilestoneData["milestone_type"],metadata:{}}))}>{milestoneTypes.map(type=><option key={type} value={type}>{t(`milestones.type.${type}`)}</option>)}</select></label><label className="field"><span>{t("common.status")}</span><select name="milestone_status" value={data.status} onChange={event=>change("status",event.target.value as MilestoneData["status"])}>{milestoneStatuses.map(status=><option key={status} value={status}>{t(`milestones.status.${status}`)}</option>)}</select></label></div>
 {(["due_at","scheduled_at","completed_at"] as const).map(key=><label className="field" key={key}><span>{t(`milestones.${key}`)}</span><DateInput name={key} type="datetime-local" value={data[key]?preferences.localDateTimeInput(data[key]):""} onChange={event=>change(key,enrollmentTimestamp(event.target.value,record?.[key]??null,preferences.localDateTimeInput,preferences.localDateTimeToIso))}/></label>)}
 <p className="field-help">{t("milestones.metadataHelp")}</p>
 {keys.map(key=><label className="field" key={key}><span>{t(`milestones.${key}`)}</span>{key==="result"&&(data.milestone_type==="INTERVIEW"||data.milestone_type==="VISA_RESULT")?<select name={`metadata_${key}`} value={String(data.metadata[key]??"")} onChange={event=>metadata(key,event.target.value)}><option value="">{t("business.unknown")}</option>{(data.milestone_type==="INTERVIEW"?interviewResults:visaResults).map(value=><option key={value} value={value}>{t(`milestones.result.${value}`)}</option>)}</select>:key==="summary"||key==="reason"?<textarea name={`metadata_${key}`} rows={2} maxLength={key==="summary"?2000:1000} value={String(data.metadata[key]??"")} onChange={event=>metadata(key,event.target.value)}/>:<input name={`metadata_${key}`} type={key==="score"?"number":"text"} step={key==="score"?"any":undefined} maxLength={key==="scale"?80:160} value={String(data.metadata[key]??"")} onChange={event=>metadata(key,key==="score"?(event.target.value===""?null:Number(event.target.value)):event.target.value)}/>}</label>)}
 <EnrollmentRelation type="USER" label={t("milestones.owner")} value={data.owner_id??""} initialLabel={record?((locale==="en"?record.owner_name_en:record.owner_name_zh)||undefined):undefined} onChange={value=>change("owner_id",value||null)}/>
 <label className="field"><span>{t("milestones.sequence")}</span><input name="sequence" type="number" min={1} max={1000000} required value={data.sequence} onChange={event=>change("sequence",Number(event.target.value))}/></label>
 {(["outcome","external_reference","note"] as const).map(key=><label className="field" key={key}><span>{t(`milestones.${key}`)}</span><textarea name={key} rows={key==="note"?2:1} maxLength={key==="note"?2000:160} value={data[key]??""} onChange={event=>change(key,event.target.value||null)}/></label>)}
 <label className="field"><span>{t("applications.statusReason")}</span><textarea name="statusReason" rows={2} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label>
 </fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={onCancel}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"enrollments.retry":"common.save")}</button></div></form>;
}
