"use client";
import {useEffect,useRef,useState} from "react";
import {applicationStatuses,applicationDecisions,applicationSaveSchema,type ApplicationData} from "@/lib/application-input";
import type {ApplicationRecord} from "@/lib/application-repository";
import type {EnrollmentPage,EnrollmentRecord} from "@/lib/enrollment-repository";
import {enrollmentTimestamp} from "@/lib/enrollment-input";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {useRemoteSearch} from "@/hooks/use-remote-search";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {useAppUser} from "./app-user-context";
import {AccessibleDrawer,InlineMessage,SearchableSelect} from "./ui";
import {DateInput} from "./structured-inputs";
import {EnrollmentRelation} from "./enrollment-relation";
export function ApplicationEditor({record,enrollment,onClose,onSaved}:{record?:ApplicationRecord;enrollment?:EnrollmentRecord|null;onClose:()=>void;onSaved:(id:string)=>Promise<void>}){
 const {t,locale}=useI18n(),user=useAppUser(),preferences=useUserPreferences(),latest=useRemoteSearch(),prefill=useRemoteSearch();
 const [id]=useState(()=>record?.id??crypto.randomUUID()),[data,setData]=useState<ApplicationData>(()=>({enrollment_id:record?.enrollment_id??enrollment?.id??"",target_organization_id:record?.target_organization_id??null,external_application_id:record?.external_application_id??null,deadline_on:record?.deadline_on??null,status:record?.status??"DRAFT",decision:record?.decision??null,submitted_at:record?.submitted_at??null,decision_at:record?.decision_at??null,withdrawn_at:record?.withdrawn_at??null,owner_id:record?record.owner_id:enrollment?.owner_id??user.id}));
 const [context,setContext]=useState<EnrollmentRecord|null>(enrollment??null),[options,setOptions]=useState<Array<{value:string;label:string}>>([]),[reason,setReason]=useState(""),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState("");
 const attempt=useRef<ReturnType<typeof applicationSaveSchema.parse>|null>(null),busy=useRef(false);
 const [cohortDeadline,setCohortDeadline]=useState<string|null>(record?.cohort_application_deadline??null);
 useEffect(()=>{if(record||!context)return;const controller=new AbortController();void apiFetch<{item:{application_deadline:string|null}}>(`/api/product-cohorts?id=${context.cohort_id}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setCohortDeadline(result.item.application_deadline);}).catch(()=>{if(!controller.signal.aborted)setError(t("applications.loadFailed"));});return()=>controller.abort();},[context,record,t]);
 const label=(zh?:string|null,en?:string|null)=>(locale==="en"?en:zh)||zh||en||"—";
 const change=<K extends keyof ApplicationData>(key:K,value:ApplicationData[K])=>setData(previous=>({...previous,[key]:value}));
 const search=async(query:string)=>{const result=await latest(signal=>apiFetch<EnrollmentPage>(`/api/enrollments?query=${encodeURIComponent(query)}`,{signal}));if(!result.current)return;if("error" in result){setError(t("applications.loadFailed"));return;}setOptions(result.value.items.map(row=>({value:row.id,label:`${label(row.student_name_zh,row.student_name_en)} · ${label(row.cohort_name_zh,row.cohort_name_en)}`})));};
 const select=async(value:string)=>{change("enrollment_id",value);setContext(null);setCohortDeadline(null);const result=await prefill(signal=>apiFetch<{item:EnrollmentRecord}>(`/api/enrollments?id=${value}`,{signal}));if(!result.current)return;if("error" in result){setError(t("applications.loadFailed"));return;}setContext(result.value.item);};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy.current)return;if(!attempt.current){const parsed=applicationSaveSchema.safeParse({id,expectedRevision:record?.revision??null,requestKey:crypto.randomUUID(),statusReason:reason,data});if(!parsed.success){setError(t("applications.invalid"));return;}attempt.current=parsed.data;}busy.current=true;setPending(true);setError("");try{await apiFetch("/api/applications",{method:record?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;setError(presentApiError(error,t,"applications.saveFailed").message);busy.current=false;setPending(false);return;}attempt.current=null;setUncertain(false);await onSaved(id);busy.current=false;setPending(false);};
 const contextLabel=record?`${label(record.student_name_zh,record.student_name_en)} · ${label(record.cohort_name_zh,record.cohort_name_en)}`:context?`${label(context.student_name_zh,context.student_name_en)} · ${label(context.cohort_name_zh,context.cohort_name_en)}`:t("applications.enrollment");
 const selected=data.enrollment_id&&!options.some(item=>item.value===data.enrollment_id)?[{value:data.enrollment_id,label:contextLabel}]:[];
 return <AccessibleDrawer title={t(record?"applications.edit":"applications.create")} description={t("applications.identityHelp")} pending={pending||uncertain} onClose={onClose}><form onSubmit={submit}><fieldset className="follow-up-fields" disabled={pending||uncertain}>
 {record||enrollment?<label className="field"><span>{t("applications.enrollment")}</span><input readOnly value={contextLabel}/></label>:<SearchableSelect label={t("applications.enrollment")} value={data.enrollment_id} required options={[...selected,...options]} onSearch={search} onChange={value=>void select(value)}/>}
 <EnrollmentRelation type="ORGANIZATION" label={t("applications.target")} value={data.target_organization_id??""} initialLabel={record?label(record.target_name_zh,record.target_name_en):undefined} onChange={value=>change("target_organization_id",value||null)}/>
 <label className="field"><span>{t("applications.externalId")}</span><input name="external_application_id" maxLength={160} value={data.external_application_id??""} onChange={event=>change("external_application_id",event.target.value||null)}/></label>
 <div className="form-grid two-column"><label className="field"><span>{t("common.status")}</span><select name="status" value={data.status} onChange={event=>change("status",event.target.value as ApplicationData["status"])}>{applicationStatuses.map(status=><option value={status} key={status}>{t(`applications.status.${status}`)}</option>)}</select></label><label className="field"><span>{t("applications.decision")}</span><select name="decision" value={data.decision??""} onChange={event=>change("decision",event.target.value as ApplicationData["decision"]||null)}><option value="">{t("business.unknown")}</option>{applicationDecisions.map(decision=><option key={decision} value={decision}>{t(`applications.decision.${decision}`)}</option>)}</select></label></div>
 <label className="field"><span>{t("applications.deadline")}</span><DateInput name="deadline_on" value={data.deadline_on??""} onChange={event=>change("deadline_on",event.target.value||null)}/></label>
 <p className="field-help">{t("applications.cohortDeadline")}: {cohortDeadline?preferences.formatDate(cohortDeadline):"—"}</p>
 {(["submitted_at","decision_at","withdrawn_at"] as const).map(key=><label className="field" key={key}><span>{t(`applications.${key}`)}</span><DateInput name={key} type="datetime-local" value={data[key]?preferences.localDateTimeInput(data[key]):""} onChange={event=>change(key,enrollmentTimestamp(event.target.value,record?.[key]??null,preferences.localDateTimeInput,preferences.localDateTimeToIso))}/></label>)}
 <EnrollmentRelation type="USER" label={t("applications.owner")} value={data.owner_id??""} initialLabel={record?label(record.owner_name_zh,record.owner_name_en):enrollment?label(enrollment.owner_name_zh,enrollment.owner_name_en):user.displayName} onChange={value=>change("owner_id",value||null)}/>
 <label className="field"><span>{t("applications.statusReason")}</span><textarea name="statusReason" maxLength={1000} rows={2} value={reason} onChange={event=>setReason(event.target.value)}/></label>
 </fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={onClose}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"enrollments.retry":"common.save")}</button></div></form></AccessibleDrawer>;
}
