"use client";
import {WorkflowsSection} from "./workflows-section";
import {AdmissionMilestonesSection} from "./admission-milestones-section";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import type {ApplicationRecord,ApplicationHistory,ApplicationTask} from "@/lib/application-repository";
import {businessSaveSchema} from "@/lib/education-business";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {AccessibleDrawer,InlineMessage,StatusBadge} from "./ui";
import {DetailTabs} from "./detail-tabs";
import {DateInput} from "./structured-inputs";
export function ApplicationStatus({status}:{status:ApplicationRecord["status"]}){const {t}=useI18n();return <StatusBadge tone={status==="DECIDED"?"green":status==="WITHDRAWN"||status==="CLOSED"?"gray":"blue"}>{t(`applications.status.${status}`)}</StatusBadge>;}
export function ApplicationDetail({record,onClose,onEdit}:{record:ApplicationRecord;onClose:()=>void;onEdit:()=>void}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),[tab,setTab]=useState("overview"),[page,setPage]=useState(1),[history,setHistory]=useState<ApplicationHistory[]>([]),[tasks,setTasks]=useState<ApplicationTask[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[task,setTask]=useState<{record?:ApplicationTask}|null>(null),[locked,setLocked]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{if(tab==="overview"||tab==="milestones"||tab==="workflow")return;setLoading(true);setError("");try{if(tab==="tasks"){const result=await apiFetch<{items:ApplicationTask[]}>(`/api/applications?id=${record.id}&resource=tasks&page=${page}`,{signal});if(!signal?.aborted)setTasks(result.items);}else{const result=await apiFetch<{items:ApplicationHistory[]}>(`/api/applications?id=${record.id}&resource=history&page=${page}`,{signal});if(!signal?.aborted)setHistory(result.items);}}catch(error){if(!signal?.aborted)setError(presentApiError(error,t,"applications.loadFailed").message);}finally{if(!signal?.aborted)setLoading(false);}},[tab,page,record.id,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const label=(zh?:string|null,en?:string|null)=>(locale==="en"?en:zh)||zh||en||"—";
 const fields:Array<[string,React.ReactNode]>=[["enrollments.student",label(record.student_name_zh,record.student_name_en)],["applications.enrollment",<Link key="enrollment" href={`/enrollments?focus=${record.enrollment_id}`}>{label(record.cohort_name_zh,record.cohort_name_en)}</Link>],["products.product",label(record.product_name_zh,record.product_name_en)],["enrollments.cohort",label(record.cohort_name_zh,record.cohort_name_en)],["applications.target",label(record.target_name_zh,record.target_name_en)],["applications.externalId",record.external_application_id||"—"],["common.status",<ApplicationStatus key="status" status={record.status}/>],["applications.decision",record.decision?t(`applications.decision.${record.decision}`):"—"],["applications.deadline",record.deadline_on?formatDate(record.deadline_on):"—"],["applications.cohortDeadline",record.cohort_application_deadline?formatDate(record.cohort_application_deadline):"—"],["applications.owner",label(record.owner_name_zh,record.owner_name_en)]];
 for(const field of ["submitted_at","decision_at","withdrawn_at"] as const)fields.push([`applications.${field}`,record[field]?formatDate(record[field],{includeTime:true}):"—"]);
 return <AccessibleDrawer title={(locale==="en"?record.target_name_en:record.target_name_zh)||record.external_application_id||t("applications.title")} description={`${label(record.student_name_zh,record.student_name_en)} · ${label(record.cohort_name_zh,record.cohort_name_en)}`} pending={locked} onClose={onClose}>
 <DetailTabs label={t("applications.title")} active={tab} disabled={locked} onChange={value=>{setTab(value);setPage(1);setTask(null);}} items={[{key:"overview",label:"applications.overview"},{key:"tasks",label:"applications.tasks"},{key:"milestones",label:"milestones.title"},{key:"workflow",label:"workflow.workflow"},{key:"history",label:"applications.history"}]}>
 {tab==="overview"?<section className="detail-section"><dl className="enrollment-summary">{fields.map(([key,value])=><div key={key}><dt>{t(key)}</dt><dd>{value}</dd></div>)}</dl>{record.can_edit&&<button type="button" className="primary-button" onClick={onEdit}>{t("applications.edit")}</button>}</section>:tab==="milestones"?<AdmissionMilestonesSection enrollmentId={record.enrollment_id} studentId={record.student_id} applicationId={record.id} ownerId={record.owner_id} canEdit={record.can_edit} onLock={setLocked}/>:tab==="workflow"?<WorkflowsSection enrollmentId={record.enrollment_id} studentId={record.student_id} productId={record.product_id} applicationId={record.id} ownerId={record.owner_id} canEdit={record.can_edit} onLock={setLocked}/>:<section className="detail-section">
 {error&&<InlineMessage type="error">{error}<button className="secondary-button" onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>}{loading&&<p role="status">{t("common.loading")}</p>}
 {tab==="tasks"?<><p className="field-help">{t("applications.genericTask")}</p>{record.can_edit&&!task&&<button className="secondary-button" type="button" onClick={()=>setTask({})}>{t("applications.addTask")}</button>}{task&&<ApplicationTaskForm key={task.record?.id??"new"} application={record} record={task.record} onLock={setLocked} onCancel={()=>setTask(null)} onSaved={async()=>{setTask(null);await load();}}/>}<div className="detail-record-list">{!error&&tasks.map(row=><article key={row.id}><div><b>{row.title}</b><small>{t(`business.option.${row.status}`)} · {row.due_on?formatDate(row.due_on):"—"}</small><p>{row.next_action}</p></div>{record.can_edit&&<button type="button" className="secondary-button" disabled={locked} onClick={()=>setTask({record:row})}>{t("applications.editTask")}</button>}</article>)}</div>{!error&&!loading&&!tasks.length&&<p>{t("applications.noTasks")}</p>}</>:<><p className="field-help">{t("applications.historyHelp")}</p><div className="detail-record-list">{!error&&history.map(row=><article key={row.id}><div><b>{row.from_status?t(`applications.status.${row.from_status}`):t("applications.created")} → {t(`applications.status.${row.to_status}`)}</b><small>{formatDate(row.changed_at,{includeTime:true})} · {t("enrollments.revision",{revision:row.application_revision})}</small>{row.reason&&<p>{row.reason}</p>}</div></article>)}</div>{!error&&!loading&&!history.length&&<p>{t("applications.noHistory")}</p>}</>}
 <div className="detail-actions"><button className="secondary-button" type="button" disabled={loading||locked||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button className="secondary-button" type="button" disabled={loading||locked||(tab==="tasks"?tasks:history).length<50} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div></section>}
 </DetailTabs></AccessibleDrawer>;
}
function ApplicationTaskForm({application,record,onLock,onCancel,onSaved}:{application:ApplicationRecord;record?:ApplicationTask;onLock:(locked:boolean)=>void;onCancel:()=>void;onSaved:()=>Promise<void>}){
 const {t}=useI18n(),[id]=useState(()=>record?.id??crypto.randomUUID()),[draft,setDraft]=useState({student_id:application.student_id,application_id:application.id,title:record?.title??"",due_on:record?.due_on??null,status:record?.status??"TODO",next_action:record?.next_action??""}),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState("");
 const busy=useRef(false),attempt=useRef<ReturnType<typeof businessSaveSchema.parse>|null>(null);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy.current)return;if(!attempt.current){const parsed=businessSaveSchema.safeParse({resource:"applications",id,expectedRevision:record?.revision??null,data:draft});if(!parsed.success){setError(t("business.invalid"));return;}attempt.current=parsed.data;}busy.current=true;setPending(true);onLock(true);setError("");try{await apiFetch("/api/education-business",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;setError(presentApiError(error,t,"business.saveFailed").message);onLock(unknown);busy.current=false;setPending(false);return;}attempt.current=null;onLock(false);await onSaved();busy.current=false;setPending(false);};
 return <form onSubmit={submit}><fieldset className="follow-up-fields" disabled={pending||uncertain}><label className="field"><span>{t("business.field.title")}</span><input name="title" maxLength={200} required value={draft.title} onChange={event=>setDraft(previous=>({...previous,title:event.target.value}))}/></label><label className="field"><span>{t("business.field.due_on")}</span><DateInput name="due_on" value={draft.due_on??""} onChange={event=>setDraft(previous=>({...previous,due_on:event.target.value||null}))}/></label><label className="field"><span>{t("common.status")}</span><select name="task_status" value={draft.status} onChange={event=>setDraft(previous=>({...previous,status:event.target.value as ApplicationTask["status"]}))}>{["TODO","IN_PROGRESS","DONE","WAIVED"].map(value=><option value={value} key={value}>{t(`business.option.${value}`)}</option>)}</select></label><label className="field"><span>{t("business.field.next_action")}</span><textarea name="next_action" rows={2} maxLength={1000} value={draft.next_action} onChange={event=>setDraft(previous=>({...previous,next_action:event.target.value}))}/></label></fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("business.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={onCancel}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"business.retry":"common.save")}</button></div></form>;
}
