"use client";

import { useState } from "react";
import { BellRing,Eye,Play,Plus,RotateCcw,Workflow } from "lucide-react";
import { AccessibleDrawer,InlineMessage,StatusBadge,Toast } from "./ui";
import { useI18n } from "./i18n-provider";
import { apiFetch } from "@/lib/api-client";
import type { AutomationPreview,AutomationRuleRecord,AutomationRunRecord } from "@/lib/v220-repository";

type Workspace={rules:AutomationRuleRecord[];runs:AutomationRunRecord[];preview?:AutomationPreview};
export function AutomationWorkspace({initial}:{initial:Workspace}){
  const{locale,t}=useI18n();const[data,setData]=useState(initial);const[preview,setPreview]=useState<AutomationPreview|null>(null);const[open,setOpen]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");
  const operate=async(body:Record<string,unknown>)=>{setPending(true);setError("");try{const result=await apiFetch<Workspace>("/api/automation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setData({rules:result.rules,runs:result.runs});if(result.preview)setPreview(result.preview);return result;}catch{setError(t("automation.failed"));return null;}finally{setPending(false);}};
  const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const result=await operate({operation:"create",nameZh:form.get("nameZh"),nameEn:form.get("nameEn"),triggerKey:form.get("triggerKey"),conditionField:form.get("conditionField")||undefined,conditionValue:form.get("conditionValue")||undefined,actionType:form.get("actionType"),titleZh:form.get("titleZh"),titleEn:form.get("titleEn"),priority:form.get("priority"),dueHours:Number(form.get("dueHours"))});if(result){setOpen(false);setToast(t("automation.created"));}};
  return <div className="page-stack v220-workspace"><section className="page-heading-row"><div><p className="eyebrow">{t("automation.eyebrow")}</p><h1>{t("automation.title")}</h1><p>{t("automation.help")}</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/>{t("automation.new")}</button></section><InlineMessage type="info">{t("automation.deterministic")}</InlineMessage>{error&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="v220-summary-grid"><article className="surface"><Workflow/><b>{data.rules.filter(item=>item.active).length}</b><span>{t("automation.active")}</span></article><article className="surface"><Play/><b>{data.runs.filter(item=>item.status==="SUCCEEDED").length}</b><span>{t("automation.succeeded")}</span></article><article className="surface"><BellRing/><b>{data.runs.filter(item=>item.status==="FAILED").length}</b><span>{t("automation.failedRuns")}</span></article></section>
    {preview&&<InlineMessage type={preview.matches?"success":"warning"}><span>{t(preview.matches?"automation.previewMatch":"automation.previewMiss",{version:preview.version})}</span><code>{preview.actionType} · {JSON.stringify(preview.actionConfig)}</code><button className="text-button" type="button" onClick={()=>setPreview(null)}>{t("common.close")}</button></InlineMessage>}
    <section className="surface"><div className="surface-heading"><div><h2>{t("automation.rules")}</h2><p>{t("automation.rulesHelp")}</p></div></div><div className="v220-list">{data.rules.map(rule=><article key={rule.id}><span className="product-icon"><Workflow size={18}/></span><div><b>{locale==="zh-CN"?rule.nameZh:rule.nameEn} · v{rule.version}</b><small>{t(`automation.trigger.${rule.triggerKey}`)} · {t(`automation.action.${rule.actionType}`)}</small><small>{Object.keys(rule.conditions).length?JSON.stringify(rule.conditions):t("automation.noCondition")}</small></div><StatusBadge tone={rule.active?"green":"gray"}>{t(rule.active?"common.enabled":"common.disabled")}</StatusBadge><button className="secondary-button" disabled={pending} onClick={()=>void operate({operation:"preview",id:rule.id,payload:rule.conditions})}><Eye size={15}/>{t("automation.preview")}</button><button className="secondary-button" disabled={pending||!rule.active} onClick={()=>void operate({operation:"run",triggerKey:rule.triggerKey,eventKey:`manual:${rule.id}:${crypto.randomUUID()}`,payload:rule.conditions})}><Play size={15}/>{t("automation.run")}</button><button className="text-button" disabled={pending} onClick={()=>void operate({operation:"toggle",id:rule.id,active:!rule.active})}>{t(rule.active?"common.disable":"common.enable")}</button></article>)}</div>{!data.rules.length&&<div className="empty-state"><span>{t("automation.empty")}</span></div>}</section>
    <section className="surface"><div className="surface-heading"><h2>{t("automation.history")}</h2></div><div className="v220-list compact">{data.runs.map(run=><article key={run.id}><div><b>{locale==="zh-CN"?run.ruleNameZh:run.ruleNameEn}</b><small>{new Date(run.lastAttemptAt||run.createdAt).toLocaleString()} · {t("automation.attempts",{count:run.attemptCount})} · {run.resultType||run.errorCode}</small></div><StatusBadge tone={run.status==="SUCCEEDED"?"green":run.status==="SKIPPED"?"gray":"red"}>{run.status}</StatusBadge>{run.status==="FAILED"&&<button className="secondary-button" disabled={pending} onClick={()=>void operate({operation:"retry",id:run.id})}><RotateCcw size={15}/>{t("common.retry")}</button>}</article>)}</div></section>
    {open&&<AccessibleDrawer title={t("automation.new")} description={t("automation.createHelp")} onClose={()=>setOpen(false)}><form onSubmit={create}><div className="form-grid two-column"><label className="field"><span>{t("education.nameZh")}</span><input name="nameZh" required/></label><label className="field"><span>{t("education.nameEn")}</span><input name="nameEn" required/></label></div><label className="field"><span>{t("automation.trigger")}</span><select name="triggerKey">{["LEAD_CREATED","LEAD_STATUS_CHANGED","OPPORTUNITY_STAGE_CHANGED","CONTRACT_RENEWAL_DUE","MANUAL"].map(value=><option key={value} value={value}>{t(`automation.trigger.${value}`)}</option>)}</select></label><div className="form-grid two-column"><label className="field"><span>{t("automation.conditionField")}</span><select name="conditionField" defaultValue=""><option value="">{t("automation.noCondition")}</option>{["status","source","stage","currency"].map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>{t("automation.conditionValue")}</span><input name="conditionValue" maxLength={160}/></label></div><label className="field"><span>{t("automation.action")}</span><select name="actionType"><option value="TASK">{t("automation.action.TASK")}</option><option value="NOTIFICATION">{t("automation.action.NOTIFICATION")}</option></select></label><div className="form-grid two-column"><label className="field"><span>{t("automation.taskTitleZh")}</span><input name="titleZh" required/></label><label className="field"><span>{t("automation.taskTitleEn")}</span><input name="titleEn" required/></label></div><div className="form-grid two-column"><label className="field"><span>{t("modules.priority")}</span><select name="priority" defaultValue="NORMAL">{["LOW","NORMAL","HIGH","URGENT"].map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>{t("automation.dueHours")}</span><input name="dueHours" type="number" min="1" max="2160" defaultValue="24" required/></label></div>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{pending?t("common.saving"):t("common.create")}</button></div></form></AccessibleDrawer>}{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
