"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {channelAnalyticsFilters,formatChannelCommissionAmount,type ChannelAnalytics,type ChannelAnalyticsFilters,type CommissionExposure,type SettlementExposure} from "@/lib/channel-analytics-input";
import {commercialTiers} from "@/lib/channel-commercial-input";
import {partnershipStages} from "@/lib/lead-pool-input";
import {useI18n} from "./i18n-provider";
import {DateInput} from "./structured-inputs";
import {EnrollmentRelation} from "./enrollment-relation";
import {InlineMessage} from "./ui";
import {FilterBar} from "./filter-bar";
import {RecordIdentity} from "./record-header";

const accountSummaryKeys=["keyContacts","openOpportunities","primaryContributions","activeEnrollments"] as const;
function useAnalytics(filters:ChannelAnalyticsFilters){
 const [stored,setData]=useState<{query:string;data:ChannelAnalytics}|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)])).toString();
 useEffect(()=>{const controller=new AbortController();void apiFetch<ChannelAnalytics>(`/api/analytics/channels?${query}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setData({query,data:result});setError(false);}}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[query,retry]);
 return {data:stored?.query===query?stored.data:null,error,reload:()=>setRetry(n=>n+1)};
}
export function ChannelAnalyticsPage({initialFilters={}}:{initialFilters?:ChannelAnalyticsFilters}){
 const {t}=useI18n(),[filters,setFilters]=useState<ChannelAnalyticsFilters>(initialFilters),[invalid,setInvalid]=useState(false);
 const {data,error,reload}=useAnalytics(filters);
 const count=(key:string,value:number|undefined)=><div key={key}><dt>{t(`channelAnalytics.${key}`)}</dt><dd>{value??0}</dd></div>;
 return <div className="page-stack channel-analytics"><section className="page-heading-row"><div><h1>{t("channelAnalytics.title")}</h1><p>{t("channelAnalytics.description")}</p></div></section>
 <FilterBar applied={filters} defaults={{}} advancedCount={Object.entries(filters).filter(([key,value])=>key!=="page"&&value!==undefined).length} activeCount={Object.entries(filters).filter(([key,value])=>key!=="page"&&value!==undefined).length} onReset={()=>setFilters({})} onApply={value=>{const parsed=channelAnalyticsFilters.safeParse(value);setInvalid(!parsed.success);if(!parsed.success)return false;setFilters({...parsed.data,page:1});reload();}} summary={<div className="scope-summary"><b>{data?data.period.from+" – "+data.period.to:t("channelAnalytics.period")}</b><span>{data?.period.timezone}</span><small>{t("channelAnalytics.boundary")}</small></div>} renderAdvanced={(draft,setDraft)=>{const change=(key:keyof ChannelAnalyticsFilters,value:string)=>setDraft({...draft,[key]:value||undefined,...(key==='product'?{cohort:undefined}:{})});return <>{(['from','to'] as const).map(key=><label className="field" key={key}><span>{t(`channelAnalytics.${key}`)}</span><DateInput value={draft[key]??""} onChange={e=>change(key,e.target.value)}/></label>)}{(['organization','owner','product','cohort'] as const).map(key=><EnrollmentRelation key={key} type={{organization:'ORGANIZATION',owner:'USER',product:'PRODUCT',cohort:'COHORT'}[key] as 'ORGANIZATION'|'USER'|'PRODUCT'|'COHORT'} label={t(`channelAnalytics.${key}`)} value={draft[key]??""} onChange={v=>change(key,v)}/>)}{(['tier','stage','sort'] as const).map(key=><label className="field" key={key}><span>{t(`channelAnalytics.${key}`)}</span><select value={draft[key]??""} onChange={e=>change(key,e.target.value)}><option value="">{t("channelAnalytics.all")}</option>{(key==='tier'?[...commercialTiers,'UNKNOWN']:key==='stage'?partnershipStages:['name','primary','active','tier']).map(v=><option key={v} value={v}>{key==='tier'?(v==='UNKNOWN'?t('channelAnalytics.unknown'):v):t(key==='stage'?`business.option.${v}`:`channelAnalytics.sort.${v}`)}</option>)}</select></label>)}{invalid&&<InlineMessage type="error">{t("channelAnalytics.invalid")}</InlineMessage>}</>;}}/>

 {error&&<InlineMessage type="error">{t("channelAnalytics.loadFailed")} <button className="secondary-button" onClick={reload}>{t("common.retry")}</button></InlineMessage>}
 {!data&&!error&&<p role="status">{t("common.loading")}</p>}
 {data&&<><section className="surface" data-surface-tone="context"><h2>{t("channelAnalytics.snapshot")}</h2><dl className="customer-profile">{count('visibleAccounts',data.snapshot.visibleAccounts)}{count('availablePublicLeads',data.snapshotTotals.availablePublicLeads)}{count('openOpportunities',data.snapshotTotals.openOpportunities)}{count('primaryContributions',data.snapshotTotals.primaryContributions)}{count('assistContributions',data.snapshotTotals.assistContributions)}{count('activeEnrollments',data.snapshot.activeAttributedEnrollments)}</dl><p>{t("channelAnalytics.contributionHelp")}</p></section>
 <details className="surface operational-disclosure" data-surface-tone="governance"><summary>{t("channelAnalytics.coverage")}</summary><dl className="customer-profile">{(['withKeyContact','withoutKeyContact','withDecisionMaker','withoutDecisionMaker','withActiveOpportunity','withoutActiveOpportunity'] as const).map(key=>count(key,data.snapshot[key]))}</dl>
 <h3>{t("channelAnalytics.byTier")}</h3><dl className="customer-profile">{[...commercialTiers,'UNKNOWN'].map(tier=><div key={tier}><dt>{tier==='UNKNOWN'?t('channelAnalytics.unknown'):tier}</dt><dd>{data.snapshot.byTier[tier]??0}</dd></div>)}</dl>
 <h3>{t("channelAnalytics.byStage")}</h3><dl className="customer-profile">{Object.entries(data.snapshot.byStage).map(([stage,n])=><div key={stage}><dt>{stage==='UNKNOWN'?t('channelAnalytics.unknown'):t(`business.option.${stage}`)}</dt><dd>{n}</dd></div>)}</dl></details>
 <section className="surface" data-surface-tone="analysis"><h2>{t("channelAnalytics.period")} · {data.period.from}–{data.period.to} · {data.period.timezone}</h2><p>{t("channelAnalytics.dateHelp")}</p><dl className="customer-profile">{Object.entries(data.totals).map(([key,n])=>count(key,n))}</dl></section>
 <section className="surface" data-surface-tone="context"><h2>{t("channelAnalytics.accounts")}</h2><p>{t("channelAnalytics.scopeHelp")}</p><div className="channel-account-grid">{data.items.map(item=><article className="detail-section" key={item.organizationId}><h3><Link href={`/schools/${item.organizationId}`}><RecordIdentity nameZh={item.nameZh} nameEn={item.nameEn}/></Link></h3><p>{item.commercialTier??t('channelAnalytics.unknown')} · {item.partnershipStage?t(`business.option.${item.partnershipStage}`):t('channelAnalytics.unknown')}</p><dl className="customer-profile">{accountSummaryKeys.map(key=>count(key,item.snapshot[key]))}</dl><details className="operational-disclosure"><summary>{t("channelAnalytics.statuses")}</summary><dl className="customer-profile">{Object.entries(item.snapshot).filter(([key])=>!(accountSummaryKeys as readonly string[]).includes(key)).map(([key,n])=>count(key,n))}{Object.entries(item.leadStatuses).map(([status,n])=><div key={status}><dt>{t(`leads.status.${status.toLowerCase()}`)}</dt><dd>{n}</dd></div>)}{Object.entries(item.enrollmentStatuses).map(([status,n])=><div key={status}><dt>{t(`enrollments.status.${status}`)}</dt><dd>{n}</dd></div>)}</dl><h4>{t('channelAnalytics.quality')}</h4><p>{Object.entries(item.quality).map(([severity,n])=>`${t(`quality.severity.${severity.toLowerCase()}`)}: ${n}`).join(' · ')||'—'}</p></details></article>)}</div>{!data.items.length&&<p>{t("common.noData")}</p>}<div className="page-actions"><button className="secondary-button" disabled={data.page<=1} onClick={()=>setFilters(f=>({...f,page:data.page-1}))}>{t("channelAnalytics.previous")}</button><span>{data.page} · {data.total}</span><button className="secondary-button" disabled={data.page*data.pageSize>=data.total} onClick={()=>setFilters(f=>({...f,page:data.page+1}))}>{t("channelAnalytics.next")}</button></div><p>{t('channelAnalytics.qualityHelp')}</p></section>
 <ChannelMoney visible={data.permissions.moneyVisible} commission={data.commissionByCurrency} settlements={data.settlementByCurrency}/></>}
 </div>;
}
function ChannelMoney({visible,commission,settlements}:{visible:boolean;commission:CommissionExposure[];settlements:SettlementExposure[]}){
 const {t,locale}=useI18n(),amount=(currency:string,value:string)=>`${currency} ${formatChannelCommissionAmount(value,locale)}`;
 if(!visible)return <InlineMessage type="info">{t('channelAnalytics.redacted')}</InlineMessage>;
 return <section className="surface" data-surface-tone="finance"><h2>{t('channelAnalytics.commission')}</h2><div className="channel-account-grid">{commission.map(c=><article className="detail-section" key={c.currency}><h3>{c.currency}</h3><dl className="customer-profile">{(['net','open','earned','reversals','period_net'] as const).map(key=><div key={key}><dt>{t(`channelAnalytics.${key==='period_net'?'periodNet':key}`)}</dt><dd>{amount(c.currency,c[key])}</dd></div>)}</dl></article>)}</div><h3>{t('channelAnalytics.settlements')}</h3><div className="channel-account-grid">{settlements.map(s=><article className="detail-section" key={`${s.currency}:${s.status}`}><h4>{s.currency} · {t(`commission.status.${s.status}`)}</h4><dl className="customer-profile"><div><dt>{t('channelAnalytics.count')}</dt><dd>{s.count}</dd></div>{(['amount','approved_in_period','paid_in_period'] as const).map(key=><div key={key}><dt>{t(`channelAnalytics.${key==='amount'?'amount':key==='approved_in_period'?'approved':'paid'}`)}</dt><dd>{amount(s.currency,s[key])}</dd></div>)}</dl></article>)}</div><Link href="/commissions">{t('commission.workspace')}</Link></section>;
}
export function ChannelPerformanceSection({organizationId}:{organizationId:string}){
 const {t}=useI18n(),{data,error}=useAnalytics({organization:organizationId}),account=data?.items[0];
 return <section className="detail-section"><h3>{t('channelAnalytics.performance')}</h3>{error?<InlineMessage type="error">{t('channelAnalytics.loadFailed')}</InlineMessage>:account?<dl className="customer-profile">{['primaryContributions','assistContributions','activeEnrollments','openOpportunities'].map(key=><div key={key}><dt>{t(`channelAnalytics.${key}`)}</dt><dd>{account.snapshot[key]}</dd></div>)}</dl>:<p>{t(data?'common.noData':'common.loading')}</p>}{account&&<ChannelMoney visible={account.moneyVisible} commission={account.commissionByCurrency} settlements={account.settlementByCurrency}/>}<Link href={`/reports/channels?organization=${organizationId}`}>{t('channelAnalytics.fullReport')}</Link></section>;
}
