"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import type {getChannelActivation} from "@/lib/channel-activation-repository";
import {partnershipStages} from "@/lib/lead-pool-input";
import {useI18n} from "./i18n-provider";
import {useCapability} from "./app-user-context";
import {useUserPreferences} from "./user-preferences-context";
import {AccessibleDrawer,InlineMessage} from "./ui";
export function ChannelActivationPanel({organizationId,onSaved}:{organizationId:string;onSaved?:()=>Promise<unknown>}){
 const {t}=useI18n(),{formatDate}=useUserPreferences(),manage=useCapability("education.manage");
 const [data,setData]=useState<Awaited<ReturnType<typeof getChannelActivation>>|null>(null),[error,setError]=useState(""),[open,setOpen]=useState(false),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false);
 const attempt=useRef<unknown>(null);
 const load=useCallback(async()=>{try{const result=await apiFetch<Awaited<ReturnType<typeof getChannelActivation>>>(`/api/organizations/${organizationId}/activation`);setData(result);setError("");}catch{setError(t("pool.loadFailed"));}},[organizationId,t]);
 useEffect(()=>{const controller=new AbortController();void apiFetch<Awaited<ReturnType<typeof getChannelActivation>>>(`/api/organizations/${organizationId}/activation`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setData(result);setError("");}}).catch(()=>{if(!controller.signal.aborted)setError(t("pool.loadFailed"));});return()=>controller.abort();},[organizationId,t]);
 const save=async(event?:React.FormEvent<HTMLFormElement>)=>{event?.preventDefault();if(pending||!data)return;if(!attempt.current&&event){const form=new FormData(event.currentTarget);attempt.current={stage:form.get("stage"),reason:form.get("reason"),expectedRevision:data.projection.profileRevision,requestKey:crypto.randomUUID()};}setPending(true);try{await apiFetch(`/api/organizations/${organizationId}/activation`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});attempt.current=null;setUncertain(false);setOpen(false);await load();await onSaved?.();}catch(caught){if(caught instanceof ApiClientError&&caught.status<500){attempt.current=null;setUncertain(false);setError(t(caught.code.includes("VERSION_CONFLICT")?"pool.conflict":"pool.forbidden"));}else{setUncertain(true);setError(t("pool.uncertain"));}}finally{setPending(false);}};
 if(!data)return <InlineMessage type={error?"error":"info"}>{error||t("common.loading")}</InlineMessage>;
 const p=data.projection;
 const metrics:[string,string,string][]=[["openLeadCount","LEAD","lead"],["claimedLeadCount","LEAD","assignment"],["keyContactCount","CONTACT","keyPeople"],["decisionMakerCount","CONTACT","decisionMakers"],["activeOpportunityCount","OPPORTUNITY","opportunity"],["recentRecruitmentEventCount","EVENT","events"],["primaryEnrollmentCount","ATTRIBUTION","primary"],["assistEnrollmentCount","ATTRIBUTION","assist"]];
 return <section className="detail-section"><div className="surface-heading"><h3>{t("pool.activation")}</h3>{manage&&p.canManage&&p.profileRevision&&<button className="secondary-button" onClick={()=>{setOpen(true);setError("");}}>{t("pool.updateStage")}</button>}</div>{error&&!open&&<InlineMessage type="error">{error}</InlineMessage>}<dl className="customer-profile"><div><dt>{t("pool.stage")}</dt><dd>{p.currentPartnershipStage?t(`business.option.${p.currentPartnershipStage}`):t("channel.unknown")}</dd><small>{t("pool.source.PROFILE")}</small></div><div><dt>{t("pool.stageSince")}</dt><dd>{p.stageChangedAt?formatDate(p.stageChangedAt,{includeTime:true}):t("channel.unknown")}</dd></div>{metrics.map(([key,source,label])=><div key={key}><dt>{t(`pool.${label}`)}</dt><dd>{String(p[key as keyof typeof p]??0)}</dd><small>{t(`pool.source.${source}`)}</small></div>)}</dl><p>{t("business.field.next_action")}: {p.nextAction||"—"}</p><div className="page-actions"><Link href={`/leads?organization=${organizationId}`}>{t("pool.lead")}</Link><Link href={`/opportunities`}>{t("pool.opportunity")}</Link><Link href="/education-business?resource=events">{t("pool.events")}</Link><Link href="/enrollments">{t("pool.primary")}</Link></div><div className="detail-record-list">{p.leads.map(l=><article key={l.id}><Link href={`/leads?focus=${l.id}`}>{t(`leads.status.${l.status.toLowerCase()}`)}</Link><span>{l.owner_id||t("pool.unassigned")}</span></article>)}{p.events.map(e=><article key={e.id}><Link href={`/education-business?resource=events&focus=${e.id}`}>{e.name}</Link><span>{formatDate(e.starts_on,{dateOnly:true})}</span></article>)}</div><h4>{t("pool.stageHistory")}</h4><div className="detail-record-list">{data.history.map(h=><article key={h.id}><div>{h.from_stage?t(`business.option.${h.from_stage}`):"—"} → {t(`business.option.${h.to_stage}`)}<p>{h.reason}</p><small>{formatDate(h.changed_at,{includeTime:true})}</small></div></article>)}</div>{!data.history.length&&<p>{t("pool.noHistory")}</p>}
 {open&&<AccessibleDrawer title={t("pool.updateStage")} pending={pending||uncertain} onClose={()=>setOpen(false)}><form onSubmit={e=>void save(e)}><fieldset className="follow-up-fields" disabled={pending||uncertain}><label className="field"><span>{t("pool.stage")}</span><select name="stage" defaultValue={p.currentPartnershipStage??"PROSPECT"}>{partnershipStages.map(stage=><option key={stage} value={stage}>{t(`business.option.${stage}`)}</option>)}</select></label><label className="field"><span>{t("pool.reason")}</span><textarea name="reason" maxLength={1000} required/></label></fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={()=>setOpen(false)}>{t("common.cancel")}</button><button className="primary-button" type={uncertain?"button":"submit"} disabled={pending} onClick={uncertain?()=>void save():undefined}>{t(uncertain?"business.retrySame":"common.save")}</button></div></form></AccessibleDrawer>}
 </section>;
}
