"use client";
import {AutomaticRecordNumber} from "./automatic-record-number";
import {RecordDeleteAction} from "./record-delete-action";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {agreementSaveSchema,type AgreementCollection,type AgreementVersion,type ChannelAgreement,type CommissionRule} from "@/lib/commission-input";
import {useI18n} from "./i18n-provider";
import {useCommissionMutation} from "./commission-mutation";
import {AccessibleDrawer,InlineMessage} from "./ui";
import {BilingualNameHint,CurrencySelect,DateInput,MoneyInput} from "./structured-inputs";
import {EnrollmentRelation} from "./enrollment-relation";
import {ContractDocumentsSection} from "./contract-documents-section";
const emptyRule=():CommissionRule=>({id:crypto.randomUUID(),scope_type:"ALL_PRODUCTS",product_id:null,cohort_id:null,attribution_type:"PRIMARY",basis_type:"FIXED_PER_ENROLLMENT",fixed_amount:"",fixed_currency:"CNY",rate_bps:null,earning_event:"ENROLLMENT_ACTIVE"});
export function ChannelAgreementsPanel({organizationId,onSaved}:{organizationId:string;onSaved?:()=>Promise<unknown>}){
 const {t,locale}=useI18n(),[data,setData]=useState<AgreementCollection|null>(null),[error,setError]=useState(""),[editor,setEditor]=useState<{agreement?:ChannelAgreement;version?:AgreementVersion;copy?:boolean}|null>(null),[action,setAction]=useState<{version:AgreementVersion;status:string}|null>(null);
 const load=useCallback(async()=>{const result=await apiFetch<AgreementCollection>(`/api/channel-agreements?organization=${organizationId}`);setData(result);},[organizationId]);
 useEffect(()=>{const controller=new AbortController();void apiFetch<AgreementCollection>(`/api/channel-agreements?organization=${organizationId}`,{signal:controller.signal}).then(setData).catch(()=>{if(!controller.signal.aborted)setError(t("commission.loadFailed"));});return()=>controller.abort();},[organizationId,t]);
 const mutation=useCommissionMutation(async()=>{setAction(null);await load();await onSaved?.();});
 return <section className="detail-section channel-agreements"><div className="surface-heading"><h3>{t("commission.agreements")}</h3>{data?.canManage&&<button className="secondary-button" onClick={()=>setEditor({})}>{t("commission.createAgreement")}</button>}</div>{error&&<InlineMessage type="error">{error}</InlineMessage>}{data&&!data.canFinance&&<InlineMessage type="info">{t("commission.unavailable")}</InlineMessage>}
 <div className="detail-record-list">{data?.items.map(a=><article className="channel-agreement-card" key={a.id}><div><h4>{(locale==="en"?a.name_en:a.name_zh)||a.name_en||a.name_zh} · {a.agreement_code}</h4>{a.versions.map(v=><div className="agreement-version" data-status={v.status} key={v.id}><b>{t("commission.version")} {v.version} · {t(`commission.status.${v.status}`)}</b><p>{v.effective_from} — {v.effective_to||t("commission.noEnd")}{v.expiredByDate&&` · ${t("commission.expiredByDate")}`}</p>{data.canFinance&&<ContractDocumentsSection sourceKind="CHANNEL_AGREEMENT_VERSION" sourceId={v.id} canManage={data.canManage}/>}{v.rules.map(r=><p className="agreement-rule-summary" key={r.id}>{t(`commission.scope.${r.scope_type}`)} · {r.product_id&&<span>{r.product_id} · </span>}{r.cohort_id&&<span>{r.cohort_id} · </span>}{t(`enrollments.type.${r.attribution_type}`)} · {t(`commission.basis.${r.basis_type}`)}{data.canFinance&&<span> · {r.basis_type==="FIXED_PER_ENROLLMENT"?`${r.fixed_currency} ${r.fixed_amount} · ${t(`commission.event.${r.earning_event}`)}`:`${r.rate_bps} ${t("commission.bps")}`}</span>}</p>)}{data.canManage&&<div className="page-actions">{v.status==="DRAFT"&&<><RecordDeleteAction kind="CHANNEL_AGREEMENT_VERSION" id={v.id} onDeleted={load}/><button className="secondary-button" onClick={()=>setEditor({agreement:a,version:v})}>{t("common.edit")}</button><button className="secondary-button" onClick={()=>{mutation.reset();setAction({version:v,status:"ACTIVE"});}}>{t("commission.activate")}</button></>}{v.status!=="DRAFT"&&<button className="secondary-button" onClick={()=>setEditor({agreement:a,version:v,copy:true})}>{t("commission.newVersion")}</button>}{v.status==="ACTIVE"&&["SUPERSEDED","TERMINATED","EXPIRED"].map(status=><button className="secondary-button" key={status} onClick={()=>{mutation.reset();setAction({version:v,status});}}>{t(`commission.status.${status}`)}</button>)}</div>}</div>)}</div></article>)}</div>{data&&!data.items.length&&<p>{t("commission.noAgreements")}</p>}
 {data?.canFinance&&<Link href={`/commissions?organization=${organizationId}`}>{t("commission.workspace")}</Link>}
 {editor&&<AgreementEditor organizationId={organizationId} {...editor} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);await load();await onSaved?.();}}/>}
 {action&&<AccessibleDrawer title={t(`commission.status.${action.status}`)} pending={mutation.pending||mutation.uncertain} onClose={()=>setAction(null)}><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void mutation.send(`/api/channel-agreements/${action.version.id}`,{expectedRevision:action.version.revision,status:action.status,reason:form.get("reason"),requestKey:crypto.randomUUID()});}}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain}><label className="field"><span>{t("commission.reason")}</span><textarea name="reason" maxLength={1000} required/></label></fieldset><MutationButtons mutation={mutation}/></form></AccessibleDrawer>}
 </section>;
}
export function MutationButtons({mutation}:{mutation:ReturnType<typeof useCommissionMutation>}){const {t}=useI18n();return <>{mutation.error&&<InlineMessage type="error">{mutation.error}</InlineMessage>}<div className="drawer-actions"><button className="primary-button" type={mutation.uncertain?"button":"submit"} disabled={mutation.pending} onClick={mutation.uncertain?()=>void mutation.send():undefined}>{t(mutation.uncertain?"business.retrySame":"common.save")}</button></div></>;}
function AgreementEditor({organizationId,agreement,version,copy,onClose,onSaved}:{organizationId:string;agreement?:ChannelAgreement;version?:AgreementVersion;copy?:boolean;onClose:()=>void;onSaved:()=>Promise<unknown>}){
 const {t}=useI18n(),[rules,setRules]=useState<CommissionRule[]>(version?.rules??[emptyRule()]),[error,setError]=useState("");const mutation=useCommissionMutation(onSaved);
 const [ids]=useState(()=>({id:agreement?.id??crypto.randomUUID(),versionId:version&&!copy?version.id:crypto.randomUUID()}));
 const edit=(index:number,patch:Partial<CommissionRule>)=>setRules(old=>old.map((r,i)=>i===index?{...r,...patch}:r));
 const save=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),text=(k:string)=>String(f.get(k)??"");const body={...ids,expectedRevision:version&&!copy?version.revision:null,requestKey:crypto.randomUUID(),data:{organization_id:organizationId,agreement_code:agreement?.agreement_code??text("code"),name_zh:agreement?.name_zh??text("nameZh"),name_en:agreement?.name_en??text("nameEn"),effective_from:text("from"),effective_to:text("to")||null,signed_on:text("signed")||null,reference_number:text("reference")||null,notes:text("notes"),rules:rules.map(r=>{const {id:_,financialTermsVisible:__,...rule}=r;void _;void __;return rule;})}};const parsed=agreementSaveSchema.safeParse(body);if(!parsed.success){setError(t("commission.invalid"));return;}setError("");void mutation.send("/api/channel-agreements",parsed.data);};
 return <AccessibleDrawer title={t(copy?"commission.newVersion":agreement?"common.edit":"commission.createAgreement")} pending={mutation.pending||mutation.uncertain} onClose={onClose}><form onSubmit={save}><fieldset disabled={mutation.pending||mutation.uncertain} className="follow-up-fields"><label className="field"><span>{t("commission.code")}</span>{agreement?<input name="code" value={agreement.agreement_code} disabled/>:<AutomaticRecordNumber name="code"/>}</label><label className="field"><span>{t("education.nameZh")}</span><input name="nameZh" defaultValue={agreement?.name_zh} disabled={!!agreement} maxLength={160}/></label><label className="field"><span>{t("education.nameEn")}</span><input name="nameEn" defaultValue={agreement?.name_en} disabled={!!agreement} maxLength={160}/></label><BilingualNameHint/><div className="form-grid two-column"><label className="field"><span>{t("commission.from")}</span><DateInput name="from" type="date" defaultValue={version?.effective_from} required/></label><label className="field"><span>{t("commission.to")}</span><DateInput name="to" type="date" defaultValue={version?.effective_to??""}/></label></div><label className="field"><span>{t("commission.signed")}</span><DateInput name="signed" type="date" defaultValue={version?.signed_on??""}/></label><label className="field"><span>{t("commission.reference")}</span><input name="reference" maxLength={160} defaultValue={version?.reference_number??""}/></label><label className="field"><span>{t("commission.notes")}</span><textarea name="notes" maxLength={4000} defaultValue={version?.notes??""}/></label>
 <h4>{t("commission.rules")}</h4>{rules.map((r,i)=><section className="detail-section" key={r.id}><div className="surface-heading"><b>{t("commission.rule")} {i+1}</b><button type="button" className="text-button" onClick={()=>setRules(old=>old.filter((_,n)=>n!==i))}>{t("commission.removeRule")}</button></div><label className="field"><span>{t("commission.scope")}</span><select value={r.scope_type} onChange={e=>edit(i,{scope_type:e.target.value as CommissionRule['scope_type'],product_id:null,cohort_id:null})}>{["ALL_PRODUCTS","PRODUCT","COHORT"].map(k=><option value={k} key={k}>{t(`commission.scope.${k}`)}</option>)}</select></label>{r.scope_type!=="ALL_PRODUCTS"&&<EnrollmentRelation type="PRODUCT" label={t("products.title")} required value={r.product_id??""} onChange={v=>edit(i,{product_id:v,cohort_id:null})}/>} {r.scope_type==="COHORT"&&<EnrollmentRelation type="COHORT" label={t("cohorts.title")} required value={r.cohort_id??""} onChange={v=>edit(i,{cohort_id:v})}/>}
 <label className="field"><span>{t("commission.attribution")}</span><select value={t(`enrollments.type.${r.attribution_type}`)} onChange={e=>edit(i,{attribution_type:e.target.value as CommissionRule['attribution_type']})}><option value="PRIMARY">{t("enrollments.type.PRIMARY")}</option><option value="ASSIST">{t("enrollments.type.ASSIST")}</option></select></label><label className="field"><span>{t("commission.basis")}</span><select value={r.basis_type} onChange={e=>edit(i,e.target.value==="FIXED_PER_ENROLLMENT"?{basis_type:"FIXED_PER_ENROLLMENT",fixed_amount:"",fixed_currency:"CNY",rate_bps:null,earning_event:"ENROLLMENT_ACTIVE"}:{basis_type:"PERCENT_OF_NET_COLLECTED",fixed_amount:null,fixed_currency:null,rate_bps:1000,earning_event:null})}>{["FIXED_PER_ENROLLMENT","PERCENT_OF_NET_COLLECTED"].map(k=><option key={k} value={k}>{t(`commission.basis.${k}`)}</option>)}</select></label>
 {r.basis_type==="FIXED_PER_ENROLLMENT"?<><label className="field"><span>{t("commission.amount")}</span><MoneyInput required value={r.fixed_amount??""} min="0.01" onValueChange={v=>edit(i,{fixed_amount:v})}/></label><label className="field"><span>{t("pipeline.currency")}</span><CurrencySelect value={r.fixed_currency??"CNY"} onChange={e=>edit(i,{fixed_currency:e.target.value})}/></label><label className="field"><span>{t("commission.earningEvent")}</span><select value={r.earning_event??"ENROLLMENT_ACTIVE"} onChange={e=>edit(i,{earning_event:e.target.value as CommissionRule['earning_event']})}>{["ENROLLMENT_ACTIVE","ENROLLMENT_COMPLETED"].map(k=><option key={k} value={k}>{t(`commission.event.${k}`)}</option>)}</select></label></>:<label className="field"><span>{t("commission.rate")}</span><input type="number" min={1} max={10000} step={1} required value={r.rate_bps??""} onChange={e=>edit(i,{rate_bps:e.target.value?Number(e.target.value):null})}/><small>{t("commission.rateHelp")}</small></label>}
 </section>)}<button type="button" className="secondary-button" disabled={rules.length>=50} onClick={()=>setRules(old=>[...old,emptyRule()])}>{t("commission.addRule")}</button></fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}<MutationButtons mutation={mutation}/></form></AccessibleDrawer>;
}
