"use client";
import {WorkspaceHeading} from "./workspace-heading";

import Link from "next/link";
import {FilterBar} from "./filter-bar";
import type {CommissionListFilters} from "@/lib/commission-repository";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {type Accrual,type Eligibility,type Settlement,type AgreementCollection,settlementSaveSchema} from "@/lib/commission-input";
import {formatFinanceAmount} from "@/lib/enrollment-finance";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {useCapability} from "./app-user-context";
import {EnrollmentRelation} from "./enrollment-relation";
import {ChannelAgreementsPanel,MutationButtons} from "./channel-agreements-panel";
import {useCommissionMutation} from "./commission-mutation";
import {AccessibleDrawer,InlineMessage} from "./ui";
import {CurrencySelect,DateInput} from "./structured-inputs";
export function CommissionWorkspace({initialOrganization=""}:{initialOrganization?:string}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),canSettle=useCapability("finance.payment.record");
 const [organization,setOrganization]=useState(initialOrganization),[tab,setTab]=useState("eligibility"),[access,setAccess]=useState<AgreementCollection|null>(null),[eligibility,setEligibility]=useState<Eligibility[]>([]),[accruals,setAccruals]=useState<Accrual[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]),[error,setError]=useState(""),[editor,setEditor]=useState<{settlement?:Settlement}|null>(null),[action,setAction]=useState<{settlement:Settlement;status:string}|null>(null),[generate,setGenerate]=useState<Eligibility|null>(null);
 const [filters,setFilters]=useState<CommissionListFilters>({}),[editorAccruals,setEditorAccruals]=useState<Accrual[]>([]);
 const generation=useRef(0);
 const load=useCallback(async()=>{if(!organization)return;const token=++generation.current;const filterQuery=new URLSearchParams(Object.entries(filters).filter(([,value])=>Boolean(value))).toString();const a=await apiFetch<AgreementCollection>(`/api/channel-agreements?organization=${organization}`);const e=await apiFetch<{available:boolean;items:Eligibility[]}>(`/api/commissions/eligibility?organization=${organization}`);const [ledger,batches]=a.canFinance?await Promise.all([apiFetch<{items:Accrual[]}>(`/api/commission-accruals?organization=${organization}&${filterQuery}`),apiFetch<{items:Settlement[]}>(`/api/commission-settlements?organization=${organization}&${filterQuery.replace(/(^|&)status=OPEN(&|$)/,"$1")}`)]):[{items:[]},{items:[]}];if(token!==generation.current)return;setAccess(a);setEligibility(e.items);setAccruals(ledger.items);setSettlements(batches.items);setError("");},[organization,filters]);
 useEffect(()=>{let current=true;if(organization)void load().catch(()=>{if(current)setError(t("commission.loadFailed"));});return()=>{current=false;};},[organization,load,t]);
 const mutation=useCommissionMutation(async()=>{setAction(null);setGenerate(null);await load();});
 const selectOrg=(id:string)=>{generation.current++;setOrganization(id);setAccess(null);setEligibility([]);setAccruals([]);setSettlements([]);setError("");};
 const openSettlement=async(settlement?:Settlement)=>{try{const result=await apiFetch<{items:Accrual[]}>(`/api/commission-accruals?organization=${organization}`);setEditorAccruals(result.items);setEditor({settlement});}catch{setError(t("commission.loadFailed"));}};
 const money=(v:string,c:string)=>`${c} ${v.startsWith("-")?"−":""}${formatFinanceAmount(v.replace(/^-/,""),locale)}`;
 return <div className="page-stack commission-workspace"><section className="page-heading-row"><div><p className="eyebrow">{t("finance.eyebrow")}</p><WorkspaceHeading>{t("commission.workspace")}</WorkspaceHeading><p>{t("commission.description")}</p></div></section><FilterBar applied={filters} defaults={{}} advancedCount={[filters.from,filters.to].filter(Boolean).length} activeCount={Object.values(filters).filter(Boolean).length} onReset={()=>setFilters({})} onApply={value=>{if(value.from&&value.to&&value.from>value.to){setError(t("commission.invalid"));return false;}setError("");setFilters(value);}} primaryFilters={<><EnrollmentRelation type="ORGANIZATION" label={t("commission.organization")} required value={organization} onChange={selectOrg}/><label className="field"><span>{t("pipeline.currency")}</span><select value={filters.currency??""} onChange={e=>setFilters(f=>({...f,currency:e.target.value||undefined}))}><option value="">{t("common.all")}</option>{["CNY","USD","GBP","EUR","HKD","SGD","AUD"].map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>{t("common.status")}</span><select value={filters.status??""} onChange={e=>setFilters(f=>({...f,status:e.target.value||undefined}))}><option value="">{t("common.all")}</option>{["OPEN","DRAFT","APPROVED","PAID","CANCELLED"].map(value=><option key={value} value={value}>{value==="OPEN"?t("commission.open"):t(`commission.status.${value}`)}</option>)}</select></label></>} summary={<small>{t("repair.commissionScope")}</small>} renderAdvanced={(draft,change)=><>{(["from","to"] as const).map(key=><label className="field" key={key}><span>{t(`commission.${key}`)}</span><DateInput value={draft[key]??""} onChange={e=>change({...draft,[key]:e.target.value||undefined})}/></label>)}<p>{t("repair.utcPeriod")}</p></>}/>{error&&<InlineMessage type="error">{error}</InlineMessage>}{!organization&&<InlineMessage type="info">{t("commission.selectOrganization")}</InlineMessage>}
 {organization&&<><details className="operational-disclosure"><summary>{t("repair.channelConfiguration")}</summary><ChannelAgreementsPanel key={organization} organizationId={organization} onSaved={load}/></details><div className="page-actions" role="tablist" aria-label={t("commission.workspace")}>{["eligibility","accruals","settlements"].map(k=><button role="tab" aria-selected={tab===k} key={k} className={tab===k?"primary-button":"secondary-button"} onClick={()=>setTab(k)}>{t(`commission.${k}`)}</button>)}</div>{access&&!access.canFinance&&<InlineMessage type="info">{t("commission.unavailable")}</InlineMessage>}
 {tab==="eligibility"&&<section className="surface"><h2>{t("commission.eligibility")}</h2><div className="business-record-grid">{eligibility.map((e,i)=><article className="detail-section" key={`${e.ruleId}:${e.enrollmentId}:${e.sourceId}:${i}`}><b>{t(`commission.eligibility.${e.eligibilityStatus}`)}</b>{e.enrollmentId&&<p><Link href={`/enrollments?focus=${e.enrollmentId}`}>{t("commission.enrollment")} · {e.enrollmentId}</Link></p>}{access?.canFinance&&<><p>{t("commission.rule")}: {e.ruleId} · {t(`enrollments.type.${e.attributionType}`)}</p><p>{t("commission.productCohort")}: {e.productId} / {e.cohortId}</p>{e.basisType&&<p>{t(`commission.basis.${e.basisType}`)}</p>}{e.eligibleBasis!==null&&e.currency&&<p>{t("commission.eligibleBasis")}: {money(e.eligibleBasis,e.currency)}</p>}{e.commissionPreview!==null&&e.currency&&<p>{t("commission.preview")}: {money(e.commissionPreview,e.currency)}</p>}{access.canManage&&e.eligibilityStatus==="ELIGIBLE"&&<button className="secondary-button" onClick={()=>{mutation.reset();setGenerate(e);}}>{t("commission.generate")}</button>}</>}</article>)}</div>{access?.canFinance&&!eligibility.length&&<p>{t("commission.empty")}</p>}</section>}
 {tab==="accruals"&&access?.canFinance&&<section className="surface"><h2>{t("commission.accruals")}</h2><p>{t("commission.ledgerHelp")}</p><p>{t("commission.listLimit")}</p><div className="business-record-grid">{accruals.map(a=><article className="detail-section" key={a.id}><b>{money(a.commission_text,a.currency)} · {t(`commission.entry.${a.entry_type}`)}</b><p>{t("commission.eligibleBasis")}: {money(a.basis_text,a.currency)}</p><p>{t("commission.rule")}: {a.rule_id}</p><p>{t("commission.source")}: {t(`commission.source.${a.source_type}`)} · {a.source_id||"—"}</p><p>{formatDate(a.accrued_at,{includeTime:true})} · {a.settlement_status?t(`commission.status.${a.settlement_status}`):t("commission.open")}</p>{a.enrollment_id&&<Link href={`/enrollments?focus=${a.enrollment_id}`}>{t("commission.enrollment")}</Link>}</article>)}</div>{!accruals.length&&<p>{t("commission.empty")}</p>}</section>}
 {tab==="settlements"&&access?.canFinance&&<section className="surface"><p>{t("commission.listLimit")}</p><div className="surface-heading"><h2>{t("commission.settlements")}</h2>{canSettle&&<button className="secondary-button" onClick={()=>void openSettlement()}>{t("commission.createSettlement")}</button>}</div><div className="business-record-grid">{settlements.map(s=><article className="detail-section" key={s.id}><b>{s.reference_number||s.id}</b><p>{t(`commission.status.${s.status}`)} · {money(s.net_amount,s.currency)}</p><p>{t("commission.lines")}: {s.line_count} · {s.period_start||"—"} — {s.period_end||"—"}</p>{s.payment_reference&&<p>{t("commission.paymentReference")}: {s.payment_reference}</p>}{canSettle&&["DRAFT","APPROVED"].includes(s.status)&&<div className="page-actions">{s.status==="DRAFT"&&<button className="secondary-button" onClick={()=>void openSettlement(s)}>{t("common.edit")}</button>}{[s.status==="DRAFT"?"APPROVED":"PAID","CANCELLED"].map(status=><button className="secondary-button" key={status} onClick={()=>{mutation.reset();setAction({settlement:s,status});}}>{t(`commission.action.${status}`)}</button>)}</div>}</article>)}</div>{!settlements.length&&<p>{t("commission.empty")}</p>}</section>}
 </>}
 {editor&&<SettlementEditor organizationId={organization} accruals={editorAccruals} settlement={editor.settlement} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);await load();}}/>}
 {action&&<AccessibleDrawer title={t(`commission.action.${action.status}`)} pending={mutation.pending||mutation.uncertain} onClose={()=>setAction(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutation.send(`/api/commission-settlements/${action.settlement.id}`,{expectedRevision:action.settlement.revision,status:action.status,reference:String(f.get("reference")??""),reason:String(f.get("reason")??""),requestKey:crypto.randomUUID()});}}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain}>{action.status==="PAID"&&<><InlineMessage type="info">{t("commission.paidHelp")}</InlineMessage><label className="field"><span>{t("commission.paymentReference")}</span><input name="reference" required maxLength={160}/></label></>}{action.status==="CANCELLED"&&<label className="field"><span>{t("commission.reason")}</span><textarea name="reason" required maxLength={1000}/></label>}<p>{money(action.settlement.net_amount,action.settlement.currency)}</p></fieldset><MutationButtons mutation={mutation}/></form></AccessibleDrawer>}
 {generate&&<AccessibleDrawer title={t("commission.generate")} pending={mutation.pending||mutation.uncertain} onClose={()=>setGenerate(null)}><form onSubmit={e=>{e.preventDefault();void mutation.send("/api/commission-accruals",{ruleId:generate.ruleId,enrollmentId:generate.enrollmentId,paymentId:generate.sourceType==="PAYMENT"?generate.sourceId:null,requestKey:crypto.randomUUID()});}}><p>{t("commission.generateHelp")}</p><MutationButtons mutation={mutation}/></form></AccessibleDrawer>}
 </div>;
}
function SettlementEditor({organizationId,accruals,settlement,onClose,onSaved}:{organizationId:string;accruals:Accrual[];settlement?:Settlement;onClose:()=>void;onSaved:()=>Promise<unknown>}){
 const {t,locale}=useI18n(),[currency,setCurrency]=useState(settlement?.currency??"CNY"),[selected,setSelected]=useState<string[]>(accruals.filter(a=>settlement&&a.settlement_id===settlement.id).map(a=>a.id)),[error,setError]=useState("");const mutation=useCommissionMutation(onSaved),[id]=useState(settlement?.id??crypto.randomUUID());
 const candidates=accruals.filter(a=>a.currency===currency&&(!a.settlement_id||a.settlement_id===settlement?.id));
 const cents=(v:string)=>{const sign=v.startsWith("-")?-BigInt(1):BigInt(1),[whole,fraction=""]=v.replace(/^-/,'').split('.');return sign*(BigInt(whole)*BigInt(100)+BigInt(fraction.padEnd(2,'0')));};const sum=candidates.filter(a=>selected.includes(a.id)).reduce((s,a)=>s+cents(a.commission_text),BigInt(0));const abs=sum<BigInt(0)?-sum:sum,display=`${sum<BigInt(0)?"−":""}${formatFinanceAmount(`${abs/BigInt(100)}.${String(abs%BigInt(100)).padStart(2,'0')}`,locale)}`;
 const save=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),s=(k:string)=>String(f.get(k)??"");const parsed=settlementSaveSchema.safeParse({id,expectedRevision:settlement?.revision??null,requestKey:crypto.randomUUID(),data:{organization_id:organizationId,currency,period_start:s("from")||null,period_end:s("to")||null,reference_number:s("reference")||null,notes:s("notes"),accrual_ids:selected}});if(!parsed.success){setError(t("commission.invalid"));return;}setError("");void mutation.send("/api/commission-settlements",parsed.data);};
 return <AccessibleDrawer title={t("commission.createSettlement")} pending={mutation.pending||mutation.uncertain} onClose={onClose}><form onSubmit={save}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain}><label className="field"><span>{t("pipeline.currency")}</span><CurrencySelect value={currency} disabled={!!settlement} onChange={e=>{setCurrency(e.target.value);setSelected([]);}}/></label><div className="form-grid two-column"><label className="field"><span>{t("commission.from")}</span><DateInput type="date" name="from" defaultValue={settlement?.period_start??""}/></label><label className="field"><span>{t("commission.to")}</span><DateInput type="date" name="to" defaultValue={settlement?.period_end??""}/></label></div><label className="field"><span>{t("commission.reference")}</span><input name="reference" maxLength={160} defaultValue={settlement?.reference_number??""}/></label><label className="field"><span>{t("commission.notes")}</span><textarea name="notes" maxLength={4000} defaultValue={settlement?.notes??""}/></label><h4>{t("commission.selectAccruals")}</h4>{candidates.map(a=><label className="field" key={a.id}><span><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,a.id]:ids.filter(v=>v!==a.id))}/> {a.id} · {a.currency} {a.commission_text} · {t(`commission.entry.${a.entry_type}`)}</span></label>)}{!candidates.length&&<p>{t("commission.empty")}</p>}<p>{t("commission.net")}: {currency} {display}</p><small>{t("commission.netHelp")}</small></fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}<MutationButtons mutation={mutation}/></form></AccessibleDrawer>;
}
