"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { Mail,Plus,RotateCcw,Send } from "lucide-react";
import { AccessibleDrawer,InlineMessage,SearchableSelect,SearchField,StatusBadge,Toast } from "./ui";
import { useI18n } from "./i18n-provider";
import { apiFetch } from "@/lib/api-client";
import type { CommunicationInboxResult } from "@/lib/v220-repository";

const communicationPurposes=["SERVICE","TRANSACTIONAL","EVENT","MARKETING"] as const;

export function CommunicationsInboxPage({initial}:{initial:CommunicationInboxResult}){const{locale,t}=useI18n();const[items,setItems]=useState(initial.items);const[total,setTotal]=useState(initial.total);const[truncated,setTruncated]=useState(initial.truncated);const[selectedId,setSelectedId]=useState(initial.items[0]?.id??"");const[open,setOpen]=useState(false);const[contact,setContact]=useState("");const[contacts,setContacts]=useState<Array<{value:string;label:string;detail:string}>>([]);const[pending,setPending]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");const[query,setQuery]=useState("");const operationLock=useRef(false);const messageRequest=useRef<{operation:"send"|"inbound";threadId:string;body:string;key:string}|null>(null);const selected=useMemo(()=>items.find(item=>item.id===selectedId)??null,[items,selectedId]);const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?items.filter(item=>[item.contactZh,item.contactEn,item.email,item.subject,...item.messages.map(message=>message.body)].some(value=>value.toLowerCase().includes(needle))):items;},[items,query]);const applyResult=useCallback((result:CommunicationInboxResult)=>{setItems(result.items);setTotal(result.total);setTruncated(result.truncated);setSelectedId(current=>result.items.some(item=>item.id===current)?current:(result.items[0]?.id??""));},[]);
  useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>{void apiFetch<CommunicationInboxResult>(`/api/communications?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal}).then(result=>{applyResult(result);setError("");}).catch(()=>{if(!controller.signal.aborted)setError(t("communications.failed"));});},250);return()=>{window.clearTimeout(timer);controller.abort();};},[applyResult,query,t]);
  const searchContacts=useCallback(async(query:string)=>{const result=await apiFetch<{items:Array<{value:string;labelZh:string;labelEn:string;type:string}>}>(`/api/search/related?q=${encodeURIComponent(query)}`).catch(()=>({items:[]}));setContacts(result.items.filter(item=>item.type==="CONTACT").map(item=>({value:item.value.split(":")[1]??"",label:locale==="zh-CN"?item.labelZh:item.labelEn,detail:t("nav.people")})));},[locale,t]);
  const reload=async()=>{const result=await apiFetch<CommunicationInboxResult>("/api/communications").catch(()=>null);if(result)applyResult(result);};
  const operate=async(body:Record<string,unknown>)=>{if(operationLock.current)return false;operationLock.current=true;setPending(true);setError("");try{const result=await apiFetch<CommunicationInboxResult>("/api/communications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});applyResult(result);return true;}catch(caught){const code=caught instanceof Error?caught.message:"";setError(code.includes("CONSENT")?t("communications.consentRequired"):code.includes("NOT_CONFIGURED")?t("communications.deliveryMissing"):t("communications.failed"));await reload();return false;}finally{operationLock.current=false;setPending(false);}};
  const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(!contact){setError(t("communications.contactRequired"));return;}if(await operate({operation:"thread",contactId:contact,subject:form.get("subject"),channel:"EMAIL",purpose:form.get("purpose")})){setOpen(false);setContact("");setToast(t("communications.created"));}};
  const send=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);const submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const operation:"send"|"inbound"=submitter?.value==="inbound"?"inbound":"send";const body=String(form.get("body")??"").trim();const prior=messageRequest.current;const request=prior&&prior.operation===operation&&prior.threadId===selected.id&&prior.body===body?prior:{operation,threadId:selected.id,body,key:crypto.randomUUID()};messageRequest.current=request;if(await operate({operation,threadId:selected.id,body,idempotencyKey:request.key})){messageRequest.current=null;event.currentTarget.reset();setToast(t(operation==="inbound"?"communications.recorded":"communications.sent"));}};
  const retry=async(messageId:string)=>{if(await operate({operation:"retry",messageId}))setToast(t("communications.retryQueued"));};
  return <div className="page-stack communications-page"><section className="page-heading-row"><div><p className="eyebrow">{t("communications.eyebrow")}</p><h1>{t("communications.title")}</h1><p>{t("communications.help")}</p></div><button className="primary-button" type="button" disabled={pending} onClick={()=>setOpen(true)}><Plus size={17}/>{t("communications.new")}</button></section><InlineMessage type="info">{t("communications.governance")}</InlineMessage>{error&&!open&&<InlineMessage type="error">{error}</InlineMessage>}<section className="communications-layout surface"><aside><div className="communications-search"><SearchField value={query} onChange={setQuery} placeholder={t("communications.search")}/></div>{truncated&&<p className="communications-limit" role="status">{t("communications.truncated",{shown:items.length,total})}</p>}{visible.map(item=><button type="button" className={item.id===selectedId?"active":""} onClick={()=>{messageRequest.current=null;setSelectedId(item.id);}} key={item.id}><Mail size={17}/><span><b>{locale==="zh-CN"?item.contactZh:item.contactEn}</b><small>{item.subject}</small></span><StatusBadge tone={item.status==="OPEN"?"green":"gray"}>{t(`communications.status.${item.status.toLowerCase()}`)}</StatusBadge></button>)}{!visible.length&&<div className="empty-state"><span>{t(query?"communications.noResults":"communications.empty")}</span></div>}</aside><article className="communication-thread">{selected?<><header><div><h2>{selected.subject}</h2><p>{locale==="zh-CN"?selected.contactZh:selected.contactEn} · {selected.email} · {t(`communications.purpose.${selected.purpose.toLowerCase()}`)}</p></div></header><div className="communication-messages">{selected.messages.map(message=><div className={message.direction.toLowerCase()} key={message.id}><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString(locale)} · {t(`communications.delivery.${message.deliveryStatus.toLowerCase()}`)} · {t("communications.attempts")} {message.attemptCount}{message.lastError?` · ${message.lastError}`:""}</small>{message.direction==="OUTBOUND"&&message.deliveryStatus==="FAILED"&&<button className="text-button" type="button" disabled={pending} onClick={()=>void retry(message.id)}><RotateCcw size={14}/>{t("communications.retry")}</button>}</div>)}</div><form className="communication-composer" onSubmit={send} onChange={()=>{if(!pending)messageRequest.current=null;}}><label className="field"><span>{t("communications.message")}</span><textarea name="body" rows={4} required maxLength={10000}/></label><div className="drawer-actions"><button className="secondary-button" name="intent" value="inbound" disabled={pending}>{t("communications.recordInbound")}</button><button className="primary-button" name="intent" value="send" disabled={pending}><Send size={16}/>{pending?t("common.processing"):t("communications.send")}</button></div></form></>:<div className="empty-state"><span>{t("communications.choose")}</span></div>}</article></section>
    {open&&<AccessibleDrawer title={t("communications.new")} description={t("communications.purposeHelp")} onClose={()=>setOpen(false)}><form onSubmit={create}><SearchableSelect label={t("privacyRequests.contact")} value={contact} options={contacts} onChange={setContact} onSearch={searchContacts}/><label className="field"><span>{t("communications.subject")}</span><input name="subject" required maxLength={200}/></label><label className="field"><span>{t("communications.purpose")}</span><select name="purpose" defaultValue="SERVICE">{communicationPurposes.map(value=><option key={value} value={value}>{t(`communications.purpose.${value.toLowerCase()}`)}</option>)}</select><small>{t("communications.purposeClassification")}</small></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setOpen(false)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t("common.create")}</button></div></form></AccessibleDrawer>}{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
