"use client";

import { useState } from "react";
import { ChartNoAxesCombined, CircleDollarSign, ReceiptText, RefreshCcw, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import { InlineMessage, ProgressBar, StatusBadge } from "@/components/ui";
import type { ConsumptionPeriod as Period, ConsumptionResult } from "@/lib/consumption-repository";
import { apiFetch } from "@/lib/api-client";

export function ConsumptionAnalysisPage({ initialData, persistent = false }: { initialData: ConsumptionResult; persistent?: boolean }) {
  const { locale, t } = useI18n(); const [period,setPeriod] = useState<Period>(initialData.period);const [currency,setCurrency]=useState(initialData.currency);
  const [cache,setCache] = useState<Record<string,ConsumptionResult>>({[`${initialData.period}:${initialData.currency}`]:initialData}); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const load=async(next:Period,nextCurrency:string)=>{const key=`${next}:${nextCurrency}`;if(!persistent||cache[key])return;setLoading(true);setError("");try{const result=await apiFetch<{data:ConsumptionResult}>(`/api/analytics/consumption?period=${next}&currency=${nextCurrency}`);setCache(current=>({...current,[key]:result.data}));}catch{setError(t("consumption.loadFailed"));}finally{setLoading(false);}};
  const choosePeriod=async(next:Period)=>{setPeriod(next);await load(next,currency);};
  const chooseCurrency=async(next:string)=>{setCurrency(next);await load(period,next);};
  const data = cache[`${period}:${currency}`] ?? initialData;
  const mix = data.productMix;
  const customers = data.topCustomers;
  const money = (value:number) => new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en",{style:"currency",currency:data.currency,notation:value>=1_000_000?"compact":"standard",maximumFractionDigits:1}).format(value);
  const maxTrend = Math.max(1,...data.trend.map(([,value])=>value)); const mixTotal = Math.max(1,mix.reduce((sum,item)=>sum+item.value,0));
  const segmentTotals = {school:customers.filter(item=>item.customerType==="school").reduce((sum,item)=>sum+item.amount,0),family:customers.filter(item=>item.customerType==="family").reduce((sum,item)=>sum+item.amount,0)};
  return <div className="page-stack consumption-page">
    <section className="page-heading-row"><div><p className="eyebrow">{t("consumption.eyebrow")}</p><h1>{t("consumption.title")}</h1><p>{t("consumption.description")}</p></div><div className="page-actions">{initialData.availableCurrencies.length>1&&<label className="compact-select"><span>{t("consumption.currency")}</span><select value={currency} onChange={(event)=>chooseCurrency(event.target.value)}>{initialData.availableCurrencies.map(item=><option key={item}>{item}</option>)}</select></label>}<div className="period-switch consumption-period" aria-label={t("consumption.period")}>{(["month","quarter","year"] as Period[]).map(item=><button type="button" className={period===item?"active":""} onClick={()=>choosePeriod(item)} key={item}>{t(`consumption.${item}`)}</button>)}</div></div></section>
    {loading&&<InlineMessage type="warning">{t("consumption.loading")}</InlineMessage>}{error&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="consumption-summary"><ConsumptionKpi icon={CircleDollarSign} tone="green" value={money(data.total)} label={t("consumption.confirmed")} detail={t("consumption.compared",{value:data.compare})}/><ConsumptionKpi icon={ReceiptText} tone="blue" value={String(data.orders)} label={t("consumption.orders")} detail={data.label}/><ConsumptionKpi icon={ShoppingBag} tone="purple" value={money(data.average)} label={t("consumption.average")} detail={t("consumption.orderBasis")}/><ConsumptionKpi icon={RefreshCcw} tone="amber" value={`${data.renewal}%`} label={t("consumption.renewal")} detail={t("consumption.rollingYear")}/></section>
    <section className="consumption-main-grid">
      <article className="surface consumption-trend"><div className="surface-heading"><div><p className="eyebrow">{t("consumption.trendEyebrow")}</p><h2>{t("consumption.trend",{period:data.label})}</h2></div><StatusBadge tone={data.compare>=0?"green":"red"}><TrendingUp size={13}/>{t("consumption.growth",{value:data.compare})}</StatusBadge></div><div className="consumption-bars" role="img" aria-label={t("consumption.chart",{period:data.label})}>{data.trend.map(([label,value])=><div key={label}><span style={{height:`${value?Math.max(6,value/maxTrend*100):0}%`}}/><b>{label}</b><small>{value?money(value):t("common.notStarted")}</small></div>)}</div></article>
      <article className="surface product-mix-card"><div className="surface-heading"><div><p className="eyebrow">{t("consumption.productMixEyebrow")}</p><h2>{t("consumption.productMix")}</h2></div><ChartNoAxesCombined size={20}/></div>{mix.map(item=>{const percent=Math.round(item.value/mixTotal*100);return <div className="product-mix-row" key={`${item.nameEn}-${item.color}`}><span className={item.color}/><div><b>{locale==="zh-CN"?item.nameZh:item.nameEn}</b><small>{t("consumption.customerLearnerCount",{count:item.customers})}</small></div><ProgressBar value={percent} label={`${percent}%`}/><strong>{money(item.value)}</strong></div>})}{!mix.length&&<div className="empty-state"><span>{t("consumption.noData")}</span></div>}</article>
    </section>
    <section className="consumption-segments"><SegmentCard icon={Users} title={t("consumption.schoolCustomer")} amount={money(segmentTotals.school)} detail={t("consumption.schoolDetail")}/><SegmentCard icon={Users} title={t("consumption.familyCustomer")} amount={money(segmentTotals.family)} detail={t("consumption.familyDetail")}/><SegmentCard icon={ShoppingBag} title={t("consumption.newCustomer")} amount={money(data.newCustomerTotal)} detail={t("consumption.newDetail")}/></section>
    <section className="surface top-consumers"><div className="surface-heading"><div><p className="eyebrow">{t("consumption.topEyebrow")}</p><h2>{t("consumption.topCustomers")}</h2></div><StatusBadge tone="blue">{t("consumption.byConfirmed")}</StatusBadge></div><div className="top-consumer-head"><span>{t("consumption.customer")}</span><span>{t("consumption.customerType")}</span><span>{t("consumption.purchasedProducts")}</span><span>{t("consumption.spend")}</span><span>{t("consumption.change")}</span></div>{customers.map(customer=><div className="top-consumer-row" key={customer.nameEn}><b>{locale==="zh-CN"?customer.nameZh:customer.nameEn}</b><span>{t(customer.customerType==="school"?"consumption.schoolCustomer":customer.customerType==="family"?"consumption.familyCustomer":"common.other")}</span><span>{(locale==="zh-CN"?customer.productsZh:customer.productsEn).join(" + ")||"—"}</span><strong>{money(customer.amount)}</strong><em>—</em></div>)}{!customers.length&&<div className="empty-state"><span>{t("consumption.noData")}</span></div>}</section>
  </div>;
}
function ConsumptionKpi({icon:Icon,tone,value,label,detail}:{icon:React.ElementType;tone:string;value:string;label:string;detail:string}){return <article className="surface consumption-kpi"><span className={tone}><Icon size={21}/></span><div><b>{value}</b><span>{label}</span><small>{detail}</small></div></article>}
function SegmentCard({icon:Icon,title,amount,detail}:{icon:React.ElementType;title:string;amount:string;detail:string}){return <article className="surface segment-card"><span><Icon size={20}/></span><div><small>{title}</small><b>{amount}</b><p>{detail}</p></div></article>}
