"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import type {ContractEnrollmentLink} from "@/lib/contract-enrollment-repository";
import type {ContractEnrollmentMutation} from "@/lib/contract-enrollment-input";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {useCapability} from "./app-user-context";
import {useRemoteSearch} from "@/hooks/use-remote-search";
import {InlineMessage,SearchableSelect,StatusBadge} from "./ui";
export function ContractEnrollmentSection({contractId,enrollmentId,onLocked}:{contractId?:string;enrollmentId?:string;onLocked?:(locked:boolean)=>void}){
  const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),canManage=useCapability("contracts.manage"),latest=useRemoteSearch();
  const [items,setItems]=useState<ContractEnrollmentLink[]>([]),[page,setPage]=useState(1),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false),[editing,setEditing]=useState<"link"|ContractEnrollmentLink|null>(null),[chosen,setChosen]=useState(""),[reason,setReason]=useState(""),[options,setOptions]=useState<Array<{value:string;label:string}>>([]),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false);
  const attempt=useRef<ContractEnrollmentMutation|null>(null),busy=useRef(false);
  const endpoint=contractId?`/api/contracts/${contractId}/enrollments`:`/api/enrollments?resource=contracts&id=${enrollmentId}`;
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const result=await apiFetch<{items:ContractEnrollmentLink[]}>(`${endpoint}${contractId?"?":"&"}page=${page}`,{signal});if(!signal?.aborted){setItems(result.items);setError("");}}catch(error){if(!signal?.aborted){setError(presentApiError(error,t,"commercial.loadFailed").message);throw error;}}finally{if(!signal?.aborted)setLoading(false);}},[endpoint,contractId,page,t]);
  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal).catch(()=>{}),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
  const search=async(query:string)=>{const result=await latest(signal=>apiFetch<{items:Array<{enrollment_id:string;student_name_zh:string;student_name_en:string;cohort_name_zh:string;cohort_name_en:string}>}>(`/api/contracts/${contractId}/enrollments?resource=options&q=${encodeURIComponent(query)}`,{signal}));if(!result.current)return;if("error" in result){setError(t("commercial.loadFailed"));return;}setOptions(result.value.items.map(item=>({value:item.enrollment_id,label:`${locale==="en"?item.student_name_en:item.student_name_zh} · ${locale==="en"?item.cohort_name_en:item.cohort_name_zh}`})));};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!contractId||!editing||busy.current)return;if(!attempt.current){if(editing==="link"&&!chosen||editing!=="link"&&!reason.trim()){setError(t("commercial.required"));return;}attempt.current=editing==="link"?{operation:"link",id:crypto.randomUUID(),enrollmentId:chosen,requestKey:crypto.randomUUID()}:{operation:"unlink",id:editing.id,expectedRevision:editing.revision,reason:reason.trim(),requestKey:crypto.randomUUID()};}
    busy.current=true;setPending(true);onLocked?.(true);setError("");try{await apiFetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);onLocked?.(unknown);if(!unknown)attempt.current=null;setError(presentApiError(error,t,"commercial.saveFailed").message);busy.current=false;setPending(false);return;}
    attempt.current=null;setUncertain(false);onLocked?.(false);setEditing(null);setNotice(t("commercial.saved"));try{await load();}catch{setNotice(t("enrollments.savedRefreshFailed"));}busy.current=false;setPending(false);
  };
  const label=(zh?:string|null,en?:string|null)=>(locale==="en"?en:zh)||zh||en||"—";
  return <section className="detail-section" aria-label={t(contractId?"commercial.relatedEnrollments":"commercial.relatedContracts")}><div className="surface-heading"><h3>{t(contractId?"commercial.relatedEnrollments":"commercial.relatedContracts")}</h3>{contractId&&canManage&&!editing&&<button className="secondary-button" type="button" onClick={()=>{setEditing("link");setChosen("");setReason("");setError("");}}>{t("commercial.link")}</button>}</div>{notice&&<InlineMessage type="success">{notice}</InlineMessage>}{error&&<InlineMessage type="error">{error}<button type="button" className="secondary-button" disabled={pending||uncertain} onClick={()=>void load().catch(()=>{})}>{t("common.retry")}</button></InlineMessage>}{loading&&<p role="status">{t("common.loading")}</p>}{!loading&&!items.length&&!error&&<p className="detail-empty">{t("commercial.emptyLinks")}</p>}
    {editing&&<form onSubmit={save} aria-label={t(editing==="link"?"commercial.link":"commercial.unlink")}><fieldset className="follow-up-fields" disabled={pending||uncertain}>{editing==="link"?<SearchableSelect label={t("enrollments.title")} value={chosen} onChange={setChosen} onSearch={search} options={options} required/>:<label className="field"><span>{t("commercial.unlinkReason")}</span><textarea name="unlink_reason" value={reason} onChange={event=>setReason(event.target.value)} maxLength={1000} required/></label>}</fieldset>{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={()=>setEditing(null)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"enrollments.retry":"common.save")}</button></div></form>}
    <div className="detail-record-list">{items.map(item=><article key={item.id}><div>{contractId?<><Link href={`/enrollments?focus=${item.enrollment_id}`}><b>{label(item.student_name_zh,item.student_name_en)}</b></Link><small>{label(item.product_name_zh,item.product_name_en)} · {label(item.cohort_name_zh,item.cohort_name_en)} · {t(`enrollments.status.${item.enrollment_status}`)}</small></>:<><Link href={`/contracts?query=${encodeURIComponent(item.contract_number)}&focus=${item.contract_id}`}><b>{item.contract_number}</b></Link><small>{t(`contracts.status.${({PENDING_APPROVAL:"pending",RENEWAL_PREP:"preparing"} as Record<string,string>)[item.contract_status]??item.contract_status.toLowerCase()}`)} · {item.currency} {Number(item.contract_value).toLocaleString(locale)} · {label(item.buyer_organization_zh??item.buyer_household_zh,item.buyer_organization_en??item.buyer_household_en)}</small></>}<small>{formatDate(item.linked_at,{includeTime:true})}{item.unlinked_at?` → ${formatDate(item.unlinked_at,{includeTime:true})}`:""}</small>{item.unlink_reason&&<p>{item.unlink_reason}</p>}</div><div className="detail-actions"><StatusBadge tone={item.status==="ACTIVE"?"green":"gray"}>{t(`commercial.linkStatus.${item.status}`)}</StatusBadge>{contractId&&item.can_edit&&item.status==="ACTIVE"&&!editing&&<button type="button" className="secondary-button" onClick={()=>{setEditing(item);setReason("");setError("");}}>{t("commercial.unlink")}</button>}</div></article>)}</div><div className="detail-actions"><button type="button" className="secondary-button" disabled={pending||uncertain||loading||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button type="button" className="secondary-button" disabled={pending||uncertain||loading||items.length<20} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div></section>;
}
