"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {useI18n} from './i18n-provider';
import {InlineMessage} from './ui';
import {apiFetch} from '@/lib/api-client';
import type {DocumentSourceKind,DocumentRequest} from '@/lib/contract-document-repository';
import type {UploadedRecord,EvidenceDetail,ExtractionCandidate} from '@/lib/contract-upload-repository';
type ReviewInput={runId:string;candidateKey:string;decision:string;confirmedValue:string|boolean|null;expectedRevision:number;expectedSourceRevision:number;requestKey:string;reason:string};
export function ContractUploadEvidence({sourceKind,sourceId,sourceRevision,context,canManage}:{sourceKind:DocumentSourceKind;sourceId:string;sourceRevision:number;context:DocumentRequest['context'];canManage:boolean}){
 const {t,locale}=useI18n(),[items,setItems]=useState<UploadedRecord[]>([]),[detail,setDetail]=useState<EvidenceDetail|null>(null),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reveal,setReveal]=useState(false),[edit,setEdit]=useState(''),[value,setValue]=useState(''),[reason,setReason]=useState(''),[uncertain,setUncertain]=useState(false);
 const pendingUpload=useRef<{file:File;input:Record<string,unknown>}|null>(null),pendingReview=useRef<{id:string;input:ReviewInput}|null>(null);
 const load=useCallback(async()=>{const result=await apiFetch<{items:UploadedRecord[]}>(`/api/contract-document-uploads?sourceKind=${sourceKind}&sourceId=${sourceId}`);setItems(result.items);},[sourceKind,sourceId]);
 useEffect(()=>{let active=true;void apiFetch<{items:UploadedRecord[]}>(`/api/contract-document-uploads?sourceKind=${sourceKind}&sourceId=${sourceId}`).then(r=>{if(active)setItems(r.items);}).catch(()=>{if(active)setMessage(t('uploads.failed'));});return()=>{active=false;};},[sourceKind,sourceId,t]);
 const open=async(id:string,show=reveal)=>{const result=await apiFetch<EvidenceDetail>(`/api/contract-document-uploads/${id}?reveal=${show}`);setDetail(result);setReveal(show);setEdit('');};
 const failed=(error:unknown)=>{const e=error as {status?:number;code?:string};if(!e.status||e.status>=500){setUncertain(true);setMessage(t('uploads.uncertain'));}else{pendingUpload.current=null;pendingReview.current=null;setUncertain(false);setMessage(t('uploads.failed'));}};
 const upload=async(retry=false)=>{if(!retry){if(!file)return;pendingUpload.current={file,input:{sourceKind,sourceId,expectedRevision:sourceRevision,context,requestKey:crypto.randomUUID()}};}const p=pendingUpload.current;if(!p)return;setBusy(true);try{const form=new FormData();form.set('input',JSON.stringify(p.input));form.set('file',p.file);const result=await apiFetch<{id:string}>('/api/contract-document-uploads',{method:'POST',body:form});pendingUpload.current=null;setUncertain(false);setMessage(t('uploads.queued'));await load();await open(result.id,false);}catch(error){failed(error);}finally{setBusy(false);}};
 const review=async(c:ExtractionCandidate,decision:string,confirmedValue:string|boolean|null)=>{if(!detail?.runId)return;pendingReview.current={id:detail.id,input:{runId:detail.runId,candidateKey:c.candidateKey,decision,confirmedValue,expectedRevision:detail.revision,expectedSourceRevision:detail.currentSourceRevision,requestKey:crypto.randomUUID(),reason}};await sendReview();};
 const sendReview=async()=>{const p=pendingReview.current;if(!p)return;setBusy(true);try{await apiFetch(`/api/contract-document-uploads/${p.id}/review`,{method:'POST',body:JSON.stringify(p.input)});pendingReview.current=null;setUncertain(false);setMessage(t('uploads.reviewed'));setReason('');await open(p.id);await load();}catch(error){failed(error);}finally{setBusy(false);}};
 const extract=async(forceNew:boolean)=>{if(!detail)return;setBusy(true);try{await apiFetch(`/api/contract-document-uploads/${detail.id}/extract`,{method:'POST',body:JSON.stringify({forceNew})});await open(detail.id);await load();}catch{setMessage(t('uploads.failed'));}finally{setBusy(false);}};
 return <section data-upload-evidence style={{minWidth:0,overflowWrap:'anywhere'}}><div className="surface-heading"><h4>{t('uploads.title')}</h4><button className="secondary-button" disabled={busy||uncertain} onClick={()=>void load().then(()=>detail?open(detail.id):null).catch(()=>setMessage(t('uploads.failed')))}>{t('uploads.refresh')}</button></div><p>{t('uploads.boundary')}</p>
 {message&&<InlineMessage type="info">{message}</InlineMessage>}
 {canManage&&<fieldset disabled={busy||uncertain} style={{minWidth:0,border:0,padding:0}}><p>{t('uploads.formats')}</p><p>{t('uploads.context')}</p><label className="field"><span>{t('uploads.upload')}</span><input data-upload-file type="file" accept=".docx,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="secondary-button" disabled={!file} onClick={()=>void upload()}>{t('uploads.upload')}</button></fieldset>}
 {uncertain&&<button className="secondary-button" disabled={busy} onClick={()=>void(pendingUpload.current?upload(true):sendReview())}>{t('uploads.retryRequest')}</button>}
 {!items.length&&<p>{t('uploads.empty')}</p>}<div className="detail-record-list">{items.map(d=><article key={d.id} data-upload-id={d.id}><b>{t('uploads.uploaded')} · {d.filename}</b><p>{d.format} · {t(`uploads.status.${d.status}`)}</p><button disabled={busy||uncertain} className="secondary-button" onClick={()=>void open(d.id,false).catch(()=>setMessage(t('uploads.failed')))}>{t('uploads.detail')}</button> <a className="secondary-button" href={`/api/contract-document-uploads/${d.id}/download`}>{t('uploads.original')}</a></article>)}</div>
 {detail&&<div data-extraction-detail><h4>{detail.filename}</h4><p>SHA256: {detail.sha256}</p><p>{t('uploads.sourceRevision')}: {detail.sourceRevision} / {detail.currentSourceRevision}</p>{detail.sourceChanged&&<InlineMessage type="error">{t('uploads.sourceChanged')}</InlineMessage>}<p>{t('uploads.run')}: {detail.runNumber??'—'} · {detail.extractorVersion??'—'}</p>
 {detail.errorCode&&<InlineMessage type="error">{t(detail.errorCode==='OCR_REQUIRED_NOT_SUPPORTED'?'uploads.noText':detail.errorCode==='PDF_PASSWORD_UNSUPPORTED'?'uploads.password':detail.errorCode==='UPLOAD_ARTIFACT_INTEGRITY_FAILED'?'uploads.integrity':'uploads.failed')}</InlineMessage>}
 {canManage&&<div className="page-actions"><button disabled={busy||uncertain} className="secondary-button" onClick={()=>void open(detail.id,true).catch(()=>setMessage(t('uploads.failed')))}>{t('uploads.reveal')}</button>{detail.status==='EXTRACTION_FAILED'&&<button disabled={busy||uncertain} className="secondary-button" onClick={()=>void extract(false)}>{t('uploads.retry')}</button>}{['EXTRACTED','REVIEWED'].includes(detail.status)&&<button disabled={busy||uncertain} className="secondary-button" onClick={()=>void extract(true)}>{t('uploads.newRun')}</button>}</div>}
 <p>{t('uploads.noApply')}</p><h4>{t('uploads.candidates')}</h4><div className="detail-record-list">{detail.candidates.map(c=><article key={c.candidateKey} data-candidate={c.fieldKey} style={{minWidth:0,display:'block'}}><b>{locale==='en'?c.labelEn:c.labelZh}</b>{c.comparisonState==='CONFLICT'?<InlineMessage type="error">{t('uploads.state.CONFLICT')}</InlineMessage>:<p>{t(`uploads.state.${c.comparisonState}`)}</p>}<p>{t('uploads.raw')}: {c.masked?t('uploads.masked'):String(c.rawValue??'—')}</p><p>{t('uploads.normalized')}: {c.masked?t('uploads.masked'):String(c.normalizedValue??'—')}</p><p>{t('uploads.canonical')}: {c.masked?t('uploads.masked'):detail.canonical[c.fieldKey]??'—'}</p>{c.sourceLocation&&<details><summary>{t('uploads.location')}</summary><p>{Object.entries(c.sourceLocation).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p style={{whiteSpace:'pre-wrap'}}>{t('uploads.excerpt')}: {c.masked||c.sourceExcerpt===null?t('uploads.masked'):c.sourceExcerpt}</p></details>}
 {c.confirmationTarget!=='DOCUMENT_ONLY'&&<p>{t('uploads.readOnly')}</p>}
 {canManage&&detail.runId&&<div className="page-actions">{c.confirmationTarget==='DOCUMENT_ONLY'&&!c.masked&&<><button className="secondary-button" disabled={busy||uncertain||c.validationState!=='VALID'||c.confidenceState==='AMBIGUOUS'} onClick={()=>void review(c,'CONFIRMED',c.normalizedValue)}>{t('uploads.confirm')}</button><button className="secondary-button" disabled={busy||uncertain} onClick={()=>{setEdit(c.candidateKey);setValue(String(c.normalizedValue??''));}}>{t('uploads.edit')}</button></>}<button disabled={busy||uncertain} className="secondary-button" onClick={()=>void review(c,'REJECTED',null)}>{t('uploads.reject')}</button><button disabled={busy||uncertain} className="secondary-button" onClick={()=>void review(c,'DEFERRED',null)}>{t('uploads.defer')}</button></div>}
 {edit===c.candidateKey&&<fieldset disabled={busy||uncertain} style={{minWidth:0}}><label className="field"><span>{t('uploads.editedValue')}</span>{c.type==='boolean'?<select value={value} onChange={e=>setValue(e.target.value)}><option value="">—</option><option value="true">{t('documents.yes')}</option><option value="false">{t('documents.no')}</option></select>:<textarea maxLength={5000} value={value} onChange={e=>setValue(e.target.value)}/>}</label><label className="field"><span>{t('uploads.reason')}</span><textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="secondary-button" disabled={!value} onClick={()=>void review(c,'EDITED',c.type==='boolean'?value==='true':value)}>{t('uploads.saveEdit')}</button></fieldset>}
 </article>)}</div>{detail.chunks.length>0&&<details><summary>{t('uploads.extractedText')}</summary>{detail.chunks.map(c=><p key={c.index} style={{whiteSpace:'pre-wrap'}}>{c.text}</p>)}</details>}<h4>{t('uploads.history')}</h4>{detail.reviews.map((r,i)=><p key={i}>{r.candidate_key} · {t(`uploads.decision.${r.decision}`)} · {r.actor_id} · {r.reviewed_at}{r.confirmed_value!==undefined?` · ${String(r.confirmed_value)}`:''}</p>)}</div>}
 </section>;
}
