"use client";

import Link from "next/link";
import { useState } from "react";
import { Building2,CalendarClock,ChevronRight,FileCheck2,HandCoins,History,Landmark,RefreshCw,Target,UserRound } from "lucide-react";
import type { Organization360,TimelineEvent } from "@/lib/phase2-repository";
import { useI18n } from "./i18n-provider";
import { InlineMessage,Pagination,ProgressBar,StatusBadge } from "./ui";

const eventIcons:Record<string,React.ElementType>={ORGANIZATION:Building2,CONTACT:UserRound,OPPORTUNITY:Target,TASK:FileCheck2,ACTIVITY:History,APPOINTMENT:CalendarClock,CONTRACT:Landmark,PAYMENT:HandCoins,RELATIONSHIP:UserRound,APPROVAL:FileCheck2};
const types=["CONTACT","OPPORTUNITY","TASK","ACTIVITY","APPOINTMENT","CONTRACT","PAYMENT","RELATIONSHIP","APPROVAL"];
export function Customer360Page({initial}: {initial:Organization360}){const{locale,t}=useI18n();const[data,setData]=useState(initial);const[type,setType]=useState("all");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const load=async(page:number,nextType=type)=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page)});if(nextType!=="all")params.set("types",nextType);const response=await fetch(`/api/customer-360/${initial.id}?${params}`);const result=await response.json() as Organization360;if(!response.ok||!result.timeline)throw new Error();setData(result);}catch{setError(t("customer360.loadFailed"));}finally{setLoading(false);}};const pages=Math.max(1,Math.ceil(data.timeline.total/data.timeline.pageSize));return <div className="page-stack customer-360"><section className="page-heading-row"><div><p className="eyebrow">{t("customer360.eyebrow")}</p><h1>{initial.nameZh} / {initial.nameEn}</h1><p>{t("customer360.description")}</p></div><Link className="secondary-button" href="/schools">{t("customer360.back")}</Link></section><section className="quick-summary"><span><b>{data.timeline.total}</b><small>{t("customer360.events")}</small></span><span><b>{initial.status}</b><small>{t("common.status")}</small></span><span><b>{initial.city||"—"}</b><small>{t("customer360.city")}</small></span><span><ProgressBar value={initial.completeness} label={`${initial.completeness}%`}/><small>{t("modules.completeness")}</small></span></section><section className="surface timeline-surface"><div className="table-toolbar"><label className="compact-filter"><span>{t("customer360.filter")}</span><select value={type} onChange={(event)=>{const next=event.target.value;setType(next);void load(1,next);}}><option value="all">{t("common.all")}</option>{types.map(item=><option key={item} value={item}>{t(`timeline.type.${item.toLowerCase()}`)}</option>)}</select></label>{loading&&<span role="status"><RefreshCw className="spin" size={15}/>{t("common.loading")}</span>}</div>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="timeline-list">{data.timeline.items.map((item,index)=><TimelineItem item={item} locale={locale} t={t} key={`${item.type}-${item.entityId}-${index}`}/>)}</div>{!data.timeline.items.length&&!loading&&<div className="empty-state"><span>{t("customer360.empty")}</span></div>}<Pagination page={data.timeline.page} totalPages={pages} total={data.timeline.total} pageSize={data.timeline.pageSize} onPage={(page)=>void load(page)}/></section></div>}
function TimelineItem({item,locale,t}:{item:TimelineEvent;locale:"zh-CN"|"en";t:(key:string,values?:Record<string,string|number>)=>string}){const Icon=eventIcons[item.type]??History;const title=locale==="en"?item.titleEn||item.titleZh:item.titleZh||item.titleEn;const href=typeof item.metadata?.href==="string"?item.metadata.href:"";const amount=typeof item.metadata?.amount==="number"?`${item.metadata.currency??""} ${new Intl.NumberFormat(locale).format(item.metadata.amount)}`:"";return <article className="timeline-item"><span className={`timeline-icon ${item.type.toLowerCase()}`}><Icon size={17}/></span><div><div><StatusBadge tone="blue">{t(`timeline.type.${item.type.toLowerCase()}`)}</StatusBadge><time>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.occurredAt))}</time></div><b>{title}</b><p>{t(`timeline.summary.${item.summary.toLowerCase()}`)===`timeline.summary.${item.summary.toLowerCase()}`?item.summary:t(`timeline.summary.${item.summary.toLowerCase()}`)}{amount?` · ${amount}`:""}</p></div>{href&&<Link href={href} aria-label={t("customer360.openSource",{title})}><ChevronRight size={17}/></Link>}</article>}
