"use client";

import {UiIcon} from "./ui-icon";
import { Building2, Clock3, FileText, Users, Target, Zap, BookOpen } from "lucide-react";
import { RecordIdentity } from "./record-header";
import { EducationBusinessWorkspace } from "./education-business-workspace";
import { ResponsiveDetailLayout, SectionHeader } from "./responsive-detail-layout";
import { accountWorkspaceTabs } from "@/lib/record-workspace-presentation";
import {OrganizationContractEditor} from "./organization-contract-editor";
import {ProductCatalogAction} from "./product-catalog-action";
import { PipelinePage } from "./pipeline-page";
import { AccountOpportunitySummary } from "./account-opportunity-summary";
import {ModulePage} from "./module-page";
import {CrmRecordEditor} from "./crm-record-editor";
import {moduleConfigs} from "@/lib/crm-data";
import {OrganizationCommercialPanel} from "./organization-commercial-panel";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { presentApiError } from "@/lib/api-error-presenter";
import { followUpProgress, type CustomerSubject } from "@/lib/customer-operations";
import type { CustomerOperationsSnapshot } from "@/lib/customer-operations-repository";
import { useCapability } from "./app-user-context";
import { useI18n } from "./i18n-provider";
import { useUserPreferences } from "./user-preferences-context";
import { DateInput } from "./structured-inputs";
import { InlineMessage, ProgressBar, SearchableSelect } from "./ui";
import { MarkdownContent } from "./markdown-content";
import { DetailTabs } from "./detail-tabs";
import { customerDetailTabs } from "@/lib/customer-detail-tabs";
import { useRemoteSearch } from "@/hooks/use-remote-search";

export function CustomerOperationsPanel({subject,id,extra,history,account=false,contentTab,onSnapshot,onRecordActivity,overview,hideIdentity=false,activeSection,onSectionChange,recordEntryRequested=0}:{subject:CustomerSubject;id:string;extra?:React.ReactNode;history?:React.ReactNode;account?:boolean;contentTab?:string;onSnapshot?:(snapshot:CustomerOperationsSnapshot)=>void;onRecordActivity?:()=>void;overview?:React.ReactNode;hideIdentity?:boolean;activeSection?:string;onSectionChange?:(section:string)=>void;recordEntryRequested?:number}) {
  const {t,locale}=useI18n();const canSend=useCapability("messages.manage"),canViewContracts=useCapability("contracts.view"),canManageFamily=useCapability("education.manage"),canViewEducation=useCapability("education.view");
  const {formatDate,localDateTimeInput,localDateTimeToIso}=useUserPreferences();
  const [data,setData]=useState<CustomerOperationsSnapshot|null>(null),[error,setError]=useState(""),[pending,setPending]=useState(false),[tab,setTab]=useState("overview");
  const [contract,setContract]=useState(""),[options,setOptions]=useState<Array<{value:string;label:string}>>([]);
  const snapshotCallback=useRef(onSnapshot);
  useEffect(()=>{snapshotCallback.current=onSnapshot;},[onSnapshot]);
  const educationContext=useMemo(()=>({type:"ORGANIZATION" as const,id}),[id]);
  const activeTab=contentTab??activeSection??tab;
  const changeTab=(value:string)=>{setTab(value);onSectionChange?.(value);};
  const request=useRef<{key:string;occurredAt:string}|null>(null);
  const busy=useRef(false),[notice,setNotice]=useState("");const runContractSearch=useRemoteSearch(),runLoad=useRemoteSearch();
  const load=useCallback(async(signal?:AbortSignal)=>{const result=await runLoad(currentSignal=>apiFetch<CustomerOperationsSnapshot>(`/api/customer-operations?subject=${subject}&id=${id}`,{signal:signal?AbortSignal.any([signal,currentSignal]):currentSignal}));if(!result.current||signal?.aborted)return false;if("error" in result){setError(presentApiError(result.error,t,"modules.loadFailed").message);return false;}setData(result.value);snapshotCallback.current?.(result.value);setError("");return true;},[subject,id,t,runLoad]);
  useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>void load(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort();};},[load]);
  useEffect(()=>{const refresh=(event:Event)=>{const detail=(event as CustomEvent<{resource:string;id:string}>).detail;if(detail?.id===id&&detail.resource===(subject==="ORGANIZATION"?"schools":"people")&&!busy.current)void load();};window.addEventListener("lumina:crm-record-saved",refresh);return()=>window.removeEventListener("lumina:crm-record-saved",refresh);},[subject,id,load]);
  const refreshAfterSave=async()=>{const refreshed=await load();setNotice(t(refreshed?"audit.saved":"audit.savedRefreshFailed"));};
  const canManageContracts=useCapability("contracts.manage");
  const canManage=!!data?.canManage&&(subject!=="HOUSEHOLD"||canManageFamily);
  const save=async(event:React.FormEvent<HTMLFormElement>,operation:string)=>{
    event.preventDefault();if(busy.current)return;const formElement=event.currentTarget,form=new FormData(formElement);
    const details:Record<string,unknown>=Object.fromEntries(form);
    if(operation==="plan"){details.targetLevel=Number(details.targetLevel);details.targetCount=Number(details.targetCount);}
    if(operation==="entry"){
      let occurredAt:string;try{occurredAt=localDateTimeToIso(String(form.get("occurredAt")));}catch{setError(t("error.invalidLocalTime"));return;}
      request.current??={key:crypto.randomUUID(),occurredAt};details.requestKey=request.current.key;details.occurredAt=request.current.occurredAt;
    }
    if(operation==="contract")details.contractId=contract;
    busy.current=true;setPending(true);setError("");setNotice("");
    try{await apiFetch("/api/customer-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subject,id,operation,...details})});if(operation==="entry"){request.current=null;formElement.reset();}if(operation==="contract")setContract("");const refreshed=await load();setNotice(t(refreshed?"audit.saved":"audit.savedRefreshFailed"));}
    catch(caught){setError(presentApiError(caught,t,"crm.saveFailed").message);}finally{busy.current=false;setPending(false);}
  };
  const searchContracts=async(query:string)=>{const result=await runContractSearch(signal=>apiFetch<{items:Array<{value:string;labelZh:string;labelEn:string}>}>(`/api/search/related?types=CONTRACT&q=${encodeURIComponent(query)}`,{signal}));if(!result.current)return;if("error" in result){setError(presentApiError(result.error,t,"modules.relatedSearchFailed").message);return;}setOptions(result.value.items.map(item=>({value:item.value.split(":")[1],label:locale==="en"?item.labelEn:item.labelZh})));};
  const name=(item:{name_zh?:string;name_en?:string;title_zh?:string;title_en?:string;contract_number?:string;id:string})=>item.contract_number||(locale==="en"?item.name_en||item.title_en:item.name_zh||item.title_zh)||item.name_zh||item.name_en||item.id;
  if(!data||data.id!==id||data.subject!==subject)return <section className="surface">{error?<><InlineMessage type="error">{error}</InlineMessage><button className="secondary-button" onClick={()=>void load()}>{t("common.retry")}</button></>:<p role="status">{t("common.loading")}</p>}</section>;
  const progress=followUpProgress(data.plan,data.entries,data.level,new Date().toISOString().slice(0,10),data.completed);
  const tabs=account?accountWorkspaceTabs:customerDetailTabs(subject,!!extra,!!history,canViewEducation&&(subject==="ORGANIZATION"||subject==="CONTACT"&&!!data.profile.organization_id));
  const displayName=(locale==="en"?data.nameEn:data.nameZh)||data.nameZh||data.nameEn;
  const profileKeys=["city","curriculum","website","email","phone","title","preferred_language","next_follow_up_at"].filter(key=>data.profile[key]);
  const contextRail=<div className="workspace-rail">
    <section className="detail-section" data-surface-tone="context"><SectionHeader icon={<BookOpen size={18}/>} title={t("ux.record.currentContext")}/><dl className="workspace-status-list"><div><dt>{t("crm.owner")}</dt><dd>{data.ownerName||t("ux.record.notRecorded")}</dd></div><div><dt>{t("ux.record.lastInteraction")}</dt><dd>{data.entries[0]?.occurred_at?formatDate(data.entries[0].occurred_at,{includeTime:true}):t("ux.record.notRecorded")}</dd></div><div><dt>{t("ux.record.nextAction")}</dt><dd>{data.entries[0]?.next_step||t("ux.record.notRecorded")}</dd></div></dl></section>
    <section className="detail-section"><SectionHeader icon={<Target size={18}/>} title={t("workspace.keyFacts")} help={t("workspace.visibleRecords")}/><dl className="workspace-facts"><div><dt>{t("customerOps.entries")}</dt><dd>{data.entryTotal}</dd></div><div><dt>{t("nav.people")}</dt><dd>{data.contacts.length}</dd></div><div><dt>{t("nav.opportunities")}</dt><dd>{data.opportunities.length}</dd></div><div><dt>{t("nav.contracts")}</dt><dd>{data.contracts.length}</dd></div></dl>{data.limited&&<p className="field-help">{t("customerOps.limited")}</p>}</section>
    <section className="detail-section" data-surface-tone="context"><SectionHeader title={t("workspace.attention")}/>{data.plan?<><b>{data.plan.title}</b><p>{t("customerOps.dueDate")}: {formatDate(data.plan.due_date,{dateOnly:true})}</p><button className="text-button" onClick={()=>setTab("activity")}>{t("workspace.moreDetails")}</button></>:<p className="field-help">{t("workspace.noAttention")}</p>}<p className="field-help">{t("workspace.attentionHelp")}</p></section>
    <section className="detail-section"><SectionHeader icon={<Zap size={18}/>} title={t("workspace.quickActions")}/><div className="workspace-quick-links"><button className="text-button" onClick={()=>setTab("opportunities")}>{t("nav.opportunities")} →</button><button className="text-button" onClick={()=>setTab("people")}>{t("nav.people")} →</button><button className="text-button" onClick={()=>setTab("business")}>{t("ux.record.contractsProducts")} →</button>{canManage&&onRecordActivity&&<button className="text-button" onClick={onRecordActivity}>{t("customer360.recordActivity")} →</button>}</div></section>
  </div>;
  return <section className={`${account||hideIdentity?"workspace-panel":"surface"} customer-operations-panel`}>
    {!account&&!contentTab&&!hideIdentity&&<header className="detail-identity"><span className="detail-avatar" aria-hidden="true">{displayName.slice(0,1)}</span><div><p className="eyebrow">{t(subject==="ORGANIZATION"?"nav.schools":subject==="CONTACT"?"nav.people":"nav.households")}</p><h2>{displayName}</h2><p>{t(subject==="ORGANIZATION"?"detail.organizationHelp":subject==="HOUSEHOLD"?"detail.familyHelp":"detail.contactHelp")}</p></div></header>}
    {error&&<InlineMessage type="error">{error}<button className="text-button" disabled={pending} onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>}
    {notice&&<InlineMessage type="info">{notice}</InlineMessage>}
    {!account&&!contentTab&&subject!=="CONTACT"&&canViewEducation&&<Link className="secondary-button" href={`/education-business?subject=${subject}&subjectId=${id}`}>{t(subject==="ORGANIZATION"?"business.organizationEntry":"business.householdEntry")} →</Link>}
    <DetailTabs hideNavigation={!!contentTab} items={tabs} active={activeTab} onChange={changeTab} disabled={pending} label={t("customerOps.title")}>
    {activeTab==="overview"&&<div className="page-stack" data-testid="account-overview">{overview??(account?<ResponsiveDetailLayout context={contextRail}><div className="workspace-main-stack">
      <section className="detail-section"><SectionHeader icon={<Target size={18}/>} title={t("workspace.businessOverview")}/><div className="workspace-summary-grid"><div><SectionHeader title={t("workspace.currentOpportunities")} action={<button className="text-button" onClick={()=>setTab("opportunities")}>{t("common.details")}</button>}/><AccountOpportunitySummary organizationId={id} limit={3}/></div><div><SectionHeader title={t("ux.record.contractsProducts")} action={<button className="text-button" onClick={()=>setTab("business")}>{t("common.details")}</button>}/><div className="detail-record-list">{data.contracts.slice(0,3).map(item=><article key={item.id}><Link href={`/contracts?focus=${item.id}`}>{name(item)}</Link><small>{t(`contracts.status.${item.status?.toLowerCase()==="pending_approval"?"pending":item.status?.toLowerCase()}`)}</small></article>)}</div>{!data.contracts.length&&<div className="workspace-empty"><FileText size={23}/><b>{t("detail.noBusiness")}</b><p>{t("workspace.relatedHelp")}</p></div>}</div></div></section>
      <section className="detail-section" data-surface-tone="context"><SectionHeader icon={<Building2 size={18}/>} title={t("workspace.organizationProfile")} action={canManage&&<CrmRecordEditor resource="schools" id={id}/>}/><dl className="workspace-info-grid">{profileKeys.map(key=><div key={key}><dt>{t(`customerOps.field.${key}`)}</dt><dd>{String(data.profile[key])}</dd></div>)}<div><dt>{t("crm.owner")}</dt><dd>{data.ownerName||t("ux.record.notRecorded")}</dd></div><div><dt>{t("contact.communicationLevel")}</dt><dd>{t(`contact.communication.level${data.level}`)}</dd></div></dl></section>
      <section className="detail-section"><SectionHeader icon={<FileText size={18}/>} title={t("workspace.background")}/><MarkdownContent value={String(data.profile.organization_overview_markdown??data.profile.notes_markdown??"")} empty={t("ux.record.notRecorded")}/></section>
      <section className="detail-section"><SectionHeader icon={<Clock3 size={18}/>} title={t("workspace.recentActivity")} action={canManage&&onRecordActivity&&<button className="secondary-button" onClick={onRecordActivity}>{t("customer360.recordActivity")}</button>}/><div className="workspace-activity-list">{data.entries.slice(0,3).map(entry=><article key={entry.id}><time>{formatDate(entry.occurred_at,{includeTime:true})}</time><div><b>{t(`activity.kind.${entry.kind}`)}</b><p>{entry.summary}</p><small>{t("ux.record.nextAction")}: {entry.next_step||t("ux.record.notRecorded")}</small></div></article>)}</div>{!data.entries.length&&<div className="workspace-empty"><Clock3 size={23}/><b>{t("workspace.noActivity")}</b><p>{t("workspace.activityHelp")}</p></div>}<button className="text-button" onClick={()=>setTab("activity")}>{t("workspace.moreDetails")} →</button></section>
    </div></ResponsiveDetailLayout>:<><div className="detail-metrics">{subject==="ORGANIZATION"&&<span><b>{data.shortName||"—"}</b><small>{t("customerOps.shortName")}</small></span>}<span><b>{data.ownerName||"—"}</b><small>{t("crm.owner")}</small></span><span><b>{t(`contact.communication.level${data.level}`)}</b><small>{t("contact.communicationLevel")}</small></span><span><b>{data.entryTotal}</b><small>{t("customerOps.entries")}</small></span></div>
      <section className="detail-section"><h3>{t("detail.identity")}</h3><dl className="customer-profile">{profileKeys.map(key=><div key={key}><dt>{t(`customerOps.field.${key}`)}</dt><dd>{key==="next_follow_up_at"?formatDate(String(data.profile[key]),{includeTime:true}):String(data.profile[key])}</dd></div>)}</dl>{!profileKeys.length&&<p className="detail-empty">{t("detail.noProfile")}</p>}
      {subject==="CONTACT"&&(data.profile.organization_id?<Link className="detail-context-link" href={`/schools/${data.profile.organization_id}`}>{t("detail.organizationLink")} →</Link>:<p className="detail-empty">{t("detail.noOrganization")}</p>)}</section>
      <section className="detail-section"><h3>{t("detail.notes")}</h3><MarkdownContent value={String(data.profile.organization_overview_markdown??data.profile.notes_markdown??data.profile.education_expectations_markdown??"")} empty={t("common.noData")}/></section>
      {subject==="CONTACT"&&canSend&&<Link className="secondary-button" href={`/messages?tab=templates&contact=${id}`}>{t("customerOps.email")}</Link>}
</>)}
    </div>}
    <div className="page-stack follow-up-workspace" hidden={activeTab!=="followUp"&&activeTab!=="activity"}>
      <dl className="follow-up-summary"><div><dt>{t("customerOps.goal")}</dt><dd>{data.plan?.title||t("ux.record.notRecorded")}</dd></div><div><dt>{t("customerOps.field.next_follow_up_at")}</dt><dd>{data.profile.next_follow_up_at?formatDate(String(data.profile.next_follow_up_at),{includeTime:true}):t("ux.record.notRecorded")}</dd></div><div><dt>{t("workspace.recentActivity")}</dt><dd>{data.entries[0]?formatDate(data.entries[0].occurred_at,{includeTime:true}):t("ux.record.notRecorded")}</dd></div><div><dt>{t("crm.owner")}</dt><dd>{data.ownerName||t("ux.record.notRecorded")}</dd></div></dl>
      <InlineMessage type="info">{t(progress.suggestionKey)} {t("customerOps.evidenceHelp")}</InlineMessage>
      {progress.overdue&&<InlineMessage type="warning">{t("customerOps.overdue")}</InlineMessage>}
      {data.plan&&<div className="detail-metrics" aria-live="polite"><span><b>{progress.remaining}</b><small>{t("audit.remaining")}</small></span><span><b>{progress.daysRemaining!<0?t("audit.pastDue",{days:-progress.daysRemaining!}):t("audit.daysLeft",{days:progress.daysRemaining!})}</b><small>{t("audit.deadlineUTC")}</small></span><span><b>{t(progress.achieved?"audit.achieved":"audit.inProgress")}</b><small>{t("customerOps.goal")}</small></span></div>}
      {data.plan?<div className="detail-section"><h3>{data.plan.title}</h3><p>{formatDate(data.plan.start_date,{dateOnly:true})} — {formatDate(data.plan.due_date,{dateOnly:true})}</p><ProgressBar value={progress.contactProgress} label={`${progress.completed} / ${data.plan.target_count} · ${t("customerOps.entries")}`}/><ProgressBar value={progress.levelProgress} label={`${data.level} / ${data.plan.target_level} · ${t("contact.communicationLevel")}`}/></div>:<p className="detail-empty">{t("detail.noPlan")}</p>}
      {canManage&&<details><summary>{t("customerOps.editPlan")}</summary><form key={data.plan?.updated_at??"new"} onSubmit={event=>void save(event,"plan")} className="page-stack"><fieldset className="follow-up-fields" disabled={pending}><label className="field"><span>{t("customerOps.goal")}</span><input name="title" required maxLength={200} defaultValue={data.plan?.title}/></label><div className="form-grid two-column"><label className="field"><span>{t("customerOps.targetLevel")}</span><select required name="targetLevel" defaultValue={data.plan?.target_level??progress.nextLevel}>{[1,2,3,4].map(level=><option key={level} value={level}>{t(`contact.communication.level${level}`)}</option>)}</select></label><label className="field"><span>{t("customerOps.targetCount")}</span><input name="targetCount" type="number" min={1} max={1000} required defaultValue={data.plan?.target_count??3}/></label><label className="field"><span>{t("customerOps.startDate")}</span><DateInput name="startDate" required defaultValue={data.plan?.start_date??new Date().toISOString().slice(0,10)}/></label><label className="field"><span>{t("customerOps.dueDate")}</span><DateInput name="dueDate" required defaultValue={data.plan?.due_date}/></label></div><button className="primary-button" disabled={pending}>{t("common.save")}</button></fieldset></form></details>}
      {canManage&&<details key={recordEntryRequested} open={recordEntryRequested>0||undefined} data-record-entry><summary>{t("customerOps.record")}</summary><form onSubmit={event=>void save(event,"entry")} onChange={()=>{request.current=null;}} className="page-stack"><fieldset className="follow-up-fields" disabled={pending}><div className="form-grid two-column"><label className="field"><span>{t("customer360.activityKind")}</span><select required name="kind">{["CALL","EMAIL","MEETING","VISIT","NOTE"].map(kind=><option key={kind} value={kind}>{t(`activity.kind.${kind}`)}</option>)}</select></label><label className="field"><span>{t("customer360.occurredAt")}</span><DateInput name="occurredAt" type="datetime-local" max={localDateTimeInput()} defaultValue={localDateTimeInput()} required/></label></div><label className="field"><span>{t("customerOps.summary")}</span><textarea name="summary" rows={3} maxLength={2000} required/></label><label className="field"><span>{t("customerOps.nextStep")}</span><textarea name="nextStep" rows={2} maxLength={1000} required/></label><button className="primary-button" disabled={pending}>{t("common.save")}</button></fieldset></form></details>}
      {subject==="ORGANIZATION"&&<Link href="/sales/performance" className="secondary-button">{t("customerOps.relationshipEvidence")}</Link>}
      <p className="detail-list-caption">{t("customerOps.recent",{count:data.entries.length,total:data.entryTotal})}</p>{!data.entries.length&&<p className="detail-empty">{t("detail.noFollowUps")}</p>}{data.entries.map(entry=><article className="follow-up-entry" key={entry.id}><b>{t(`activity.kind.${entry.kind}`)} · {formatDate(entry.occurred_at,{includeTime:true})}</b><p>{entry.summary}</p><small>{t("customerOps.nextStep")}: {entry.next_step||"—"}</small></article>)}
    </div>
    {activeTab==="activity"&&history}
    {activeTab==="opportunities"&&<section className="detail-section"><SectionHeader title={t("nav.opportunities")} action={<><PipelinePage createOnly contextOrganization={{id,label:displayName}} initialItems={[]} initialTotal={0} initialFunnel={[]} initialCurrency="CNY" initialCurrencies={["CNY"]} onContextSaved={()=>void refreshAfterSave()}/><Link className="secondary-button" href="/opportunities">{t("ux.record.openWorkspace")}</Link></>}/><AccountOpportunitySummary organizationId={id}/></section>}
    {activeTab==="business"&&<div className="page-stack"><section className="detail-section"><div className="surface-heading"><h3>{t("nav.contracts")} <small>{data.contracts.length}</small></h3>{subject==="ORGANIZATION"&&canManage&&canManageContracts&&<OrganizationContractEditor organizationId={id} onSaved={()=>void refreshAfterSave()}/>}</div><div className="detail-record-list">{data.contracts.map(item=><article key={item.id}><div><Link href={`/contracts?query=${encodeURIComponent(item.contract_number??"")}&focus=${item.id}`}>{name(item)}</Link><small>{t("crm.owner")}: {item.owner_name||"—"}</small></div><span>{t(`contracts.status.${item.status?.toLowerCase()==="pending_approval"?"pending":item.status?.toLowerCase()}`)}</span>{subject==="ORGANIZATION"&&canManage&&canManageContracts&&item.status==="DRAFT"&&<OrganizationContractEditor organizationId={id} contractId={item.id} onSaved={()=>void refreshAfterSave()}/>}</article>)}</div>{!data.contracts.length&&<p className="detail-empty">{t("detail.noBusiness")}</p>}
      {subject!=="ORGANIZATION"&&canManage&&canViewContracts&&<form onSubmit={event=>void save(event,"contract")}><fieldset className="follow-up-fields" disabled={pending}><SearchableSelect label={t("customerOps.linkContract")} required value={contract} options={options} onChange={setContract} onSearch={searchContracts}/><button className="secondary-button" disabled={pending||!contract}>{t("common.save")}</button></fieldset></form>}
      </section><div className="detail-section-grid"><section className="detail-section account-products-section"><SectionHeader icon={<UiIcon name="product" size={20}/>} title={t("nav.products")} action={<ProductCatalogAction/>}/><ul className="account-product-list">{data.products.map(item=><li key={item.id}><div className="account-product-identity"><UiIcon name="product" size={20}/><strong>{name(item)}</strong></div><div className="account-product-actions"><ProductCatalogAction productId={item.id}/></div></li>)}</ul>{!data.products.length&&<p className="detail-empty">{t("detail.noBusiness")}</p>}</section><section className="detail-section"><h3>{t("nav.opportunities")}</h3>{data.opportunities.map(item=><p key={item.id}><Link href={`/opportunities?focus=${item.id}`}>{name(item)}</Link> · {t(`sales.stage.${item.stage?.toLowerCase()}`)}</p>)}{!data.opportunities.length&&<p className="detail-empty">{t(subject==="CONTACT"?"audit.contactBusinessScope":"detail.noBusiness")}</p>}</section></div>{data.limited&&<InlineMessage type="warning">{t("customerOps.limited")}</InlineMessage>}
    </div>}
    {activeTab==="commercial"&&<div className="page-stack"><OrganizationCommercialPanel embedded={account} contextRail={account?contextRail:undefined} organizationId={subject==="ORGANIZATION"?id:String(data.profile.organization_id)} contactId={subject==="CONTACT"?id:undefined}/>{account&&canViewEducation&&<><details><summary>{t("pool.events")}</summary><EducationBusinessWorkspace embedded context={educationContext} initialResource="events"/></details><details><summary>{t("business.resource.referrals")}</summary><EducationBusinessWorkspace embedded context={educationContext} initialResource="referrals"/></details><Link className="secondary-button" href={`/education-business?subject=ORGANIZATION&subjectId=${id}`}>{t("ux.record.moreOperations")}</Link></>}</div>}
    {activeTab==="people"&&<div className="page-stack"><section className="detail-section"><SectionHeader icon={<Users size={18}/>} title={t(subject==="ORGANIZATION"?"detail.organizationContacts":"detail.familyMembers")} action={subject==="ORGANIZATION"&&canManage&&<ModulePage config={moduleConfigs.people} resource="people" createOnly organizationId={id} onCreated={()=>void refreshAfterSave()}/>}/><div className="detail-record-list">{data.contacts.map(item=><article key={item.id}><div><Link href={`/people/${item.id}`}><RecordIdentity nameZh={item.name_zh} nameEn={item.name_en}/></Link><small>{subject==="HOUSEHOLD"&&item.member_role?`${t(`education.memberRole.${item.member_role.toLowerCase()}`)} · `:""}{t("crm.owner")}: {item.owner_name||"—"}</small>{item.next_follow_up_at&&<small>{t("customerOps.field.next_follow_up_at")}: {formatDate(item.next_follow_up_at,{includeTime:true})}</small>}</div><span>{t(`contact.communication.level${item.communication_level??1}`)}</span>{canManage&&<CrmRecordEditor resource="people" id={item.id} onSaved={()=>void refreshAfterSave()}/>}</article>)}</div></section>{subject==="HOUSEHOLD"&&<section className="detail-section"><h3>{t("nav.students")}</h3><div className="detail-record-list">{data.students.map(item=><article key={item.id}><div><Link href={`/students?focus=${item.id}`}>{name(item)}</Link></div></article>)}</div></section>}{!data.contacts.length&&(subject!=="HOUSEHOLD"||!data.students.length)&&<p className="detail-empty">{t(subject==="ORGANIZATION"?"detail.noContacts":"detail.noMembers")}</p>}{data.limited&&<InlineMessage type="warning">{t("customerOps.limited")}</InlineMessage>}</div>}
    {account&&extra&&<details><summary>{t("ux.record.privacy")}</summary>{extra}</details>}
    {activeTab==="privacy"&&extra}
    {activeTab==="history"&&history}
    </DetailTabs>
  </section>;
}
