"use client";
import Link from "next/link";
import { useState } from "react";
import { AlertTriangle,ArrowRight,CalendarDays,Check,CircleDollarSign,FileCheck2,ListTodo,PackageCheck,ShieldCheck } from "lucide-react";
import type { DashboardSnapshot,DashboardTask } from "@/lib/dashboard-repository";
import { useAppUser } from "./app-user-context";
import { useI18n } from "./i18n-provider";
import { InlineMessage,StatusBadge,Toast } from "./ui";

export function DashboardPage({initialSnapshot}:{initialSnapshot:DashboardSnapshot}){
  const {locale,t}=useI18n();const user=useAppUser();const [snapshot,setSnapshot]=useState(initialSnapshot);const [error,setError]=useState("");const [toast,setToast]=useState("");
  const money=Object.entries(snapshot.monthRevenueByCurrency).map(([currency,value])=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en",{style:"currency",currency,notation:"compact",maximumFractionDigits:1}).format(value)).join(" · ")||"—";
  const complete=async(task:DashboardTask)=>{setError("");const response=await fetch(`/api/tasks/${task.id}`,{method:"PATCH"});if(!response.ok){setError(t("dashboard.taskCompleteFailed"));return;}setSnapshot(current=>({...current,todayTasks:Math.max(0,current.todayTasks-(task.dueAt?.slice(0,10)===new Date().toISOString().slice(0,10)?1:0)),overdueTasks:Math.max(0,current.overdueTasks-(task.dueAt&&new Date(task.dueAt)<new Date()?1:0)),focusTasks:current.focusTasks.filter(item=>item.id!==task.id)}));setToast(t("dashboard.taskCompleted"));};
  return <div className="page-stack dashboard-page"><section className="welcome-strip"><div><p className="eyebrow">{new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{dateStyle:"full"}).format(new Date())}</p><h1>{t("dashboard.greeting",{name:`${user.displayNameZh} / ${user.displayName}`})}</h1><p>{t("dashboard.realSummary")}</p></div><div className="welcome-actions"><Link className="secondary-button" href="/calendar"><CalendarDays size={17}/>{t("dashboard.viewCalendar")}</Link><Link className="primary-button" href="/tasks"><ListTodo size={17}/>{t("dashboard.allTasks")}</Link></div></section>{error&&<InlineMessage type="error">{error}</InlineMessage>}
  <section className="metric-grid"><Metric icon={ListTodo} tone="coral" label={t("dashboard.todayTasks")} value={String(snapshot.todayTasks)} note={t("dashboard.overdueCount",{count:snapshot.overdueTasks})} href="/tasks"/><Metric icon={ShieldCheck} tone="purple" label={t("dashboard.pendingApprovals")} value={String(snapshot.pendingApprovals)} note={t("dashboard.makerChecker")} href="/admin/approvals"/><Metric icon={FileCheck2} tone="blue" label={t("dashboard.renewalsDue")} value={String(snapshot.renewalsDue)} note={t("dashboard.riskCount",{count:snapshot.riskContracts})} href="/contracts"/><Metric icon={CircleDollarSign} tone="mint" label={t("dashboard.monthConfirmed")} value={money} note={t("dashboard.currencySeparated")} href="/analytics/consumption"/></section>
  <section className="dashboard-main-grid"><article className="surface task-focus-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.todayFocus")}</p><h2>{t("dashboard.focus")}</h2></div><Link href="/tasks">{t("dashboard.allTasks")} <ArrowRight size={15}/></Link></div><div className="focus-list">{snapshot.focusTasks.map(task=><TaskRow task={task} complete={complete} key={task.id}/>)}{!snapshot.focusTasks.length&&<div className="empty-state"><span>{t("dashboard.noFocusTasks")}</span></div>}</div></article>
  <article className="surface operations-snapshot"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.operationsCenter")}</p><h2>{t("dashboard.operationsSnapshot")}</h2></div></div><Operation icon={AlertTriangle} tone="red" value={snapshot.riskContracts} title={t("dashboard.riskContracts")} href="/contracts"/><Operation icon={PackageCheck} tone="green" value={snapshot.activeProducts} title={t("dashboard.activeProducts")} href="/products"/><Operation icon={ShieldCheck} tone="purple" value={snapshot.unreadNotifications} title={t("dashboard.unreadNotifications")} href="/messages"/></article></section>
  <section className="surface dashboard-trust-note"><ShieldCheck size={20}/><div><b>{t("dashboard.trustedMetrics")}</b><p>{t("dashboard.trustedMetricsHelp")}</p></div></section>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
function Metric({icon:Icon,tone,label,value,note,href}:{icon:React.ElementType;tone:string;label:string;value:string;note:string;href:string}){return <Link href={href} className="metric-card"><span className={`metric-icon ${tone}`}><Icon size={21}/></span><div><span className="metric-label">{label}</span><b>{value}</b><small>{note}</small></div><span className="metric-detail"><ArrowRight size={14}/></span></Link>}
function TaskRow({task,complete}:{task:DashboardTask;complete:(task:DashboardTask)=>void}){const {locale,t}=useI18n();const title=locale==="zh-CN"?task.titleZh:task.titleEn;return <div className="focus-task"><button className="task-check" type="button" onClick={()=>complete(task)} aria-label={t("dashboard.completeTask",{title})}><Check size={15}/></button><time>{task.dueAt?new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(task.dueAt)):"—"}</time><div><b>{title}</b><small>{task.related||t("common.other")}</small></div><StatusBadge tone={task.priority==="URGENT"?"red":task.priority==="HIGH"?"amber":"blue"}>{t(`dashboard.priority.${task.priority.toLowerCase()}`)}</StatusBadge></div>}
function Operation({icon:Icon,tone,value,title,href}:{icon:React.ElementType;tone:string;value:number;title:string;href:string}){return <Link className="attention-row" href={href}><span className={tone}><Icon size={17}/></span><span><b>{title}</b><small>{value}</small></span><ArrowRight size={16}/></Link>}
