"use client";
import {WorkflowLaunchpad} from "./workflow-launchpad";
import Link from "next/link";
import {AttentionPanel,type AttentionItem} from "./attention-panel";
import {SectionHeader} from "./responsive-detail-layout";
import {localeIdentity} from "@/lib/ux-presentation";
import {dashboardDefaultMode,readDashboardMode,saveDashboardMode,type DashboardMode} from "@/lib/frontline-presentation";
import { useEffect, useRef, useState } from "react";
import { ArrowRight,CalendarDays,Check,CircleDollarSign,FileCheck2,GraduationCap,ListTodo,Megaphone,PackageCheck,RefreshCw,ShieldCheck,Target } from "lucide-react";
import type { DashboardSnapshot,DashboardTask } from "@/lib/dashboard-repository";
import { useAppUser } from "./app-user-context";
import { useCapability } from "./app-user-context";
import { useI18n } from "./i18n-provider";
import { InlineMessage,StatusBadge,Toast } from "./ui";
import { apiFetch } from "@/lib/api-client";
import { presentApiError } from "@/lib/api-error-presenter";
import { useUserPreferences } from "./user-preferences-context";

export function DashboardPage({initialSnapshot}:{initialSnapshot:DashboardSnapshot}){
  const {locale,t}=useI18n();const {formatFullDate,todayKey,timezone}=useUserPreferences();const user=useAppUser();const canViewFinance=useCapability("finance.view");const canViewApprovals=useCapability("admin.access");const canViewLeads=useCapability("leads.view");const canViewEducation=useCapability("education.view");const canManageProgression=useCapability("progression.manage");const canViewGrowth=useCapability("leads.view");const [snapshot,setSnapshot]=useState(initialSnapshot);const [error,setError]=useState("");const [toast,setToast]=useState("");const[pendingTasks,setPendingTasks]=useState<Set<string>>(()=>new Set());const pendingTaskIds=useRef(new Set<string>());
  const money=Object.entries(snapshot.monthRevenueByCurrency).map(([currency,value])=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en",{style:"currency",currency,currencyDisplay:"code",notation:"compact",maximumFractionDigits:1}).format(value)).join(" · ")||"—";
  const complete=async(task:DashboardTask)=>{if(pendingTaskIds.current.has(task.id))return;pendingTaskIds.current.add(task.id);setPendingTasks(current=>new Set(current).add(task.id));setError("");try{await apiFetch(`/api/tasks/${task.id}`,{method:"PATCH"});setSnapshot(current=>{if(!current.focusTasks.some(item=>item.id===task.id))return current;return{...current,todayTasks:Math.max(0,current.todayTasks-(task.dueAt&&new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(task.dueAt))===todayKey()?1:0)),overdueTasks:Math.max(0,current.overdueTasks-(task.dueAt&&new Date(task.dueAt)<new Date()?1:0)),focusTasks:current.focusTasks.filter(item=>item.id!==task.id)}});setToast(t("dashboard.taskCompleted"));}catch(caught){setError(presentApiError(caught,t,"dashboard.taskCompleteFailed").message);}finally{pendingTaskIds.current.delete(task.id);setPendingTasks(current=>{const next=new Set(current);next.delete(task.id);return next;});}};
  const [preference,setPreference]=useState<{userId:string;mode:DashboardMode}|null>(null);
  const managementAllowed=canViewEducation;
  const mode=preference?.userId===user.id&&!(preference.mode==="management"&&!managementAllowed)?preference.mode:dashboardDefaultMode(user.role,managementAllowed);
  useEffect(()=>{const timer=setTimeout(()=>{let storage:Storage|null=null;try{storage=window.localStorage;}catch{}setPreference({userId:user.id,mode:readDashboardMode(storage,user.id,user.role,managementAllowed)});},0);return()=>clearTimeout(timer);},[user.id,user.role,managementAllowed]);
  const chooseMode=(next:DashboardMode)=>{if(next==="management"&&!managementAllowed)return;setPreference({userId:user.id,mode:next});let storage:Storage|null=null;try{storage=window.localStorage;}catch{}saveDashboardMode(storage,user.id,next);};
  const signals:AttentionItem[]=[];
  if(snapshot.riskContracts>0)signals.push({id:"contracts",title:t("dashboard.riskContracts"),description:String(snapshot.riskContracts),href:"/contracts",actionLabel:t("nav.contracts"),priority:"high"});
  if(canViewGrowth&&!snapshot.growthUnavailable&&snapshot.pendingAdmissions>0)signals.push({id:"admissions",title:t("dashboard.pendingAdmissions"),description:String(snapshot.pendingAdmissions),href:"/growth",actionLabel:t("dashboard.pendingAdmissions"),priority:"normal"});
  if(snapshot.unreadNotifications>0)signals.push({id:"notifications",title:t("dashboard.unreadNotifications"),description:String(snapshot.unreadNotifications),href:"/notifications",actionLabel:t("dashboard.unreadNotifications"),priority:"normal"});
  const business=<section className="surface ux-dashboard-business" data-region="business-snapshot"><SectionHeader title={t("frontline.snapshot")}/><div className="metric-grid">{canViewApprovals&&<Metric icon={ShieldCheck} tone="purple" label={t("dashboard.pendingApprovals")} value={String(snapshot.pendingApprovals)} note={t("dashboard.makerChecker")} href="/admin/approvals"/>}<Metric icon={FileCheck2} tone="blue" label={t("dashboard.renewalsDue")} value={String(snapshot.renewalsDue)} note={t("dashboard.riskCount",{count:snapshot.riskContracts})} href="/contracts"/>{canViewFinance&&<Metric icon={CircleDollarSign} tone="mint" label={t("dashboard.monthConfirmed")} value={money} note={t("dashboard.currencySeparated")} href="/analytics/consumption"/>}{canViewEducation&&<Metric icon={GraduationCap} tone="green" label={t("dashboard.activeStudents")} value={String(snapshot.activeStudents)} note={t("ux.metric.snapshot")} href="/students"/>}</div></section>;
  return <div className="page-stack dashboard-page ux-dashboard"><section className="welcome-strip"><div><p className="eyebrow">{formatFullDate(new Date())}</p><h1>{t("dashboard.greeting",{name:localeIdentity(locale,user.displayNameZh,user.displayName).primary})}</h1><p>{t("dashboard.realSummary")}</p></div><div className="welcome-actions"><Link href="/calendar"><CalendarDays size={17}/>{t("dashboard.viewCalendar")}</Link><Link className="secondary-button" href="/tasks"><ListTodo size={17}/>{t("dashboard.allTasks")}</Link></div></section>
  <div className="workflow-audience ux-dashboard-mode" role="group" aria-label={t("frontline.mode")}><button type="button" aria-pressed={mode==="daily"} onClick={()=>chooseMode("daily")}>{t("frontline.daily")}</button>{managementAllowed&&<button type="button" aria-pressed={mode==="management"} onClick={()=>chooseMode("management")}>{t("frontline.management")}</button>}</div>
  {error&&<InlineMessage type="error">{error}</InlineMessage>}
  {mode==="daily"?<><section className="ux-dashboard-work"><article className="surface task-focus-card" data-region="my-today"><div className="surface-heading"><div><h2>{t("frontline.today")}</h2><p>{t("frontline.taskCounts",{today:snapshot.todayTasks,overdue:snapshot.overdueTasks})}</p></div><Link href="/tasks">{t("dashboard.allTasks")} <ArrowRight size={15}/></Link></div><div className="focus-list">{snapshot.focusTasks.map(task=><TaskRow task={task} pending={pendingTasks.has(task.id)} complete={complete} key={task.id}/>)}{!snapshot.focusTasks.length&&<div className="empty-state"><span>{t("dashboard.noFocusTasks")}</span><Link href="/tasks">{t("dashboard.allTasks")}</Link></div>}</div></article>
  <div data-region="operational-attention"><AttentionPanel title={t("frontline.attention")} items={signals} summary={<p>{t("frontline.attentionHelp")}</p>} emptyLabel={t("frontline.noAttention")} action={<Link href="/action-center">{t("nav.actionCenter")}</Link>}/></div></section>{business}
  <div data-region="quick-navigation"><SectionHeader title={t("frontline.quick")}/><WorkflowLaunchpad audience="daily"/></div>
  <article className="surface operations-snapshot"><SectionHeader title={t("dashboard.operationsSnapshot")}/><div className="ux-dashboard-operations"><Operation icon={PackageCheck} tone="green" value={snapshot.activeProducts} title={t("dashboard.activeProducts")} href="/products"/>{canViewLeads&&<Operation icon={Target} tone="blue" value={snapshot.newLeads} title={t("dashboard.newLeads")} href="/leads"/>}{canManageProgression&&<Operation icon={RefreshCw} tone="amber" value={snapshot.pendingProgression} title={t("dashboard.pendingProgression")} href="/progression"/>}{canViewGrowth&&!snapshot.growthUnavailable&&<Operation icon={Megaphone} tone="blue" value={snapshot.attributedLeads} title={t("dashboard.attributedLeads")} href="/growth"/>}</div>{snapshot.growthUnavailable&&<InlineMessage type="warning">{t("flow.growthUnavailable")}</InlineMessage>}</article></>:<section className="ux-dashboard-management" data-region="management-summary"><SectionHeader title={t("frontline.management")} help={t("frontline.manageHelp")} action={<Link className="primary-button" href="/reports/executive">{t("frontline.openExecutive")}</Link>}/>{business}{snapshot.growthUnavailable&&<InlineMessage type="warning">{t("flow.growthUnavailable")}</InlineMessage>}</section>}
  <section className="dashboard-trust-note"><ShieldCheck size={20}/><div><b>{t("dashboard.trustedMetrics")}</b><p>{t("dashboard.trustedMetricsHelp")}</p></div></section>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}

function Metric({icon:Icon,tone,label,value,note,href}:{icon:React.ElementType;tone:string;label:string;value:string;note:string;href?:string}){const content=<><span className={`metric-icon ${tone}`}><Icon size={21}/></span><div><span className="metric-label">{label}</span><b>{value}</b><small>{note}</small></div>{href&&<span className="metric-detail"><ArrowRight size={14}/></span>}</>;return href?<Link href={href} className="metric-card">{content}</Link>:<article className="metric-card">{content}</article>}
function TaskRow({task,pending,complete}:{task:DashboardTask;pending:boolean;complete:(task:DashboardTask)=>void}){const {locale,t}=useI18n();const {formatDate}=useUserPreferences();const title=locale==="zh-CN"?task.titleZh:task.titleEn;return <div className="focus-task"><button className="task-check" type="button" disabled={pending} aria-busy={pending} onClick={()=>complete(task)} aria-label={t("dashboard.completeTask",{title})}><Check size={15}/></button><time>{task.dueAt?formatDate(task.dueAt,{includeTime:true}):"—"}</time><div><b>{title}</b><small>{task.related||t("common.other")}</small></div><StatusBadge tone={task.priority==="URGENT"?"red":task.priority==="HIGH"?"amber":"blue"}>{t(`dashboard.priority.${task.priority.toLowerCase()}`)}</StatusBadge></div>}
function Operation({icon:Icon,tone,value,title,href}:{icon:React.ElementType;tone:string;value:number;title:string;href:string}){return <Link className="attention-row" href={href}><span className={tone}><Icon size={17}/></span><span><b>{title}</b><small>{value}</small></span><ArrowRight size={16}/></Link>}
