"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {attentionHref,managementModules,type ManagementModule,type MetricValue,type ManagementOverviewProjection} from "@/lib/management-metric-contract";
import {formatChannelCommissionAmount} from "@/lib/channel-analytics-input";
import {useI18n} from "./i18n-provider";
import {attentionQueueHref} from "@/lib/management-attention-contract";
import {ManagementTrendsPanel} from "./management-trends";
import {EnrollmentRelation} from "./enrollment-relation";
import {metricDrillHref,metricContextHref,overviewFiltersSchema,type TrendFilters} from "@/lib/management-trend-contract";
import {DateInput} from "./structured-inputs";
import {InlineMessage} from "./ui";
const links:Record<ManagementModule,string>={commercial:"/opportunities",delivery:"/enrollments",finance:"/finance",channel:"/reports/channels",admissions:"/applications",studentSuccess:"/student-success"};
export function ExecutiveOverviewPage({initialFilters={}}:{initialFilters?:TrendFilters}){
 const [showTrends,setShowTrends]=useState(false);const {t,locale}=useI18n(),[filters,setFilters]=useState(initialFilters),[draft,setDraft]=useState(initialFilters),[invalid,setInvalid]=useState(false),[retry,setRetry]=useState(0),[stored,setStored]=useState<{query:string;data:ManagementOverviewProjection}|null>(null),[error,setError]=useState(false);
 const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined) as [string,string][]).toString(),data=stored?.query===query?stored.data:null;
 useEffect(()=>{const controller=new AbortController();void apiFetch<ManagementOverviewProjection>(`/api/management/overview?${query}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setStored({query,data:result});setError(false);setDraft(d=>({...d,from:result.period.from,to:result.period.to}));}}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[query,retry]);
 const value=(metric:MetricValue)=>metric.value===null?"—":metric.unit==="MONEY"?`${metric.currency} ${formatChannelCommissionAmount(String(metric.value),locale)}`:metric.unit==="RATIO"?`${(Number(metric.value)*100).toLocaleString(locale,{maximumFractionDigits:1})}%`:String(metric.value);
 const metric=(item:MetricValue)=><div key={`${item.key}:${item.currency??""}`}><dt>{t(`management.metric.${item.key}`)}</dt><dd data-metric={item.key} data-currency={item.currency??undefined}>{value(item)}</dd>{metricDrillHref(item,filters,data?.period)&&<Link data-drill={item.key} href={metricDrillHref(item,filters,data?.period)!}>{t("management.drilldown")}</Link>}{!metricDrillHref(item,filters,data?.period)&&<Link href={metricContextHref(item.key,{...filters,from:data?.period.from,to:data?.period.to})}>{t("management.open")}</Link>}{item.key==="goalAttainment"&&<small>{t("management.goalHelp")}</small>}</div>;
 return <div className="page-stack executive-overview"><section className="page-heading-row"><div><h1>{t("management.title")}</h1><p>{t("management.description")}</p></div></section><p>{t("management.boundary")}</p>
 <form className="surface page-stack" onSubmit={event=>{event.preventDefault();const parsed=overviewFiltersSchema.safeParse(draft);setInvalid(!parsed.success);if(parsed.success){setFilters(parsed.data);setRetry(n=>n+1);}}}><div className="form-grid two-column">{(["from","to"] as const).map(key=><label className="field" key={key}><span>{t(`management.${key}`)}</span><DateInput value={draft[key]??""} onChange={event=>setDraft(d=>({...d,[key]:event.target.value||undefined}))}/></label>)}<EnrollmentRelation type="PRODUCT" value={draft.productId??""} label={t("products.product")} onChange={v=>setDraft(d=>({...d,productId:v||undefined,cohortId:undefined}))}/><EnrollmentRelation type="COHORT" value={draft.cohortId??""} label={t("enrollments.cohort")} onChange={v=>setDraft(d=>({...d,cohortId:v||undefined}))}/></div>{invalid&&<InlineMessage type="error">{t("management.invalid")}</InlineMessage>}<button className="primary-button">{t("management.apply")}</button></form>
 {error&&<InlineMessage type="error">{t("management.failed")} <button className="secondary-button" onClick={()=>setRetry(n=>n+1)}>{t("common.retry")}</button></InlineMessage>}{!data&&!error&&<p role="status">{t("common.loading")}</p>}
 {data&&<><p>{t("management.asOf")} {data.asOf} · {t("management.period")} {data.period.from}–{data.period.to} · {data.period.timezone}</p>
 <button className="secondary-button" onClick={()=>setShowTrends(v=>!v)} aria-expanded={showTrends}>{t("management.trends")}</button>{showTrends&&<ManagementTrendsPanel refreshKey={retry} filters={{...filters,from:data.period.from,to:data.period.to}}/>}<p>{t("management.filterHelp")}</p><section className="surface"><h2>{t("management.summary")}</h2><dl className="customer-profile">{(["openLeads","openOpportunities","activeEnrollments","visibleAccounts","applicationsInProgress","activeCases","atRiskCases","recordedOutcomes"] as const).flatMap(key=>managementModules.flatMap(module=>data.modules[module].metrics.filter(m=>m.key===key).map(metric)))}</dl></section>
 {managementModules.map(module=>{const section=data.modules[module];return <section className="surface page-stack" data-module={module} key={module}><div className="surface-heading"><h2>{t(`management.section.${module}`)}</h2>{section.available&&<Link href={links[module]}>{t("management.open")}</Link>}</div>{!section.available?<InlineMessage type="info">{t("management.restricted")}</InlineMessage>:<>{(["SNAPSHOT","PERIOD"] as const).map(mode=><div key={mode}><h3>{t(mode==="SNAPSHOT"?"management.current":"management.period")}</h3><dl className="customer-profile">{section.metrics.filter(m=>m.mode===mode).map(metric)}</dl></div>)}
 {module==="finance"&&<p>{t("management.financeHelp")}</p>}{module==="commercial"&&<Link href="/leads">{t("nav.leads")}</Link>}{module==="channel"&&<><p>{t("management.channelHelp")}</p>{!data.permissions.commissionMoney&&<InlineMessage type="info">{t("management.moneyRestricted")}</InlineMessage>}<div className="channel-account-grid">{data.channelContributions.map(row=><article className="detail-section" key={row.organizationId}><Link href={`/schools/${row.organizationId}`}>{(locale==="en"?row.nameEn:row.nameZh)||row.nameZh||row.nameEn}</Link><p>{t("management.metric.primaryContributions")}: {row.primary} · {t("management.metric.assistContributions")}: {row.assist}</p></article>)}</div><Link href="/reports/channels">{t("management.fullChannel")}</Link></>}
 {Object.entries(section.distributions).map(([kind,counts])=><div key={kind}><h3>{t(`management.distribution.${kind}`)}</h3><dl className="customer-profile">{Object.entries(counts).map(([status,n])=><div key={status}><dt>{status==="UNKNOWN"?t("management.unknown"):t(`management.status.${status}`)}</dt><dd>{n}</dd></div>)}</dl></div>)}</>}</section>;})}
 <section className="surface page-stack"><h2>{t("management.attention")}</h2><Link href={attentionQueueHref(filters)} data-view-all-attention>{t("management.queue.viewAll")}</Link><p>{t("management.attentionHelp")} · {data.attention.total} · {t("management.limit",{count:data.attention.limit})}</p>{data.attention.items.map(item=><article className="detail-section" key={`${item.source_domain}:${item.source_type}:${item.source_id}:${item.reason_code}`}><b>{t(`management.reason.${item.reason_code}`)}</b><p>{t(`management.section.${item.source_domain==="STUDENT_SUCCESS"?"studentSuccess":item.source_domain==="DATA_QUALITY"?"quality":item.source_domain.toLowerCase()}`)} · {t(`management.severity.${item.severity}`)} · {item.business_date??"—"}</p><Link href={attentionHref(item)}>{t("management.openSource")}</Link></article>)}{!data.attention.items.length&&<p>{t("common.noData")}</p>}</section>
 {data.permissions.quality&&<section className="surface"><h2>{t("management.section.quality")}</h2><p>{t("management.qualityHelp")} · {data.quality.count}</p><dl className="customer-profile">{data.quality.distribution.map(row=><div key={`${row.entity_type}:${row.severity}`}><dt>{t(`management.source.${row.entity_type}`)} · {t(`quality.severity.${row.severity.toLowerCase()}`)}</dt><dd>{row.count}</dd></div>)}</dl><Link href="/data-quality">{t("management.open")}</Link></section>}</>}
 </div>;
}
