"use client";

import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, CircleDollarSign, FileCheck2, Plus, Send, ShieldCheck, TimerReset, UserRoundCheck, X } from "lucide-react";
import { EmptyState } from "@/components/data-state";
import { useAppUser } from "@/components/app-user-context";
import { useI18n } from "@/components/i18n-provider";
import { InlineMessage, Pagination, ProgressBar, SearchableSelect, SearchField, StatusBadge, Toast } from "@/components/ui";
import type { ApprovalPage, ApprovalRecord, PerformanceWorkspace } from "@/lib/governance-repository";
import { roleMessageKey } from "@/lib/roles";

type ApprovalStatus="pending"|"approved"|"rejected";
export function RoleHierarchyNote(){const {t}=useI18n();return <InlineMessage type="warning">{t("admin.hierarchyNote")}</InlineMessage>;}

export function ApprovalCenterPage({initialPage}:{initialPage:ApprovalPage}){
  const {locale,t}=useI18n();const user=useAppUser();const [requests,setRequests]=useState(initialPage.items);const [total,setTotal]=useState(initialPage.total);const [summary,setSummary]=useState(initialPage.summary);const [query,setQuery]=useState("");const [typeFilter,setTypeFilter]=useState<"all"|ApprovalRecord["type"]>("all");const [statusFilter,setStatusFilter]=useState<"all"|ApprovalStatus>("pending");const [page,setPage]=useState(1);const [reviewing,setReviewing]=useState<string|null>(null);const [rejectReason,setRejectReason]=useState("");const [error,setError]=useState("");const [toast,setToast]=useState("");const [loading,setLoading]=useState(false);const pageSize=8;
  const pages=Math.max(1,Math.ceil(total/pageSize));const safePage=Math.min(page,pages);const visible=requests;
  const load=useCallback(async(nextPage:number)=>{setLoading(true);try{const params=new URLSearchParams({q:query,type:typeFilter,status:statusFilter,page:String(nextPage),pageSize:String(pageSize)});const response=await fetch(`/api/approvals?${params}`);const result=await response.json() as ApprovalPage;if(!response.ok||!result.items)throw new Error();setRequests(result.items);setTotal(result.total);setSummary(result.summary);}catch{setError(t("approval.loadFailed"));}finally{setLoading(false);}},[query,statusFilter,t,typeFilter]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(page),query?250:0);return()=>window.clearTimeout(timer);},[load,page,query]);
  const decide=async(request:ApprovalRecord,status:ApprovalStatus)=>{if(status==="rejected"&&!rejectReason.trim()){setError(t("approval.rejectRequired"));return;}setError("");const response=await fetch(`/api/approvals/${request.id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision:status.toUpperCase(),comment:rejectReason})});const result=await response.json() as {item?:{execution_status?:string}};if(!response.ok){setError(t("approval.saveFailed"));return;}if(status==="approved"&&result.item?.execution_status==="FAILED"){setError(t("approval.executionFailed"));return;}setToast(t(status==="approved"?"approval.approvedMessage":"approval.rejectedMessage",{id:request.requestNumber}));setReviewing(null);setRejectReason("");await load(page);};
  const formatDate=(value:string)=>new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
  return <div className="page-stack governance-page"><section className="page-heading-row"><div><p className="eyebrow">{t("approval.eyebrow")}</p><h1>{t("approval.title")}</h1><p>{t("approval.description")}</p></div><StatusBadge tone="purple"><ShieldCheck size={14}/>{t("approval.auditNote")}</StatusBadge></section><section className="quick-summary"><span><b>{summary.pending}</b><small>{t("approval.pending")}</small></span><span><b>{summary.approved}</b><small>{t("approval.approved")}</small></span><span><b>{summary.rejected}</b><small>{t("approval.rejected")}</small></span><span><b>{summary.highPrivilegePending}</b><small>{t("approval.highPrivilege")}</small></span></section>
    <section className="surface governance-list"><div className="table-toolbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("approval.search")}/><div className="filter-chips"><label className="compact-select"><span>{t("approval.type")}</span><select value={typeFilter} onChange={event=>{setTypeFilter(event.target.value as typeof typeFilter);setPage(1);}}><option value="all">{t("common.all")}</option>{(["contractSign","contractExport","performanceSummary","performanceAllocation"] as const).map(value=><option value={value} key={value}>{t(`approval.type.${value}`)}</option>)}</select></label><label className="compact-select"><span>{t("common.status")}</span><select value={statusFilter} onChange={event=>{setStatusFilter(event.target.value as typeof statusFilter);setPage(1);}}><option value="all">{t("common.all")}</option>{(["pending","approved","rejected"] as const).map(value=><option value={value} key={value}>{t(`approval.status.${value}`)}</option>)}</select></label></div></div>
      {visible.length?<><div className="governance-table-head"><span>{t("approval.type")}</span><span>{t("approval.requester")}</span><span>{t("approval.reason")}</span><span>{t("approval.level")}</span><span>{t("common.status")}</span><span>{t("common.actions")}</span></div>{visible.map(request=>{const canDecide=request.level==="admin"||user.role==="SUPER_ADMIN";return <div className="approval-item" key={request.id}><div className="governance-row"><span className={`workflow-icon ${request.type}`}><FileCheck2 size={18}/></span><div><b>{t(`approval.type.${request.type}`)}</b><small>{request.requestNumber} · {request.object}</small></div><span><b>{request.requester}</b><small>{formatDate(request.submitted)}</small></span><span><b>{request.reason}</b><small>{t(`approval.level.${request.level}`)}</small></span><StatusBadge tone={request.level==="superAdmin"?"purple":"blue"}>{t(`approval.level.${request.level}`)}</StatusBadge><StatusBadge tone={request.status==="pending"?"amber":request.status==="approved"?"green":"red"}>{t(`approval.status.${request.status}`)}</StatusBadge><button className="secondary-button" type="button" title={!canDecide?t("approval.requiresSuperAdmin"):undefined} disabled={request.status!=="pending"||!canDecide} onClick={()=>{setReviewing(request.id);setError("");}}>{t("approval.review")}</button></div>{reviewing===request.id&&<div className="approval-review"><div><b>{request.object}</b><p>{request.reason}</p></div><label className="field"><span>{t("approval.rejectReason")}</span><textarea rows={2} value={rejectReason} onChange={event=>{setRejectReason(event.target.value);setError("");}} placeholder={t("approval.rejectPlaceholder")}/>{error&&<InlineMessage type="error">{error}</InlineMessage>}</label><div className="approval-actions"><button className="ghost-button" type="button" onClick={()=>{setReviewing(null);setError("");}}>{t("approval.cancelReview")}</button><button className="danger-button" type="button" onClick={()=>decide(request,"rejected")}><X size={16}/>{t("approval.reject")}</button><button className="primary-button" type="button" onClick={()=>decide(request,"approved")}><BadgeCheck size={16}/>{t("approval.approve")}</button></div></div>}</div>;})}</>:<EmptyState messageKey="approval.empty"/>}<Pagination page={safePage} totalPages={pages} total={total} pageSize={pageSize} onPage={setPage}/>{loading&&<span className="sr-only" aria-live="polite">{t("common.loading")}</span>}</section>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}

type Allocation={id:string;name:string;role:"specialist"|"support";amount:number;actual:number;rule:"direct"|"assisted"};
export function PerformanceAllocationPage({workspace,persistent=true}:{workspace:PerformanceWorkspace;persistent?:boolean}){
  const {locale,t}=useI18n();const appUser=useAppUser();const members=workspace.members.map(item=>({value:item.id,label:item.name,role:item.role,team:item.team}));const [targetId,setTargetId]=useState(workspace.targetId);const [target,setTarget]=useState(workspace.target);const [periodStart,setPeriodStart]=useState(workspace.periodStart);const [periodEnd,setPeriodEnd]=useState(workspace.periodEnd);const [allocations,setAllocations]=useState<Allocation[]>(workspace.allocations.map(item=>({id:item.memberId,name:item.name,role:item.role,amount:item.amount,actual:item.actual,rule:item.rule})));const [query,setQuery]=useState("");const [page,setPage]=useState(1);const [adding,setAdding]=useState(false);const [member,setMember]=useState("");const [amount,setAmount]=useState("");const [error,setError]=useState("");const [toast,setToast]=useState("");const [pending,setPending]=useState(false);const locked=workspace.status!=="DRAFT";
  const allocated=allocations.reduce((sum,item)=>sum+item.amount,0);const remaining=target-allocated;const money=(value:number)=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en-US",{style:"currency",currency:workspace.currency,maximumFractionDigits:0}).format(value);const memberOptions=members.map(item=>({value:item.value,label:item.label,detail:`${item.team} · ${t(`allocation.${item.role}`)}`}));const filtered=allocations.filter(item=>`${item.name} ${item.role}`.toLowerCase().includes(query.toLowerCase()));const pageSize=8;const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  const add=()=>{const selected=members.find(item=>item.value===member);const parsed=Number(amount);if(!selected){setError(t("allocation.memberSelect"));return;}if(allocations.some(item=>item.id===member)){setError(t("allocation.duplicate"));return;}if(!Number.isFinite(parsed)||parsed<=0||parsed>remaining){setError(t("allocation.invalidAmount"));return;}setAllocations(items=>[...items,{id:member,name:selected.label,role:selected.role,amount:parsed,actual:0,rule:selected.role==="support"?"assisted":"direct"}]);setAdding(false);setMember("");setAmount("");setError("");};
  const persist=async(submit:boolean)=>{if(target<=0||periodEnd<periodStart){setError(t("allocation.invalidPlan"));return;}if(submit&&remaining!==0){setError(t("allocation.mustFullyAllocate"));return;}if(!persistent)return;setPending(true);setError("");const saved=await fetch("/api/performance/plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"save",targetId,managerId:workspace.managerId,target,periodStart,periodEnd,currency:workspace.currency,allocations:allocations.map(item=>({memberId:item.id,amount:item.amount,rule:item.rule}))})});const result=await saved.json() as {item?:{id?:string}};if(!saved.ok||!result.item?.id){setError(t("allocation.saveFailed"));setPending(false);return;}setTargetId(result.item.id);if(submit){const response=await fetch("/api/performance/plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"submit",targetId:result.item.id,reason:t("allocation.submitReason")})});if(!response.ok){setError(t("allocation.submitFailed"));setPending(false);return;}}setToast(t(submit?"allocation.submitted":"allocation.saved"));setPending(false);};
  return <div className="page-stack governance-page"><section className="page-heading-row"><div><p className="eyebrow">{t("allocation.eyebrow")}</p><h1>{t("allocation.title")}</h1><p>{t("allocation.description")}</p></div><div className="page-actions"><button className="secondary-button" type="button" disabled={pending||locked} onClick={()=>persist(false)}>{t("allocation.save")}</button><button className="primary-button" type="button" disabled={pending||locked} onClick={()=>persist(true)}><Send size={16}/>{t("allocation.submit")}</button></div></section>{locked&&<InlineMessage type="warning">{t("allocation.locked",{status:workspace.status})}</InlineMessage>}{error&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="surface allocation-context"><label className="field"><span>{t("allocation.manager")}</span><input value={`${appUser.displayNameZh} / ${appUser.displayName} · ${t(roleMessageKey[appUser.role])}`} readOnly/></label><label className="field"><span>{t("allocation.periodStart")}</span><input type="date" value={periodStart} disabled={locked} onChange={event=>setPeriodStart(event.target.value)}/></label><label className="field"><span>{t("allocation.periodEnd")}</span><input type="date" value={periodEnd} disabled={locked} onChange={event=>setPeriodEnd(event.target.value)}/></label><label className="field"><span>{t("allocation.target")}</span><input type="number" min="1" step="1000" value={target} disabled={locked} onChange={event=>setTarget(Number(event.target.value))}/></label></section>
    <section className="allocation-summary"><article className="surface"><span><CircleDollarSign size={19}/></span><div><small>{t("allocation.target")}</small><b>{money(target)}</b></div></article><article className="surface"><span><UserRoundCheck size={19}/></span><div><small>{t("allocation.allocated")}</small><b>{money(allocated)}</b></div></article><article className="surface"><span><TimerReset size={19}/></span><div><small>{t("allocation.remaining")}</small><b>{money(remaining)}</b></div></article><article className="surface allocation-progress"><div><small>{t("allocation.coverage")}</small><b>{target?Math.round(allocated/target*100):0}%</b></div><ProgressBar value={target?allocated/target*100:0} label={`${target?Math.round(allocated/target*100):0}%`}/></article></section><InlineMessage type="warning">{t("allocation.noDoubleCount")}</InlineMessage>
    <section className="surface governance-list"><div className="table-toolbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("allocation.search")}/><button className="secondary-button" type="button" disabled={locked} onClick={()=>{setAdding(true);setError("");}}><Plus size={16}/>{t("allocation.add")}</button></div>{adding&&<div className="allocation-add"><div><b>{t("allocation.addTitle")}</b><small>{t("allocation.remaining")}: {money(remaining)}</small></div><SearchableSelect label={t("allocation.memberSelect")} options={memberOptions} value={member} onChange={value=>{setMember(value);setError("");}}/><label className="field"><span>{t("allocation.amountInput")}</span><input type="number" min="1" max={Math.max(0,remaining)} step="1000" value={amount} onChange={event=>{setAmount(event.target.value);setError("");}}/>{error&&<InlineMessage type="error">{error}</InlineMessage>}</label><div className="approval-actions"><button className="ghost-button" type="button" onClick={()=>setAdding(false)}>{t("common.cancel")}</button><button className="primary-button" type="button" onClick={add}>{t("common.create")}</button></div></div>}
      {visible.length?<><div className="allocation-table-head"><span>{t("allocation.member")}</span><span>{t("allocation.branch")}</span><span>{t("allocation.amount")}</span><span>{t("allocation.share")}</span><span>{t("allocation.actual")}</span><span>{t("allocation.contribution")}</span><span>{t("common.actions")}</span></div>{visible.map(item=><div className="allocation-row" key={item.id}><div><span className="record-avatar">{item.name.split(" / ")[1]?.split(" ").map(part=>part[0]).join("")??"—"}</span><b>{item.name}</b></div><StatusBadge tone={item.role==="support"?"green":"blue"}>{t(`allocation.${item.role}`)}</StatusBadge><b>{money(item.amount)}</b><ProgressBar value={target?item.amount/target*100:0} label={`${target?Math.round(item.amount/target*100):0}%`}/><b>{money(item.actual)}</b><StatusBadge tone={item.rule==="direct"?"purple":"amber"}>{t(`allocation.${item.rule}`)}</StatusBadge><button className="ghost-button" type="button" disabled={locked} onClick={()=>setAllocations(items=>items.filter(entry=>entry.id!==item.id))}>{t("allocation.remove")}</button></div>)}</>:<EmptyState messageKey="allocation.empty"/>}<Pagination page={safePage} totalPages={pages} total={filtered.length} pageSize={pageSize} onPage={setPage}/><InlineMessage type="warning">{t("allocation.audit")}</InlineMessage></section>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
