"use client";
import {useState} from "react";
import {useReceiptMutation} from "@/hooks/use-receipt-mutation";
import {useI18n} from "./i18n-provider";
import {AccessibleDrawer,InlineMessage} from "./ui";
const blank=()=>({key:crypto.randomUUID(),nameZh:"",nameEn:"",email:"",phone:"",occupation:"",employer:"",title:"",role:"PARENT",relationship:"UNSPECIFIED",primary:false});
export function HouseholdCreateEditor({onClose,onSaved}:{onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),en=locale==="en",mutation=useReceiptMutation("/api/households/create");
 const [people,setPeople]=useState(()=>[{...blank(),primary:true},blank()]),[accepted,setAccepted]=useState(false),[notice,setNotice]=useState("");
 const refresh=async()=>{try{await onSaved();}catch{setNotice(t("audit.savedRefreshFailed"));}};
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(accepted){await refresh();return;}const f=new FormData(e.currentTarget);const household=Object.fromEntries(["nameZh","nameEn","address","preferredLanguage","educationExpectationsMarkdown","familyBackgroundMarkdown"].map(key=>[key,String(f.get(key)??"")]));const incomplete=people.some(p=>!p.nameZh.trim()&&!p.nameEn.trim()&&[p.email,p.phone,p.occupation,p.employer,p.title].some(v=>v.trim()));if(incomplete){setNotice(en?"Enter a name for each person whose details you have filled in.":"请为已填写资料的每位家庭成员补充姓名。");return;}setNotice("");const entries=people.filter(p=>p.nameZh.trim()||p.nameEn.trim()).map(({key,...p})=>{void key;return p;});if(await mutation.send({household,people:entries})){setAccepted(true);await refresh();}};
 const frozen=mutation.pending||mutation.uncertain||accepted;
 return <AccessibleDrawer title={t("education.newHousehold")} pending={mutation.pending||mutation.uncertain} onClose={onClose}><form onSubmit={save}><fieldset className="follow-up-fields" disabled={frozen}><h3>{en?"Family / Household":"家庭"}</h3><div className="form-grid two-column">{["nameZh","nameEn"].map(key=><label className="field" key={key}><span>{t(`education.${key}`)}</span><input name={key} maxLength={160}/></label>)}</div><label className="field"><span>{t("education.address")}</span><textarea name="address" rows={2} maxLength={1000}/></label><label className="field"><span>{t("education.preferredLanguage")}</span><select name="preferredLanguage" defaultValue=""><option value="">{en?"Not specified":"未指定"}</option><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option></select></label><details><summary>{en?"Family context":"家庭背景"}</summary><label className="field"><span>{t("education.familyExpectations")}</span><textarea name="educationExpectationsMarkdown" maxLength={10000}/></label><label className="field"><span>{t("education.familyBackground")}</span><textarea name="familyBackgroundMarkdown" maxLength={10000}/></label></details>
 {people.map((p,index)=><section className="detail-section household-person-card" key={p.key}><h3>{en?"Parent / Guardian":"家长／监护人"} {index+1}</h3><div className="form-grid two-column">{([['nameZh','Chinese name','中文姓名'],['nameEn','English name','英文姓名'],['phone','Mobile','手机'],['email','Email','电子邮箱'],['occupation','Occupation','职业'],['employer','Employer / organization','雇主／机构'],['title','Title','职务']] as const).map(([key,english,chinese])=><label className="field" key={key}><span>{en?english:chinese}</span><input type={key==="email"?"email":"text"} value={p[key]} maxLength={key==="email"?320:key==="phone"?40:160} onChange={e=>setPeople(old=>old.map(x=>x.key===p.key?{...x,[key]:e.target.value}:x))}/></label>)}<label className="field"><span>{en?"Family relationship":"家庭关系"}</span><select value={p.relationship} onChange={e=>setPeople(old=>old.map(x=>x.key===p.key?{...x,relationship:e.target.value}:x))}>{[["UNSPECIFIED","Not specified","未指定"],["FATHER","Father","父亲"],["MOTHER","Mother","母亲"],["GUARDIAN","Guardian","监护人"],["OTHER","Other","其他"]].map(([value,english,chinese])=><option key={value} value={value}>{en?english:chinese}</option>)}</select></label><label className="field"><span>{t("education.memberRole")}</span><select value={p.role} onChange={e=>setPeople(old=>old.map(x=>x.key===p.key?{...x,role:e.target.value}:x))}>{["PARENT","GUARDIAN","PAYER","OTHER"].map(role=><option key={role} value={role}>{t(`education.memberRole.${role.toLowerCase()}`)}</option>)}</select></label></div><label className="checkbox-row"><input type="radio" name="primaryMember" checked={p.primary} onChange={()=>setPeople(old=>old.map(x=>({...x,primary:x.key===p.key})))}/>{t("education.primaryContact")}</label>{people.length>1&&<button type="button" className="text-button" onClick={()=>setPeople(old=>old.filter(x=>x.key!==p.key))}>{en?"Remove":"移除"}</button>}</section>)}
 <button type="button" className="secondary-button" disabled={people.length>=10} onClick={()=>setPeople(old=>[...old,blank()])}>{en?"Add another parent / guardian":"添加另一位家长／监护人"}</button><p className="field-help">{en?"Household membership does not grant legal guardian authorization.":"家庭成员关系不等于监护授权。"}</p></fieldset>{mutation.error&&<InlineMessage type="error">{mutation.error}</InlineMessage>}{notice&&<InlineMessage type="info">{notice}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" disabled={mutation.pending||mutation.uncertain} onClick={onClose}>{t("common.cancel")}</button><button className="primary-button" disabled={mutation.pending}>{t(accepted?"ux.management.refresh":mutation.uncertain?"enrollments.retry":"common.create")}</button></div></form></AccessibleDrawer>;
}
