"use client";
import {WorkspaceHeading} from "./workspace-heading";

import {useEffect,useState} from 'react';
import {apiFetch} from '@/lib/api-client';
import {parseCsvDocument} from '@/lib/csv';
import {parseXlsxDocument} from '@/lib/xlsx';
import {normalizeLocalizedImport} from "@/lib/import-localized-headers";
import {setResources,relationResources,relationFields,isEntity,setHeaders,validateSetHeaders,type SetResource} from '@/lib/import-set-contract';
import {relationLabels} from '@/lib/import-set-labels';
import type {ImportSetView} from '@/lib/import-set-repository';
import {useI18n} from './i18n-provider';
import {InlineMessage,StatusBadge} from './ui';
import {ImportReferencePanel} from './import-reference-panel';

export function ImportSetsPage({relationships=false,embedded=false}:{relationships?:boolean;embedded?:boolean}){
 const {locale}=useI18n(),zh=locale==='zh-CN';
 const [sets,setSets]=useState<Array<{id:string;name:string;status:string}>>([]),[view,setView]=useState<ImportSetView|null>(null),[name,setName]=useState(''),[resource,setResource]=useState<SetResource>(relationships?'HOUSEHOLD_MEMBERS':'ORGANIZATIONS'),[format,setFormat]=useState('xlsx'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [repair,setRepair]=useState<ImportSetView['rows'][number]|null>(null),[replacement,setReplacement]=useState<Record<string,string>>({});
 const text=(cn:string,en:string)=>zh?cn:en;
 const label=(r:string)=>relationLabels[r]?.[zh?0:1]??({ORGANIZATIONS:text('机构','Organizations'),HOUSEHOLDS:text('家庭','Households'),CONTACTS:text('联系人','Contacts'),STUDENTS:text('学生','Students')} as Record<string,string>)[r]??r;
 const load=async()=>{try{const result=await apiFetch<{items:typeof sets}>('/api/imports/sets');setSets(result.items);}catch{setError('INVALID_REFERENCE');}};
 useEffect(()=>{void apiFetch<{items:typeof sets}>('/api/imports/sets').then(r=>setSets(r.items)).catch(()=>setError('INVALID_REFERENCE'));},[]);
 const open=async(id:string)=>{setBusy(true);setError('');try{setView((await apiFetch<{item:ImportSetView}>('/api/imports/sets?set='+id)).item);}catch{setError('INVALID_REFERENCE');}finally{setBusy(false);}};
 const act=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');try{const result=await apiFetch<{item:ImportSetView|{id?:string;setId?:string}}>('/api/imports/sets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const id='rows' in result.item?result.item.id:result.item.setId??result.item.id;if(id)await open(id);await load();return true;}catch(e){setError(e instanceof Error?e.message:'IMPORT_SET_FAILED');return false;}finally{setBusy(false);}};
 const upload=async(file?:File)=>{if(!file||!view)return;setBusy(true);setError('');try{
  if(file.size>5*1024*1024)throw Error('IMPORT_SET_LIMIT');
  const doc=file.name.toLowerCase().endsWith('.xlsx')?await parseXlsxDocument(file,1000,{resource,templateVersion:'SET_V1'}):file.name.toLowerCase().endsWith('.csv')?parseCsvDocument(await file.text(),1000,true):null;
  if(!doc)throw Error('TEMPLATE_VERSION_UNSUPPORTED');Object.assign(doc,normalizeLocalizedImport(doc,setHeaders(resource)));validateSetHeaders(resource,doc.headers);
  const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');
  await act({operation:'addSetFile',setId:view.id,expectedRevision:view.revision,requestKey:crypto.randomUUID(),file:{resource,templateVersion:'SET_V1',filename:file.name,contentHash:hash,headers:doc.headers,rows:doc.rows,rowLocations:doc.rowLocations??doc.rows.map((_,i)=>i+2),...(doc.sheet?{sheet:doc.sheet}:{})}});
 }catch(e){setError(e instanceof Error?e.message:'IMPORT_SET_FAILED');}finally{setBusy(false);}};
 const startRepair=(row:ImportSetView['rows'][number])=>{const input:Record<string,string>=Object.fromEntries(setHeaders(row.resource).map(key=>[key,'']));input.operation=row.operation;
  if(isEntity(row.resource)){input.alias=row.alias;input.targetReference=row.normalized.targetReference??'';}
  for(const [key,value] of Object.entries(row.normalized.patch??{})){const field=isEntity(row.resource)?key:relationFields[row.resource].find(f=>f.column===key)?.key;if(field)input[field]=value===null?'__CLEAR__':Array.isArray(value)?value.join('|'):String(value);}
  for(const [key,value] of Object.entries(row.normalized.profile??{}))input['profile.'+key]=value===null?'__CLEAR__':Array.isArray(value)?value.join('|'):String(value);
  setReplacement(input);setRepair(row);
 };
 return <div className="page-stack import-sets-page"><section className="panel">{embedded?<h2>{text('关系导入与 Import Set','Relationship imports and Import Sets')}</h2>:<WorkspaceHeading>{text('关系导入与 Import Set','Relationship imports and Import Sets')}</WorkspaceHeading>}<InlineMessage type="info">{text('关系模板独立于实体模板。别名只在本 Set 内有效；授权引用有效期 24 小时。预检不写入业务事实。每行独立提交，失败会阻止依赖行；回滚会保留后续已修改的记录。','Relationships use separate templates. Aliases exist only in this Set; selected references expire after 24 hours. Preflight changes no business facts. Rows commit independently; failed parents block dependent rows. Rollback preserves subsequently edited records.')}</InlineMessage>
 <div className="form-grid"><label className="field"><span>{text('Set 名称','Set name')}</span><input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary-button" disabled={busy||!name.trim()} onClick={()=>void act({operation:'createSet',name:name.trim(),requestKey:crypto.randomUUID()})}>{text('创建 Set','Create Set')}</button><label className="field"><span>{text('选择 Set','Select Set')}</span><select value={view?.id??''} onChange={e=>void open(e.target.value)}><option value="">—</option>{sets.map(s=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select></label></div>
 {error&&<InlineMessage type="error">{error}</InlineMessage>}</section>
 <section className="panel"><h2>{text('分类模板与文件','Templates and files')}</h2><div className="form-grid"><label className="field"><span>{text('资源','Resource')}</span><select value={resource} onChange={e=>setResource(e.target.value as SetResource)}>{(relationships?relationResources:setResources).map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label className="field"><span>{text('格式','Format')}</span><select value={format} onChange={e=>setFormat(e.target.value)}><option value="xlsx">XLSX</option><option value="csv">CSV</option></select></label></div><div className="toolbar">{(['blank','example','guide'] as const).map(kind=><a key={kind} className="secondary-button" href={`/api/imports/template?resource=${resource}&templateVersion=SET_V1&locale=${locale}&format=${kind==='guide'?'csv':format.toLowerCase()}&kind=${kind}`}>{kind==='blank'?text('空白模板','Blank template'):kind==='example'?text('示例模板','Example template'):text('字段指南','Field guide')}</a>)}</div><label className="field"><span>{text('添加文件（SET_V1；最多 20 文件 / 2000 行）','Add file (SET_V1; max 20 files / 2000 rows)')}</span><input type="file" accept=".csv,.xlsx" disabled={busy||!view} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><ImportReferencePanel/></section>
 {view&&<><section className="panel"><h2>{view.name} · <StatusBadge>{view.status}</StatusBadge></h2><p>{text('修订','Revision')} {view.revision} · {text('已应用','Applied')} {view.rows.filter(r=>r.status==='APPLIED').length}/{view.rows.length} · {text('依赖阻塞','Blocked dependency')} {view.rows.filter(r=>r.error==='BLOCKED_DEPENDENCY').length} · {text('需要复核','Needs review')} {view.rows.filter(r=>['INVALID','FAILED','DUPLICATE'].includes(r.status)).length}</p><div className="toolbar">{(['preflightSet','executeSet','rollbackSet'] as const).map(operation=><button key={operation} className="secondary-button" disabled={busy||!view.rows.length} onClick={()=>void act({operation,setId:view.id,expectedRevision:view.revision,limit:50})}>{operation==='preflightSet'?text('预检 Set','Preflight Set'):operation==='executeSet'?text('执行就绪行 / 继续','Execute ready rows / Resume'):text('受保护回滚（最多 50 行）','Guarded rollback (max 50 rows)')}</button>)}<button className="secondary-button" disabled={busy} onClick={()=>void open(view.id)}>{text('刷新','Refresh')}</button></div>
 <ul>{view.batches.map(b=><li key={b.id}>{label(b.resource)} · {b.filename} · {b.applied}/{b.total} · {b.status}</li>)}</ul><details><summary>{text('别名与依赖','Aliases and dependencies')}</summary><ul>{view.aliases.map(a=><li key={a.alias}><code>{a.alias}</code> · {a.status}</li>)}</ul><ul>{view.dependencies.map(d=><li key={d.row+d.parent}>{view.rows.find(r=>r.id===d.parent)?.alias||view.rows.find(r=>r.id===d.parent)?.row} → {label(view.rows.find(r=>r.id===d.row)?.resource??'')} #{view.rows.find(r=>r.id===d.row)?.row}</li>)}</ul></details></section>
 <section className="panel"><h2>{text('逐行结果','Row outcomes')}</h2><div className="table-scroll"><table className="data-table"><thead><tr>{[text('资源 / 行','Resource / Row'),text('操作','Operation'),text('别名','Alias'),text('状态','Status'),text('错误','Error'),text('修复','Repair')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{view.rows.map(r=><tr key={r.id}><td data-label={text('资源 / 行','Resource / Row')}>{label(r.resource)} #{r.row}</td><td data-label={text('操作','Operation')}>{r.operation}</td><td data-label={text('别名','Alias')}>{r.alias}</td><td data-label={text('状态','Status')}>{r.status}</td><td data-label={text('错误','Error')}>{r.error||r.errors.map(e=>`${e.code} ${e.field??''}`).join('; ')}</td><td data-label={text('修复','Repair')}>{!['APPLIED','SKIPPED','ROLLED_BACK'].includes(r.status)&&<button className="secondary-button" disabled={busy} onClick={()=>startRepair(r)}>{text('修复并重新预检','Repair and preflight')}</button>}</td></tr>)}</tbody></table></div></section></>}
 {repair&&view&&<section className="panel"><h2>{text('修复行','Repair row')} #{repair.row}</h2><p>{text('更新需要明确选择目标；相同名称不是身份。空白不清空；敏感字段可选。','Updates require an explicit selected target; a matching name is not an identity. Blanks preserve values; sensitive fields are optional.')}</p><div className="form-grid">{setHeaders(repair.resource).map(k=><label className="field" key={k}><span>{relationLabels[k]?.[zh?0:1]??k}</span><textarea value={replacement[k]??''} disabled={k==='alias'} onChange={e=>setReplacement({...replacement,[k]:e.target.value})}/></label>)}</div><button className="primary-button" disabled={busy} onClick={()=>void act({operation:'repairSetRow',setId:view.id,rowId:repair.id,expectedRevision:view.revision,rowRevision:repair.revision,replacement}).then(ok=>{if(ok)setRepair(null);})}>{text('保存修复并预检','Save repair and preflight')}</button><button className="secondary-button" onClick={()=>setRepair(null)}>{text('取消','Cancel')}</button></section>}</div>;
}
