"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {metricDefinitions,managementModules,type ManagementMetricKey} from "@/lib/management-metric-contract";
import {metricDrillHref,type TrendFilters,type ManagementTrends,type ManagementTrendSeries} from "@/lib/management-trend-contract";
import {formatChannelCommissionAmount} from "@/lib/channel-analytics-input";
import {useI18n} from "./i18n-provider";
import {InlineMessage} from "./ui";
const primary:ManagementMetricKey[]=["leadsCreated","leadsConverted","enrollmentsCreated","enrollmentsActivated","payments_in_period","refunds_in_period","eventsHeld","commissionPeriod","applicationsSubmitted","milestonesCompleted","checkins","outcomesRecorded"];
export function ManagementTrendsPanel({filters,refreshKey=0}:{filters:TrendFilters;refreshKey?:number}){
 const {t,locale}=useI18n(),[stored,setStored]=useState<{query:string;data:ManagementTrends}|null>(null),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined) as [string,string][]).toString(),data=stored?.query===query?stored.data:null;
 useEffect(()=>{const controller=new AbortController();void apiFetch<ManagementTrends>(`/api/management/trends?${query}`,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setStored({query,data});setFailed(false);}}).catch(()=>{if(!controller.signal.aborted)setFailed(true);});return()=>controller.abort();},[query,retry,refreshKey]);
 const display=(series:ManagementTrendSeries,value:number|string)=>series.unit==="MONEY"?`${series.currency} ${formatChannelCommissionAmount(String(value),locale)}`:String(value);
 return <section className="surface page-stack" data-testid="management-trends"><h2>{t("management.trends")}</h2><p>{t("management.trendHelp")}</p>{failed?<InlineMessage type="error">{t("management.trendFailed")} <button className="secondary-button" onClick={()=>setRetry(n=>n+1)}>{t("common.retry")}</button></InlineMessage>:!data?<p role="status">{t("common.loading")}</p>:<>
 <p>{t("management.currentPeriod")}: {data.period.from}–{data.period.to} · {t("management.previousPeriod")}: {data.previousPeriod.from}–{data.previousPeriod.to} · {data.period.timezone} · {t(`management.granularity.${data.granularity}`)}</p>
 {managementModules.map(module=><section className="page-stack" key={module} data-trend-module={module}><h3>{t(`management.section.${module}`)}</h3>{!data.permissions[module]?<InlineMessage type="info">{t("management.restricted")}</InlineMessage>:<div className="channel-account-grid">{data.series.filter(s=>s.module===module&&primary.includes(s.key)).map(series=>{const comparison=series.comparison,href=metricDrillHref({key:series.key,mode:metricDefinitions[series.key][1],currency:series.currency},filters,data.period),max=series.unit==="COUNT"?Math.max(1,...series.points.map(p=>Number(p.value))):1;return <article className="detail-section page-stack" key={`${series.key}:${series.currency??""}`} data-series={series.key} data-currency={series.currency??undefined}><h4>{t(`management.metric.${series.key}`)} {series.currency??""}</h4><dl className="customer-profile"><div><dt>{t("management.currentPeriod")}</dt><dd>{display(series,comparison.current)}</dd></div><div><dt>{t("management.previousPeriod")}</dt><dd>{display(series,comparison.previous)}</dd></div><div><dt>{t("management.absoluteChange")}</dt><dd>{display(series,comparison.absoluteChange)}</dd></div><div><dt>{t("management.percentChange")}</dt><dd>{comparison.percentChange===null?"—":`${Number(comparison.percentChange).toLocaleString(locale,{maximumFractionDigits:2})}%`}</dd></div></dl>
 <div className="page-stack" aria-label={t(`management.metric.${series.key}`)}>{series.points.map(point=><div key={point.bucketStart} className="form-grid two-column"><span>{point.bucketStart}–{point.bucketEnd}</span><span>{display(series,point.value)} {series.unit==="COUNT"&&<span aria-hidden="true" style={{display:"block",height:5,width:`${Number(point.value)/max*100}%`,background:"var(--color-text-muted, #64748b)"}}/>}</span></div>)}</div>{href&&<Link href={href}>{t("management.drilldown")}</Link>}</article>;})}</div>}{module==="channel"&&!data.permissions.commissionMoney&&<p>{t("management.moneyRestricted")}</p>}</section>)}
 </>}</section>;
}
