"use client";

import { useState } from "react";
import { CheckCircle2, Download, Plus, ScanSearch, SlidersHorizontal, X } from "lucide-react";
import type { ModuleConfig } from "@/lib/crm-data";
import type { PersistentResource } from "@/lib/crm-repository";
import { DataTable } from "@/components/data-table";
import { InlineMessage, Toast } from "@/components/ui";
import { useI18n } from "@/components/i18n-provider";

export function ModulePage({ config, resource, initialTotal }: { config: ModuleConfig; resource?: PersistentResource; initialTotal?: number }) {
  const { t } = useI18n(); const prefix=`modules.${config.key}`;
  const [drawer,setDrawer]=useState(false); const [duplicateChecked,setDuplicateChecked]=useState(false); const [duplicates,setDuplicates]=useState<{nameZh:string;nameEn:string;reason:string}[]>([]); const [checking,setChecking]=useState(false); const [error,setError]=useState(""); const [toast,setToast]=useState(""); const [refreshKey,setRefreshKey]=useState(0);
  const close=()=>{setDrawer(false);setDuplicateChecked(false);setDuplicates([]);setError("");};
  const payload=(form:HTMLFormElement)=>{const data=new FormData(form);const contact=String(data.get("contact")??"").trim();return {nameZh:String(data.get("nameZh")??""),nameEn:String(data.get("nameEn")??""),contact,email:contact.includes("@")?contact:"",phone:contact&&!contact.includes("@")?contact:""};};
  const check=async(form:HTMLFormElement)=>{if(!resource)return;setChecking(true);setError("");const response=await fetch(`/api/crm/${resource}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload(form),operation:"check"})});const result=await response.json() as {duplicates?:typeof duplicates;code?:string};setChecking(false);if(!response.ok){setError(t("records.error.check"));return;}setDuplicates(result.duplicates??[]);setDuplicateChecked(true);};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!resource||!duplicateChecked)return;setError("");const response=await fetch(`/api/crm/${resource}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload(event.currentTarget),operation:"create"})});const result=await response.json() as {code?:string};if(!response.ok){setError(t(result.code==="DUPLICATE_FOUND"?"records.error.duplicate":"records.error.save"));return;}close();setRefreshKey((value)=>value+1);setToast(t("records.created"));};
  return <div className="page-stack module-page"><section className="page-heading-row"><div><p className="eyebrow">{t(`${prefix}.eyebrow`)}</p><h1>{t(`${prefix}.title`)}</h1><p>{t(`${prefix}.description`)}</p></div><div className="page-actions"><button className="secondary-button" type="button" onClick={()=>resource&&window.location.assign(`/api/crm/${resource}?format=csv&pageSize=100`)} disabled={!resource}><Download size={16}/>{t("modules.export")}</button><button className="primary-button" type="button" onClick={()=>setDrawer(true)} disabled={!resource}><Plus size={17}/>{t(`${prefix}.add`)}</button></div></section>
    <section className="quick-summary"><span><b>{initialTotal??config.rows.length}</b><small>{t("modules.allRecords")}</small></span><span><b>{config.rows.filter((row)=>row.statusTone==="red"||row.statusTone==="amber").length}</b><small>{t("modules.needsAttention")}</small></span><span><b>{config.rows.length?Math.round(config.rows.reduce((sum,row)=>sum+row.completeness,0)/config.rows.length):0}%</b><small>{t("modules.averageCompleteness")}</small></span><button type="button" disabled title={t("records.savedViewsUnavailable")}><SlidersHorizontal size={16}/>{t("modules.savedViews")}</button></section>
    <DataTable config={config} resource={resource} initialTotal={initialTotal} refreshKey={refreshKey}/>
    {drawer&&<><button className="drawer-overlay" type="button" aria-label={t("common.close")} onClick={close}/><aside className="record-drawer" role="dialog" aria-modal="true" aria-label={t("modules.createRecord",{record:t(`${prefix}.singular`)})}><div className="drawer-heading"><div><p className="eyebrow">{t("eyebrow.createRecord")}</p><h2>{t("modules.createRecord",{record:t(`${prefix}.singular`)})}</h2><p>{t("modules.createHelp")}</p></div><button className="icon-button" type="button" aria-label={t("common.close")} onClick={close}><X size={20}/></button></div><form onSubmit={submit}><div className="form-grid two-column"><label className="field"><span>{t("products.nameZh")} <b>*</b></span><input name="nameZh" required/></label><label className="field"><span>{t("products.nameEn")} <b>*</b></span><input name="nameEn" required/></label></div><label className="field"><span>{t("modules.contact")}</span><input name="contact" placeholder={t("modules.duplicatePlaceholder")}/></label>
      <div className="duplicate-check"><div><span><ScanSearch size={18}/></span><div><b>{t("modules.duplicateTitle")}</b><p>{t("modules.duplicateHelp")}</p></div></div>{duplicateChecked?<InlineMessage type={duplicates.length?"warning":"success"}>{duplicates.length?t("records.duplicateCount",{count:duplicates.length}):t("modules.duplicateClear")}</InlineMessage>:<button className="secondary-button" type="button" disabled={checking} onClick={(event)=>check(event.currentTarget.form!)}><ScanSearch size={16}/>{checking?t("records.checking"):t("modules.checkNow")}</button>}</div>
      {duplicates.length>0&&<div className="duplicate-results">{duplicates.map((item)=><p key={`${item.nameZh}-${item.nameEn}`}><b>{item.nameZh} / {item.nameEn}</b><small>{item.reason}</small></p>)}</div>}{!duplicateChecked&&<InlineMessage type="warning">{t("modules.checkRequired")}</InlineMessage>}{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={close}>{t("common.cancel")}</button><button className="primary-button" type="submit" disabled={!duplicateChecked||duplicates.length>0}><CheckCircle2 size={17}/>{t("modules.createRecord",{record:t(`${prefix}.singular`)})}</button></div></form></aside></>}{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
