"use client";

import { useState } from "react";
import { AlertTriangle, ArrowRight, Bot, Check, CheckCircle2, ChevronRight, Clock3, Download, FileBarChart, FileSpreadsheet, GraduationCap, Import, MessageSquareText, Play, Plus, RotateCcw, ScanSearch, School, ShieldCheck, Sparkles, UploadCloud, Users, WandSparkles } from "lucide-react";
import { InlineMessage, ProgressBar, StatusBadge, Toast } from "@/components/ui";
import { useI18n } from "@/components/i18n-provider";

export function ProgressionPage() { const { locale, t } = useI18n(); const [toast, setToast] = useState(""); const candidates = [
  { name: "何雨乔 / Mia Ho", school: locale === "zh-CN" ? "杭州国际学校" : "Hangzhou International School", from: "IB Year 1", to: "IB Year 2", reason: locale === "zh-CN" ? "年级资料 9 个月未确认" : "Grade data not verified for 9 months", status: "manual" },
  { name: "林俊佑 / Jay Lin", school: locale === "zh-CN" ? "台北欧洲学校" : "Taipei European School", from: "IB Year 1", to: "IB Year 2", reason: locale === "zh-CN" ? "规则匹配，生效日 2026-08-15" : "Rule matched; effective 2026-08-15", status: "ready" },
  { name: "陈语彤 / Avery Chen", school: locale === "zh-CN" ? "上海惠灵顿" : "Wellington College Shanghai", from: "IGCSE Y11", to: "IB Year 1", reason: locale === "zh-CN" ? "课程体系变化需确认" : "Curriculum change needs confirmation", status: "manual" },
  { name: "张若熙 / Rosie Zhang", school: locale === "zh-CN" ? "香港汉基" : "Chinese International School", from: "MYP 5", to: "IB Year 1", reason: locale === "zh-CN" ? "缺少课程选择" : "Course selection missing", status: "missing" },
]; return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.academicProgression")}</p><h1>{t("ops.progression.title")}</h1><p>{t("ops.progression.description")}</p></div><div className="page-actions"><button className="secondary-button" type="button"><Play size={16} />{t("ops.simulate")}</button><button className="primary-button" type="button">{t("ops.batchConfirm")}</button></div></section><section className="quick-summary"><span><b>148</b><small>{t("ops.candidates")}</small></span><span><b>132</b><small>{t("ops.autoReady")}</small></span><span><b>12</b><small>{t("ops.manualReview")}</small></span><span><b>4</b><small>{t("ops.missingData")}</small></span></section><section className="surface progression-surface"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.promotionWindow")}</p><h2>{t("ops.pendingEvents")}</h2></div><StatusBadge tone="blue">{t("ops.effectiveDate")}</StatusBadge></div>{candidates.map((item) => <div className="progression-row" key={item.name}><span className="record-avatar">{item.name[0]}</span><div><b>{item.name}</b><small>{item.school}</small></div><span className="grade-change"><b>{item.from}</b><ArrowRight size={16} /><b>{item.to}</b></span><span><small>{t("ops.suggestionBasis")}</small><b>{item.reason}</b></span><StatusBadge tone={item.status === "ready" ? "green" : item.status === "missing" ? "red" : "amber"}>{t(item.status === "ready" ? "ops.status.ready" : item.status === "missing" ? "ops.missingData" : "ops.manualReview")}</StatusBadge><button className="secondary-button" type="button" onClick={() => setToast(t("ops.progressionOpened", { name: item.name }))}>{t("admin.review")}</button></div>)}</section><InlineMessage type="warning">{t("ops.progressionWarning")}</InlineMessage>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>; }

export function ImportCenterPage() { const { t } = useI18n(); const [step, setStep] = useState(1); const [file, setFile] = useState(""); const steps = ["upload", "mapping", "validate", "preview"]; return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.dataOnboarding")}</p><h1>{t("ops.import.title")}</h1><p>{t("ops.import.description")}</p></div><button className="secondary-button" type="button"><Download size={16} />{t("ops.downloadTemplate")}</button></section><section className="import-stepper">{steps.map((key, index) => <div className={step >= index + 1 ? "active" : ""} key={key}><span>{step > index + 1 ? <Check size={15} /> : index + 1}</span><b>{t(`ops.step.${key}`)}</b></div>)}</section><section className="surface import-workspace">
  {step === 1 && <><div className="upload-zone"><span><UploadCloud size={28} /></span><h2>{t("ops.uploadTitle")}</h2><p>{t("ops.uploadHelp")}</p><label className="primary-button"><input type="file" accept=".csv,.xlsx" hidden onChange={(event) => setFile(event.target.files?.[0]?.name ?? "")} />{t("ops.chooseFile")}</label>{file && <InlineMessage type="success">{t("ops.fileSelected", { file })}</InlineMessage>}</div><div className="drawer-actions"><span /><button className="primary-button" disabled={!file} type="button" onClick={() => setStep(2)}>{t("ops.continueMapping")} <ArrowRight size={16} /></button></div></>}
  {step === 2 && <><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.fieldMapping")}</p><h2>{t("ops.confirmMapping")}</h2></div><StatusBadge tone="green">{t("ops.detected")}</StatusBadge></div>{[["Person.chineseName", "Person.chineseName"], ["Person.englishName", "Person.englishName"], ["Guardian.email", "ContactMethod.email"], ["School", "Enrollment.organization"], ["Grade", "Enrollment.gradeLevel"], ["Phone", "ContactMethod.phone"]].map(([source, target]) => <div className="mapping-row" key={source}><b>{source}</b><ArrowRight size={15} /><select defaultValue={target}><option>{target}</option><option>{t("ops.ignoreField")}</option></select><CheckCircle2 size={17} /></div>)}<StepActions back={() => setStep(1)} next={() => setStep(3)} nextLabel={t("ops.step.validate")} /></>}
  {step === 3 && <><div className="validation-cards"><span><CheckCircle2 size={22} /><b>2,418</b><small>{t("ops.validRows")}</small></span><span><AlertTriangle size={22} /><b>7</b><small>{t("ops.needsFix")}</small></span><span><ScanSearch size={22} /><b>23</b><small>{t("ops.duplicateCandidates")}</small></span></div><InlineMessage type="warning">{t("ops.duplicateWarning")}</InlineMessage><div className="duplicate-preview"><div><b>林俊佑 / Jay Lin</b><small>{t("ops.uploadRow")}</small></div><StatusBadge tone="amber">{t("ops.highConfidence")}</StatusBadge><select defaultValue="update"><option value="update">{t("action.update")}</option><option value="create">{t("action.create")}</option><option value="merge">{t("action.merge")}</option><option value="skip">{t("action.skip")}</option></select></div><StepActions back={() => setStep(2)} next={() => setStep(4)} nextLabel={t("ops.previewExecution")} /></>}
  {step === 4 && <><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.executionPreview")}</p><h2>{t("ops.readyImport")}</h2></div><StatusBadge tone="green">{t("ops.safeExecute")}</StatusBadge></div><div className="execution-summary"><span><b>2,402</b><small>{t("action.create")}</small></span><span><b>16</b><small>{t("action.update")}</small></span><span><b>8</b><small>{t("action.merge")}</small></span><span><b>15</b><small>{t("action.skipError")}</small></span></div><InlineMessage type="success">{t("ops.executionHelp")}</InlineMessage><div className="drawer-actions"><button className="secondary-button" type="button" onClick={() => setStep(3)}>{t("ops.previous")}</button><button className="primary-button" type="button">{t("ops.startImport")} <Import size={16} /></button></div></>}
  </section><section className="surface recent-imports"><div className="surface-heading"><h2>{t("ops.recentBatches")}</h2><button type="button">{t("ops.viewAll")}</button></div><ImportRow file="schools_q3.xlsx" rows="618 / 620" status="completed" date={t("ops.todayTime")} /><ImportRow file="guardian_updates.csv" rows="184 / 189" status="attention" date={t("ops.yesterdayTime")} /><ImportRow file="students_2026.xlsx" rows="1,402 / 1,402" status="rolledback" date={t("ops.july12")} /></section></div>; }
function StepActions({ back, next, nextLabel }: { back: () => void; next: () => void; nextLabel: string }) { const { t } = useI18n(); return <div className="drawer-actions"><button className="secondary-button" type="button" onClick={back}>{t("ops.previous")}</button><button className="primary-button" type="button" onClick={next}>{nextLabel} <ArrowRight size={16} /></button></div>; }
function ImportRow({ file, rows, status, date }: { file: string; rows: string; status: "completed" | "attention" | "rolledback"; date: string }) { const { t } = useI18n(); const statusKey = status === "completed" ? "common.completed" : status === "attention" ? "ops.status.needsAction" : "ops.status.rolledBack"; return <div className="import-row"><FileSpreadsheet size={19} /><div><b>{file}</b><small>{date}</small></div><span><small>{t("ops.successRows")}</small><b>{rows}</b></span><StatusBadge tone={status === "completed" ? "green" : status === "attention" ? "amber" : "gray"}>{t(statusKey)}</StatusBadge><button aria-label={t(status === "completed" ? "admin.view" : "ops.handle")} className="icon-button" type="button">{status === "completed" ? <ChevronRight size={16} /> : <RotateCcw size={16} />}</button></div>; }

export function DuplicatesPage() { const { locale, t } = useI18n(); const [choice, setChoice] = useState("review"); const school = locale === "zh-CN" ? "台北欧洲学校" : "Taipei European School"; return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.duplicateResolution")}</p><h1>{t("ops.duplicates.title")}</h1><p>{t("ops.duplicates.description")}</p></div><StatusBadge tone="amber">{t("ops.groupsPending")}</StatusBadge></section><section className="duplicate-workbench"><Candidate title={t("ops.existing")} school={school} phone="+886 912 556 018" updated /><div className="duplicate-score"><span><ScanSearch size={24} /></span><b>92%</b><small>{t("ops.duplicateConfidence")}</small><i>{t("ops.emailMatch")}</i><i>{t("ops.bilingualNameMatch")}</i><i>{t("ops.schoolMatch")}</i></div><Candidate title={t("ops.incoming")} school={school} phone="+886 912 556 081" /></section><section className="surface merge-decision"><div><h2>{t("ops.chooseAction")}</h2><p>{t("ops.mergeHelp")}</p></div><div className="decision-buttons"><button className={choice === "create" ? "active" : ""} type="button" onClick={() => setChoice("create")}>{t("ops.keepBoth")}</button><button className={choice === "update" ? "active" : ""} type="button" onClick={() => setChoice("update")}>{t("ops.updatePrimary")}</button><button className={choice === "merge" ? "active" : ""} type="button" onClick={() => setChoice("merge")}>{t("ops.fieldMerge")}</button></div>{choice === "merge" && <InlineMessage type="warning">{t("ops.mergeWarning")}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button">{t("ops.later")}</button><button className="primary-button" type="button" disabled={choice === "review"}>{t("ops.confirmAction")}</button></div></section></div>; }
function Candidate({ title, school, phone, updated }: { title: string; school: string; phone: string; updated?: boolean }) { const { t } = useI18n(); return <article className={`surface candidate-card${updated ? "" : " incoming"}`}><p className="eyebrow">{title}</p><span className="large-record-avatar">林</span><h2>林俊佑 / Jay Lin</h2><dl><dt>{t("common.email")}</dt><dd>jay.lin@student.tes.edu</dd><dt>{t("ops.phone")}</dt><dd className={updated ? "" : "changed"}>{phone}</dd><dt>{t("ops.school")}</dt><dd>{school}</dd><dt>{t("ops.grade")}</dt><dd className={updated ? "" : "changed"}>{updated ? "IB Year 1" : "IB Year 2"}</dd><dt>{t(updated ? "ops.lastUpdated" : "ops.source")}</dt><dd>{updated ? t("ops.today0912") : "#IMP-1048"}</dd></dl></article>; }

export function DataQualityPage() { const { t } = useI18n(); const issues = [{ key: "school", rule: "ORGANIZATION_MISSING_DECISION_MAKER", owner: "Jason Wu", tone: "red" }, { key: "student", rule: "STUDENT_PROGRESSION_RULE_MISSING", owner: "Sophia Lin", tone: "red" }, { key: "staff", rule: "STAFF_ASSIGNMENT_STALE_VERIFICATION", owner: "Olivia Chen", tone: "amber" }, { key: "opportunity", rule: "OPPORTUNITY_STALE", owner: "Jason Wu", tone: "amber" }]; return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.trustedData")}</p><h1>{t("ops.quality.title")}</h1><p>{t("ops.quality.description")}</p></div><button className="primary-button" type="button"><Play size={16} />{t("ops.runRules")}</button></section><section className="quality-score"><div className="health-donut small"><div><b>86</b><small>{t("ops.qualityScore")}</small></div></div><span><b>4</b><small>{t("ops.highPriority")}</small></span><span><b>11</b><small>{t("ops.needsAttention")}</small></span><span><b>27</b><small>{t("ops.resolvedWeek")}</small></span><ProgressBar value={86} label={t("ops.completeness")} /></section><section className="surface issue-list"><div className="surface-heading"><h2>{t("ops.openIssues")}</h2><StatusBadge tone="amber">{t("admin.items", { count: 15 })}</StatusBadge></div>{issues.map((issue) => <div className="issue-row" key={issue.key}><span className={issue.tone}><AlertTriangle size={18} /></span><div><b>{t(`ops.issue.${issue.key}`)}</b><small>{issue.rule}</small></div><span><small>{t("common.owner")}</small><b>{issue.owner}</b></span><StatusBadge tone={issue.tone}>{t(issue.tone === "red" ? "ops.highPriority" : "ops.needsAttention")}</StatusBadge><button className="secondary-button" type="button">{t("ops.handle")}</button></div>)}</section></div>; }

export function ReportsPage() { const { t } = useI18n(); return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.reportsInsights")}</p><h1>{t("ops.reports.title")}</h1><p>{t("ops.reports.description")}</p></div><button className="primary-button" type="button"><Plus size={16} />{t("ops.generateReport")}</button></section><section className="report-cards"><ReportCard icon={School} tone="blue" title={t("ops.report.school")} meta="28 · Today" /><ReportCard icon={GraduationCap} tone="purple" title={t("ops.report.student")} meta="148 · Today" /><ReportCard icon={Users} tone="green" title={t("ops.report.household")} meta="96 · Yesterday" /><ReportCard icon={FileBarChart} tone="amber" title={t("ops.report.pipeline")} meta="¥ 3.84M · 12 min" /></section><section className="surface report-history"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.recentReports")}</p><h2>{t("ops.recentGenerated")}</h2></div><button className="secondary-button" type="button">{t("ops.manageTemplates")}</button></div><ReportRow title={t("ops.report.q3")} type="PDF · 4.8 MB" owner="Olivia Chen" status={t("ops.download6d")} /><ReportRow title={t("ops.report.ib")} type="XLSX · 1.2 MB" owner="Sophia Lin" status={t("ops.download3d")} /><ReportRow title={t("ops.report.sales")} type="PDF · 2.1 MB" owner="Jason Wu" status={t("ops.generating")} pending /></section></div>; }
function ReportCard({ icon: Icon, tone, title, meta }: { icon: React.ElementType; tone: string; title: string; meta: string }) { return <button className="report-card" type="button"><span className={tone}><Icon size={22} /></span><div><b>{title}</b><small>{meta}</small></div><ChevronRight size={17} /></button>; }
function ReportRow({ title, type, owner, status, pending }: { title: string; type: string; owner: string; status: string; pending?: boolean }) { const { t } = useI18n(); return <div className="report-row"><FileBarChart size={19} /><div><b>{title}</b><small>{type}</small></div><span><small>{t("ops.createdBy")}</small><b>{owner}</b></span><StatusBadge tone={pending ? "blue" : "green"}>{status}</StatusBadge><button aria-label={t("ops.downloadTemplate")} className="icon-button" type="button"><Download size={17} /></button></div>; }

export function AiWorkbenchPage() { const { t } = useI18n(); const [toast, setToast] = useState(""); return <div className="page-stack"><section className="ai-hero"><div><span><Sparkles size={20} /></span><p className="eyebrow">{t("eyebrow.humanIntelligence")}</p><h1>{t("ops.ai.title")}</h1><p>{t("ops.ai.description")}</p></div><StatusBadge tone="purple">{t("ops.serviceNormal")}</StatusBadge></section><section className="ai-tool-grid"><AiTool icon={WandSparkles} title={t("ops.ai.extract")} description={t("ops.ai.extractHelp")} action={t("ops.ai.start")} /><AiTool icon={Bot} title={t("ops.ai.summary")} description={t("ops.ai.summaryHelp")} action={t("ops.ai.select")} /><AiTool icon={Sparkles} title={t("ops.ai.next")} description={t("ops.ai.nextHelp")} action={t("ops.ai.view")} /></section><section className="surface ai-review"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.reviewQueue")}</p><h2>{t("ops.reviewQueue")}</h2></div><StatusBadge tone="amber">{t("admin.items", { count: 4 })}</StatusBadge></div><div className="ai-review-row"><span className="purple"><WandSparkles size={18} /></span><div><b>{t("ops.ai.extractReview")}</b><small>{t("ops.ai.extractMeta")}</small></div><ProgressBar value={91} label={t("ops.averageConfidence")} /><button className="secondary-button" type="button" onClick={() => setToast(t("ops.ai.opened"))}>{t("admin.review")}</button></div><div className="ai-review-row"><span className="blue"><Bot size={18} /></span><div><b>{t("ops.ai.household")}</b><small>{t("ops.ai.householdMeta")}</small></div><StatusBadge tone="blue">{t("ops.narrativeDraft")}</StatusBadge><button className="secondary-button" type="button">{t("admin.review")}</button></div></section>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>; }
function AiTool({ icon: Icon, title, description, action }: { icon: React.ElementType; title: string; description: string; action: string }) { return <article><span><Icon size={22} /></span><h2>{title}</h2><p>{description}</p><button type="button">{action} <ArrowRight size={15} /></button></article>; }

const messageCards = [{ icon: MessageSquareText, key: "guardian" }, { icon: AlertTriangle, key: "quality" }, { icon: CheckCircle2, key: "workflow" }, { icon: Clock3, key: "expiry" }];
export function MessagesPage() { const { t } = useI18n(); return <SimpleHub eyebrow={t("eyebrow.teamInbox")} title={t("ops.messages.title")} description={t("ops.messages.description")} cards={messageCards.map(({ icon, key }) => ({ icon, title: t(`ops.messages.${key}`), meta: t(`ops.messages.${key}Meta`) }))} />; }
function SimpleHub({ eyebrow, title, description, cards }: { eyebrow: string; title: string; description: string; cards: { icon: React.ElementType; title: string; meta: string }[] }) { return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></section><section className="simple-hub-grid">{cards.map(({ icon: Icon, title, meta }) => <button type="button" key={title}><span><Icon size={21} /></span><div><b>{title}</b><small>{meta}</small></div><ChevronRight size={16} /></button>)}</section></div>; }
export function HelpPage() { const { t } = useI18n(); const cards = [{ icon: Users, key: "people" }, { icon: Import, key: "import" }, { icon: ShieldCheck, key: "security" }, { icon: Bot, key: "ai" }]; return <div className="page-stack help-page"><SimpleHub eyebrow={t("eyebrow.helpSupport")} title={t("ops.help.title")} description={t("ops.help.description")} cards={cards.map(({ icon, key }) => ({ icon, title: t(`ops.help.${key}`), meta: t(`ops.help.${key}Meta`) }))} /><section className="surface help-contact"><Sparkles size={22} /><div><h2>{t("ops.help.still")}</h2><p>{t("ops.help.hours")}</p></div><a className="primary-button" href="mailto:support@lumina-edu.com">{t("ops.help.contact")}</a></section></div>; }
