"use client";
import type {ReactNode} from "react";
import { Building2, Layers, Users, Network, GraduationCap } from "lucide-react";
import {RecordIdentity} from "./record-header";
import {ResponsiveDetailLayout,SectionHeader} from "./responsive-detail-layout";
import {ChannelPerformanceSection} from "./channel-analytics-page";
import {ChannelAgreementsPanel} from "./channel-agreements-panel";
import {ContactWechatEditor} from "./contact-wechat-editor";

import {ChannelActivationPanel} from "./channel-activation-panel";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {commercialFields,commercialProfileSchema,commercialTiers,destinationRegions,intelligenceDataSchema,keyContactStatuses,outcomeDataSchema,relationshipDataSchema,relationshipTypes} from "@/lib/channel-commercial-input";
import {businessConfig} from "@/lib/education-business";
import type {OrganizationCommercialSnapshot} from "@/lib/education-business-repository";
import {useCapability} from "./app-user-context";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {AccessibleDrawer,InlineMessage} from "./ui";
import {DateInput} from "./structured-inputs";
import {MarkdownContent} from "./markdown-content";
import {formatFinanceAmount} from "@/lib/enrollment-finance";

type Editor={kind:"profile"|"intelligence"|"relationship"|"outcome";record:Record<string,unknown>};
export function OrganizationCommercialPanel({organizationId,contactId,embedded=false,contextRail}:{organizationId:string;contactId?:string;embedded?:boolean;contextRail?:ReactNode}){
 const {t,locale}=useI18n(),canWrite=useCapability("education.manage"),{formatDate}=useUserPreferences();
 const formatCurrency=(value:number,currency:string)=>`${currency} ${formatFinanceAmount(String(value),locale)}`;
 const [section,setSection]=useState("overview");
 const [snapshot,setSnapshot]=useState<OrganizationCommercialSnapshot|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[editor,setEditor]=useState<Editor|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const result=await apiFetch<OrganizationCommercialSnapshot>(`/api/organizations/${organizationId}/commercial`,{signal});if(!signal?.aborted){setSnapshot(result);setError("");}return true;}catch{if(!signal?.aborted)setError(t("channel.loadFailed"));return false;}},[organizationId,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const label=(r:Record<string,unknown>)=>String((locale==="en"?r.name_en:r.name_zh)||r.name_zh||r.name_en||"—"),unknown=t("channel.unknown");
 if(!snapshot)return <div className="page-stack">{error?<InlineMessage type="error">{error}<button className="secondary-button" onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>:<p role="status">{t("common.loading")}</p>}</div>;
 const {profile,organization,contacts,intelligence,relationships,outcomes,opportunities}=snapshot;
 const edit=(kind:Editor["kind"],record:Record<string,unknown>={})=>{setNotice("");setEditor({kind,record});};
 const score=(v:unknown)=>v==null?unknown:`${v} / 100`;
 const contactRows=contacts.filter(c=>!contactId||c.id===contactId);
 const saved=async()=>{setEditor(null);const refreshed=await load();setNotice(t(refreshed?"channel.saved":"channel.savedRefreshFailed"));};
 if(embedded&&!contactId)return <div className="workspace-channel channel-commercial-panel">
   {error&&<InlineMessage type="error">{error}</InlineMessage>}{notice&&<InlineMessage type="info">{notice}</InlineMessage>}
   <ResponsiveDetailLayout context={contextRail}><div className="workspace-main-stack">
     <ChannelActivationPanel compact organizationId={organizationId} onSaved={load}/>
     <div className="workspace-summary-grid">
       <section className="detail-section"><SectionHeader icon={<Layers size={18}/>} title={t("workspace.currentProducts")}/><div className="detail-record-list">{opportunities.slice(0,4).map(o=><article key={String(o.id)}><div><Link href={`/opportunities?focus=${o.id}`}><RecordIdentity nameZh={String(o.title_zh??"")} nameEn={String(o.title_en??"")}/></Link><small>{String((locale==="en"?o.product_name_en:o.product_name_zh)||t("ux.record.notRecorded"))} · {String((locale==="en"?o.cohort_name_en:o.cohort_name_zh)||t("ux.record.notRecorded"))}</small>{Boolean(o.currency)&&o.amount!=null&&<small>{formatCurrency(Number(o.amount),String(o.currency))}</small>}{Boolean(o.stage)&&<small>{t(`sales.stage.${String(o.stage).toLowerCase()}`)}</small>}</div></article>)}</div>{!opportunities.length&&<div className="workspace-empty"><Layers size={24}/><b>{t("workspace.noRelated")}</b><p>{t("workspace.relatedHelp")}</p></div>}</section>
       <section className="detail-section" data-surface-tone="context"><SectionHeader icon={<Building2 size={18}/>} title={t("channel.schoolProfile")} action={canWrite&&snapshot.canManage&&<button className="text-button" onClick={()=>edit("profile",profile??{})}>{t("crm.edit")}</button>}/><dl className="workspace-info-grid">{["curriculum","city","student_count"].map(k=><div key={k}><dt>{t(`channel.field.${k}`)}</dt><dd>{organization[k]==null||organization[k]===""?t("ux.record.notRecorded"):String(organization[k])}</dd></div>)}<div><dt>{t("channel.field.school_type")}</dt><dd>{profile?.school_type?t(`channel.option.${profile.school_type}`):t("ux.record.notRecorded")}</dd></div><div><dt>{t("channel.field.commercial_tier")}</dt><dd>{profile?.commercial_tier?t(`channel.tier.${profile.commercial_tier}`):t("ux.record.notRecorded")}</dd></div><div><dt>{t("channel.field.partnership_potential_score")}</dt><dd>{score(profile?.partnership_potential_score)}</dd></div></dl></section>
       <section className="detail-section"><SectionHeader icon={<Users size={18}/>} title={t("channel.intelligence")}/><div className="detail-record-list">{contacts.slice(0,4).map(c=>{const i=intelligence.find(i=>i.contact_id===c.id);return <article key={c.id}><div><Link href={`/people/${c.id}`}><RecordIdentity nameZh={c.name_zh} nameEn={c.name_en}/></Link><small>{c.title||t("ux.record.notRecorded")} · {t(`contact.decisionRole.${c.decision_role.toLowerCase()}`)}</small><small>{t(`channel.option.${i?.key_contact_status??"UNKNOWN"}`)}</small></div>{canWrite&&snapshot.canManage&&c.can_edit&&(!i||i.can_edit)&&<button className="text-button" onClick={()=>edit("intelligence",i??{contact_id:c.id})}>{t("crm.edit")}</button>}</article>;})}</div>{!contacts.length&&<div className="workspace-empty"><Users size={24}/><b>{t("workspace.noContacts")}</b><p>{t("workspace.contactsHelp")}</p></div>}</section>
       <section className="detail-section"><SectionHeader icon={<Network size={18}/>} title={t("channel.decisionMap")} action={canWrite&&snapshot.canManage&&<button className="text-button" onClick={()=>edit("relationship")}>{t("channel.addRelationship")}</button>}/><div className="detail-record-list">{relationships.slice(0,4).map(r=><article key={r.id}><div><b>{(locale==="en"?r.source_name_en:r.source_name_zh)||r.source_name_zh||r.source_name_en}</b><small>{t(`channel.option.${r.relationship_type}`)} → {(locale==="en"?r.target_name_en:r.target_name_zh)||r.target_name_zh||r.target_name_en}</small></div>{canWrite&&r.can_edit&&<button className="text-button" onClick={()=>edit("relationship",r)}>{t("crm.edit")}</button>}</article>)}</div>{!relationships.length&&<div className="workspace-empty"><Network size={24}/><b>{t("channel.emptyMap")}</b></div>}</section>
     </div>
     <section className="detail-section"><SectionHeader icon={<GraduationCap size={18}/>} title={t("channel.outcomes")} action={canWrite&&snapshot.canManage&&<button className="text-button" onClick={()=>edit("outcome")}>{t("channel.addOutcome")}</button>}/>{outcomes.map(o=><article className="workspace-outcome" key={o.id}><b>{o.academic_year} · {t(`channel.option.${o.destination_region}`)}</b><span>{t("channel.field.offer_count")}: {o.offer_count??t("ux.record.notRecorded")} · {t("channel.field.matriculation_count")}: {o.matriculation_count??t("ux.record.notRecorded")}</span>{canWrite&&o.can_edit&&<button className="text-button" onClick={()=>edit("outcome",o)}>{t("crm.edit")}</button>}</article>)}{!outcomes.length&&<p className="field-help">{t("ux.record.notRecorded")}</p>}</section>
     <details className="workspace-secondary-disclosure"><summary>{t("workspace.commercialDetails")}</summary><div className="workspace-info-grid"><div><h3>{t("channel.field.bd_plan_markdown")}</h3><MarkdownContent value={String(profile?.bd_plan_markdown??"")} empty={unknown}/></div><div><h3>{t("channel.field.competitor_analysis_markdown")}</h3><MarkdownContent value={String(profile?.competitor_analysis_markdown??"")} empty={unknown}/></div></div><Link href={`/education-business?subject=ORGANIZATION&subjectId=${organizationId}`}>{t("ux.record.moreOperations")}</Link></details>
     <details className="workspace-secondary-disclosure"><summary>{t("experience.agreements")}</summary><ChannelAgreementsPanel organizationId={organizationId}/></details><details className="workspace-secondary-disclosure"><summary>{t("experience.performance")}</summary><ChannelPerformanceSection organizationId={organizationId}/></details>
   </div></ResponsiveDetailLayout>
   {snapshot.limited&&<InlineMessage type="warning">{t("channel.limited")}</InlineMessage>}{editor&&<CommercialEditor key={`${editor.kind}:${editor.record.id??editor.record.contact_id??"new"}`} editor={editor} snapshot={snapshot} onClose={()=>setEditor(null)} onSaved={saved}/>}
 </div>;
 return <div className="page-stack channel-commercial-panel">{!contactId&&!embedded&&<nav className="commercial-section-picker" aria-label={t("channel.commercial")}>{["overview","agreements","contacts","performance"].map(key=><button type="button" key={key} aria-pressed={section===key} className={section===key?"primary-button":"secondary-button"} onClick={()=>setSection(key)}>{t("experience."+key)}</button>)}</nav>}
 {!contactId&&embedded&&<details><summary>{t("experience.agreements")}</summary><ChannelAgreementsPanel organizationId={organizationId}/></details>}{!contactId&&!embedded&&section==="agreements"&&<ChannelAgreementsPanel organizationId={organizationId}/>}
 {!contactId&&embedded&&<details><summary>{t("experience.performance")}</summary><ChannelPerformanceSection organizationId={organizationId}/></details>}{!contactId&&!embedded&&section==="performance"&&<ChannelPerformanceSection organizationId={organizationId}/>}
 {!contactId&&section==="overview"&&<ChannelActivationPanel organizationId={organizationId} onSaved={load}/>}
 {error&&<InlineMessage type="error">{error}</InlineMessage>}{notice&&<InlineMessage type="info">{notice}</InlineMessage>}
 {!contactId&&section==="overview"&&<><section className="detail-section"><div className="surface-heading"><h3>{t("channel.commercial")}</h3>{canWrite&&snapshot.canManage&&<button className="secondary-button" onClick={()=>edit("profile",profile??{})}>{t("crm.edit")}</button>}</div><dl className="customer-profile">
 <div><dt>{t("channel.field.commercial_tier")}</dt><dd>{profile?.commercial_tier?`${profile.commercial_tier} · ${t(`channel.tier.${profile.commercial_tier}`)}`:unknown}</dd></div>
 <div><dt>{t("channel.field.partnership_potential_score")}</dt><dd>{score(profile?.partnership_potential_score)}</dd></div>
 <div><dt>{t("common.status")}</dt><dd>{t(`crm.status.${organization.status}`)}</dd></div>
 <div><dt>{t("business.field.next_action")}</dt><dd>{String(profile?.next_action||"—")}</dd></div>
 </dl><h4>{t("channel.field.bd_plan_markdown")}</h4><MarkdownContent value={String(profile?.bd_plan_markdown??"")} empty={unknown}/><h4>{t("channel.field.competitor_analysis_markdown")}</h4><MarkdownContent value={String(profile?.competitor_analysis_markdown??"")} empty={unknown}/></section>
 <section className="detail-section"><h3>{t("channel.schoolProfile")}</h3><dl className="customer-profile">{["curriculum","student_count","website","city","address"].map(k=><div key={k}><dt>{t(`channel.field.${k}`)}</dt><dd>{organization[k]==null||organization[k]===""?unknown:String(organization[k])}</dd></div>)}<div><dt>{t("channel.field.school_type")}</dt><dd>{profile?.school_type?t(`channel.option.${profile.school_type}`):unknown}</dd></div><div><dt>{t("channel.gradeSpan")}</dt><dd>{profile?.grade_min!=null||profile?.grade_max!=null?`${profile?.grade_min==null?"—":`G${profile.grade_min}`}–${profile?.grade_max==null?"—":`G${profile.grade_max}`}`:unknown}</dd></div><div><dt>{t("channel.tuition")}</dt><dd>{profile?.tuition_currency&&(profile.tuition_min!=null||profile.tuition_max!=null)?`${profile.tuition_min==null?"—":formatCurrency(Number(profile.tuition_min),String(profile.tuition_currency))} – ${profile.tuition_max==null?"—":formatCurrency(Number(profile.tuition_max),String(profile.tuition_currency))}`:unknown}</dd></div></dl><Link className="text-button" href={`/schools/${organizationId}`}>{t("channel.editMasterHelp")}</Link></section>
 <section className="detail-section"><h3>{t("channel.opportunities")}</h3><div className="detail-record-list">{opportunities.map(o=><article key={String(o.id)}><Link href={`/opportunities?focus=${o.id}`}>{String((locale==="en"?o.title_en:o.title_zh)||o.title_zh||o.title_en)}</Link><div>{String((locale==="en"?o.product_name_en:o.product_name_zh)||"—")} · {String((locale==="en"?o.cohort_name_en:o.cohort_name_zh)||"—")}</div></article>)}</div>{!opportunities.length&&<p className="detail-empty">{t("common.noData")}</p>}</section></>}
 {(contactId||(section==="contacts"||embedded))&&<section className="detail-section"><h3>{t("channel.intelligence")}</h3><p>{t("channel.internalHelp")}</p><div className="business-record-grid">{contactRows.map(c=>{const i=intelligence.find(i=>i.contact_id===c.id);return <article className="detail-section" key={c.id}><div className="surface-heading"><Link href={`/people/${c.id}`}>{label(c)}</Link>{canWrite&&snapshot.canManage&&c.can_edit&&(!i||i.can_edit)&&<button className="secondary-button" onClick={()=>edit("intelligence",i??{contact_id:c.id})}>{t("crm.edit")}</button>}</div><p>{c.title||"—"}</p><dl className="customer-profile"><div><dt>{t("channel.decisionRole")}</dt><dd>{t(`contact.decisionRole.${c.decision_role.toLowerCase()}`)}</dd></div><div><dt>{t("channel.field.decision_power_score")}</dt><dd>{score(i?.decision_power_score)}</dd></div><div><dt>{t("channel.field.contribution_score")}</dt><dd>{score(i?.contribution_score)}</dd></div><div><dt>{t("channel.field.key_contact_status")}</dt><dd>{t(`channel.option.${i?.key_contact_status??"UNKNOWN"}`)}</dd></div><div><dt>{t("customerOps.field.next_follow_up_at")}</dt><dd>{c.next_follow_up_at?formatDate(c.next_follow_up_at,{includeTime:true}):"—"}</dd></div><div><dt>{t("channel.wechat")}</dt><dd>{c.wechat_id||"—"}</dd></div></dl>{canWrite&&<ContactWechatEditor key={c.updated_at} contact={c} onSaved={async()=>{await load();}}/>}{["working_style_markdown","cooperation_notes","potential_notes"].map(k=><div key={k}><h4>{t(`channel.field.${k}`)}</h4><MarkdownContent value={String(i?.[k as keyof typeof i]??"")} empty={unknown}/></div>)}</article>;})}</div>{!contactRows.length&&<p className="detail-empty">{t("common.noData")}</p>}</section>}
 {!contactId&&(section==="contacts"||embedded)&&<><section className="detail-section"><div className="surface-heading"><h3>{t("channel.decisionMap")}</h3>{canWrite&&snapshot.canManage&&<button className="secondary-button" onClick={()=>edit("relationship")}>{t("channel.addRelationship")}</button>}</div><div className="detail-record-list">{relationships.map(r=><article key={r.id}><div><span>{locale==="en"?r.source_name_en||r.source_name_zh:r.source_name_zh||r.source_name_en}</span><strong> {t(`channel.option.${r.relationship_type}`)} → </strong><span>{locale==="en"?r.target_name_en||r.target_name_zh:r.target_name_zh||r.target_name_en}</span><small>{t(`channel.option.${r.status}`)}</small><p>{r.note}</p></div>{canWrite&&r.can_edit&&<button className="secondary-button" onClick={()=>edit("relationship",r)}>{t("crm.edit")}</button>}</article>)}</div>{!relationships.length&&<p className="detail-empty">{t("channel.emptyMap")}</p>}</section>
 <section className="detail-section"><div className="surface-heading"><h3>{t("channel.outcomes")}</h3>{canWrite&&snapshot.canManage&&<button className="secondary-button" onClick={()=>edit("outcome")}>{t("channel.addOutcome")}</button>}</div><div className="business-record-grid">{outcomes.map(o=><article key={o.id} className="detail-section"><div className="surface-heading"><h4>{o.academic_year} · {t(`channel.option.${o.destination_region}`)}</h4>{canWrite&&o.can_edit&&<button className="secondary-button" onClick={()=>edit("outcome",o)}>{t("crm.edit")}</button>}</div><p>{t("channel.field.offer_count")}: {o.offer_count??unknown} · {t("channel.field.matriculation_count")}: {o.matriculation_count??unknown}</p><p>{o.notable_destinations.join(" / ")}</p><p>{o.source_note}</p>{o.as_of_date&&<small>{formatDate(o.as_of_date,{dateOnly:true})}</small>}</article>)}</div>{!outcomes.length&&<p className="detail-empty">{t("common.noData")}</p>}</section></>}
 {snapshot.limited&&<InlineMessage type="warning">{t("channel.limited")}</InlineMessage>}
 {editor&&<CommercialEditor key={`${editor.kind}:${editor.record.id??editor.record.contact_id??"new"}`} editor={editor} snapshot={snapshot} onClose={()=>setEditor(null)} onSaved={saved}/>}
 </div>;
}

function CommercialEditor({editor,snapshot,onClose,onSaved}:{editor:Editor;snapshot:OrganizationCommercialSnapshot;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n();const id=useRef(String(editor.record.id??crypto.randomUUID())),requestKey=useRef(crypto.randomUUID()),attempt=useRef<{url:string;body:unknown}|null>(null),busy=useRef(false);
 const {kind,record}=editor,organizationId=String(snapshot.organization.id);
 const fields=kind==="profile"?[...commercialFields,"next_action"]:kind==="intelligence"?["key_contact_status","decision_power_score","contribution_score","working_style_markdown","cooperation_notes","potential_notes"]:kind==="relationship"?["source_contact_id","target_contact_id","relationship_type","status","note"]:["academic_year","destination_region","offer_count","matriculation_count","notable_destinations","as_of_date","source_note"];
 const defaults:Record<string,unknown>={commercial_tier:null,partnership_potential_score:null,competitor_analysis_markdown:"",bd_plan_markdown:"",school_type:null,grade_min:null,grade_max:null,tuition_min:null,tuition_max:null,tuition_currency:null,next_action:"",contact_id:record.contact_id,key_contact_status:"UNKNOWN",decision_power_score:null,contribution_score:null,working_style_markdown:"",cooperation_notes:"",potential_notes:"",source_contact_id:"",target_contact_id:"",relationship_type:"REPORTS_TO",status:"ACTIVE",note:"",academic_year:"",destination_region:"UNITED_STATES",offer_count:null,matriculation_count:null,notable_destinations:[],as_of_date:null,source_note:""};
 const [draft,setDraft]=useState<Record<string,unknown>>(()=>({...defaults,...Object.fromEntries(fields.filter(k=>k in record).map(k=>[k,record[k]]))})),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState("");
 const choices:Record<string,readonly string[]>={commercial_tier:commercialTiers,school_type:["PUBLIC","PRIVATE","INTERNATIONAL","OTHER"],tuition_currency:["CNY","USD","GBP","AUD","CAD","EUR","NZD","HKD","SGD","TWD"],key_contact_status:keyContactStatuses,relationship_type:relationshipTypes,status:["ACTIVE","INACTIVE"],destination_region:destinationRegions};
 const numbers=new Set(["partnership_potential_score","decision_power_score","contribution_score","grade_min","grade_max","tuition_min","tuition_max","offer_count","matriculation_count"]);
 const save=async(event?:React.FormEvent)=>{event?.preventDefault();if(busy.current)return;setError("");
 if(!attempt.current){const data=Object.fromEntries(fields.filter(k=>k!=="next_action").map(k=>[k,numbers.has(k)?draft[k]===null||draft[k]===""?null:Number(draft[k]):draft[k]]));
 if(kind==="profile"){const parsed=commercialProfileSchema.safeParse(data);if(!parsed.success){setError(t("channel.invalid"));return;}const previous=snapshot.profile;const existing=Object.fromEntries(businessConfig.organizations.fields.map(f=>[f.key,previous?.[f.key]??(f.kind==="multi"?[]:f.key==="organization_type"?snapshot.organization.organization_type??"SCHOOL":f.key==="partnership_stage"?"PROSPECT":f.kind==="relation"||f.kind==="date"||f.kind==="number"?null:"")]));attempt.current={url:"/api/education-business",body:{resource:"organizations",id:organizationId,expectedRevision:previous?.revision??null,data:{...existing,...parsed.data,next_action:draft.next_action,id:organizationId}}};}
 else{const full={...data,organization_id:organizationId,...(kind==="intelligence"?{contact_id:record.contact_id}:{})};const parsed=(kind==="intelligence"?intelligenceDataSchema:kind==="relationship"?relationshipDataSchema:outcomeDataSchema).safeParse(full);if(!parsed.success){setError(t("channel.invalid"));return;}attempt.current={url:kind==="intelligence"?`/api/contacts/${record.contact_id}/intelligence`:`/api/organizations/${organizationId}/${kind==="relationship"?"decision-map":"admission-outcomes"}`,body:{id:id.current,expectedRevision:record.revision??null,requestKey:requestKey.current,data:parsed.data}};}}
 busy.current=true;setPending(true);try{await apiFetch(attempt.current.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current.body)});attempt.current=null;await onSaved();}catch(caught){if(caught instanceof ApiClientError&&caught.status<500){attempt.current=null;setUncertain(false);setError(t(caught.code.includes("VERSION_CONFLICT")?"channel.conflict":caught.code.includes("FORBIDDEN")?"channel.forbidden":caught.code.includes("CYCLE")?"channel.cycle":caught.code.includes("CONFLICT")?"channel.duplicate":"channel.invalid"));requestKey.current=crypto.randomUUID();}else{setUncertain(true);setError(t("channel.uncertain"));}}finally{busy.current=false;setPending(false);}};
 return <AccessibleDrawer title={t(`channel.${kind}`)} onClose={onClose} pending={pending||uncertain}><form className="page-stack" onSubmit={event=>void save(event)}><fieldset className="follow-up-fields" disabled={pending||uncertain}><div className="form-grid two-column">{fields.map(k=>{const immutable=kind==="relationship"&&!!record.id&&["source_contact_id","target_contact_id","relationship_type"].includes(k);return <label key={k} className="field"><span>{t(k==="next_action"?"business.field.next_action":`channel.field.${k}`)}</span>{k.endsWith("contact_id")?<select disabled={immutable} required value={String(draft[k]??"")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))}><option value="">{t("business.select")}</option>{snapshot.contacts.map(c=><option key={c.id} value={c.id}>{(locale==="en"?c.name_en:c.name_zh)||c.name_zh||c.name_en}</option>)}</select>:choices[k]?<select disabled={immutable} value={String(draft[k]??"")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value||null}))}>{["commercial_tier","school_type","tuition_currency"].includes(k)&&<option value="">{t("channel.unknown")}</option>}{choices[k].map(v=><option key={v} value={v}>{commercialTiers.includes(v as typeof commercialTiers[number])?`${v} · ${t(`channel.tier.${v}`)}`:k==="tuition_currency"?v:t(`channel.option.${v}`)}</option>)}</select>:numbers.has(k)?<input type="number" min={k.includes("score")?10:0} max={k.includes("score")?100:k.startsWith("grade_")?12:k.endsWith("count")?1e6:1e9} step={k.startsWith("tuition_")?.01:1} value={String(draft[k]??"")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value===""?null:Number(e.target.value)}))}/>:k==="as_of_date"?<DateInput value={String(draft[k]??"")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value||null}))}/>:k==="notable_destinations"?<textarea value={(draft[k] as string[]).join("\n")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value.split("\n").filter(v=>v.trim())}))}/>:<textarea rows={k.includes("markdown")||k.endsWith("notes")?4:2} maxLength={k.includes("markdown")?20000:10000} value={String(draft[k]??"")} onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))}/>}</label>;})}</div></fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" disabled={pending||uncertain} onClick={onClose}>{t("common.cancel")}</button><button className="primary-button" type={uncertain?"button":"submit"} disabled={pending} onClick={uncertain?()=>void save():undefined}>{t(pending?"common.saving":uncertain?"business.retrySame":"common.save")}</button></div></form></AccessibleDrawer>;
}
