"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CircleDollarSign, Plus, RefreshCcw, Sparkles, UserRound, X } from "lucide-react";
import { EmptyState } from "@/components/data-state";
import { useI18n } from "@/components/i18n-provider";
import { InlineMessage, Pagination, SearchableSelect, SearchField, StatusBadge, Toast } from "@/components/ui";
import type { FunnelMetric, OpportunityRecord } from "@/lib/sales-repository";

const stageOrder=["DISCOVERY","EVALUATION","HESITATION","PAYMENT","WON","LOST"] as const;
const stageTone:Record<string,string>={DISCOVERY:"blue",EVALUATION:"purple",HESITATION:"amber",PAYMENT:"green",WON:"green",LOST:"gray"};
const stageProbability:Record<string,number>={DISCOVERY:20,EVALUATION:40,HESITATION:60,PAYMENT:85};
type ProductOption={id:string;nameZh:string;nameEn:string;active:boolean};

export function PipelinePage({initialItems,initialTotal,initialFunnel,persistent=true}:{initialItems:OpportunityRecord[];initialTotal:number;initialFunnel:FunnelMetric[];persistent?:boolean}){
  const {locale,t}=useI18n();const [items,setItems]=useState(initialItems);const [total,setTotal]=useState(initialTotal);const [page,setPage]=useState(1);const [query,setQuery]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [toast,setToast]=useState("");const [open,setOpen]=useState(false);const [organization,setOrganization]=useState("");const [organizationOptions,setOrganizationOptions]=useState<Array<{value:string;label:string;detail:string}>>([]);const [relatedLoading,setRelatedLoading]=useState(false);const [product,setProduct]=useState("");const [productOptions,setProductOptions]=useState<Array<{value:string;label:string}>>([]);const closeRef=useRef<HTMLButtonElement>(null);const pageSize=24;
  const funnelMap=new Map(initialFunnel.map(item=>[item.stage,item]));const currency=initialFunnel.find(item=>item.amount>0)?items[0]?.currency??"CNY":"CNY";const money=(value:number,currencyCode=currency)=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en-US",{style:"currency",currency:currencyCode,maximumFractionDigits:0,notation:Math.abs(value)>=1_000_000?"compact":"standard"}).format(value);
  const pages=Math.max(1,Math.ceil(total/pageSize));const groups=useMemo(()=>stageOrder.map(stage=>({stage,items:items.filter(item=>item.stage===stage)})),[items]);
  const load=useCallback(async(nextPage:number,nextQuery:string)=>{if(!persistent)return;setLoading(true);setError("");try{const response=await fetch(`/api/opportunities?page=${nextPage}&pageSize=${pageSize}&query=${encodeURIComponent(nextQuery)}`);const result=await response.json() as {items?:OpportunityRecord[];total?:number};if(!response.ok||!result.items)throw new Error();setItems(result.items);setTotal(result.total??result.items.length);}catch{setError(t("pipeline.loadFailed"));}finally{setLoading(false);}},[persistent,t]);
  useEffect(()=>{if(page===1&&!query)return;const timer=setTimeout(()=>void load(page,query),250);return()=>clearTimeout(timer);},[load,page,query]);
  useEffect(()=>{if(!open)return;closeRef.current?.focus();document.body.style.overflow="hidden";fetch("/api/products").then(response=>response.json()).then((result:{items?:ProductOption[]})=>setProductOptions((result.items??[]).filter(item=>item.active).map(item=>({value:item.id,label:locale==="zh-CN"?item.nameZh:item.nameEn})))).catch(()=>setError(t("pipeline.productsLoadFailed")));const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKey);};},[locale,open,t]);
  const searchOrganizations=async(value:string)=>{setRelatedLoading(true);try{const response=await fetch(`/api/search/related?q=${encodeURIComponent(value)}`);const result=await response.json() as {items?:Array<{value:string;labelZh:string;labelEn:string;type:string}>};setOrganizationOptions((result.items??[]).filter(item=>item.type==="ORGANIZATION").map(item=>({value:item.value.split(":")[1],label:locale==="zh-CN"?item.labelZh:item.labelEn,detail:t("pipeline.organization")})));}finally{setRelatedLoading(false);}};
  const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");const form=new FormData(event.currentTarget);if(!organization){setError(t("pipeline.organizationRequired"));return;}const stage=String(form.get("stage"));const body={organizationId:organization,productId:product||null,titleZh:String(form.get("titleZh")),titleEn:String(form.get("titleEn")),stage,amount:Number(form.get("amount")),currency:String(form.get("currency")).toUpperCase(),probability:stageProbability[stage]??20,expectedCloseDate:String(form.get("expectedCloseDate"))||null,nextActionZh:String(form.get("nextActionZh")),nextActionEn:String(form.get("nextActionEn"))};const response=await fetch("/api/opportunities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {field?:string};if(!response.ok){setError(t("pipeline.createFailed",{field:result.field??t("pipeline.form")}));return;}setOpen(false);setPage(1);await load(1,query);setToast(t("pipeline.created"));};
  const changeStage=async(item:OpportunityRecord,stage:OpportunityRecord["stage"])=>{setError("");const previous=item.stage;setItems(current=>current.map(value=>value.id===item.id?{...value,stage}:value));const response=await fetch(`/api/opportunities/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage,probability:stage==="WON"?100:stage==="LOST"?0:stageProbability[stage]})});if(!response.ok){setItems(current=>current.map(value=>value.id===item.id?{...value,stage:previous}:value));setError(t("pipeline.stageFailed"));return;}setToast(t("pipeline.stageUpdated"));};
  const activeCount=initialFunnel.filter(item=>!(["WON","LOST"] as string[]).includes(item.stage)).reduce((sum,item)=>sum+item.count,0);const totalAmount=initialFunnel.filter(item=>!(["WON","LOST"] as string[]).includes(item.stage)).reduce((sum,item)=>sum+item.amount,0);const weighted=initialFunnel.filter(item=>!(["WON","LOST"] as string[]).includes(item.stage)).reduce((sum,item)=>sum+item.weighted,0);const paymentAmount=funnelMap.get("PAYMENT")?.amount??0;
  return <div className="page-stack pipeline-page"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.revenueMomentum")}</p><h1>{t("pipeline.title")}</h1><p>{t("pipeline.description")}</p></div><div className="page-actions"><button className="primary-button" type="button" onClick={()=>{setOpen(true);setError("");}}><Plus size={17}/>{t("pipeline.new")}</button></div></section>{error&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="pipeline-summary"><span><CircleDollarSign size={19}/><div><small>{t("pipeline.total")}</small><b>{money(totalAmount)}</b></div></span><span><Sparkles size={19}/><div><small>{t("pipeline.weighted")}</small><b>{money(weighted)}</b></div></span><span><CalendarDays size={19}/><div><small>{t("pipeline.paymentStage")}</small><b>{money(paymentAmount)}</b></div></span><span><UserRound size={19}/><div><small>{t("pipeline.active")}</small><b>{activeCount}</b></div></span></section>
    <section className="surface table-toolbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("pipeline.search")}/><button className="icon-button" type="button" disabled={loading} aria-label={t("common.retry")} onClick={()=>load(page,query)}><RefreshCcw className={loading?"spin":""} size={16}/></button></section>
    {items.length?<div className="kanban-scroll"><section className="kanban-board">{groups.map(group=><div className="kanban-column" key={group.stage}><div className="kanban-heading"><span><i className={stageTone[group.stage]}/><b>{t(`sales.stage.${group.stage.toLowerCase()}`)}</b><small>{funnelMap.get(group.stage)?.count??group.items.length}</small></span><b>{money(funnelMap.get(group.stage)?.amount??0)}</b></div><div className="kanban-cards">{group.items.map(card=><article className="opportunity-card" key={card.id}><span className="opportunity-top"><StatusBadge tone={stageTone[card.stage]}>{t(`sales.stage.${card.stage.toLowerCase()}`)}</StatusBadge><select aria-label={t("pipeline.changeStage",{title:locale==="zh-CN"?card.titleZh:card.titleEn})} value={card.stage} onChange={event=>changeStage(card,event.target.value as OpportunityRecord["stage"])}>{stageOrder.map(stage=><option value={stage} key={stage}>{t(`sales.stage.${stage.toLowerCase()}`)}</option>)}</select></span><b>{locale==="zh-CN"?card.titleZh:card.titleEn}</b><small>{locale==="zh-CN"?card.organizationZh:card.organizationEn}</small><div className="opportunity-meta"><b>{money(card.amount,card.currency)}</b><span><CalendarDays size={13}/>{card.expectedCloseDate?new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${card.expectedCloseDate}T00:00:00Z`)):t("common.notSet")}</span></div><div className="opportunity-footer"><span className="mini-avatar">{card.ownerEn.split(/\s+/).map(part=>part[0]).join("").slice(0,2)||"—"}</span><span className="next-action">{locale==="zh-CN"?card.nextActionZh:card.nextActionEn||t("pipeline.nextNeeded")}</span></div></article>)}</div><button className="add-kanban" type="button" onClick={()=>setOpen(true)}><Plus size={15}/>{t("pipeline.add")}</button></div>)}</section></div>:<EmptyState messageKey="pipeline.empty"/>}
    <Pagination page={Math.min(page,pages)} totalPages={pages} total={total} pageSize={pageSize} onPage={setPage}/><p className="kanban-note">{t("pipeline.note")}</p>
    {open&&<><button className="drawer-overlay" type="button" aria-label={t("common.close")} onClick={()=>setOpen(false)}/><aside className="record-drawer" role="dialog" aria-modal="true" aria-label={t("pipeline.new")}><div className="drawer-heading"><div><p className="eyebrow">{t("eyebrow.revenueMomentum")}</p><h2>{t("pipeline.new")}</h2><p>{t("pipeline.createHelp")}</p></div><button ref={closeRef} className="icon-button" type="button" aria-label={t("common.close")} onClick={()=>setOpen(false)}><X size={20}/></button></div><form onSubmit={create}><SearchableSelect label={t("pipeline.organization")} options={organizationOptions} value={organization} onChange={setOrganization} onSearch={searchOrganizations} loading={relatedLoading}/><SearchableSelect label={t("products.title")} options={productOptions} value={product} onChange={setProduct}/><div className="form-grid two-column"><label className="field"><span>{t("products.nameZh")}</span><input name="titleZh" required maxLength={160}/></label><label className="field"><span>{t("products.nameEn")}</span><input name="titleEn" required maxLength={180}/></label></div><div className="form-grid two-column"><label className="field"><span>{t("common.status")}</span><select name="stage" defaultValue="DISCOVERY">{stageOrder.slice(0,4).map(stage=><option value={stage} key={stage}>{t(`sales.stage.${stage.toLowerCase()}`)}</option>)}</select></label><label className="field"><span>{t("pipeline.expectedClose")}</span><input name="expectedCloseDate" type="date"/></label></div><div className="form-grid two-column"><label className="field"><span>{t("pipeline.amount")}</span><input name="amount" type="number" min="0" step="100" required/></label><label className="field"><span>{t("pipeline.currency")}</span><input name="currency" defaultValue="CNY" pattern="[A-Za-z]{3}" required/></label></div><div className="form-grid two-column"><label className="field"><span>{t("pipeline.nextActionZh")}</span><textarea name="nextActionZh" rows={3} maxLength={300}/></label><label className="field"><span>{t("pipeline.nextActionEn")}</span><textarea name="nextActionEn" rows={3} maxLength={300}/></label></div>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setOpen(false)}>{t("common.cancel")}</button><button className="primary-button" type="submit">{t("common.create")}</button></div></form></aside></>}
    {toast&&<Toast message={toast} onClose={()=>setToast("")}/>}
  </div>;
}
