"use client";

import { useCallback,useState } from "react";
import { Copy,Link2,Plus,ShieldCheck,Trash2 } from "lucide-react";
import { AccessibleDrawer,InlineMessage,SearchableSelect,StatusBadge,Toast } from "./ui";
import { useI18n } from "./i18n-provider";
import { useCapability } from "./app-user-context";
import { useUserPreferences } from "./user-preferences-context";
import { apiFetch } from "@/lib/api-client";
import type { PortalInvitationRecord,PortalUpdateRecord } from "@/lib/v220-repository";

type Workspace={invitations:PortalInvitationRecord[];updates:PortalUpdateRecord[];invitationUrl?:string};
export function PortalWorkspace({initial}:{initial:Workspace}){const{locale,t}=useI18n();const{localDateTimeToIso}=useUserPreferences();const canDecide=useCapability("portal.decide");const[data,setData]=useState(initial);const[open,setOpen]=useState(false);const[household,setHousehold]=useState("");const[households,setHouseholds]=useState<Array<{value:string;label:string;detail:string}>>([]);const[decision,setDecision]=useState<PortalUpdateRecord|null>(null);const[link,setLink]=useState("");const[pending,setPending]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");
  const searchHouseholds=useCallback(async(query:string)=>{const result=await apiFetch<{items:Array<{id:string;nameZh:string;nameEn:string;address:string}>}>(`/api/education?resource=households&q=${encodeURIComponent(query)}&pageSize=20`).catch(()=>({items:[]}));setHouseholds(result.items.map(item=>({value:item.id,label:locale==="zh-CN"?item.nameZh:item.nameEn,detail:item.address})));},[locale]);
  const operate=async(body:Record<string,unknown>)=>{setPending(true);setError("");try{const result=await apiFetch<Workspace>("/api/portal/invitations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setData(result);if(result.invitationUrl)setLink(result.invitationUrl);return true;}catch{setError(t("portal.failed"));return false;}finally{setPending(false);}};
  const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(!household){setError(t("portal.householdRequired"));return;}if(await operate({operation:"create",householdId:household,email:form.get("email"),expiresAt:localDateTimeToIso(String(form.get("expiresAt")))})){setOpen(false);setHousehold("");setToast(t("portal.created"));}};
  const decide=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!decision)return;const form=new FormData(event.currentTarget);if(await operate({operation:"decide",id:decision.id,status:form.get("status"),note:form.get("note")})){setDecision(null);setToast(t("portal.decided"));}};
  return <div className="page-stack v220-workspace"><section className="page-heading-row"><div><p className="eyebrow">{t("portal.eyebrow")}</p><h1>{t("portal.title")}</h1><p>{t("portal.help")}</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/>{t("portal.invite")}</button></section><InlineMessage type="warning">{t("portal.security")}</InlineMessage>{link&&<InlineMessage type="success"><span>{t("portal.linkOnce")}</span><code className="one-time-link">{link}</code><button className="text-button" onClick={()=>void navigator.clipboard.writeText(link).then(()=>setToast(t("portal.copied")))}><Copy size={14}/>{t("common.copy")}</button></InlineMessage>}{error&&!open&&!decision&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="surface"><div className="surface-heading"><div><h2>{t("portal.invitations")}</h2><p>{t("portal.invitationHelp")}</p></div><Link2 size={20}/></div><div className="v220-list">{data.invitations.map(item=><article key={item.id}><span className="product-icon"><ShieldCheck size={18}/></span><div><b>{locale==="zh-CN"?item.householdZh:item.householdEn}</b><small>{item.email} · {t("portal.expires",{date:item.expiresAt.slice(0,10)})}</small><small>{item.lastAccessedAt?t("portal.lastAccess",{date:new Date(item.lastAccessedAt).toLocaleString()}):t("portal.neverAccessed")}</small></div><StatusBadge tone={item.status==="ACTIVE"?"green":"gray"}>{item.status}</StatusBadge>{item.status==="ACTIVE"&&<button className="text-button danger" disabled={pending} onClick={()=>void operate({operation:"revoke",id:item.id})}><Trash2 size={14}/>{t("portal.revoke")}</button>}</article>)}</div></section>
    <section className="surface"><div className="surface-heading"><h2>{t("portal.updateRequests")}</h2></div><div className="v220-list">{data.updates.map(item=><article key={item.id}><div><b>{Object.keys(item.changes).map(key=>t(`portal.field.${key}`)).join(" · ")}</b><small>{JSON.stringify(item.changes)} · {new Date(item.createdAt).toLocaleString()}</small>{Object.keys(item.appliedChanges).length>0&&<small>{t("portal.appliedChanges")}: {JSON.stringify(item.appliedChanges)}</small>}</div><StatusBadge tone={item.status==="APPROVED"?"green":item.status==="REJECTED"?"red":"amber"}>{item.status}</StatusBadge>{canDecide&&item.status==="PENDING"&&<button className="secondary-button" onClick={()=>setDecision(item)}>{t("portal.review")}</button>}</article>)}</div>{!data.updates.length&&<div className="empty-state"><span>{t("portal.noUpdates")}</span></div>}</section>
    {open&&<AccessibleDrawer title={t("portal.invite")} description={t("portal.inviteHelp")} onClose={()=>setOpen(false)}><form onSubmit={create}><SearchableSelect label={t("nav.households")} value={household} options={households} onChange={setHousehold} onSearch={searchHouseholds}/><label className="field"><span>{t("common.email")}</span><input name="email" type="email" required/></label><label className="field"><span>{t("portal.expiry")}</span><input name="expiresAt" type="datetime-local" required/></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setOpen(false)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{pending?t("common.saving"):t("portal.createLink")}</button></div></form></AccessibleDrawer>}
    {decision&&<AccessibleDrawer title={t("portal.review")} description={JSON.stringify(decision.changes)} onClose={()=>setDecision(null)}><form onSubmit={decide}><label className="field"><span>{t("common.status")}</span><select name="status"><option value="APPROVED">{t("common.approve")}</option><option value="REJECTED">{t("common.reject")}</option></select></label><label className="field"><span>{t("portal.decisionNote")}</span><textarea name="note" minLength={3} rows={4} required/></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setDecision(null)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t("common.confirm")}</button></div></form></AccessibleDrawer>}{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
