"use client";

import { useMemo, useState } from "react";
import { Box, CircleDollarSign, PackageCheck, Plus, RefreshCw, Trash2, Users } from "lucide-react";
import { EmptyState } from "@/components/data-state";
import { useI18n } from "@/components/i18n-provider";
import { AccessibleDrawer, InlineMessage, Pagination, SearchField, StatusBadge, Toast } from "@/components/ui";
import type { ProductRecord } from "@/lib/product-repository";
import type { ExchangeRateSnapshot, ProductBundle } from "@/lib/operations-repository";
import { useAppUser } from "./app-user-context";
import { ADMIN_ROLES } from "@/lib/roles";
import { apiFetch } from "@/lib/api-client";
import { useUserPreferences } from "@/components/user-preferences-context";

export function ProductsPage({initialProducts,initialBundles,initialExchangeRates,initialCatalogError=false}:{initialProducts:ProductRecord[];initialBundles:ProductBundle[];initialExchangeRates:ExchangeRateSnapshot[];initialCatalogError?:boolean}){
  const {locale,t}=useI18n();const {formatDate,todayKey,localDateTimeInput,localDateTimeToIso}=useUserPreferences();const user=useAppUser();const [products,setProducts]=useState(initialProducts);const [query,setQuery]=useState("");const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(10);const [bundlePage,setBundlePage]=useState(1);const [bundlePageSize,setBundlePageSize]=useState(10);const [ratePage,setRatePage]=useState(1);const [ratePageSize,setRatePageSize]=useState(10);const [createOpen,setCreateOpen]=useState(false);const [priceProduct,setPriceProduct]=useState<ProductRecord|null>(null);const [formError,setFormError]=useState("");const [catalogError,setCatalogError]=useState(initialCatalogError);const [toast,setToast]=useState("");const [bundles,setBundles]=useState(initialBundles);const [exchangeRates,setExchangeRates]=useState(initialExchangeRates);const [bundleOpen,setBundleOpen]=useState(false);const [rateOpen,setRateOpen]=useState(false);const [bundleItems,setBundleItems]=useState([{productId:initialProducts[0]?.id??"",quantity:1,optional:false,discountCeiling:0}]);const canManageCatalog=ADMIN_ROLES.includes(user.role)||user.role==="SALES_DIRECTOR";const canManageRates=ADMIN_ROLES.includes(user.role);
  const filtered=useMemo(()=>products.filter(product=>`${product.nameZh} ${product.nameEn} ${product.code}`.toLowerCase().includes(query.toLowerCase())),[products,query]);const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);const bundlePages=Math.max(1,Math.ceil(bundles.length/bundlePageSize));const safeBundlePage=Math.min(bundlePage,bundlePages);const visibleBundles=bundles.slice((safeBundlePage-1)*bundlePageSize,safeBundlePage*bundlePageSize);const ratePages=Math.max(1,Math.ceil(exchangeRates.length/ratePageSize));const safeRatePage=Math.min(ratePage,ratePages);const visibleRates=exchangeRates.slice((safeRatePage-1)*ratePageSize,safeRatePage*ratePageSize);const currencies=[...new Set(products.flatMap(product=>product.prices.map(price=>price.currency)))];const money=(value:number,currency:string)=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en-US",{style:"currency",currency,maximumFractionDigits:0,notation:Math.abs(value)>=1_000_000?"compact":"standard"}).format(value);
  const reload=async()=>{const result=await apiFetch<{items:ProductRecord[]}>("/api/products");setProducts(result.items);};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setFormError("");const form=new FormData(event.currentTarget);const body={operation:"create",nameZh:String(form.get("nameZh")),nameEn:String(form.get("nameEn")),code:String(form.get("code")).toUpperCase(),price:Number(form.get("price")),currency:String(form.get("currency")).toUpperCase(),billing:String(form.get("billing")).replace("schoolYear","SCHOOL_YEAR").toUpperCase(),duration:String(form.get("duration")),durationEn:String(form.get("durationEn"))};try{await apiFetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await reload();setCreateOpen(false);setToast(t("products.created",{name:locale==="zh-CN"?body.nameZh:body.nameEn}));}catch{setFormError(t("products.saveFailed"));}};
  const savePrice=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!priceProduct)return;setFormError("");const form=new FormData(event.currentTarget);try{await apiFetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"price",id:priceProduct.id,currency:String(form.get("currency")).toUpperCase(),amount:Number(form.get("amount")),effectiveOn:String(form.get("effectiveOn"))})});await reload();setPriceProduct(null);setToast(t("products.priceSaved"));}catch{setFormError(t("products.priceSaveFailed"));}};
  const toggle=async(product:ProductRecord)=>{const active=!product.active;try{await apiFetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"toggle",id:product.id,active})});setProducts(current=>current.map(item=>item.id===product.id?{...item,active}:item));setToast(t("products.toggled",{name:locale==="zh-CN"?product.nameZh:product.nameEn,status:t(active?"common.enabled":"common.inactive")}));}catch{setToast(t("products.saveFailed"));}};
  const reloadCatalog=async()=>{try{const result=await apiFetch<{bundles:ProductBundle[];exchangeRates:ExchangeRateSnapshot[]}>("/api/catalog");setBundles(result.bundles);setExchangeRates(result.exchangeRates);setCatalogError(false);}catch{setCatalogError(true);throw new Error("CATALOG_LOAD_FAILED");}};
  const saveBundle=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setFormError("");const form=new FormData(event.currentTarget);try{await apiFetch("/api/catalog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"bundle",code:form.get("code"),nameZh:form.get("nameZh"),nameEn:form.get("nameEn"),items:bundleItems})});await reloadCatalog();setBundleOpen(false);setToast(t("catalog.bundleSaved"));}catch{setFormError(t("catalog.bundleFailed"));}};
  const saveRate=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setFormError("");const form=new FormData(event.currentTarget);try{await apiFetch("/api/catalog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"exchangeRate",base:String(form.get("base")).toUpperCase(),quote:String(form.get("quote")).toUpperCase(),rate:Number(form.get("rate")),source:form.get("source"),effectiveAt:localDateTimeToIso(String(form.get("effectiveAt")))})});await reloadCatalog();setRateOpen(false);setToast(t("catalog.rateSaved"));}catch{setFormError(t("catalog.rateFailed"));}};
  return <div className="page-stack products-page"><section className="page-heading-row"><div><p className="eyebrow">{t("products.eyebrow")}</p><h1>{t("products.title")}</h1><p>{t("products.description")}</p></div><button className="primary-button" type="button" onClick={()=>{setCreateOpen(true);setFormError("");}}><Plus size={17}/>{t("products.custom")}</button></section>
    {catalogError&&<InlineMessage type="error">{t("catalog.loadFailed")}</InlineMessage>}
    <section className="product-kpis"><ProductKpi icon={PackageCheck} tone="green" value={String(products.filter(item=>item.active).length)} label={t("products.activeCount")}/><ProductKpi icon={CircleDollarSign} tone="blue" value={currencies.join(" · ")||"—"} label={t("products.pricedCurrencies")}/><ProductKpi icon={Users} tone="purple" value={String(products.reduce((sum,item)=>sum+item.customers,0))} label={t("products.productCustomerLinks")}/><ProductKpi icon={Box} tone="amber" value={String(products.filter(item=>item.isDefault).length)} label={t("products.defaultCount")}/></section>
    <section className="surface product-catalog-card"><div className="table-toolbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("products.search")}/><StatusBadge tone="green">{t("products.supportCustom")}</StatusBadge></div>{visible.length?<><div className="product-list-head"><span>{t("products.product")}</span><span>{t("products.price")}</span><span>{t("products.delivery")}</span><span>{t("products.customerCount")}</span><span>{t("products.spend")}</span><span>{t("common.status")}</span></div>{visible.map(product=>{const productName=locale==="zh-CN"?product.nameZh:product.nameEn;return <article className="product-list-row" key={product.id}><div><span className="product-icon"><PackageCheck size={19}/></span><span><b>{productName}</b><small>{product.code}{product.isDefault?` · ${t("products.default")}`:""}</small></span></div><button className="product-price-button" type="button" onClick={()=>{setPriceProduct(product);setFormError("");}}><b>{money(product.price,product.currency)}</b><small>{product.prices.length>1?t("products.currencyCount",{count:product.prices.length}):t("products.managePrice")}</small></button><span><b>{locale==="en"?product.durationEn:product.duration}</b><small>{t(product.billing)}</small></span><span><b>{product.customers}</b><small>{t("products.purchaseCount")}</small></span><span><b>{money(product.revenue,product.currency)}</b><small>{t("products.confirmedTotal")}</small></span><button type="button" onClick={()=>toggle(product)}><StatusBadge tone={product.active?"green":"gray"}>{t(product.active?"products.onSale":"common.inactive")}</StatusBadge></button></article>;})}</>:<EmptyState messageKey="products.empty"/>}<Pagination page={safePage} totalPages={totalPages} total={filtered.length} pageSize={pageSize} onPage={setPage} onPageSize={(value)=>{setPageSize(value);setPage(1);}}/></section>
    <section className="catalog-extension-grid"><article className="surface catalog-extension"><div className="surface-heading"><div><p className="eyebrow">BUNDLES</p><h2>{t("catalog.bundles")}</h2><p>{t("catalog.bundleHelp")}</p></div>{canManageCatalog&&<button className="secondary-button" type="button" onClick={()=>{setFormError("");setBundleOpen(true);}}><Plus size={16}/>{t("catalog.newBundle")}</button>}</div><div className="bundle-list">{visibleBundles.map(bundle=><div key={bundle.id}><span><b>{locale==="zh-CN"?bundle.nameZh:bundle.nameEn}</b><small>{bundle.code} · v{bundle.version} · {bundle.items.length} items</small></span><StatusBadge tone={bundle.active?"green":"gray"}>{t(bundle.active?"common.enabled":"common.inactive")}</StatusBadge><ul>{bundle.items.map(item=><li key={item.productId}>{locale==="zh-CN"?item.productNameZh:item.productNameEn} × {item.quantity}{item.optional?` · ${t("catalog.optional")}`:""} · ≤ {item.discountCeiling}%</li>)}</ul></div>)}</div>{!bundles.length&&<div className="empty-state"><span>{t("catalog.bundleHelp")}</span></div>}<Pagination page={safeBundlePage} totalPages={bundlePages} total={bundles.length} pageSize={bundlePageSize} onPage={setBundlePage} onPageSize={(value)=>{setBundlePageSize(value);setBundlePage(1);}}/></article><article className="surface catalog-extension"><div className="surface-heading"><div><p className="eyebrow">FX SNAPSHOTS</p><h2>{t("catalog.exchangeRates")}</h2><p>{t("catalog.exchangeHelp")}</p></div>{canManageRates&&<button className="secondary-button" type="button" onClick={()=>{setFormError("");setRateOpen(true);}}><RefreshCw size={16}/>{t("catalog.newRate")}</button>}</div><div className="rate-list">{visibleRates.map(rate=><div key={rate.id}><b>{rate.baseCurrency}/{rate.quoteCurrency}</b><strong>{rate.rate}</strong><small>{rate.source} · {formatDate(rate.effectiveAt,{includeTime:true})}</small></div>)}</div>{!exchangeRates.length&&<div className="empty-state"><span>{t("catalog.exchangeHelp")}</span></div>}<Pagination page={safeRatePage} totalPages={ratePages} total={exchangeRates.length} pageSize={ratePageSize} onPage={setRatePage} onPageSize={(value)=>{setRatePageSize(value);setRatePage(1);}}/></article></section>
    {createOpen&&<Drawer title={t("products.custom")} close={()=>setCreateOpen(false)}><form onSubmit={submit}><div className="form-grid two-column"><label className="field"><span>{t("products.nameZh")}</span><input name="nameZh" required maxLength={100}/></label><label className="field"><span>{t("products.nameEn")}</span><input name="nameEn" required maxLength={120}/></label></div><label className="field"><span>{t("products.code")}</span><input name="code" pattern="[A-Za-z0-9-]+" placeholder="EXAMPLE-PRODUCT" required/></label><div className="form-grid two-column"><label className="field"><span>{t("products.price")}</span><input name="price" type="number" min="0" step="100" required/></label><label className="field"><span>{t("products.currency")}</span><input name="currency" defaultValue="CNY" pattern="[A-Za-z]{3}" required/></label></div><label className="field"><span>{t("products.billing")}</span><select name="billing" defaultValue="project"><option value="project">{t("products.billing.project")}</option><option value="term">{t("products.billing.term")}</option><option value="month">{t("products.billing.month")}</option><option value="year">{t("products.billing.year")}</option><option value="schoolYear">{t("products.billing.schoolYear")}</option><option value="season">{t("products.billing.season")}</option></select></label><div className="form-grid two-column"><label className="field"><span>{t("products.durationZh")}</span><input name="duration" required/></label><label className="field"><span>{t("products.durationEn")}</span><input name="durationEn" required/></label></div>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setCreateOpen(false)} label={t("products.create")}/></form></Drawer>}
    {priceProduct&&<Drawer title={t("products.managePriceTitle")} close={()=>setPriceProduct(null)}><form onSubmit={savePrice}><p>{locale==="zh-CN"?priceProduct.nameZh:priceProduct.nameEn}</p><div className="form-grid two-column"><label className="field"><span>{t("products.currency")}</span><input name="currency" defaultValue={priceProduct.currency} pattern="[A-Za-z]{3}" required/></label><label className="field"><span>{t("products.price")}</span><input name="amount" type="number" min="0" step="100" defaultValue={priceProduct.price} required/></label></div><label className="field"><span>{t("products.effectiveOn")}</span><input name="effectiveOn" type="date" min={todayKey()} defaultValue={todayKey()} required/></label><InlineMessage type="warning">{t("products.priceVersionHelp")}</InlineMessage>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setPriceProduct(null)} label={t("common.save")}/></form></Drawer>}
    {bundleOpen&&<Drawer title={t("catalog.newBundle")} close={()=>setBundleOpen(false)}><form onSubmit={saveBundle}><label className="field"><span>{t("catalog.bundleCode")}</span><input name="code" pattern="[A-Za-z0-9-]+" required/></label><div className="form-grid two-column"><label className="field"><span>{t("catalog.bundleNameZh")}</span><input name="nameZh" minLength={2} required/></label><label className="field"><span>{t("catalog.bundleNameEn")}</span><input name="nameEn" minLength={2} required/></label></div><h3>{t("catalog.bundleItems")}</h3>{bundleItems.map((item,index)=><div className="bundle-item-form" key={index}><label className="field"><span>{t("products.product")}</span><select value={item.productId} onChange={event=>setBundleItems(current=>current.map((entry,itemIndex)=>itemIndex===index?{...entry,productId:event.target.value}:entry))}>{products.filter(product=>product.active).map(product=><option value={product.id} key={product.id}>{locale==="zh-CN"?product.nameZh:product.nameEn}</option>)}</select></label><label className="field"><span>{t("catalog.quantity")}</span><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={event=>setBundleItems(current=>current.map((entry,itemIndex)=>itemIndex===index?{...entry,quantity:Number(event.target.value)}:entry))}/></label><label className="field"><span>{t("catalog.discountCeiling")}</span><input type="number" min="0" max="100" step="0.1" value={item.discountCeiling} onChange={event=>setBundleItems(current=>current.map((entry,itemIndex)=>itemIndex===index?{...entry,discountCeiling:Number(event.target.value)}:entry))}/></label><label className="check-row"><input type="checkbox" checked={item.optional} onChange={event=>setBundleItems(current=>current.map((entry,itemIndex)=>itemIndex===index?{...entry,optional:event.target.checked}:entry))}/><span>{t("catalog.optional")}</span></label><button className="icon-button" type="button" disabled={bundleItems.length===1} onClick={()=>setBundleItems(current=>current.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={16}/></button></div>)}<button className="secondary-button" type="button" onClick={()=>setBundleItems(current=>[...current,{productId:products.find(product=>product.active)?.id??"",quantity:1,optional:true,discountCeiling:0}])}><Plus size={16}/>{t("catalog.addItem")}</button>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setBundleOpen(false)} label={t("common.save")}/></form></Drawer>}
    {rateOpen&&<Drawer title={t("catalog.newRate")} close={()=>setRateOpen(false)}><form onSubmit={saveRate}><div className="form-grid two-column"><label className="field"><span>{t("catalog.baseCurrency")}</span><input name="base" defaultValue="CNY" pattern="[A-Za-z]{3}" required/></label><label className="field"><span>{t("catalog.quoteCurrency")}</span><input name="quote" defaultValue="USD" pattern="[A-Za-z]{3}" required/></label></div><label className="field"><span>{t("catalog.rate")}</span><input name="rate" type="number" min="0.00000001" step="0.00000001" required/></label><label className="field"><span>{t("catalog.rateSource")}</span><input name="source" minLength={2} placeholder="Bank treasury desk / signed quote" required/></label><label className="field"><span>{t("catalog.effectiveAt")}</span><input name="effectiveAt" type="datetime-local" defaultValue={localDateTimeInput()} required/></label><InlineMessage type="warning">{t("catalog.exchangeHelp")}</InlineMessage>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setRateOpen(false)} label={t("common.save")}/></form></Drawer>}
    {toast&&<Toast message={toast} onClose={()=>setToast("")}/>}
  </div>;
}
function Drawer({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){const {t}=useI18n();return <AccessibleDrawer title={title} eyebrow={t("products.eyebrow")} description={t("products.codeHelp")} onClose={close}>{children}</AccessibleDrawer>;}
function FormActions({close,label}:{close:()=>void;label:string}){const {t}=useI18n();return <div className="drawer-actions"><button className="secondary-button" type="button" onClick={close}>{t("common.cancel")}</button><button className="primary-button" type="submit"><Plus size={17}/>{label}</button></div>;}
function ProductKpi({icon:Icon,tone,value,label}:{icon:React.ElementType;tone:string;value:string;label:string}){return <article className="surface product-kpi"><span className={tone}><Icon size={21}/></span><div><b>{value}</b><small>{label}</small></div></article>;}
