"use client";

import { useMemo, useState } from "react";
import { Box, CircleDollarSign, PackageCheck, Plus, Users, X } from "lucide-react";
import { EmptyState } from "@/components/data-state";
import { useI18n } from "@/components/i18n-provider";
import { InlineMessage, Pagination, SearchField, StatusBadge, Toast } from "@/components/ui";
import type { ProductRecord } from "@/lib/product-repository";

export function ProductsPage({initialProducts}:{initialProducts:ProductRecord[]}){
  const {locale,t}=useI18n();const [products,setProducts]=useState(initialProducts);const [query,setQuery]=useState("");const [page,setPage]=useState(1);const [createOpen,setCreateOpen]=useState(false);const [priceProduct,setPriceProduct]=useState<ProductRecord|null>(null);const [formError,setFormError]=useState("");const [toast,setToast]=useState("");const pageSize=8;
  const filtered=useMemo(()=>products.filter(product=>`${product.nameZh} ${product.nameEn} ${product.code}`.toLowerCase().includes(query.toLowerCase())),[products,query]);const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);const currencies=[...new Set(products.flatMap(product=>product.prices.map(price=>price.currency)))];const money=(value:number,currency:string)=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en-US",{style:"currency",currency,maximumFractionDigits:0,notation:Math.abs(value)>=1_000_000?"compact":"standard"}).format(value);
  const reload=async()=>{const response=await fetch("/api/products");const result=await response.json() as {items?:ProductRecord[]};if(!response.ok||!result.items)throw new Error();setProducts(result.items);};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setFormError("");const form=new FormData(event.currentTarget);const body={operation:"create",nameZh:String(form.get("nameZh")),nameEn:String(form.get("nameEn")),code:String(form.get("code")).toUpperCase(),price:Number(form.get("price")),currency:String(form.get("currency")).toUpperCase(),billing:String(form.get("billing")).replace("schoolYear","SCHOOL_YEAR").toUpperCase(),duration:String(form.get("duration")),durationEn:String(form.get("durationEn"))};const response=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setFormError(t("products.saveFailed"));return;}await reload();setCreateOpen(false);setToast(t("products.created",{name:locale==="zh-CN"?body.nameZh:body.nameEn}));};
  const savePrice=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!priceProduct)return;setFormError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"price",id:priceProduct.id,currency:String(form.get("currency")).toUpperCase(),amount:Number(form.get("amount")),effectiveOn:String(form.get("effectiveOn"))})});if(!response.ok){setFormError(t("products.priceSaveFailed"));return;}await reload();setPriceProduct(null);setToast(t("products.priceSaved"));};
  const toggle=async(product:ProductRecord)=>{const active=!product.active;const response=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"toggle",id:product.id,active})});if(!response.ok){setToast(t("products.saveFailed"));return;}setProducts(current=>current.map(item=>item.id===product.id?{...item,active}:item));setToast(t("products.toggled",{name:locale==="zh-CN"?product.nameZh:product.nameEn,status:t(active?"common.enabled":"common.inactive")}));};
  return <div className="page-stack products-page"><section className="page-heading-row"><div><p className="eyebrow">{t("products.eyebrow")}</p><h1>{t("products.title")}</h1><p>{t("products.description")}</p></div><button className="primary-button" type="button" onClick={()=>{setCreateOpen(true);setFormError("");}}><Plus size={17}/>{t("products.custom")}</button></section>
    <section className="product-kpis"><ProductKpi icon={PackageCheck} tone="green" value={String(products.filter(item=>item.active).length)} label={t("products.activeCount")}/><ProductKpi icon={CircleDollarSign} tone="blue" value={currencies.join(" · ")||"—"} label={t("products.pricedCurrencies")}/><ProductKpi icon={Users} tone="purple" value={String(products.reduce((sum,item)=>sum+item.customers,0))} label={t("products.productCustomerLinks")}/><ProductKpi icon={Box} tone="amber" value={String(products.filter(item=>item.isDefault).length)} label={t("products.defaultCount")}/></section>
    <section className="surface product-catalog-card"><div className="table-toolbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1);}} placeholder={t("products.search")}/><StatusBadge tone="green">{t("products.supportCustom")}</StatusBadge></div>{visible.length?<><div className="product-list-head"><span>{t("products.product")}</span><span>{t("products.price")}</span><span>{t("products.delivery")}</span><span>{t("products.customerCount")}</span><span>{t("products.spend")}</span><span>{t("common.status")}</span></div>{visible.map(product=>{const productName=locale==="zh-CN"?product.nameZh:product.nameEn;return <article className="product-list-row" key={product.id}><div><span className="product-icon"><PackageCheck size={19}/></span><span><b>{productName}</b><small>{product.code}{product.isDefault?` · ${t("products.default")}`:""}</small></span></div><button className="product-price-button" type="button" onClick={()=>{setPriceProduct(product);setFormError("");}}><b>{money(product.price,product.currency)}</b><small>{product.prices.length>1?t("products.currencyCount",{count:product.prices.length}):t("products.managePrice")}</small></button><span><b>{locale==="en"?product.durationEn:product.duration}</b><small>{t(product.billing)}</small></span><span><b>{product.customers}</b><small>{t("products.purchaseCount")}</small></span><span><b>{money(product.revenue,product.currency)}</b><small>{t("products.confirmedTotal")}</small></span><button type="button" onClick={()=>toggle(product)}><StatusBadge tone={product.active?"green":"gray"}>{t(product.active?"products.onSale":"common.inactive")}</StatusBadge></button></article>;})}</>:<EmptyState messageKey="products.empty"/>}<Pagination page={safePage} totalPages={totalPages} total={filtered.length} pageSize={pageSize} onPage={setPage}/></section>
    {createOpen&&<Drawer title={t("products.custom")} close={()=>setCreateOpen(false)}><form onSubmit={submit}><div className="form-grid two-column"><label className="field"><span>{t("products.nameZh")}</span><input name="nameZh" required maxLength={100}/></label><label className="field"><span>{t("products.nameEn")}</span><input name="nameEn" required maxLength={120}/></label></div><label className="field"><span>{t("products.code")}</span><input name="code" pattern="[A-Za-z0-9-]+" placeholder="EXAMPLE-PRODUCT" required/></label><div className="form-grid two-column"><label className="field"><span>{t("products.price")}</span><input name="price" type="number" min="0" step="100" required/></label><label className="field"><span>{t("products.currency")}</span><input name="currency" defaultValue="CNY" pattern="[A-Za-z]{3}" required/></label></div><label className="field"><span>{t("products.billing")}</span><select name="billing" defaultValue="project"><option value="project">{t("products.billing.project")}</option><option value="term">{t("products.billing.term")}</option><option value="month">{t("products.billing.month")}</option><option value="year">{t("products.billing.year")}</option><option value="schoolYear">{t("products.billing.schoolYear")}</option><option value="season">{t("products.billing.season")}</option></select></label><div className="form-grid two-column"><label className="field"><span>{t("products.durationZh")}</span><input name="duration" required/></label><label className="field"><span>{t("products.durationEn")}</span><input name="durationEn" required/></label></div>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setCreateOpen(false)} label={t("products.create")}/></form></Drawer>}
    {priceProduct&&<Drawer title={t("products.managePriceTitle")} close={()=>setPriceProduct(null)}><form onSubmit={savePrice}><p>{locale==="zh-CN"?priceProduct.nameZh:priceProduct.nameEn}</p><div className="form-grid two-column"><label className="field"><span>{t("products.currency")}</span><input name="currency" defaultValue={priceProduct.currency} pattern="[A-Za-z]{3}" required/></label><label className="field"><span>{t("products.price")}</span><input name="amount" type="number" min="0" step="100" defaultValue={priceProduct.price} required/></label></div><label className="field"><span>{t("products.effectiveOn")}</span><input name="effectiveOn" type="date" min={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)} required/></label><InlineMessage type="warning">{t("products.priceVersionHelp")}</InlineMessage>{formError&&<InlineMessage type="error">{formError}</InlineMessage>}<FormActions close={()=>setPriceProduct(null)} label={t("common.save")}/></form></Drawer>}
    {toast&&<Toast message={toast} onClose={()=>setToast("")}/>}
  </div>;
}
function Drawer({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){const {t}=useI18n();return <><button className="drawer-overlay" type="button" aria-label={t("common.close")} onClick={close}/><aside className="record-drawer" role="dialog" aria-modal="true" aria-label={title}><div className="drawer-heading"><div><p className="eyebrow">{t("products.eyebrow")}</p><h2>{title}</h2><p>{t("products.codeHelp")}</p></div><button className="icon-button" type="button" aria-label={t("common.close")} onClick={close}><X size={20}/></button></div>{children}</aside></>;}
function FormActions({close,label}:{close:()=>void;label:string}){const {t}=useI18n();return <div className="drawer-actions"><button className="secondary-button" type="button" onClick={close}>{t("common.cancel")}</button><button className="primary-button" type="submit"><Plus size={17}/>{label}</button></div>;}
function ProductKpi({icon:Icon,tone,value,label}:{icon:React.ElementType;tone:string;value:string;label:string}){return <article className="surface product-kpi"><span className={tone}><Icon size={21}/></span><div><b>{value}</b><small>{label}</small></div></article>;}
