"use client";

import { useState } from "react";
import { GraduationCap,Home,ShieldCheck } from "lucide-react";
import { InlineMessage,StatusBadge,Toast } from "./ui";
import { useI18n } from "./i18n-provider";
import { apiFetch } from "@/lib/api-client";
import type { PublicPortalSnapshot } from "@/lib/v220-repository";

export function PublicPortalPage({token,initial}:{token:string;initial:PublicPortalSnapshot}){
  const{locale,t}=useI18n();const[data,setData]=useState(initial);const[pending,setPending]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");
  const acceptConsent=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(form.get("accepted")!=="on"){setError(t("portal.public.consentRequired"));return;}setPending(true);setError("");try{const result=await apiFetch<{data:PublicPortalSnapshot}>(`/api/portal/public/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"consent",requestKey:crypto.randomUUID(),accepted:true})});setData(result.data);setToast(t("portal.public.consentSaved"));}catch{setError(t("portal.public.failed"));}finally{setPending(false);}};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const changes=Object.fromEntries(["address","preferredContact","note"].map(key=>[key,String(form.get(key)??"").trim()]).filter(([,value])=>value));if(!Object.keys(changes).length){setError(t("portal.public.changeRequired"));return;}setPending(true);setError("");try{await apiFetch(`/api/portal/public/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"update",requestKey:crypto.randomUUID(),changes})});event.currentTarget.reset();setToast(t("portal.public.submitted"));}catch{setError(t("portal.public.failed"));}finally{setPending(false);}};
  return <main className="public-portal"><header><span><ShieldCheck/></span><div><p className="eyebrow">{t("portal.public.eyebrow")}</p><h1>{t("portal.public.title")}</h1><p>{t("portal.public.expires",{date:data.expiresAt.slice(0,10)})}</p></div></header>{data.consentRequired?<section className="surface portal-consent"><ShieldCheck/><div><h2>{t("portal.public.consentTitle")}</h2><p>{t("portal.public.consentHelp")}</p></div><form onSubmit={acceptConsent}><label className="check-row"><input name="accepted" type="checkbox" required/><span>{t("portal.public.consentAgreement")}</span></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<button className="primary-button" disabled={pending}>{pending?t("common.processing"):t("portal.public.continue")}</button></form></section>:<><section className="surface portal-household"><Home/><div><h2>{locale==="zh-CN"?data.household.nameZh:data.household.nameEn}</h2><p>{data.household.address||t("portal.public.noAddress")}</p></div></section><section className="surface"><div className="surface-heading"><h2>{t("portal.public.students")}</h2></div><div className="portal-students">{data.students.map(student=><article key={student.id}><GraduationCap/><div><b>{locale==="zh-CN"?student.nameZh:student.nameEn}</b><small>{student.grade} · {student.academicYear}</small></div><StatusBadge tone="green">{student.status}</StatusBadge></article>)}</div></section><section className="surface"><div className="surface-heading"><div><h2>{t("portal.public.requestUpdate")}</h2><p>{t("portal.public.requestHelp")}</p></div></div><form onSubmit={submit}><label className="field"><span>{t("portal.field.address")}</span><input name="address" maxLength={500}/></label><label className="field"><span>{t("portal.field.preferredContact")}</span><input name="preferredContact" maxLength={160}/></label><label className="field"><span>{t("portal.field.note")}</span><textarea name="note" rows={4} maxLength={1000}/></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<button className="primary-button" disabled={pending}>{pending?t("common.processing"):t("portal.public.submit")}</button></form></section></>}{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</main>;
}
