"use client";
import {WorkspaceHeading} from "./workspace-heading";

import {UiIcon} from "./ui-icon";
import Link from 'next/link';
import {useAppUser} from './app-user-context';
import {RevenueAdministration} from './revenue-administration';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {AccessibleDrawer} from './ui';
import {useI18n} from './i18n-provider';
import {apiFetch,ApiClientError} from '@/lib/api-client';
import {isDefinitiveMutationFailure,settleMutation} from '@/lib/mutation-outcome';
import {revenueLabel} from '@/lib/revenue-workspace-labels';
import {revenueRows as rows,revenueText as text,type RevenueRow,type RevenueWorkspace} from '@/lib/revenue-workspace';
import styles from './revenue-workspace.module.css';

type Action={operation:string;command?:string;row:RevenueRow;label:string};
const candidateFields=['id','contract_number','description_snapshot','contract_version_id','recognition_unit_key','amount','currency','business_date','period_key','period_status','status','health','recognition_strategy','policy_version','binding_version','created_by','created_at','reviewed_by','reviewed_at','approval_reference','basis_digest'];
const serviceFields=['contract_number','description_snapshot','contract_version_id','stable_service_key','supersedes_service_id','accepted_amount','accepted_quantity','currency','source_quote_version_id','source_quote_line_reference','accepted_price_source'];
const bindingFields=['description_snapshot','contract_version_id','version','policy_key','policy_version','principal_agent_role','presentation','amount_basis_snapshot','agent_fee','allocation_decision_reference','refund_contract_version_id','scenario_reference','reference_fallback','has_variance','variance_review_reference','recognition_unit_schedule','fulfillment_requirements','status','created_by','reviewed_by','approved_by','approved_at','approval_reference'];
const evidenceFields=['source_domain','source_id','source_version','source_hash','evidence_type','recognition_unit_key','business_date','coverage_from','coverage_to','verified_units','status','health','attested_by','created_at','verified_by','verified_at','verification_reference','withdrawn_by','withdrawn_at','withdrawal_reference'];
const factFields=['id','candidate_id','fact_kind','current_amount','amount','currency','business_date','accounting_period_id','contract_version_id','specified_service_id','recognition_unit_key','binding_id','policy_version_id','original_fact_id','prior_fact_id','correction_intent_key','prior_period_flag','posted_by','posted_at','approval_reference','posting_reference','source_basis_digest'];
const policyFields=['policy_key','version','recognition_strategy','presentation','amount_strategy','fulfillment_rule_reference','refund_correction_reference','correction_rule','currency','effective_from','effective_to','status','test_only','created_by','created_at','approved_by','approved_at'];

export function RevenueWorkspaceView({initial,contractId}:{initial:RevenueWorkspace;contractId?:string}){
 const actor=useAppUser();const [administration,setAdministration]=useState(false);
 const {locale}=useI18n();const l=(key:string)=>revenueLabel(locale,key);const params=useSearchParams();
 const readGeneration=useRef(0);const sourceGeneration=useRef(0);
 const [data,setData]=useState(initial);const [tab,setTab]=useState(params.get('tab')??(contractId?'contracts':'queue'));
 const [filter,setFilter]=useState({q:params.get('q')??'',status:params.get('status')??'',currency:params.get('currency')??'',page:params.get('page')??'1'});
 const [detail,setDetail]=useState<{row:RevenueRow;fields:string[];title:string}|null>(null);
 const [action,setAction]=useState<Action|null>(null);const [pending,setPending]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [retry,setRetry]=useState<RevenueRow|null>(null);const [refreshOnly,setRefreshOnly]=useState(false);
 const [form,setForm]=useState<Record<string,string>>({});const [schedule,setSchedule]=useState([{key:'DELIVERY',units:'1',from:'',to:''}]);const [sourceOptions,setSourceOptions]=useState<RevenueRow[]>([]);
 const receiptStorage=`revenue-pending:${data.actor??''}:${data.entity??''}`;
 useEffect(()=>{try{const saved=sessionStorage.getItem(receiptStorage);if(saved){const record=JSON.parse(saved) as {payload:RevenueRow;accepted?:boolean};if(record.accepted){setRefreshOnly(true);setNotice(revenueLabel(locale,'refreshFailed'));}else{setRetry(record.payload);setError(revenueLabel(locale,'uncertain'));}}}catch{/* An unavailable browser store never authorizes a replay. */}},[receiptStorage,locale]);
 const load=useCallback(async(next=filter,entity=data.entity)=>{const generation=++readGeneration.current;const search=new URLSearchParams(Object.entries({...next,entity:entity??'',contract:contractId??''}).filter(([,v])=>v));const value=await apiFetch<RevenueWorkspace>(`/api/revenue?${search}`);if(generation===readGeneration.current)setData(value);return value;},[filter,data.entity,contractId]);
 const refresh=()=>{setError('');void load().then(()=>{setRefreshOnly(false);if(!retry){try{sessionStorage.removeItem(receiptStorage);}catch{}}}).catch(()=>setError(l('failed')));};
 // URL state survives refresh and browser back/forward without changing financial state.
 useEffect(()=>{const listener=()=>{const s=new URLSearchParams(window.location.search);const next={q:s.get('q')??'',status:s.get('status')??'',currency:s.get('currency')??'',page:s.get('page')??'1'};setTab(s.get('tab')??'queue');setFilter(next);void load(next).catch(()=>setError(revenueLabel(locale,'failed')));};window.addEventListener('popstate',listener);return()=>window.removeEventListener('popstate',listener);},[load,locale]);
 const navigate=(nextTab:string,next=nextTab===tab?filter:{...filter,page:'1'})=>{setTab(nextTab);setFilter(next);const s=new URLSearchParams(Object.entries({...next,tab:nextTab,entity:data.entity??'',contract:contractId??''}).filter(([,v])=>v));window.history.pushState(null,'',`${window.location.pathname}?${s}`);void load(next).catch(()=>setError(l('failed')));};
 function value(v:unknown):React.ReactNode{if(v==null||v==='')return '—';if(typeof v==='boolean')return l(v?'yes':'no');if(Array.isArray(v))return <ul>{v.map((x,i)=><li key={i}>{value(x)}</li>)}</ul>;if(typeof v==='object')return <dl className={styles.nested}>{Object.entries(v as RevenueRow).map(([k,x])=><div key={k}><dt>{l(k)}</dt><dd>{value(x)}</dd></div>)}</dl>;return l(String(v));}
 const basis=(row:RevenueRow,fields:string[])=><dl className={styles.basis}>{fields.filter(k=>row[k]!=null&&row[k]!=='').map(k=><div key={k}><dt>{l(k)}</dt><dd>{value(row[k])}</dd></div>)}</dl>;
 const peek=(row:RevenueRow,fields:string[],title:string)=>setDetail({row,fields,title});
 const open=async(a:Action)=>{if(retry||pending||refreshOnly)return;const generation=++sourceGeneration.current;setDetail(null);setAction(a);setError('');setForm({reference:'',policy_key:text(a.row,'policy_key'),currency:text(a.row,'currency')||'CNY',recognition_strategy:text(a.row,'recognition_strategy')||'POINT_IN_TIME_ON_APPROVED_EVIDENCE',amount_strategy:text(a.row,'amount_strategy')||'ACCEPTED_SERVICE_CONSIDERATION',presentation:text(a.row,'presentation')||'GROSS',principal_agent_role:'PRINCIPAL',kind:'ADJUSTMENT',method:'BLOCKED'});setSchedule([{key:'DELIVERY',units:'1',from:'',to:''}]);setSourceOptions([]);
  if(a.operation==='requirements'||(a.operation==='evidence'&&a.command==='CREATE')){try{const options=await apiFetch<RevenueRow[]>(`/api/revenue?entity=${data.entity}&service=${text(a.row,'specified_service_id')}${a.operation==='evidence'?`&binding=${text(a.row,'id')}`:''}`);if(generation===sourceGeneration.current)setSourceOptions(options);}catch{setError(l('failed'));}}
 };
 const act=(a:Action)=><button type="button" key={`${a.operation}:${a.command??a.label}:${a.row.id??'new'}`} className="secondary-button" onClick={()=>void open(a)} disabled={pending||!!retry||refreshOnly}>{l(a.label)}</button>;
 async function execute(payload:RevenueRow){setPending(true);setError('');setNotice('');try{sessionStorage.setItem(receiptStorage,JSON.stringify({payload}));}catch{}const outcome=await settleMutation(async()=>{const response=await apiFetch('/api/revenue',{method:'POST',body:JSON.stringify(payload)});try{sessionStorage.setItem(receiptStorage,JSON.stringify({accepted:true}));}catch{}return response;},()=>load());setPending(false);
  if(outcome.state==='failed'){const e=outcome.error;if(e instanceof ApiClientError&&['MFA_REQUIRED','REVENUE_AAL2_REQUIRED'].includes(e.code)){setRetry(payload);setError(l('aal'));}
   else if(isDefinitiveMutationFailure(e)){setRetry(null);try{sessionStorage.removeItem(receiptStorage);}catch{}const code=e.code.toLowerCase();const message=l(code);setError(message===code?l('failed'):message);void load().catch(()=>{if(['revenue_authority_required','cash_authority_required'].includes(code))setData({state:'NO_DESIGNATION',entities:[]});});}
   else{setRetry(payload);setError(l('uncertain'));}return;}
  setRetry(null);setAction(null);setRefreshOnly(outcome.state==='saved-refresh-failed');if(outcome.state==='saved'){try{sessionStorage.removeItem(receiptStorage);}catch{}}setNotice(l(outcome.state==='saved'?'saved':'refreshFailed'));
 }
 function submit(event:React.FormEvent){event.preventDefault();if(!action||pending||retry)return;const a=action;const r=a.row;const payload:RevenueRow={operation:a.operation,entity:data.entity,target:r.id??null,revision:r.revision??null,requestKey:crypto.randomUUID()};
  switch(a.operation){
   case 'candidate':Object.assign(payload,{command:a.command,reference:form.reference||undefined});break;
   case 'post':Object.assign(payload,{reference:form.reference});break;
   case 'evaluate':Object.assign(payload,{service:r.specified_service_id,binding:r.id,unit:form.unit});break;
   case 'correction':Object.assign(payload,{root:r.original_fact_id??r.id,revised:form.revised,kind:form.kind,intent:crypto.randomUUID(),reference:form.reference});break;
   case 'foundation':Object.assign(payload,{command:a.command,reference:form.reference||undefined});break;
   case 'approval':Object.assign(payload,{target:r.approval_reference,decision:form.decision||'APPROVED',reference:form.reference});break;
   case 'correctionRule':Object.assign(payload,{method:form.method,priorPeriod:form.priorPeriod==='true',reference:form.reference});break;
   case 'evidence':{let evidence:RevenueRow={reference:form.reference};if(a.command==='CREATE'){const selected=sourceOptions.find(x=>`${x.unit}:${x.id}`===form.source);if(!selected)return;const blankless=Object.fromEntries(Object.entries({coverage_from:form.coverage_from,coverage_to:form.coverage_to}).filter(([,v])=>v));evidence={specified_service_id:r.specified_service_id,binding_id:r.id,recognition_unit_key:selected.unit,source_id:selected.id,source_domain:selected.domain,evidence_type:selected.evidence_type,business_date:selected.business_date,verified_units:form.verified_units,...blankless};payload.target=crypto.randomUUID();payload.revision=null;}Object.assign(payload,{command:a.command,data:evidence});break;}
   case 'requirements':{const selected=sourceOptions.find(x=>text(x,'id')===form.source);if(!selected)return;const requirements={...(r.fulfillment_requirements as RevenueRow??{}),[form.unit]:{source_domain:selected.domain,source_ids:[selected.id],evidence_type:form.evidence_type||'DELIVERABLE',condition:selected.condition,date_basis:selected.domain==='CRM_ACTIVITY'?'OCCURRED_ON':'COMPLETED_ON'}};Object.assign(payload,{requirements});break;}
   case 'policy':Object.assign(payload,{target:crypto.randomUUID(),revision:null,data:Object.fromEntries(Object.entries({policy_key:form.policy_key,recognition_strategy:form.recognition_strategy,amount_strategy:form.amount_strategy,presentation:form.presentation,fulfillment_rule_reference:form.fulfillment_rule_reference,refund_correction_reference:form.refund_correction_reference,currency:form.currency,effective_from:form.effective_from,effective_to:form.effective_to}).filter(([,v])=>v))});break;
   case 'binding':{const predecessor=(data.bindings??[]).filter(x=>x.specified_service_id===form.service).sort((x,y)=>Number(y.version)-Number(x.version))[0];const policy=(data.policies??[]).find(x=>x.id===form.policy);Object.assign(payload,{target:crypto.randomUUID(),revision:null,data:{specified_service_id:form.service,policy_version_id:form.policy,predecessor_id:predecessor?.id,principal_agent_role:form.principal_agent_role,presentation:form.presentation,assessment_basis_reference:form.reference,assessment_sources:[form.reference],amount:form.amount,agent_fee:policy?.amount_strategy==='APPROVED_AGENT_FEE'?form.amount:undefined,allocation_decision_reference:form.allocation_decision_reference||undefined,has_variance:form.has_variance==='true',variance_review_reference:form.variance_review_reference||undefined,recognition_unit_schedule:schedule.map(u=>Object.fromEntries(Object.entries(u).filter(([,v])=>v)))}});break;}
   case 'cash':{const target=rows(r.targets).find(x=>`${x.service}:${x.receivable}`===form.target);Object.assign(payload,{target:r.payment,revision:null,command:a.command,data:{service_id:target?.service,receivable_id:target?.receivable,application_id:a.command==='REVERSE'?form.application:undefined,amount:form.amount,intent:crypto.randomUUID(),reference:form.reference}});break;}
  }
  void execute(payload);
 }
 const field=(name:string,type='text',required=true)=><label key={name}>{l(name)}<input name={name} type={type} required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})} maxLength={type==='text'?200:undefined}/></label>;
 const select=(name:string,options:{id:string;label:string}[],required=true)=><label key={name}>{l(name)}<select name={name} aria-label={l(name)} required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}><option value="">{l('unknown')}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>;
 const enumSelect=(name:string,options:string[])=>select(name,options.map(id=>({id,label:l(id)})));
 const table=(items:RevenueRow[],fields:string[],title:string,renderActions?:(r:RevenueRow)=>React.ReactNode)=><div className={styles.records}>{items.length===0?<p className="empty-state">{l('noRows')}</p>:items.map((r,i)=><article className={styles.record} key={text(r,'id')||i}><div className={styles.recordFields}>{fields.map(k=><div key={k}><span>{l(k)}</span><strong>{value(r[k])}</strong></div>)}</div><div className={styles.actions}><button type="button" className="secondary-button" onClick={()=>peek(r,title==='candidate'?[...candidateFields,'amount_basis_snapshot','evidence_references','source_fact_references','revised_entitlement_snapshot']:title==='services'?(r.policy_version_id||r.policy_key?bindingFields:serviceFields):title==='evidence'?evidenceFields:title==='history'?factFields:title==='configuration'?policyFields:Object.keys(r).filter(k=>!k.startsWith('can_')&&!['actions','source_options','workspace_id','targets'].includes(k)),title)}>{l('details')}</button>{renderActions?.(r)}</div></article>)}</div>;
 return <section className={styles.workspace}>
  <header className="page-heading-row"><div><p className="eyebrow">{l('title')}</p><WorkspaceHeading><UiIcon name="finance" size={24}/> {contractId?l('contracts'):l('title')}</WorkspaceHeading><p>{l('subtitle')}</p></div><div className={styles.actions}>{["ADMIN","SUPER_ADMIN"].includes(actor.role)&&<button className="primary-button" type="button" onClick={()=>setAdministration(true)}><UiIcon name="settings" size={16}/>{locale==="en"?"Revenue configuration":"收入配置"}</button>}<button className="secondary-button" type="button" onClick={refresh}>{l('refresh')}</button></div></header>{administration&&<RevenueAdministration onClose={()=>{setAdministration(false);refresh();}}/>}
  {error&&<div role="alert" className="inline-message error">{error}{error===l('aal')&&<Link href="/mfa-challenge" target="_blank" rel="noreferrer">{l('security')}</Link>}</div>}
  {notice&&<p role="status">{notice}</p>}
  {retry&&<button className="primary-button" type="button" disabled={pending} onClick={()=>void execute(retry)}>{l('retry')}</button>}
  {data.state!=='READY'?<section className={styles.emptyContext} role="status" data-state={data.state}><h2>{l(data.state)}</h2>{data.state==='NO_CONFIGURATION'&&<><p>{locale==='en'?'Revenue has not been configured for this workspace.':'本工作区尚未配置收入管理。'}</p><details><summary>{locale==='en'?'View configuration requirements':'查看配置要求'}</summary><ul>{(locale==='en'?['Reporting entity','Designated business authorities','Accounting periods','Approved policies']:['报告主体','指定业务授权','会计期间','已批准政策']).map(item=><li key={item}>{item}</li>)}</ul><p>{l('provisioning')}</p></details><p>{locale==='en'?'Administrators can start configuration using Revenue configuration above.':'管理员和超级管理员可通过上方“收入配置”入口开始配置。'}</p></>}</section>:<>
   <div className={styles.context}><strong>{text(data.profile??{},'legal_name')}</strong><span>{l(text(data.profile??{},'status'))}</span>{data.entities.length>1&&<select aria-label={l('reporting_entity_id')} value={data.entity} onChange={e=>void load({...filter,page:'1'},e.target.value).catch(()=>setError(l('failed')))}>{data.entities.map(e=><option key={text(e,'id')} value={text(e,'id')}>{text(e,'name')}</option>)}</select>}<span>{l('governance')}</span></div>
   {data.profile?.status!=='ACTIVE'&&<p role="status">{l('configurationInactive')}</p>}
   <div className={styles.summary}>{(data.recognized??[]).map(r=><div key={text(r,'currency')}><span>{l('recognized')} · {text(r,'currency')}</span><strong>{text(r,'amount')}</strong></div>)}{(data.candidate_totals??[]).map((r,i)=><div key={i}><span>{l('candidate')} · {l(text(r,'status'))} · {text(r,'currency')}</span><strong>{text(r,'amount')}</strong></div>)}</div>
   <nav className={styles.tabs} aria-label={l('title')}>{['queue','contracts','services','evidence','history','configuration',...(data.authorities?.includes('CASH_APPLICATION_MANAGER')?['cash']:[])].map(key=><button type="button" key={key} aria-current={tab===key?'page':undefined} onClick={()=>navigate(key)}>{l(key)}</button>)}</nav>
   <p className={styles.muted}>{l('pageScope')}</p>
   {tab==='queue'&&<><form className={styles.filters} onSubmit={e=>{e.preventDefault();navigate(tab,{...filter,page:'1'});}}><label>{l('search')}<input value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})}/></label><label>{l('status')}<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">{l('all')}</option>{['DRAFT','READY_FOR_REVIEW','APPROVED','STALE','REJECTED'].map(s=><option key={s} value={s}>{l(s)}</option>)}</select></label><label>{l('currency')}<select value={filter.currency} onChange={e=>setFilter({...filter,currency:e.target.value})}><option value="">{l('all')}</option>{(data.profile?.allowed_currencies as string[]??[]).map(c=><option key={c}>{c}</option>)}</select></label><button className="secondary-button">{l('search')}</button></form>
    {(data.queue??[]).length===0?<section className={styles.emptyContext} data-state="CONFIGURED_NO_CANDIDATES"><h2>{filter.q||filter.status||filter.currency?l('noMatches'):locale==='en'?'No recognition candidates yet':'尚无收入确认候选'}</h2><p>{locale==='en'?'Qualifying fulfillment evidence and an approved service binding are required before evaluation. Cash receipt does not create Revenue.':'评估前需要符合要求的履约证据及已批准的服务绑定。收款不会自动产生收入。'}</p></section>:table(data.queue??[],['contract_number','description_snapshot','recognition_unit_key','business_date','amount','currency','status','health'],'candidate',r=><>{r.reason&&<span>{l(text(r,'reason'))}</span>}{Array.isArray(r.actions)&&r.actions.map(command=>act({operation:command==='POST'?'post':'candidate',command,row:r,label:command}))}</>)}
    <div className={styles.actions}><button type="button" className="secondary-button" disabled={Number(filter.page)<=1} onClick={()=>navigate(tab,{...filter,page:String(Number(filter.page)-1)})}>{l('previous')}</button><span>{filter.page}</span><button type="button" className="secondary-button" disabled={(data.queue??[]).length<25} onClick={()=>navigate(tab,{...filter,page:String(Number(filter.page)+1)})}>{l('next')}</button></div></>}
   {tab==='contracts'&&<>{table(data.contracts??[],['contract_number','currency','contracted','receivable','collected','applied_cash','outstanding','refunded'],'contracts',r=><Link href={`/finance/revenue?contract=${r.contract_id}&tab=services`}>{l('services')}</Link>)}<h2>{l('commission')}</h2>{table(data.commissions??[],['contract_id','currency','amount'],'commission')}{table(data.services??[],serviceFields,'services')}</>}
   {tab==='services'&&<>{data.can_create_binding&&act({operation:'binding',row:{},label:'bindingCreate'})}{table(data.bindings??[],['description_snapshot','version','policy_key','principal_agent_role','presentation','status'],'services',r=><>{r.can_submit&&act({operation:'foundation',command:'BINDING_SUBMIT',row:r,label:'BINDING_SUBMIT'})}{r.can_review&&act({operation:'approval',row:r,label:'approval'})}{r.can_configure&&act({operation:'requirements',row:r,label:'requirements'})}{r.can_evaluate&&act({operation:'evaluate',row:r,label:'EVALUATE'})}{r.can_attest===true&&act({operation:'evidence',command:'CREATE',row:r,label:'CREATE'})}</>)}</>}
   {tab==='evidence'&&<><p>{l('noSourceDetail')}</p>{table(data.evidence??[],['source_domain','evidence_type','recognition_unit_key','business_date','verified_units','status','health'],'evidence',r=><>{typeof r.source_href==='string'&&<Link href={r.source_href}>{l('openSource')}</Link>}{r.can_submit&&act({operation:'evidence',command:'SUBMIT',row:r,label:'SUBMIT'})}{r.can_review&&<>{r.health==='CURRENT'&&act({operation:'evidence',command:'ACCEPT',row:r,label:'ACCEPT'})}{act({operation:'evidence',command:'REJECT',row:r,label:'REJECT'})}</>}{r.can_withdraw&&act({operation:'evidence',command:'WITHDRAW',row:r,label:'WITHDRAW'})}</>)}</>}
   {tab==='history'&&<><p>{l('immutable')}</p>{table(data.facts??[],['business_date','contract_number','fact_kind','amount','currency','stable_service_key','recognition_unit_key','posted_by'],'history',r=>data.can_prepare_correction&&act({operation:'correction',row:r,label:'correction'}))}<div className={styles.actions}><button type="button" className="secondary-button" disabled={Number(filter.page)<=1} onClick={()=>navigate(tab,{...filter,page:String(Number(filter.page)-1)})}>{l('previous')}</button><span>{filter.page}</span><button type="button" className="secondary-button" disabled={(data.facts??[]).length<100} onClick={()=>navigate(tab,{...filter,page:String(Number(filter.page)+1)})}>{l('next')}</button></div></>}
   {tab==='configuration'&&<><p>{l('provisioning')}</p>{basis(data.profile??{},['legal_name','accounting_framework','business_timezone','allowed_currencies','status','maker_checker_required'])}{table(data.designations??[],['user_id','authority','status','effective_from','effective_to'],'authority')}{table(data.periods??[],['period_key','start_on','end_on','status','closed_by','closed_at'],'period_key',r=>r.can_close===true&&act({operation:'foundation',command:'PERIOD_CLOSE',row:r,label:'PERIOD_CLOSE'}))}{data.can_create_policy&&act({operation:'policy',row:{},label:'policyCreate'})}{table(data.policies??[],['policy_key','version','recognition_strategy','amount_strategy','status','test_only'],'configuration',r=><>{r.can_submit&&<>{act({operation:'foundation',command:'POLICY_SUBMIT',row:r,label:'POLICY_SUBMIT'})}{act({operation:'correctionRule',row:r,label:'correctionRule'})}</>}{r.can_review&&act({operation:'approval',row:r,label:'approval'})}{data.can_create_policy&&act({operation:'policy',row:r,label:'policyCreate'})}</>)}</>}
   {tab==='cash'&&<><p>{l('cashBoundary')}</p>{table(data.cash??[],['payment','purpose','currency','amount','reserved','applied','available','refunded'],'cash',r=>r.can_manage===true&&<>{r.can_apply===true&&act({operation:'cash',command:'APPLY',row:r,label:'apply'})}{r.can_reverse===true&&act({operation:'cash',command:'REVERSE',row:r,label:'reverse'})}</>)}</>}
  </>}
  {detail&&<AccessibleDrawer title={l(detail.title)} onClose={()=>setDetail(null)}>{basis(detail.row,detail.fields)}</AccessibleDrawer>}
  {action&&<AccessibleDrawer title={l(action.label)} onClose={()=>setAction(null)} pending={pending}><form className={styles.form} onSubmit={submit}>
   {action.operation==='post'&&<p>{l('postNotice')}</p>}
   {['candidate','post'].includes(action.operation)&&basis(action.row,[...candidateFields,'amount_basis_snapshot','evidence_references','source_fact_references','revised_entitlement_snapshot'])}
   {action.operation==='approval'&&basis(action.row,action.row.policy_key&& !action.row.specified_service_id?policyFields:bindingFields)}
   {action.operation==='foundation'&&basis(action.row,action.command==='PERIOD_CLOSE'?['period_key','start_on','end_on','status']:action.command==='POLICY_SUBMIT'?policyFields:bindingFields)}
   {action.operation==='correction'&&<>{basis(action.row,factFields)}<p>{l('revisedPrerequisite')}</p>{enumSelect('kind',['ADJUSTMENT','REVERSAL','REPLACEMENT'])}{select('revised',(data.queue??[]).filter(c=>c.candidate_kind==='ORIGINAL'&&!c.fact_id&&c.status==='APPROVED'&&c.health==='CURRENT'&&c.contract_id===action.row.contract_id&&c.stable_service_key===action.row.stable_service_key&&c.recognition_unit_key===action.row.recognition_unit_key).map(c=>({id:text(c,'id'),label:`${c.currency} ${c.amount} · ${c.business_date} · ${c.id}`})))}</>}
   {action.operation==='evaluate'&&<>{basis(action.row,bindingFields)}{select('unit',rows(action.row.recognition_unit_schedule).map(u=>({id:text(u,'key'),label:text(u,'key')})))}</>}
   {action.operation==='evidence'&&(action.command==='CREATE'?<>{select('source',sourceOptions.map(s=>({id:`${s.unit}:${s.id}`,label:`${s.unit} · ${l(text(s,'domain'))} · ${s.business_date} · ${s.id}`})))}{field('verified_units')}{field('coverage_from','date',false)}{field('coverage_to','date',false)}</>:basis(action.row,evidenceFields))}
   {action.operation==='requirements'&&<>{basis(action.row,['description_snapshot','recognition_unit_schedule'])}{select('unit',rows(action.row.recognition_unit_schedule).map(u=>({id:text(u,'key'),label:text(u,'key')})))}{select('source',sourceOptions.map(s=>({id:text(s,'id'),label:`${l(text(s,'domain'))} · ${s.date??'—'} · ${l(text(s,'condition'))} · ${s.id}`})))}{enumSelect('evidence_type',['DELIVERABLE','COVERAGE','MILESTONE','SERVICE_DELIVERY'])}</>}
   {action.operation==='policy'&&<>{field('policy_key')}{enumSelect('recognition_strategy',['POINT_IN_TIME_ON_APPROVED_EVIDENCE','OVER_TIME_BY_VERIFIED_UNITS','OVER_TIME_BY_APPROVED_MILESTONES'])}{enumSelect('amount_strategy',['ACCEPTED_SERVICE_CONSIDERATION','APPROVED_AGENT_FEE','APPROVED_ALLOCATED_CONSIDERATION'])}{enumSelect('presentation',['GROSS','NET'])}{enumSelect('currency',data.profile?.allowed_currencies as string[]??[])}{field('fulfillment_rule_reference')}{field('refund_correction_reference')}{field('effective_from','date')}{field('effective_to','date',false)}</>}
   {action.operation==='binding'&&<>{select('service',(data.services??[]).map(s=>({id:text(s,'id'),label:`${s.contract_number} · ${s.description_snapshot} · ${s.currency} ${s.accepted_amount}`})))}{select('policy',(data.policies??[]).filter(p=>p.status==='APPROVED'&&!p.test_only).map(p=>({id:text(p,'id'),label:`${p.policy_key} v${p.version} · ${l(text(p,'amount_strategy'))}`})))}{enumSelect('principal_agent_role',['PRINCIPAL','AGENT'])}{enumSelect('presentation',['GROSS','NET'])}{field('amount')}{field('allocation_decision_reference','text',false)}{select('has_variance',[{id:'false',label:l('no')},{id:'true',label:l('yes')}])}{field('variance_review_reference','text',false)}<fieldset><legend>{l('recognition_unit_schedule')}</legend>{schedule.map((u,i)=><div className={styles.unit} key={i}>{(['key','units','from','to'] as const).map(k=><label key={k}>{l(k==='key'?'unit':k)}<input required={k==='key'||k==='units'} type={k==='from'||k==='to'?'date':'text'} value={u[k]} onChange={e=>setSchedule(schedule.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>)}</div>)}{schedule.length<24&&<button type="button" onClick={()=>setSchedule([...schedule,{key:'',units:'1',from:'',to:''}])}>{l('addUnit')}</button>}</fieldset></>}
   {action.operation==='correctionRule'&&<>{enumSelect('method',['BLOCKED','REVISED_ENTITLEMENT'])}{select('priorPeriod',[{id:'false',label:l('no')},{id:'true',label:l('yes')}])}</>}
   {action.operation==='approval'&&select('decision',[{id:'APPROVED',label:l('APPROVED')},{id:'REJECTED',label:l('REJECTED')}])}
   {action.operation==='cash'&&<>{basis(action.row,['payment','purpose','currency','amount','reserved','applied','available','refunded'])}{action.command==='APPLY'?select('target',rows(action.row.targets).map(t=>({id:`${t.service}:${t.receivable}`,label:`${t.receivable} · ${t.currency} · ${l('outstanding')} ${t.outstanding}`}))):select('application',rows(action.row.reversible_applications).filter(h=>h.available_to_release!=='0.00').map(h=>({id:text(h,'id'),label:`${h.id} · ${h.currency} ${h.available_to_release}`})))}{field('amount')}<p>{l('cashBoundary')}</p></>}
   {!['evaluate','policy','requirements'].includes(action.operation)&&!(action.operation==='evidence'&&action.command==='CREATE')&&field('reference','text',!['SUBMIT','REVALIDATE','POLICY_SUBMIT','BINDING_SUBMIT'].includes(action.command??''))}
   {error&&<p role="alert">{error}</p>}{retry?<button type="button" className="primary-button" disabled={pending} onClick={()=>void execute(retry)}>{l('retry')}</button>:<button type="submit" className="primary-button" disabled={pending}>{pending?l('saving'):l(action.operation==='post'?'postConfirm':'confirm')}</button>}
  </form></AccessibleDrawer>}
 </section>;
}
