"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {apiFetch} from '@/lib/api-client';
import {useReceiptMutation} from '@/hooks/use-receipt-mutation';
import {useI18n} from './i18n-provider';
import {AccessibleDrawer,InlineMessage} from './ui';
const frameworks=[
 {value:'CAS',zh:'中国企业会计准则',en:'China Accounting Standards for Business Enterprises'},
 {value:'CASSBE',zh:'中国小企业会计准则',en:'China Accounting Standards for Small Business Enterprises'},
 {value:'IFRS',zh:'国际财务报告准则（IFRS）',en:'International Financial Reporting Standards (IFRS)'},
 {value:'US_GAAP',zh:'美国公认会计原则（US GAAP）',en:'US Generally Accepted Accounting Principles (US GAAP)'},
 {value:'OTHER',zh:'其他已确定的会计准则',en:'Other established accounting framework'},
] as const;
const referenceFields=[
 {key:'cutoff_reference',zh:'收入归属与关账依据',en:'Revenue cutoff & closing reference',helpZh:'填写确定收入归属业务日期、会计期间及关账流程的制度名称、版本和章节。业务时区采用工作区设置。',helpEn:'Identify the policy, version and section defining revenue business dates, accounting periods and closing procedures. The workspace timezone applies.',exampleZh:'例：《收入截止与关账制度》v1.0，第 3 节',exampleEn:'Example: Revenue cutoff and closing policy v1.0, section 3'},
 {key:'correction_reference',zh:'收入更正处理依据',en:'Revenue correction reference',helpZh:'填写规定差错、退费或合同变更后如何审核收入更正的制度或审批记录，注明版本／编号。退费本身不会自动冲减收入。',helpEn:'Identify the policy or approval record for reviewing revenue corrections after errors, refunds or contract changes, including version/reference. Refunds do not automatically reverse revenue.',exampleZh:'例：《收入差错与更正流程》v1.0，第 2 节',exampleEn:'Example: Revenue correction procedure v1.0, section 2'},
 {key:'retention_reference',zh:'记录保留制度依据',en:'Record retention reference',helpZh:'填写规定收入证据、审批与过账记录保留期限及处置责任的制度名称、版本和章节。这里填写制度引用，不是直接输入保留天数。',helpEn:'Identify the policy, version and section specifying retention periods and responsibilities for evidence, approvals and posting records. Enter a policy reference, not a number of days.',exampleZh:'例：《财务记录保留制度》v1.0，第 4 节',exampleEn:'Example: Financial record retention policy v1.0, section 4'},
 {key:'authority_reference',zh:'负责人及审批人授权依据',en:'Owner and approver appointment reference',helpZh:'填写任命下方政策负责人和独立审批人的授权记录编号、决议或审批单引用。管理员身份不替代这项业务授权。',helpEn:'Identify the appointment record, resolution or approval assigning the policy owner and independent approver below. An administrator role does not replace this business authorization.',exampleZh:'例：财务授权审批单 AUTH-001，政策负责人及审批人任命',exampleEn:'Example: Authorization AUTH-001, policy owner and approver appointment'},
] as const;
type Profile={reporting_entity_id:string;legal_name:string;status:string;revision:number;can_submit?:boolean;can_approve?:boolean;accounting_framework:string;business_timezone:string;allowed_currencies:string[]};
type Configuration={timezone:string;profiles:Profile[];periods:{id:string;period_key:string;start_on:string;end_on:string;status:string}[];administrators:{id:string;name:string}[]};
export function RevenueAdministration({onClose}:{onClose:()=>void}){
 const {locale,t}=useI18n(),en=locale==='en',[snapshot,setSnapshot]=useState<Configuration|null>(null),[error,setError]=useState(false),[accepted,setAccepted]=useState(false),[entity]=useState(()=>crypto.randomUUID());
 const [framework,setFramework]=useState('');
 const mutation=useReceiptMutation('/api/revenue/configuration','error.invalidInput');
 const load=async()=>{setError(false);try{setSnapshot(await apiFetch<Configuration>('/api/revenue/configuration'));setAccepted(false);}catch{setError(true);}};
 useEffect(()=>{void apiFetch<Configuration>('/api/revenue/configuration').then(setSnapshot).catch(()=>setError(true));},[]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(accepted){await load();return;}const f=new FormData(e.currentTarget),value=(key:string)=>String(f.get(key)??'');const hasProfile=!!snapshot?.profiles.length;
 const payload=hasProfile?{command:'PERIOD_CREATE',entity:value('entity'),data:{period_key:value('period_key'),start_on:value('start_on'),end_on:value('end_on')}}:{command:'PROFILE_CREATE',entity,data:{owner:value('owner'),approver:value('approver'),profile:{...Object.fromEntries(['legal_name','cutoff_reference','correction_reference','retention_reference','authority_reference'].map(k=>[k,value(k)])),accounting_framework:framework==='OTHER'?`OTHER: ${value('accounting_framework_other').trim()}`:framework,business_timezone:snapshot?.timezone,allowed_currencies:value('currency').split(',').map(v=>v.trim().toUpperCase()).filter(Boolean)}}};
 if(await mutation.send(payload)){setAccepted(true);await load();}};
 const input=(key:string,zh:string,english:string,type='text')=><label className="field" key={key}><span>{en?english:zh}</span><input name={key} type={type} maxLength={200} required/></label>;
 return <AccessibleDrawer title={en?'Revenue configuration':'收入配置'} pending={mutation.pending||mutation.uncertain} onClose={onClose}>
 <p>{en?'Administrators configure the reporting entity and accounting periods. Activation, policy review and posting still require designated authorities and independent review.':'管理员可以配置报告主体与会计期间。启用、政策审批和收入过账仍需指定业务职权及独立审核。'}</p>
 {error&&<InlineMessage type="error">{accepted?t('audit.savedRefreshFailed'):(en?'Revenue configuration could not be loaded.':'收入配置加载失败。')}<button className="secondary-button" onClick={()=>void load()}>{t('common.retry')}</button></InlineMessage>}
 {snapshot&&<><div className="revenue-admin-profiles">{snapshot.profiles.map(p=><article key={p.reporting_entity_id}><strong>{p.legal_name}</strong><span> · {p.status==='DRAFT'?(en?'Draft':'草稿'):p.status==='ACTIVE'?(en?'Active':'已启用'):(en?'Review / retired':'审核中／已停用')}</span><p>{frameworks.find(f=>f.value===p.accounting_framework)?.[en?'en':'zh']??p.accounting_framework} · {p.business_timezone} · {p.allowed_currencies.join(", ")}</p>{(p.can_submit||p.can_approve)&&<ProfileReview profile={p} onSaved={load}/>}</article>)}</div>
 <form onSubmit={submit}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain||accepted}><h3>{snapshot.profiles.length?(en?'Add accounting period':'添加会计期间'):(en?'Configure reporting entity':'配置报告主体')}</h3><div className="form-grid two-column">
 {snapshot.profiles.length?<><label className="field"><span>{en?'Reporting entity':'报告主体'}</span><select name="entity">{snapshot.profiles.map(p=><option value={p.reporting_entity_id} key={p.reporting_entity_id}>{p.legal_name}</option>)}</select></label>{input('period_key','期间名称','Period key')}{input('start_on','开始日期','Start date','date')}{input('end_on','结束日期','End date','date')}</>:<>{input('legal_name','报告主体名称','Reporting entity name')}<label className="field"><span>{en?'Accounting framework':'会计准则'}</span><select name="accounting_framework" required value={framework} onChange={e=>setFramework(e.target.value)} aria-describedby="revenue-framework-help"><option value="">{en?'Select the framework adopted by this entity':'请选择该主体实际采用的准则'}</option>{frameworks.map(f=><option key={f.value} value={f.value}>{en?f.en:f.zh}</option>)}</select><small id="revenue-framework-help" className="field-help">{en?'Confirm the applicable framework with your finance owner. This records the reporting basis; selecting it does not generate revenue policies.':'请与财务负责人确认本主体实际采用的准则。此处记录报告基础，选择后不会自动生成收入政策。'}</small></label>{framework==='OTHER'&&<label className="field"><span>{en?'Framework name and edition':'准则全称及版本'}</span><input name="accounting_framework_other" required maxLength={190} placeholder={en?'Enter the adopted framework and edition':'填写实际采用的准则名称与版本'}/></label>}{input('currency','允许币种（逗号分隔，如 CNY,USD）','Allowed currencies (e.g. CNY,USD)')}<div className="revenue-reference-guidance"><h4>{en?'Policy and authorization references':'制度与授权依据'}</h4><p>{en?'Enter traceable document names, versions, approval IDs or internal document links (up to 200 characters). The examples are format guidance only; use your own established records. If a policy or appointment has not been established, arrange it before submitting configuration for approval.':'填写可追溯的制度名称、版本、审批编号或内部文档链接（每项最多 200 字）。示例仅说明填写格式，请替换为本单位真实依据。尚未制定制度或完成任命时，请先补齐，再提交配置审核。'}</p><p>{en?'These references provide review context. They do not automatically set closing dates, correction amounts or deletion schedules.':'这些引用供审核与追溯使用，不会自动设置关账日期、更正金额或删除计划。'}</p></div>{referenceFields.map(f=><label className="field revenue-reference-field" key={f.key}><span>{en?f.en:f.zh}</span><textarea name={f.key} required maxLength={200} rows={2} placeholder={en?f.exampleEn:f.exampleZh} aria-describedby={`revenue-help-${f.key}`}/><small id={`revenue-help-${f.key}`} className="field-help">{en?f.helpEn:f.helpZh}</small></label>)}{(['owner','approver'] as const).map(key=><label className="field" key={key}><span>{key==='owner'?(en?'Policy owner':'政策负责人'):(en?'Independent policy approver':'独立政策审批人')}</span><select name={key} required defaultValue=""><option value="">{en?'Select administrator':'选择管理员'}</option>{snapshot.administrators.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}<p>{en?'Business timezone':'业务时区'}: {snapshot.timezone}</p></>}
 </div></fieldset>{mutation.error&&<InlineMessage type="error">{mutation.error}<Link href="/mfa-challenge" target="_blank">{en?'Verify identity':'验证身份'}</Link></InlineMessage>}
 <div className="drawer-actions"><button className="primary-button" disabled={mutation.pending}>{t(accepted?'ux.management.refresh':mutation.uncertain?'enrollments.retry':'common.save')}</button></div></form>
 {snapshot.periods.length>0&&<section><h3>{en?'Accounting periods':'会计期间'}</h3>{snapshot.periods.map(p=><p key={p.id}>{p.period_key} · {p.start_on} — {p.end_on} · {p.status==='OPEN'?(en?'Open':'开放'):(en?'Closed':'已关闭')}</p>)}</section>}</>}
 </AccessibleDrawer>;
}

function ProfileReview({profile,onSaved}:{profile:Profile;onSaved:()=>Promise<void>}){
 const {locale,t}=useI18n(),en=locale==='en',mutation=useReceiptMutation('/api/revenue/configuration','error.invalidInput'),[accepted,setAccepted]=useState(false);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!accepted){const reference=String(new FormData(e.currentTarget).get('reference')??'');if(!await mutation.send({command:profile.can_submit?'PROFILE_SUBMIT':'PROFILE_APPROVE',entity:profile.reporting_entity_id,data:{revision:profile.revision,reference}}))return;setAccepted(true);}await onSaved();};
 return <form onSubmit={submit}><fieldset disabled={mutation.pending||mutation.uncertain||accepted}><label className="field"><span>{en?'Review reference':'审核依据'}</span><input name="reference" required maxLength={200}/></label></fieldset>{mutation.error&&<InlineMessage type="error">{mutation.error}</InlineMessage>}<button className="secondary-button" disabled={mutation.pending}>{accepted?t('ux.management.refresh'):mutation.uncertain?t('enrollments.retry'):profile.can_submit?(en?'Submit configuration for review':'提交配置审核'):(en?'Approve and activate configuration':'批准并启用配置')}</button></form>;
}
