"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { BadgeDollarSign, ChartNoAxesCombined, Goal, HeartHandshake, Megaphone, MessageCircle, Phone, RefreshCcw, TrendingUp, Utensils, X } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import { EmptyState } from "@/components/data-state";
import { InlineMessage, ProgressBar, SearchableSelect, StatusBadge, Toast } from "@/components/ui";
import type { RelationshipAccount, RelationshipScores, SalesPerformanceData } from "@/lib/sales-repository";
import { roleMessageKey, type AppRole } from "@/lib/roles";

const goalDefinitions=[
  {key:"contact" as const,icon:Phone,tone:"blue",title:"sales.relationship.contact",help:"sales.relationship.contactHelp",milestone:"CONTACT"},
  {key:"meal" as const,icon:Utensils,tone:"green",title:"sales.relationship.meal",help:"sales.relationship.mealHelp",milestone:"MEAL"},
  {key:"family" as const,icon:MessageCircle,tone:"purple",title:"sales.relationship.family",help:"sales.relationship.familyHelp",milestone:"FAMILY_CHAT"},
  {key:"advocacy" as const,icon:Megaphone,tone:"amber",title:"sales.relationship.advocacy",help:"sales.relationship.advocacyHelp",milestone:"ADVOCACY"},
] as const;
const relationshipPlaybook=[{stage:"contact",icon:Phone,tone:"blue",suggestions:["verifyChannel","shareValue","askPreference","setNextStep"]},{stage:"meal",icon:Utensils,tone:"green",suggestions:["inviteMeal","chooseContext","listenMore","followUp"]},{stage:"family",icon:MessageCircle,tone:"purple",suggestions:["startEveryday","rememberBoundaries","connectNeeds","respectPrivacy"]},{stage:"advocacy",icon:Megaphone,tone:"amber",suggestions:["confirmValue","offerMaterial","makeEasy","askPermission"]}] as const;
const closingPlaybook=[{stage:"discovery",suggestions:["clarifyNeed","mapDecision","confirmBudget","agreeNext"]},{stage:"evaluation",suggestions:["tailorProposal","showEvidence","compareOptions","reviewTogether"]},{stage:"hesitation",suggestions:["surfaceConcern","reduceRisk","bringDecisionMaker","setDecisionDate"]},{stage:"payment",suggestions:["confirmTerms","simplifyPayment","sendChecklist","confirmKickoff"]}] as const;

export function SalesPerformancePage({initialData,persistent=true}:{initialData:SalesPerformanceData;persistent?:boolean}){
  const {locale,t}=useI18n();const [data,setData]=useState(initialData);const [period,setPeriod]=useState<SalesPerformanceData["period"]>(initialData.period);const [team,setTeam]=useState("all");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [toast,setToast]=useState("");const [targetDialog,setTargetDialog]=useState(false);const [milestoneAccount,setMilestoneAccount]=useState<RelationshipAccount|null>(null);const [milestoneKey,setMilestoneKey]=useState<(typeof goalDefinitions)[number]["key"]>("contact");const closeRef=useRef<HTMLButtonElement>(null);
  const money=(value:number)=>new Intl.NumberFormat(locale==="zh-CN"?"zh-CN":"en-US",{style:"currency",currency:data.currency,maximumFractionDigits:0,notation:Math.abs(value)>=1_000_000?"compact":"standard"}).format(value);
  const dateLabel=(value:string)=>new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));
  const reload=async(nextPeriod=period,nextTeam=team)=>{if(!persistent)return;setLoading(true);setError("");try{const response=await fetch(`/api/sales/performance?period=${nextPeriod}&team=${encodeURIComponent(nextTeam)}`);const result=await response.json() as {data?:SalesPerformanceData};if(!response.ok||!result.data)throw new Error();setData(result.data);}catch{setError(t("sales.loadFailed"));}finally{setLoading(false);}};
  useEffect(()=>{if(!targetDialog&&!milestoneAccount)return;closeRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){setTargetDialog(false);setMilestoneAccount(null);}};document.body.style.overflow="hidden";window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKey);};},[milestoneAccount,targetDialog]);
  const attainment=data.target?Math.round(data.actual/data.target*100):0;const forecastAttainment=data.target?Math.round(data.forecast/data.target*100):0;const maxTrend=Math.max(1,...data.trends.flatMap(item=>[item.target,item.actual]));
  const summaryApproval=async()=>{setError("");const response=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"PERFORMANCE_SUMMARY",objectType:"PERFORMANCE_SUMMARY",objectId:`${data.periodStart}_${period}_${team}`,reason:t("approval.reason.summary")})});if(response.ok)setToast(t("flow.approvalRequested"));else setError(t("flow.approvalFailed"));};
  const saveTargets=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const scores={contact:Number(form.get("contact")),meal:Number(form.get("meal")),family:Number(form.get("family")),advocacy:Number(form.get("advocacy"))};const response=await fetch("/api/sales/relationship",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"targets",periodStart:data.periodStart,periodEnd:data.periodEnd,...scores})});if(!response.ok){setError(t("sales.relationshipSaveFailed"));return;}setData(current=>({...current,relationshipTargets:scores}));setTargetDialog(false);setToast(t("sales.relationshipUpdated"));};
  const saveMilestone=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!milestoneAccount)return;const evidence=String(new FormData(event.currentTarget).get("evidence")??"");const definition=goalDefinitions.find(item=>item.key===milestoneKey)!;const response=await fetch("/api/sales/relationship",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"milestone",organizationId:milestoneAccount.id,milestone:definition.milestone,evidence})});if(!response.ok){setError(t("sales.milestoneSaveFailed"));return;}setData(current=>({...current,relationshipAccounts:current.relationshipAccounts.map(item=>item.id===milestoneAccount.id?{...item,[milestoneKey]:true}:item),relationshipActual:recalculateScores(current.relationshipAccounts.map(item=>item.id===milestoneAccount.id?{...item,[milestoneKey]:true}:item))}));setMilestoneAccount(null);setToast(t("sales.milestoneSaved"));};
  const teamOptions=useMemo(()=>[{value:"all",label:t("sales.team.all")},...data.teams.map(value=>({value,label:value,detail:t("sales.teamLabel")}))],[data.teams,t]);
  const changePeriod=(value:SalesPerformanceData["period"])=>{setPeriod(value);void reload(value,team);};
  const changeTeam=(value:string)=>{setTeam(value);void reload(period,value);};
  return <div className="page-stack sales-performance-page">
    <section className="page-heading-row"><div><p className="eyebrow">{t("sales.eyebrow")}</p><h1>{t("sales.title")}</h1><p>{t("sales.description")}</p></div><div className="page-actions"><Link className="secondary-button" href="/sales/allocation">{t("nav.allocation")}</Link><button className="secondary-button" type="button" onClick={summaryApproval}>{t("flow.requestSummaryApproval")}</button><button className="primary-button" type="button" onClick={()=>setTargetDialog(true)}><Goal size={17}/>{t("sales.manageRelationship")}</button></div></section>
    {error&&<InlineMessage type="error">{error}</InlineMessage>}
    <section className="sales-filterbar surface"><div className="period-switch" aria-label={t("sales.analysisPeriod")}>{(["month","quarter","year"] as const).map(value=><button type="button" className={period===value?"active":""} onClick={()=>changePeriod(value)} key={value}>{t(`sales.period.${value}`)}</button>)}</div><SearchableSelect label={t("sales.teamScope")} options={teamOptions} value={team} onChange={changeTeam}/><span>{dateLabel(data.periodStart)} – {dateLabel(data.periodEnd)}</span><button className="icon-button" type="button" aria-label={t("common.retry")} disabled={loading} onClick={()=>reload()}><RefreshCcw className={loading?"spin":""} size={16}/></button></section>
    <section className="sales-kpi-grid"><SalesKpi icon={Goal} tone="green" label={t("sales.target")} value={money(data.target)} detail={t("sales.periodScope")}/><SalesKpi icon={BadgeDollarSign} tone="blue" label={t("sales.actualPerformance")} value={money(data.actual)} detail={t("sales.attainment",{value:attainment})}/><SalesKpi icon={TrendingUp} tone="purple" label={t("sales.forecast")} value={money(data.forecast)} detail={t("sales.forecastAttainment",{value:forecastAttainment})}/><SalesKpi icon={ChartNoAxesCombined} tone={data.forecast>=data.target?"green":"amber"} label={t("sales.forecastGap")} value={money(data.forecast-data.target)} detail={t(data.forecast>=data.target?"sales.exceedTarget":"sales.needPipeline")}/></section>
    <section className="sales-main-grid"><article className="surface sales-trend-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.targetActual")}</p><h2>{t("sales.targetTrend")}</h2></div></div>{data.trends.length?<div className="sales-bar-chart" role="img" aria-label={t("sales.trendChart")}>{data.trends.map(item=><div className="sales-bar-group" key={item.date}><div><span className="target" style={{height:`${Math.max(3,item.target/maxTrend*100)}%`}} title={`${t("sales.target")} ${money(item.target)}`}/><span className="actual" style={{height:`${Math.max(item.actual?3:0,item.actual/maxTrend*100)}%`}} title={`${t("sales.actual")} ${money(item.actual)}`}/></div><b>{new Intl.DateTimeFormat(locale==="zh-CN"?"zh-CN":"en",{month:"short",timeZone:"UTC"}).format(new Date(`${item.date}T00:00:00Z`))}</b><small>{money(item.actual)}</small></div>)}</div>:<EmptyState messageKey="sales.noTrend"/>}</article><article className="surface funnel-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.conversionFunnel")}</p><h2>{t("sales.funnel")}</h2></div></div>{data.funnel.length?<div className="sales-funnel">{data.funnel.map((stage,index)=><div key={stage.stage}><span style={{width:`${Math.max(32,100-index*12)}%`}}><b>{t(`sales.stage.${stage.stage.toLowerCase()}`)}</b><small>{t("sales.funnelItems",{count:stage.count})} · {money(stage.amount)}</small></span><em>{money(stage.weighted)}</em></div>)}</div>:<EmptyState messageKey="sales.noPipeline"/>}</article></section>
    <section className="surface team-performance-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.teamContribution")}</p><h2>{t("sales.teamProgress")}</h2></div><StatusBadge tone="blue">{t("sales.memberCount",{count:data.members.length})}</StatusBadge></div>{data.members.length?<><div className="sales-team-head"><span>{t("sales.member")}</span><span>{t("sales.targetActual")}</span><span>{t("sales.attainmentLabel")}</span><span>{t("sales.forecast")}</span><span>{t("sales.opportunities")}</span></div>{data.members.map(member=>{const percent=member.target?Math.round(member.actual/member.target*100):0;return <div className="sales-member-row" key={member.id}><div><span className="record-avatar">{member.nameEn.split(/\s+/).map(part=>part[0]).join("").slice(0,2)}</span><span><b>{member.nameZh} / {member.nameEn}</b><small>{member.team} · {t(roleMessageKey[member.role as AppRole]??"roles.salesSpecialist")}</small></span></div><span><b>{money(member.actual)}</b><small>{t("sales.targetValue",{value:money(member.target)})}</small></span><ProgressBar value={percent} label={`${percent}%`}/><span><b>{money(member.forecast)}</b><small>{t("sales.weightedForecast")}</small></span><span><b>{member.opportunities}</b><small>{t("sales.openDeals")}</small></span></div>;})}</>:<EmptyState messageKey="sales.noMembers"/>}</section>
    <section className="surface relationship-goals-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.relationshipGoals")}</p><h2>{t("sales.relationshipTitle")}</h2><p>{t("sales.relationshipDescription")}</p></div></div><div className="relationship-goal-grid">{goalDefinitions.map(({key,icon:Icon,tone,title,help},index)=>{const actual=data.relationshipActual[key],target=data.relationshipTargets[key];return <article key={key}><span className={tone}><Icon size={19}/></span><div><small>{t("sales.relationshipLevel",{level:index+1})}</small><b>{t(title)}</b><p>{t(help)}</p></div><strong>{actual}% <small>/ {target}%</small></strong><ProgressBar value={actual} label={actual>=target?t("sales.achieved"):t("sales.pointsGap",{value:target-actual})}/></article>;})}</div><InlineMessage type="warning">{t("sales.relationship.privacy")}</InlineMessage><div className="relationship-matrix-wrap"><div className="relationship-matrix-head"><span>{t("sales.keyAccounts")}</span><span>{t("common.owner")}</span>{goalDefinitions.map(item=><span key={item.key}>{t(`sales.matrix.${item.key}`)}</span>)}</div>{data.relationshipAccounts.map(account=><div className="relationship-matrix-row" key={account.id}><b>{locale==="zh-CN"?account.name_zh:account.name_en}</b><span>{account.owner_zh&&account.owner_en?`${account.owner_zh} / ${account.owner_en}`:"—"}</span>{goalDefinitions.map(item=><button type="button" className={account[item.key]?"achieved":"pending"} disabled={account[item.key]} onClick={()=>{setMilestoneAccount(account);setMilestoneKey(item.key);setError("");}} key={item.key}>{t(account[item.key]?"sales.achieved":"sales.recordMilestone")}</button>)}</div>)}</div></section>
    <section className="surface sales-playbook-card"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.relationshipPlaybook")}</p><h2>{t("sales.relationshipPlaybook.title")}</h2><p>{t("sales.relationshipPlaybook.description")}</p></div><HeartHandshake size={20}/></div><div className="sales-playbook-grid">{relationshipPlaybook.map(({stage,icon:Icon,tone,suggestions},index)=><article key={stage}><span className={tone}><Icon size={18}/></span><div><small>{t("sales.relationshipLevel",{level:index+1})}</small><h3>{t(`sales.relationship.${stage}`)}</h3><ol>{suggestions.map(item=><li key={item}>{t(`sales.relationshipPlaybook.${stage}.${item}`)}</li>)}</ol></div></article>)}</div></section>
    <section className="surface sales-playbook-card closing"><div className="surface-heading"><div><p className="eyebrow">{t("eyebrow.closingPlaybook")}</p><h2>{t("sales.closingPlaybook.title")}</h2><p>{t("sales.closingPlaybook.description")}</p></div><BadgeDollarSign size={20}/></div><div className="sales-playbook-grid">{closingPlaybook.map(({stage,suggestions},index)=><article key={stage}><span className={`stage-${index+1}`}><BadgeDollarSign size={18}/></span><div><small>{t("sales.closingStage",{stage:index+1})}</small><h3>{t(`sales.closingPlaybook.${stage}.title`)}</h3><ol>{suggestions.map(item=><li key={item}>{t(`sales.closingPlaybook.${stage}.${item}`)}</li>)}</ol></div></article>)}</div><InlineMessage type="warning">{t("sales.closingPlaybook.ethics")}</InlineMessage></section>
    {targetDialog&&<DialogShell closeRef={closeRef} title={t("sales.relationshipDialog")} description={t("sales.relationshipDialogHelp")} close={()=>setTargetDialog(false)}><form onSubmit={saveTargets}>{goalDefinitions.map(item=><label className="field" key={item.key}><span>{t("sales.relationshipCoverage",{name:t(item.title)})}</span><input name={item.key} type="number" min="0" max="100" defaultValue={data.relationshipTargets[item.key]} required/></label>)}{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setTargetDialog(false)}>{t("common.cancel")}</button><button className="primary-button" type="submit">{t("sales.saveRelationship")}</button></div></form></DialogShell>}
    {milestoneAccount&&<DialogShell closeRef={closeRef} title={t("sales.recordMilestoneTitle")} description={locale==="zh-CN"?milestoneAccount.name_zh:milestoneAccount.name_en} close={()=>setMilestoneAccount(null)}><form onSubmit={saveMilestone}><label className="field"><span>{t("sales.milestoneEvidence")}</span><textarea name="evidence" rows={4} minLength={3} maxLength={500} required placeholder={t("sales.milestoneEvidenceHelp")}/></label>{error&&<InlineMessage type="error">{error}</InlineMessage>}<div className="drawer-actions"><button className="secondary-button" type="button" onClick={()=>setMilestoneAccount(null)}>{t("common.cancel")}</button><button className="primary-button" type="submit">{t("common.save")}</button></div></form></DialogShell>}
    {toast&&<Toast message={toast} onClose={()=>setToast("")}/>}
  </div>;
}

function recalculateScores(accounts:RelationshipAccount[]):RelationshipScores{const total=accounts.length||1;return{contact:Math.round(accounts.filter(item=>item.contact).length/total*100),meal:Math.round(accounts.filter(item=>item.meal).length/total*100),family:Math.round(accounts.filter(item=>item.family).length/total*100),advocacy:Math.round(accounts.filter(item=>item.advocacy).length/total*100)};}
function SalesKpi({icon:Icon,tone,label,value,detail}:{icon:React.ElementType;tone:string;label:string;value:string;detail:string}){return <article className="surface"><span className={tone}><Icon size={19}/></span><div><small>{label}</small><b>{value}</b><p>{detail}</p></div></article>;}
function DialogShell({closeRef,title,description,close,children}:{closeRef:React.RefObject<HTMLButtonElement|null>;title:string;description:string;close:()=>void;children:React.ReactNode}){const {t}=useI18n();return <><button className="drawer-overlay" type="button" aria-label={t("common.close")} onClick={close}/><aside className="record-drawer" role="dialog" aria-modal="true" aria-label={title}><div className="drawer-heading"><div><p className="eyebrow">{t("eyebrow.relationshipTargets")}</p><h2>{title}</h2><p>{description}</p></div><button ref={closeRef} className="icon-button" type="button" aria-label={t("common.close")} onClick={close}><X size={20}/></button></div>{children}</aside></>;}
