"use client";
/* eslint-disable @next/next/no-img-element -- private avatar and MFA QR images are served by authenticated endpoints. */

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { BellRing, Camera, Check, ChevronRight, Eye, KeyRound, Languages, Laptop, LockKeyhole, Mail, MonitorSmartphone, Save, ShieldCheck, UserRound } from "lucide-react";
import { InlineMessage, SearchableSelect, StatusBadge, Toast } from "@/components/ui";
import { useAppUser } from "@/components/app-user-context";
import type { AppUser } from "@/lib/user";
import type { Locale } from "@/lib/i18n";
import type { NotificationPreferences, UserSettings } from "@/lib/settings-repository";
import { roleMessageKey } from "@/lib/roles";
import { useI18n } from "./i18n-provider";

const tabs = [
  { href: "/settings/profile", key: "settings.profile", icon: UserRound }, { href: "/settings/account", key: "settings.accountLanguage", icon: Languages },
  { href: "/settings/notifications", key: "settings.notifications", icon: BellRing }, { href: "/settings/security", key: "settings.security", icon: ShieldCheck }, { href: "/settings/privacy", key: "settings.privacy", icon: Eye },
];

const defaultNotifications: NotificationPreferences = { tasks: { email: true, inApp: true }, relationship: { email: true, inApp: true }, sales: { email: false, inApp: true }, security: { email: true, inApp: true }, ai: { email: false, inApp: true } };
function fallbackSettings(user: AppUser): UserSettings { return { username: user.username, displayNameZh: user.displayNameZh, displayNameEn: user.displayName, honorific: "", bio: "", avatarPath: null, locale: "zh-CN", timezone: "Asia/Taipei", dateFormat: "yyyy-MM-dd", quietHoursStart: null, quietHoursEnd: null, notifications: defaultNotifications }; }

export function SettingsPage({ section }: { section: string }) {
  const { t } = useI18n(); const pathname = usePathname(); const user = useAppUser();
  const [settings, setSettings] = useState(() => fallbackSettings(user)); const [email, setEmail] = useState(user.email); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [toast, setToast] = useState("");
  useEffect(() => { let active = true; fetch("/api/settings").then(async (response) => { const result = await response.json() as { settings?: UserSettings; email?: string }; if (!response.ok || !result.settings) throw new Error(); if (active) { setSettings(result.settings); setEmail(result.email ?? user.email); } }).catch(() => active && setLoadError(t("settings.loadFailed"))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [t, user.email]);
  const persist = async (body: unknown, successKey: string) => { const response = await fetch("/api/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); setToast(t(successKey)); };
  return <div className="page-stack settings-page"><section className="page-heading-row"><div><p className="eyebrow">{t("eyebrow.personalSettings")}</p><h1>{t("settings.title")}</h1><p>{t("settings.description")}</p></div><StatusBadge tone="green">{t("settings.accountNormal")}</StatusBadge></section><div className="settings-layout"><aside className="settings-nav">{tabs.map(({ href, key, icon: Icon }) => <Link key={href} className={pathname === href ? "active" : ""} href={href}><Icon size={17} /><span>{t(key)}</span><ChevronRight size={14} /></Link>)}<div className="settings-role-note"><LockKeyhole size={17} /><div><b>{t("settings.protected")}</b><p>{t("settings.protectedHelp")}</p></div></div></aside><section className="settings-content">{loading && <InlineMessage type="warning">{t("settings.loading")}</InlineMessage>}{loadError && <InlineMessage type="error">{loadError}</InlineMessage>}{section === "profile" && <ProfileSettings user={user} settings={settings} setSettings={setSettings} persist={persist} />}{section === "account" && <AccountSettings user={user} email={email} settings={settings} setSettings={setSettings} setEmail={setEmail} persist={persist} />}{section === "notifications" && <NotificationSettings settings={settings} setSettings={setSettings} persist={persist} />}{section === "security" && <SecuritySettings />}{section === "privacy" && <PrivacySettings />}</section></div>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}

const settingsEyebrowKeys: Record<string, string> = { PROFILE: "eyebrow.profile", ACCOUNT: "eyebrow.accountLanguage", NOTIFICATIONS: "eyebrow.notifications", SECURITY: "eyebrow.passwordSecurity", PRIVACY: "eyebrow.privacyDevices" };
function SettingsHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { const { t } = useI18n(); return <div className="settings-section-heading"><p className="eyebrow">{t(settingsEyebrowKeys[eyebrow] ?? eyebrow)}</p><h2>{title}</h2><p>{description}</p></div>; }
type Setter = React.Dispatch<React.SetStateAction<UserSettings>>;
type Persist = (body: unknown, successKey: string) => Promise<void>;

function ProfileSettings({ user, settings, setSettings, persist }: { user: AppUser; settings: UserSettings; setSettings: Setter; persist: Persist }) {
  const { t } = useI18n(); const fileRef = useRef<HTMLInputElement>(null); const [avatar, setAvatar] = useState(""); const [file, setFile] = useState<File>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const avatarSource=avatar||(settings.avatarPath?"/api/settings/avatar":"");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setSaving(true); try { if (file) { const data = new FormData(); data.set("avatar", file); const upload = await fetch("/api/settings/avatar", { method: "POST", body: data }); const result = await upload.json() as { url?: string }; if (!upload.ok) throw new Error(); setAvatar(result.url ?? "/api/settings/avatar"); } await persist({ section: "profile", displayNameZh: settings.displayNameZh, displayNameEn: settings.displayNameEn, honorific: settings.honorific, bio: settings.bio }, "settings.profileSaved"); } catch { setError(t("settings.saveFailed")); } finally { setSaving(false); } };
  return <form onSubmit={submit}><SettingsHeader eyebrow="PROFILE" title={t("settings.profile")} description={t("settings.profileDescription")} /><div className="avatar-editor"><span className="large-avatar">{avatarSource ? <img src={avatarSource} alt={t("settings.avatarPreview")} /> : user.initials}</span><div><b>{t("settings.avatar")}</b><p>{t("settings.avatarHelp")}</p><button className="secondary-button" type="button" onClick={() => fileRef.current?.click()}><Camera size={16} />{t("settings.changeAvatar")}</button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const next = event.target.files?.[0]; if (next) { if (avatar.startsWith("blob:")) URL.revokeObjectURL(avatar); setFile(next); setAvatar(URL.createObjectURL(next)); } }} /></div></div><div className="form-grid two-column"><label className="field"><span>{t("settings.nameZh")}</span><input value={settings.displayNameZh} onChange={(event) => setSettings((current) => ({ ...current, displayNameZh: event.target.value }))} required /></label><label className="field"><span>{t("settings.nameEn")}</span><input value={settings.displayNameEn} onChange={(event) => setSettings((current) => ({ ...current, displayNameEn: event.target.value }))} required /></label></div><SearchableSelect label={t("settings.honorific")} options={[{ value: "ms", label: "Ms." }, { value: "mr", label: "Mr." }, { value: "dr", label: "Dr." }, { value: "mx", label: "Mx." }]} value={settings.honorific || "ms"} onChange={(honorific) => setSettings((current) => ({ ...current, honorific }))} /><label className="field"><span>{t("settings.bio")}</span><textarea rows={4} value={settings.bio} onChange={(event) => setSettings((current) => ({ ...current, bio: event.target.value }))} /></label><ProtectedFields role={user.role} />{error && <InlineMessage type="error">{error}</InlineMessage>}<SaveRow saving={saving} /></form>;
}

function ProtectedFields({ role }: { role: AppUser["role"] }) { const { t } = useI18n(); return <div className="protected-field-grid"><div><span>{t("settings.role")}</span><b>{t(roleMessageKey[role])}</b><small>{t("settings.immutable")}</small></div><div><span>{t("settings.verificationLevel")}</span><b>{t(role === "SUPER_ADMIN" || role === "ADMIN" ? "settings.highPrivilege" : "settings.byRole")}</b><small>{t("settings.immutable")}</small></div><div><span>{t("settings.accountStatus")}</span><b className="good-text">{t("settings.activeVerified")}</b><small>{t("settings.immutable")}</small></div></div>; }

function AccountSettings({ user, email, setEmail, settings, setSettings, persist }: { user: AppUser; email: string; setEmail: (value: string) => void; settings: UserSettings; setSettings: Setter; persist: Persist }) {
  const { locale, setLocale, t } = useI18n(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setSaving(true); try { await persist({ section: "account", email, locale: settings.locale, timezone: settings.timezone, dateFormat: settings.dateFormat }, "settings.accountSaved"); setLocale(settings.locale as Locale); } catch { setError(t("settings.saveFailed")); } finally { setSaving(false); } };
  return <form onSubmit={submit}><SettingsHeader eyebrow="ACCOUNT" title={t("settings.accountLanguage")} description={t("settings.languageHelp")} /><div className="form-grid two-column"><label className="field"><span>{t("settings.username")}</span><input value={settings.username} readOnly aria-readonly="true" /></label><label className="field"><span>{t("settings.internalId")}</span><input value={user.id} readOnly aria-readonly="true" /><small className="field-help">{t("settings.internalIdHelp")}</small></label></div><label className="field"><span>{t("settings.loginEmail")}</span><span className="input-with-status"><Mail size={17} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><b><Check size={14} />{t("nav.verified")}</b></span></label><InlineMessage type="warning">{t("settings.emailWarning")}</InlineMessage><div className="form-grid two-column"><SearchableSelect label={t("settings.language")} options={[{ value: "zh-CN", label: "简体中文" }, { value: "en", label: "English" }]} value={settings.locale || locale} onChange={(value) => setSettings((current) => ({ ...current, locale: value as Locale }))} /><SearchableSelect label={t("settings.timezone")} options={[{ value: "Asia/Taipei", label: "Asia/Taipei (UTC+8)" }, { value: "Asia/Shanghai", label: "Asia/Shanghai (UTC+8)" }, { value: "Asia/Singapore", label: "Asia/Singapore (UTC+8)" }, { value: "Europe/London", label: "Europe/London" }, { value: "America/New_York", label: "America/New_York" }]} value={settings.timezone} onChange={(timezone) => setSettings((current) => ({ ...current, timezone }))} /></div><label className="field"><span>{t("settings.dateFormat")}</span><select value={settings.dateFormat} onChange={(event) => setSettings((current) => ({ ...current, dateFormat: event.target.value as UserSettings["dateFormat"] }))}><option value="yyyy-MM-dd">2026-07-16</option><option value="dd/MM/yyyy">16/07/2026</option><option value="MM/dd/yyyy">07/16/2026</option></select></label>{error && <InlineMessage type="error">{error}</InlineMessage>}<SaveRow saving={saving} /></form>;
}

function NotificationSettings({ settings, setSettings, persist }: { settings: UserSettings; setSettings: Setter; persist: Persist }) {
  const { t } = useI18n(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const rows = ["tasks", "relationship", "sales", "security"];
  const updateChannel = (key: string, channel: "email" | "inApp", value: boolean) => setSettings((current) => ({ ...current, notifications: { ...current.notifications, [key]: { ...(current.notifications[key] ?? { email: false, inApp: false }), [channel]: value } } }));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setSaving(true); try { await persist({ section: "notifications", notifications: settings.notifications, quietHoursStart: settings.quietHoursStart, quietHoursEnd: settings.quietHoursEnd }, "settings.notificationSaved"); } catch { setError(t("settings.saveFailed")); } finally { setSaving(false); } };
  return <form onSubmit={submit}><SettingsHeader eyebrow="NOTIFICATIONS" title={t("settings.notifications")} description={t("settings.notificationHelp")} /><div className="notification-settings-head"><span>{t("settings.notificationType")}</span><span>{t("settings.emailChannel")}</span><span>{t("settings.inApp")}</span></div>{rows.map((key) => <div className="notification-setting-row" key={key}><div><b>{t(`settings.notify.${key}`)}</b><small>{t(`settings.notify.${key}Help`)}</small></div><label className="switch"><input aria-label={`${t(`settings.notify.${key}`)} · ${t("settings.emailChannel")}`} type="checkbox" checked={settings.notifications[key]?.email ?? false} onChange={(event) => updateChannel(key, "email", event.target.checked)} /><span /></label><label className="switch"><input aria-label={`${t(`settings.notify.${key}`)} · ${t("settings.inApp")}`} type="checkbox" checked={settings.notifications[key]?.inApp ?? false} onChange={(event) => updateChannel(key, "inApp", event.target.checked)} /><span /></label></div>)}<label className="field"><span>{t("settings.quietHours")}</span><select value={settings.quietHoursStart?.slice(0, 5) ?? "off"} onChange={(event) => setSettings((current) => ({ ...current, quietHoursStart: event.target.value === "off" ? null : `${event.target.value}:00`, quietHoursEnd: event.target.value === "off" ? null : event.target.value === "22:00" ? "08:00:00" : "09:00:00" }))}><option value="off">{t("settings.off")}</option><option value="22:00">22:00–08:00</option><option value="21:00">21:00–09:00</option></select></label>{error && <InlineMessage type="error">{error}</InlineMessage>}<SaveRow saving={saving} /></form>;
}

type Factor = { id: string; status: string; friendly_name?: string };
function SecuritySettings() {
  const { t } = useI18n(); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [factors, setFactors] = useState<Factor[]>([]); const [enrollment, setEnrollment] = useState<{ factorId: string; challengeId: string; qrCode: string }>(); const [busy, setBusy] = useState(false);
  const loadMfa = () => fetch("/api/settings/mfa").then((response) => response.ok ? response.json() : Promise.reject()).then((result: { factors?: Factor[] }) => setFactors(result.factors ?? [])).catch(() => setError(t("settings.mfaFailed")));
  useEffect(() => { loadMfa(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const enroll = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/settings/mfa", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "enroll" }) }); const result = await response.json() as { factor?: { id?: string; totp?: { qr_code?: string } } }; if (!response.ok || !result.factor?.id) throw new Error(); const challengeResponse = await fetch("/api/settings/mfa", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "challenge", factorId: result.factor.id }) }); const challengeResult = await challengeResponse.json() as { challenge?: { id?: string } }; if (!challengeResponse.ok || !challengeResult.challenge?.id) throw new Error(); setEnrollment({ factorId: result.factor.id, challengeId: challengeResult.challenge.id, qrCode: result.factor.totp?.qr_code ?? "" }); } catch { setError(t("settings.mfaFailed")); } finally { setBusy(false); } };
  const verify = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!enrollment) return; const code = String(new FormData(event.currentTarget).get("code")); setBusy(true); setError(""); const response = await fetch("/api/settings/mfa", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "verify", factorId: enrollment.factorId, challengeId: enrollment.challengeId, code }) }); if (response.ok) { setEnrollment(undefined); setSuccess(t("settings.mfaEnabled")); loadMfa(); } else setError(t("settings.mfaCodeInvalid")); setBusy(false); };
  const changePassword = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setSuccess(""); const data = new FormData(event.currentTarget); if (data.get("newPassword") !== data.get("confirmPassword")) { setError(t("settings.passwordMismatch")); return; } setBusy(true); const response = await fetch("/api/settings/password", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }) }); if (response.ok) { setSuccess(t("settings.passwordSaved")); event.currentTarget.reset(); } else { const result = await response.json() as { code?: string }; setError(t(result.code === "CURRENT_PASSWORD_INCORRECT" ? "settings.currentPasswordIncorrect" : "settings.passwordFailed")); } setBusy(false); };
  return <div><SettingsHeader eyebrow="SECURITY" title={t("settings.security")} description={t("settings.securityHelp")} /><section className="mfa-card"><span><ShieldCheck size={25} /></span><div><b>{factors.some((factor) => factor.status === "verified") ? t("settings.mfaEnabled") : t("settings.mfaReady")}</b><p>{t("settings.mfaReadyHelp")}</p></div><StatusBadge tone={factors.some((factor) => factor.status === "verified") ? "green" : "amber"}>{t(factors.some((factor) => factor.status === "verified") ? "common.enabled" : "settings.setupRequired")}</StatusBadge>{!factors.some((factor) => factor.status === "verified") && <button className="secondary-button" type="button" disabled={busy} onClick={enroll}>{t("settings.manageMfa")}</button>}</section>{enrollment && <form className="settings-subform" onSubmit={verify}><h3>{t("settings.verifyMfa")}</h3>{enrollment.qrCode && <img className="mfa-qr" src={enrollment.qrCode} alt={t("settings.mfaQrAlt")} />}<label className="field"><span>{t("settings.mfaCode")}</span><input name="code" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" required /></label><button className="primary-button" disabled={busy}>{t("settings.verifyMfa")}</button></form>}<form onSubmit={changePassword} className="settings-subform"><h3>{t("settings.changePassword")}</h3><label className="field"><span>{t("settings.currentPassword")}</span><input type="password" name="currentPassword" autoComplete="current-password" required /></label><div className="form-grid two-column"><label className="field"><span>{t("settings.newPassword")}</span><input type="password" name="newPassword" autoComplete="new-password" minLength={10} required /></label><label className="field"><span>{t("settings.confirmPassword")}</span><input type="password" name="confirmPassword" autoComplete="new-password" minLength={10} required /></label></div>{error && <InlineMessage type="error">{error}</InlineMessage>}{success && <InlineMessage type="success">{success}</InlineMessage>}<div className="settings-actions"><span>{t("settings.securitySubmitHelp")}</span><button className="primary-button" type="submit" disabled={busy}><KeyRound size={16} />{t("settings.updatePassword")}</button></div></form></div>;
}

function PrivacySettings() { const { t } = useI18n(); const [status, setStatus] = useState<"" | "success" | "error">(""); const revoke = async () => { setStatus(""); const response = await fetch("/api/settings/sessions", { method: "DELETE" }); setStatus(response.ok ? "success" : "error"); }; return <div><SettingsHeader eyebrow="PRIVACY" title={t("settings.privacyDevices")} description={t("settings.privacyDevicesHelp")} /><section className="privacy-links"><Link href="/privacy"><span><Eye size={18} /></span><div><b>{t("settings.privacyPolicy")}</b><p>{t("settings.privacyPolicyHelp")}</p></div><ChevronRight size={16} /></Link></section><h3 className="device-heading">{t("settings.loginDevices")}</h3><InlineMessage type="warning">{t("settings.sessionPrivacyNote")}</InlineMessage><div className="device-list"><div className="device-row"><span><Laptop size={20} /></span><div><b>{t("settings.currentBrowser")}</b><small>{t("settings.currentDevice")} · {t("settings.now")}</small></div><StatusBadge tone="green">{t("settings.currentDevice")}</StatusBadge></div></div>{status === "success" && <InlineMessage type="success">{t("settings.otherDevicesRevoked")}</InlineMessage>}{status === "error" && <InlineMessage type="error">{t("settings.sessionRevokeFailed")}</InlineMessage>}<button className="danger-button" type="button" onClick={revoke}><MonitorSmartphone size={17} />{t("settings.signOutOthers")}</button></div>; }
function SaveRow({ saving }: { saving: boolean }) { const { t } = useI18n(); return <div className="settings-actions"><span>{t("settings.requiredHelp")}</span><button className="primary-button" type="submit" disabled={saving}><Save size={16} />{saving ? t("settings.saving") : t("settings.saveChanges")}</button></div>; }
