"use client";
/* eslint-disable @next/next/no-img-element -- Blob URLs are local previews, not persisted content images. */

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useRef, useState } from "react";
import { BellRing, Camera, Check, ChevronRight, Eye, KeyRound, Languages, Laptop, LockKeyhole, Mail, MonitorSmartphone, Save, ShieldCheck, Smartphone, UserRound } from "lucide-react";
import { InlineMessage, SearchableSelect, StatusBadge, Toast } from "@/components/ui";
import { useAppUser } from "@/components/app-shell";
import type { AppUser } from "@/lib/auth";
import { useI18n } from "./i18n-provider";
import type { Locale } from "@/lib/i18n";

const tabs = [
  { href: "/settings/profile", key: "settings.profile", icon: UserRound }, { href: "/settings/account", key: "settings.accountLanguage", icon: Languages },
  { href: "/settings/notifications", key: "settings.notifications", icon: BellRing }, { href: "/settings/security", key: "settings.security", icon: ShieldCheck }, { href: "/settings/privacy", key: "settings.privacy", icon: Eye },
];

export function SettingsPage({ section }: { section: string }) {
  const { t } = useI18n(); const pathname = usePathname(); const user = useAppUser(); const [toast, setToast] = useState("");
  const prototypeSave = () => setToast(t("settings.savedPrototype"));
  return <div className="page-stack settings-page"><section className="page-heading-row"><div><p className="eyebrow">PERSONAL SETTINGS</p><h1>{t("settings.title")}</h1><p>{t("settings.description")}</p></div><StatusBadge tone="green">{t("settings.accountNormal")}</StatusBadge></section><div className="settings-layout"><aside className="settings-nav">{tabs.map(({ href, key, icon: Icon }) => <Link key={href} className={pathname === href ? "active" : ""} href={href}><Icon size={17} /><span>{t(key)}</span><ChevronRight size={14} /></Link>)}<div className="settings-role-note"><LockKeyhole size={17} /><div><b>{t("settings.protected")}</b><p>{t("settings.protectedHelp")}</p></div></div></aside><section className="settings-content"><InlineMessage type="warning">{t("settings.prototypeWarning")}</InlineMessage>{section === "profile" && <ProfileSettings user={user} onSave={prototypeSave} />}{section === "account" && <AccountSettings user={user} onSave={prototypeSave} />}{section === "notifications" && <NotificationSettings onSave={prototypeSave} />}{section === "security" && <SecuritySettings onSave={prototypeSave} />}{section === "privacy" && <PrivacySettings onSave={prototypeSave} />}</section></div>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}

function SettingsHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="settings-section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div>; }

function ProfileSettings({ user, onSave }: { user: AppUser; onSave: () => void }) {
  const { t } = useI18n(); const fileRef = useRef<HTMLInputElement>(null); const [avatar, setAvatar] = useState<string>(); const [title, setTitle] = useState("ms");
  return <form onSubmit={(event) => { event.preventDefault(); onSave(); }}><SettingsHeader eyebrow="PROFILE" title={t("settings.profile")} description={t("settings.profileDescription")} /><div className="avatar-editor"><span className="large-avatar">{avatar ? <img src={avatar} alt={t("settings.avatarPreview")} /> : user.initials}</span><div><b>{t("settings.avatar")}</b><p>{t("settings.avatarHelp")}</p><button className="secondary-button" type="button" onClick={() => fileRef.current?.click()}><Camera size={16} />{t("settings.changeAvatar")}</button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) setAvatar(URL.createObjectURL(file)); }} /></div></div><div className="form-grid two-column"><label className="field"><span>{t("settings.nameZh")}</span><input defaultValue={user.displayNameZh} required /></label><label className="field"><span>{t("settings.nameEn")}</span><input defaultValue={user.displayName} required /></label></div><SearchableSelect label={t("settings.honorific")} options={[{ value: "ms", label: "Ms." }, { value: "mr", label: "Mr." }, { value: "dr", label: "Dr." }, { value: "mx", label: "Mx." }]} value={title} onChange={setTitle} /><label className="field"><span>{t("settings.bio")}</span><textarea rows={4} defaultValue={t("settings.bioDefault")} /></label><ProtectedFields role={user.role} /><SaveRow /></form>;
}

function ProtectedFields({ role }: { role: AppUser["role"] }) { const { t } = useI18n(); const labels = { ADMIN: "settings.role.admin", OPERATIONS: "settings.role.operations", SALES: "settings.role.sales" }; return <div className="protected-field-grid"><div><span>{t("settings.role")}</span><b>{t(labels[role])}</b><small>{t("settings.immutable")}</small></div><div><span>{t("settings.verificationLevel")}</span><b>{t(role === "ADMIN" ? "settings.highPrivilege" : "settings.byRole")}</b><small>{t("settings.immutable")}</small></div><div><span>{t("settings.accountStatus")}</span><b className="good-text">{t("settings.activeVerified")}</b><small>{t("settings.immutable")}</small></div></div>; }

function AccountSettings({ user, onSave }: { user: AppUser; onSave: () => void }) {
  const { locale, setLocale, t } = useI18n(); const [timezone, setTimezone] = useState("asia-taipei");
  return <form onSubmit={(event) => { event.preventDefault(); onSave(); }}><SettingsHeader eyebrow="ACCOUNT & LANGUAGE" title={t("settings.accountLanguage")} description={t("settings.languageHelp")} /><div className="form-grid two-column"><label className="field"><span>{t("settings.username")}</span><input value={user.username} readOnly aria-readonly="true" /></label><label className="field"><span>{t("settings.internalId")}</span><input value={user.id} readOnly aria-readonly="true" /><small className="field-help">{t("settings.internalIdHelp")}</small></label></div><label className="field"><span>{t("settings.loginEmail")}</span><span className="input-with-status"><Mail size={17} /><input type="email" defaultValue={user.email} /><b><Check size={14} />{t("nav.verified")}</b></span></label><InlineMessage type="warning">{t("settings.emailWarning")}</InlineMessage><div className="form-grid two-column"><SearchableSelect label={t("settings.language")} options={[{ value: "zh-CN", label: "简体中文" }, { value: "en", label: "English" }]} value={locale} onChange={(value) => setLocale(value as Locale)} /><SearchableSelect label={t("settings.timezone")} options={[{ value: "asia-taipei", label: "Asia/Taipei (UTC+8)" }, { value: "asia-shanghai", label: "Asia/Shanghai (UTC+8)" }, { value: "asia-singapore", label: "Asia/Singapore (UTC+8)" }, { value: "europe-london", label: "Europe/London" }, { value: "america-new-york", label: "America/New_York" }]} value={timezone} onChange={setTimezone} /></div><label className="field"><span>{t("settings.dateFormat")}</span><select defaultValue="yyyy"><option value="yyyy">2026-07-16</option><option value="dd">16/07/2026</option><option value="mm">07/16/2026</option></select></label><SaveRow /></form>;
}

function NotificationSettings({ onSave }: { onSave: () => void }) { const { t } = useI18n(); const rows = [{ key: "tasks", email: true }, { key: "relationship", email: true }, { key: "sales", email: false }, { key: "security", email: true }, { key: "ai", email: false }]; return <form onSubmit={(event) => { event.preventDefault(); onSave(); }}><SettingsHeader eyebrow="NOTIFICATIONS" title={t("settings.notifications")} description={t("settings.notificationHelp")} /><div className="notification-settings-head"><span>{t("settings.notificationType")}</span><span>{t("settings.emailChannel")}</span><span>{t("settings.inApp")}</span></div>{rows.map((row) => <div className="notification-setting-row" key={row.key}><div><b>{t(`settings.notify.${row.key}`)}</b><small>{t(`settings.notify.${row.key}Help`)}</small></div><label className="switch"><input aria-label={`${t(`settings.notify.${row.key}`)} · ${t("settings.emailChannel")}`} type="checkbox" defaultChecked={row.email} /><span /></label><label className="switch"><input aria-label={`${t(`settings.notify.${row.key}`)} · ${t("settings.inApp")}`} type="checkbox" defaultChecked /><span /></label></div>)}<label className="field"><span>{t("settings.quietHours")}</span><select defaultValue="22"><option value="off">{t("settings.off")}</option><option value="22">22:00–08:00</option><option value="21">21:00–09:00</option></select></label><SaveRow /></form>; }

function SecuritySettings({ onSave }: { onSave: () => void }) { const { t } = useI18n(); const [error, setError] = useState(""); const changePassword = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (data.get("newPassword") !== data.get("confirmPassword")) { setError(t("settings.passwordMismatch")); return; } setError(""); onSave(); }; return <div><SettingsHeader eyebrow="PASSWORD & SECURITY" title={t("settings.security")} description={t("settings.securityHelp")} /><section className="mfa-card"><span><ShieldCheck size={25} /></span><div><b>{t("settings.mfaPending")}</b><p>{t("settings.mfaPendingHelp")}</p></div><StatusBadge tone="amber">{t("settings.unavailable")}</StatusBadge><button className="secondary-button" type="button" disabled>{t("settings.manageMfa")}</button></section><form onSubmit={changePassword} className="settings-subform"><h3>{t("settings.changePassword")}</h3><label className="field"><span>{t("settings.currentPassword")}</span><input type="password" name="currentPassword" autoComplete="current-password" required /></label><div className="form-grid two-column"><label className="field"><span>{t("settings.newPassword")}</span><input type="password" name="newPassword" autoComplete="new-password" minLength={10} required /></label><label className="field"><span>{t("settings.confirmPassword")}</span><input type="password" name="confirmPassword" autoComplete="new-password" minLength={10} required /></label></div>{error && <InlineMessage type="error">{error}</InlineMessage>}<div className="settings-actions"><span>{t("settings.securitySubmitHelp")}</span><button className="primary-button" type="submit"><KeyRound size={16} />{t("settings.validateForm")}</button></div></form><section className="recovery-section"><h3>{t("settings.recoveryCodes")}</h3><p>{t("settings.recoveryHelp")}</p><button className="secondary-button" type="button" disabled>{t("settings.regenerateRecovery")}</button></section></div>; }

function PrivacySettings({ onSave }: { onSave: () => void }) { const { t } = useI18n(); const [revoked, setRevoked] = useState(false); return <div><SettingsHeader eyebrow="PRIVACY & DEVICES" title={t("settings.privacyDevices")} description={t("settings.privacyDevicesHelp")} /><section className="privacy-links"><a href="/privacy"><span><Eye size={18} /></span><div><b>{t("settings.privacyPolicy")}</b><p>{t("settings.privacyPolicyHelp")}</p></div><ChevronRight size={16} /></a><button type="button" onClick={onSave}><span><Mail size={18} /></span><div><b>{t("settings.exportMine")}</b><p>{t("settings.exportMineHelp")}</p></div><ChevronRight size={16} /></button></section><h3 className="device-heading">{t("settings.loginDevices")}</h3><div className="device-list"><Device icon={Laptop} title="Chrome · Windows 11" meta={`Taipei · ${t("settings.currentDevice")} · ${t("settings.now")}`} current /><Device icon={Laptop} title="Safari · macOS" meta={`Taipei · ${t("settings.minutesAgo")}`} /><Device icon={Smartphone} title="Chrome · Android" meta={`Singapore · ${t("settings.daysAgo")}`} /></div>{revoked ? <InlineMessage type="success">{t("settings.otherDevicesRevoked")}</InlineMessage> : <button className="danger-button" type="button" onClick={() => setRevoked(true)}><MonitorSmartphone size={17} />{t("settings.signOutOthers")}</button>}</div>; }

function Device({ icon: Icon, title, meta, current }: { icon: React.ElementType; title: string; meta: string; current?: boolean }) { const { t } = useI18n(); return <div className="device-row"><span><Icon size={20} /></span><div><b>{title}</b><small>{meta}</small></div>{current ? <StatusBadge tone="green">{t("settings.currentDevice")}</StatusBadge> : <button type="button">{t("settings.signOut")}</button>}</div>; }
function SaveRow() { const { t } = useI18n(); return <div className="settings-actions"><span>{t("settings.requiredHelp")}</span><button className="primary-button" type="submit"><Save size={16} />{t("settings.saveChanges")}</button></div>; }
