"use client";
import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import type {SuccessCase} from "@/lib/student-success-repository";
import type {SuccessCheckin,SuccessRisk,SuccessIntervention} from "@/lib/student-success-operations-repository";
import type {SuccessOperationKind} from "@/lib/student-success-operations-input";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {InlineMessage} from "./ui";
import {SuccessOperationEditor} from "./student-success-operations-editor";
type Record=SuccessCheckin|SuccessRisk|SuccessIntervention;
export function SuccessOperationsPanel({kind,record,onRefresh,onEditing,onViewTasks}:{kind:SuccessOperationKind;record:SuccessCase;onRefresh:()=>Promise<void>;onEditing:(value:boolean)=>void;onViewTasks:(id:string)=>void}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),[items,setItems]=useState<Record[]>([]),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editor,setEditor]=useState<Record|"new"|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const result=await apiFetch<{items:Record[]}>(`/api/student-success/${record.id}?resource=${kind==="checkin"?"checkins":kind==="risk"?"risks":"interventions"}&page=${page}`,{signal});if(!signal?.aborted)setItems(result.items);}catch{if(!signal?.aborted)setError(t("success.loadFailed"));}finally{if(!signal?.aborted)setLoading(false);}},[record.id,kind,page,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const edit=(item:Record|"new"|null)=>{setEditor(item);onEditing(item!==null);},saved=async()=>{edit(null);await onRefresh();await load();},name=(zh?:string|null,en?:string|null)=>(locale==="en"?en:zh)||zh||en||"—",date=(v?:string|null,time=false)=>v?formatDate(v,{includeTime:time}):"—";
 return <section className="detail-section"><p className="field-help">{t("successOps.independence")}</p>{record.can_edit&&<button className="primary-button" onClick={()=>edit("new")}>{t(`successOps.create.${kind}`)}</button>}{loading&&<p role="status">{t("common.loading")}</p>}{error&&<InlineMessage type="error">{error}<button onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>}{!loading&&!error&&!items.length&&<p>{t("successOps.noRecords")}</p>}
 <div className="detail-record-list">{!loading&&!error&&items.map(item=><article key={item.id}><div>{"checkin_type" in item?<><b>{t(`successOps.checkinType.${item.checkin_type}`)}</b><small>{t("successOps.field.occurred_at")}: {date(item.occurred_at,true)} · {t("successOps.field.conducted_by")}: {name(item.conducted_name_zh,item.conducted_name_en)}</small>{item.assessments?.length?item.assessments.map(a=><small key={a.id}>{t("successOps.assessments")}: {t(`success.health.${a.health_status}`)} · {date(a.assessed_at,true)}</small>):<small>{t("successOps.noAssessment")}</small>}<p className="success-narrative">{item.summary||"—"}</p><small>{t("successOps.field.next_steps")}: {item.next_steps||"—"}</small></>:"risk_type" in item?<><b>{t(`successOps.riskType.${item.risk_type}`)} · {t(`successOps.severity.${item.severity}`)} · {t(`successOps.riskStatus.${item.status}`)}</b><small>{t("successOps.field.observed_at")}: {date(item.observed_at,true)} · {t("enrollments.owner")}: {name(item.owner_name_zh,item.owner_name_en)}</small><p className="success-narrative">{item.summary}</p><small>{t("successOps.field.source_checkin_id")}: {date(item.source_checkin_at??null,true)} · {t("successOps.activeInterventionCount")}: {item.active_intervention_count}</small>{item.resolution_note&&<p>{item.resolution_note}</p>}{item.resolved_at&&<small>{t("successOps.field.resolved_at")}: {date(item.resolved_at,true)}</small>}</>:<><b>{t(`successOps.interventionType.${item.intervention_type}`)} · {t(`successOps.interventionStatus.${item.status}`)}</b><small>{t("enrollments.owner")}: {name(item.owner_name_zh,item.owner_name_en)}</small><p className="success-narrative">{item.summary}</p><small>{t("successOps.field.risk_signal_id")}: {item.risk_summary||"—"}</small><small>{t("successOps.field.started_on")}: {date(item.started_on)} · {t("successOps.field.target_end_on")}: {date(item.target_end_on)}</small>{item.completed_at&&<small>{t("successOps.field.completed_at")}: {date(item.completed_at,true)}</small>}{item.outcome_note&&<p>{item.outcome_note}</p>}<button className="secondary-button" onClick={()=>onViewTasks(item.id)}>{t("successOps.viewTasks")} ({item.visible_task_count})</button></>}</div>{record.can_edit&&<button className="secondary-button" onClick={()=>edit(item)}>{t("successOps.edit")}</button>}</article>)}</div>
 <div className="detail-actions"><button disabled={page===1||loading} className="secondary-button" onClick={()=>setPage(v=>v-1)}>{t("cohorts.previous")}</button><span>{page}</span><button disabled={items.length<50||loading} className="secondary-button" onClick={()=>setPage(v=>v+1)}>{t("cohorts.next")}</button></div>
 {editor&&<SuccessOperationEditor kind={kind} record={editor==="new"?undefined:editor} caseRecord={record} onClose={()=>edit(null)} onSaved={saved} onReload={()=>{edit(null);void saved();}}/>}</section>;
}
