"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {successTaskLinkSchema} from "@/lib/student-success-input";
import type {SuccessCase,SuccessGoal,SuccessTask} from "@/lib/student-success-repository";
import type {SuccessOperationalHistory,SuccessIntervention} from "@/lib/student-success-operations-repository";
import {SuccessOutcomesPanel} from "./student-success-outcomes-panel";
import {SuccessOperationsPanel} from "./student-success-operations-panel";
import {AccessibleDrawer,InlineMessage,SearchableSelect} from "./ui";
import {DetailTabs} from "./detail-tabs";
import {useI18n} from "./i18n-provider";
import {useUserPreferences} from "./user-preferences-context";
import {useRemoteSearch} from "@/hooks/use-remote-search";
import {SuccessGoalEditor,useSuccessSave} from "./student-success-editor";
export function SuccessCaseDetail({record,onClose,onEdit,onRefresh}:{record:SuccessCase;onClose:()=>void;onEdit:()=>void;onRefresh:()=>Promise<void>}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),[tab,setTab]=useState("overview"),[page,setPage]=useState(1),[goals,setGoals]=useState<SuccessGoal[]>([]),[history,setHistory]=useState<Array<SuccessOperationalHistory&{case_revision?:number}>>([]),[tasks,setTasks]=useState<SuccessTask[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false),[editing,setEditing]=useState<SuccessGoal|"new"|null>(null),[linking,setLinking]=useState(false),[operationEditing,setOperationEditing]=useState(false),[interventionFilter,setInterventionFilter]=useState("");
 const label=(zh?:string|null,en?:string|null)=>(locale==="en"?en:zh)||zh||en||"—";
 const load=useCallback(async(signal?:AbortSignal)=>{if(!["goals","tasks","history"].includes(tab))return;setLoading(true);setError("");try{const result=await apiFetch<{items:Array<SuccessGoal|SuccessOperationalHistory|SuccessTask>}>(`/api/student-success/${record.id}?resource=${tab==="history"?"operationHistory":tab}&page=${page}${tab==="tasks"&&interventionFilter?`&interventionId=${interventionFilter}`:""}`,{signal});if(!signal?.aborted){if(tab==="goals")setGoals(result.items as SuccessGoal[]);else if(tab==="history")setHistory(result.items as SuccessOperationalHistory[]);else setTasks(result.items as SuccessTask[]);}}catch{if(!signal?.aborted)setError(t("success.loadFailed"));}finally{if(!signal?.aborted)setLoading(false);}},[tab,page,record.id,t,interventionFilter]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const saved=async()=>{setEditing(null);setLinking(false);await onRefresh();await load();};
 const items=tab==="goals"?goals:tab==="tasks"?tasks:history;
 const statusLabel=(source:string,status:string)=>t(`${source==="HEALTH"?"success.health":source==="RISK"?"successOps.riskStatus":source==="INTERVENTION"?"successOps.interventionStatus":"success.status"}.${status}`);
 return <><AccessibleDrawer title={label(record.student_name_zh,record.student_name_en)} description={`${t("success.title")} · ${label(record.cohort_name_zh,record.cohort_name_en)}`} onClose={onClose} pending={editing!==null||linking||operationEditing}>
 <DetailTabs active={tab} label={t("success.title")} disabled={editing!==null||linking||operationEditing} onChange={value=>{setTab(value);setPage(1);setError("");setInterventionFilter("");}} items={[{key:"overview",label:"applications.overview"},{key:"goals",label:"success.goals"},{key:"tasks",label:"applications.tasks"},{key:"checkins",label:"successOps.checkins"},{key:"risks",label:"successOps.risks"},{key:"interventions",label:"successOps.interventions"},{key:"outcomes",label:"successOutcome.title"},{key:"history",label:"applications.history"}]}>
 {tab==="overview"?<section className="detail-section"><dl className="enrollment-summary">
 <div><dt>{t("applications.enrollment")}</dt><dd><Link href={`/enrollments?focus=${record.enrollment_id}`}>{label(record.cohort_name_zh,record.cohort_name_en)}</Link></dd></div><div><dt>{t("products.product")}</dt><dd>{label(record.product_name_zh,record.product_name_en)}</dd></div>
 <div><dt>{t("success.enrollmentOwner")}</dt><dd>{label(record.enrollment_owner_name_zh,record.enrollment_owner_name_en)}</dd></div><div><dt>{t("success.enrollmentStatus")}</dt><dd>{t(`enrollments.status.${record.enrollment_status}`)}</dd></div><div><dt>{t("success.caseStatus")}</dt><dd>{t(`success.status.${record.status}`)}</dd></div><div><dt>{t("success.health")}</dt><dd>{t(`success.health.${record.health_status}`)}</dd></div>
 <div><dt>{t("enrollments.owner")}</dt><dd>{label(record.owner_name_zh,record.owner_name_en)}</dd></div><div><dt>{t("success.nextReview")}</dt><dd>{record.next_review_on?formatDate(record.next_review_on):"—"}</dd></div>
 <div><dt>{t("success.success_summary")}</dt><dd className="success-narrative">{record.success_summary||"—"}</dd></div><div><dt>{t("success.plan_summary")}</dt><dd className="success-narrative">{record.plan_summary||"—"}</dd></div>
 <div><dt>{t("successOps.lastCheckin")}</dt><dd>{record.last_checkin_at?formatDate(record.last_checkin_at,{includeTime:true}):"—"}</dd></div><div><dt>{t("successOps.openRisks")}</dt><dd>{record.open_risk_count??0}</dd></div><div><dt>{t("successOps.highRisks")}</dt><dd>{record.high_risk_count??0}</dd></div><div><dt>{t("successOps.activeInterventions")}</dt><dd>{record.active_intervention_count??0}</dd></div><div><dt>{t("success.activeGoals")}</dt><dd>{record.active_goal_count}</dd></div><div><dt>{t("success.openTasks")}</dt><dd>{record.open_task_count}</dd></div>
 {["recorded","achieved","partial","not_achieved","observed"].map(key=><div key={key}><dt>{t(`successOutcome.count.${key}`)}</dt><dd>{record[(`${key}_outcome_count`) as keyof SuccessCase]??0}</dd></div>)}
</dl>{record.status==="COMPLETED"&&!record.recorded_outcome_count&&<p className="field-help">{t("successOutcome.completionWarning")}</p>}<p className="field-help">{t("success.healthHelp")}</p>{record.can_edit&&<button className="primary-button" onClick={onEdit}>{t("success.edit")}</button>}</section>:tab==="outcomes"?<SuccessOutcomesPanel record={record} onRefresh={onRefresh} onEditing={setOperationEditing}/>: ["checkins","risks","interventions"].includes(tab)?<SuccessOperationsPanel key={tab} kind={tab==="checkins"?"checkin":tab==="risks"?"risk":"intervention"} record={record} onRefresh={onRefresh} onEditing={setOperationEditing} onViewTasks={id=>{setInterventionFilter(id);setTab("tasks");setPage(1);}}/>:<section className="detail-section">
 {loading&&<p role="status">{t("common.loading")}</p>}{error&&<InlineMessage type="error">{error}<button onClick={()=>void load()}>{t("common.retry")}</button></InlineMessage>}
 {!loading&&!error&&items.length===0&&<p className="detail-empty">{t("success.noRecords")}</p>}
 {tab==="goals"&&<><p className="field-help">{t("success.goalHelp")}</p>{record.can_edit&&<button className="primary-button" onClick={()=>setEditing("new")}>{t("success.addGoal")}</button>}<div className="detail-record-list">{!loading&&!error&&goals.map(goal=><article key={goal.id}><div><b>{goal.title}</b><small>{t(`success.goalType.${goal.goal_type}`)} · {t(`success.goalStatus.${goal.status}`)} · {goal.target_on?formatDate(goal.target_on):"—"}</small>{goal.description&&<p className="success-narrative">{goal.description}</p>}<small>{t("enrollments.owner")}: {label(goal.owner_name_zh,goal.owner_name_en)}</small>{goal.achieved_at&&<small>{t("success.achievedAt")}: {formatDate(goal.achieved_at,{includeTime:true})}</small>}</div>{record.can_edit&&<button className="secondary-button" onClick={()=>setEditing(goal)}>{t("success.editGoal")}</button>}</article>)}</div></>}
 {tab==="tasks"&&<>{interventionFilter&&<button className="secondary-button" onClick={()=>setInterventionFilter("")}>{t("successOps.allTasks")}</button>}{record.can_edit&&<button className="primary-button" onClick={()=>setLinking(true)}>{t("success.linkTask")}</button>}<div className="detail-record-list">{!loading&&!error&&tasks.map(task=><article key={task.id}><div><Link href={`/tasks/${task.task_id}`}><b>{label(task.title_zh,task.title_en)}</b></Link><small>{t(`status.${task.status}`)} · {task.due_at?formatDate(task.due_at):"—"}</small></div></article>)}</div><p className="field-help">{t("success.taskHelp")}</p></>}
 {tab==="history"&&<div className="detail-record-list">{!loading&&!error&&history.map(item=><article key={item.id}><div><small>{t("successOps.historySource")}: {t(`successOps.source.${item.source_type??"CASE"}`)}</small><b>{item.from_status?statusLabel(item.source_type,item.from_status):t("successOps.started")} → {statusLabel(item.source_type,item.to_status)}</b><small>{formatDate(item.changed_at,{includeTime:true})} · {t("enrollments.revision",{revision:item.revision??item.case_revision})}</small>{item.reason&&<p className="success-narrative">{item.reason}</p>}</div></article>)}</div>}
 <div className="detail-actions"><button className="secondary-button" disabled={page===1||loading} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button className="secondary-button" disabled={items.length<50||loading} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div>
 </section>}
 </DetailTabs></AccessibleDrawer>{editing&&<SuccessGoalEditor key={editing==="new"?"new":editing.id} caseRecord={record} record={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onSaved={saved} onReload={()=>{setEditing(null);void saved();}}/>}{linking&&<SuccessTaskLinkEditor record={record} initialIntervention={interventionFilter} onClose={()=>setLinking(false)} onSaved={saved}/>}</>;
}
function SuccessTaskLinkEditor({record,initialIntervention,onClose,onSaved}:{record:SuccessCase;initialIntervention:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),[taskId,setTaskId]=useState(""),[goalId,setGoalId]=useState(""),[interventionId,setInterventionId]=useState(initialIntervention),[goals,setGoals]=useState<SuccessGoal[]>([]),[interventions,setInterventions]=useState<SuccessIntervention[]>([]),[options,setOptions]=useState<Array<{value:string;label:string}>>([]),[id]=useState(()=>crypto.randomUUID()),mutation=useSuccessSave(onSaved),latest=useRemoteSearch(),{setError}=mutation;
 useEffect(()=>{const controller=new AbortController();void Promise.all([apiFetch<{items:SuccessGoal[]}>(`/api/student-success/${record.id}?resource=goals`,{signal:controller.signal}),apiFetch<{items:SuccessIntervention[]}>(`/api/student-success/${record.id}?resource=interventions`,{signal:controller.signal})]).then(([g,i])=>{if(!controller.signal.aborted){setGoals(g.items);setInterventions(i.items);}}).catch(()=>{if(!controller.signal.aborted)setError(t("success.loadFailed"));});return()=>controller.abort();},[record.id,t,setError]);
 const search=async(q:string)=>{const result=await latest(signal=>apiFetch<{items:Array<{id:string;title_zh:string;title_en:string}>}>(`/api/student-success/${record.id}?resource=taskOptions&q=${encodeURIComponent(q)}`,{signal}));if(!result.current)return;if("error" in result){setError(t("success.loadFailed"));return;}setOptions(result.value.items.map(item=>({value:item.id,label:locale==="en"?item.title_en:item.title_zh})));};
 const submit=(event:React.FormEvent)=>{event.preventDefault();const parsed=successTaskLinkSchema.safeParse({id,expectedRevision:null,requestKey:crypto.randomUUID(),caseId:record.id,taskId,goalId:goalId||null,interventionId:interventionId||null,unlink:false});if(!parsed.success){mutation.setError(t("success.invalid"));return;}void mutation.save({operation:"taskLink",input:parsed.data});};
 return <AccessibleDrawer title={t("success.linkTask")} description={t("success.taskHelp")} onClose={onClose} pending={mutation.pending||mutation.uncertain}><form onSubmit={submit}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain}><SearchableSelect label={t("applications.tasks")} required value={taskId} options={options} onSearch={search} onChange={setTaskId}/><label className="field"><span>{t("success.goals")}</span><select value={goalId} onChange={event=>setGoalId(event.target.value)}><option value="">{t("success.wholeCase")}</option>{goals.map(goal=><option value={goal.id} key={goal.id}>{goal.title}</option>)}</select></label><label className="field"><span>{t("successOps.field.intervention_id")}</span><select name="intervention_id" value={interventionId} onChange={event=>setInterventionId(event.target.value)}><option value="">{t("successOps.noContext")}</option>{interventions.map(item=><option key={item.id} value={item.id}>{item.summary}</option>)}</select></label></fieldset>{mutation.error&&<InlineMessage type="error">{mutation.error}</InlineMessage>}{mutation.uncertain&&<InlineMessage type="warning">{t("success.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={mutation.pending||mutation.uncertain} onClick={onClose}>{t("common.cancel")}</button><button className="primary-button" disabled={mutation.pending}>{t(mutation.uncertain?"success.retry":"common.save")}</button></div></form></AccessibleDrawer>;
}
