"use client";
import {NextActionInput} from "./next-action-input";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api-client";
import {successHealth} from "@/lib/student-success-input";
import {successCheckinTypes,successRiskTypes,successRiskSeverities,successRiskStatuses,successInterventionTypes,successInterventionStatuses,successCheckinSaveSchema,successRiskSaveSchema,successInterventionSaveSchema,type SuccessOperationKind} from "@/lib/student-success-operations-input";
import type {SuccessCase} from "@/lib/student-success-repository";
import type {SuccessCheckin,SuccessRisk,SuccessIntervention} from "@/lib/student-success-operations-repository";
import {enrollmentTimestamp} from "@/lib/enrollment-input";
import {AccessibleDrawer,InlineMessage} from "./ui";
import {DateInput} from "./structured-inputs";
import {EnrollmentRelation} from "./enrollment-relation";
import {useI18n} from "./i18n-provider";
import {useAppUser} from "./app-user-context";
import {useUserPreferences} from "./user-preferences-context";
import {useSuccessSave} from "./student-success-editor";
type OperationRecord=SuccessCheckin|SuccessRisk|SuccessIntervention;
export function SuccessOperationEditor({kind,record,caseRecord,onClose,onSaved,onReload}:{kind:SuccessOperationKind;record?:OperationRecord;caseRecord:SuccessCase;onClose:()=>void;onSaved:()=>Promise<void>;onReload:()=>void}){
 const {t,locale}=useI18n(),user=useAppUser(),preferences=useUserPreferences(),{formatDate}=preferences,[id]=useState(()=>record?.id??crypto.randomUUID()),mutation=useSuccessSave(onSaved),[related,setRelated]=useState<Array<{id:string;label:string}>>([]),{setError}=mutation;
 const defaults:Record<string,unknown>=kind==="checkin"?{case_id:caseRecord.id,checkin_type:"ROUTINE",occurred_at:new Date().toISOString(),conducted_by:user.id,summary:null,next_steps:null}:kind==="risk"?{case_id:caseRecord.id,source_checkin_id:null,risk_type:"ACADEMIC",severity:"MEDIUM",status:"OPEN",observed_at:new Date().toISOString(),owner_id:caseRecord.owner_id,summary:"",resolution_note:null,resolved_at:null}:{case_id:caseRecord.id,risk_signal_id:null,intervention_type:"ACADEMIC_SUPPORT",status:"PLANNED",owner_id:caseRecord.owner_id,started_on:null,target_end_on:null,completed_at:null,summary:"",outcome_note:null};
 const [data,setData]=useState<Record<string,unknown>>(()=>Object.fromEntries(Object.keys(defaults).map(key=>[key,record?(record as unknown as Record<string,unknown>)[key]:defaults[key]]))),[assess,setAssess]=useState(false),[health,setHealth]=useState(caseRecord.health_status),[rationale,setRationale]=useState(""),[review,setReview]=useState(false),[nextReview,setNextReview]=useState(caseRecord.next_review_on??""),[reason,setReason]=useState("");
 const change=(key:string,value:unknown)=>setData(old=>({...old,[key]:value}));
 useEffect(()=>{if(kind==="checkin")return;const controller=new AbortController();void apiFetch<{items:Array<SuccessCheckin|SuccessRisk>}>(`/api/student-success/${caseRecord.id}?resource=${kind==="risk"?"checkins":"risks"}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setRelated(result.items.map(item=>({id:item.id,label:"risk_type" in item?`${t(`successOps.riskType.${item.risk_type}`)} · ${item.summary}`:`${t(`successOps.checkinType.${item.checkin_type}`)} · ${formatDate(item.occurred_at,{includeTime:true})}`})));}).catch(()=>{if(!controller.signal.aborted)setError(t("success.loadFailed"));});return()=>controller.abort();},[kind,caseRecord.id,t,formatDate,setError]);
 const select=(key:string,values:readonly string[],prefix:string)=><label className="field"><span>{t(`successOps.field.${key}`)}</span><select name={key} value={String(data[key]??"")} onChange={event=>change(key,event.target.value)}>{values.map(value=><option key={value} value={value}>{t(`${prefix}.${value}`)}</option>)}</select></label>;
 const date=(key:string,time=false)=><label className="field"><span>{t(`successOps.field.${key}`)}</span><DateInput name={key} type={time?"datetime-local":"date"} required={key==="occurred_at"||key==="observed_at"} value={data[key]?time?preferences.localDateTimeInput(String(data[key])):String(data[key]):""} onChange={event=>change(key,time?enrollmentTimestamp(event.target.value,String((record as unknown as Record<string,unknown>)?.[key]??""),preferences.localDateTimeInput,preferences.localDateTimeToIso):event.target.value||null)}/></label>;
 const text=(key:string,required=false)=>{const TextControl=key==="next_steps"?NextActionInput:"textarea";return <label className="field"><span>{t(`successOps.field.${key}`)}</span><TextControl name={key} required={required} rows={3} maxLength={key==="next_steps"?4000:2000} value={String(data[key]??"")} onChange={event=>change(key,event.target.value||null)}/></label>;};
 const relationKey=kind==="risk"?"source_checkin_id":"risk_signal_id",owner=kind==="checkin"?"conducted_by":"owner_id",recordNames=record as (SuccessRisk&SuccessCheckin)|undefined;
 const submit=(event:React.FormEvent)=>{event.preventDefault();const input={id,expectedRevision:record?.revision??null,requestKey:crypto.randomUUID(),data,...(kind==="checkin"?{options:{assess_health:assess,health_status:assess?health:null,rationale:assess?rationale||null:null,update_next_review:review,next_review_on:review?nextReview||null:null,expected_case_revision:assess||review?caseRecord.revision:null}}:{statusReason:reason})};const schema=kind==="checkin"?successCheckinSaveSchema:kind==="risk"?successRiskSaveSchema:successInterventionSaveSchema,parsed=schema.safeParse(input);if(!parsed.success){setError(t("successOps.invalid"));return;}void mutation.save({operation:kind,input:parsed.data});};
 return <AccessibleDrawer title={t(record?"successOps.edit":`successOps.create.${kind}`)} description={t("successOps.independence")} onClose={onClose} pending={mutation.pending||mutation.uncertain}><form onSubmit={submit}><fieldset className="follow-up-fields" disabled={mutation.pending||mutation.uncertain||mutation.conflict}>
 {kind==="checkin"?<>{select("checkin_type",successCheckinTypes,"successOps.checkinType")}{date("occurred_at",true)}{text("summary")}{text("next_steps")}</>:kind==="risk"?<>{select("risk_type",successRiskTypes,"successOps.riskType")}{select("severity",successRiskSeverities,"successOps.severity")}{select("status",successRiskStatuses,"successOps.riskStatus")}{date("observed_at",true)}{text("summary",true)}{date("resolved_at",true)}{text("resolution_note")}</>:<>{select("intervention_type",successInterventionTypes,"successOps.interventionType")}{select("status",successInterventionStatuses,"successOps.interventionStatus")}{text("summary",true)}{date("started_on")}{date("target_end_on")}{date("completed_at",true)}{text("outcome_note")}</>}
 <EnrollmentRelation type="USER" label={t(`successOps.field.${owner}`)} value={String(data[owner]??"")} initialLabel={record?(locale==="en"?recordNames?.owner_name_en??recordNames?.conducted_name_en:recordNames?.owner_name_zh??recordNames?.conducted_name_zh)||"":kind==="checkin"?user.displayName:(locale==="en"?caseRecord.owner_name_en:caseRecord.owner_name_zh)||""} onChange={value=>change(owner,value||null)}/>
 {kind!=="checkin"&&<><label className="field"><span>{t(`successOps.field.${relationKey}`)}</span><select name={relationKey} value={String(data[relationKey]??"")} onChange={event=>change(relationKey,event.target.value||null)}><option value="">{t("successOps.noContext")}</option>{related.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="field"><span>{t("success.reason")}</span><input name="statusReason" maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label></>}
 {kind==="checkin"&&<><label className="field checkbox-field"><input name="assess_health" type="checkbox" checked={assess} onChange={event=>setAssess(event.target.checked)}/><span>{t("successOps.assessHealth")}</span></label><p className="field-help">{t("successOps.healthOptional")}</p>{assess&&<><label className="field"><span>{t("success.health")}</span><select name="assessment_health" value={health} onChange={event=>setHealth(event.target.value as typeof health)}>{successHealth.map(value=><option key={value} value={value}>{t(`success.health.${value}`)}</option>)}</select></label><label className="field"><span>{t("successOps.rationale")}</span><textarea name="rationale" maxLength={1000} value={rationale} onChange={event=>setRationale(event.target.value)}/></label></>}<label className="field checkbox-field"><input name="update_next_review" type="checkbox" checked={review} onChange={event=>setReview(event.target.checked)}/><span>{t("successOps.updateReview")}</span></label>{review&&<label className="field"><span>{t("success.nextReview")}</span><DateInput name="checkin_next_review" value={nextReview} onChange={event=>setNextReview(event.target.value)}/></label>}</>}
 <p className="field-help">{t("successOps.notesHelp")}</p></fieldset>{mutation.error&&<InlineMessage type="error">{mutation.error}</InlineMessage>}{mutation.uncertain&&<InlineMessage type="warning">{t("success.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={mutation.pending||mutation.uncertain} onClick={onClose}>{t("common.cancel")}</button>{mutation.conflict&&<button className="secondary-button" type="button" onClick={onReload}>{t("success.reload")}</button>}<button className="primary-button" disabled={mutation.pending||mutation.conflict}>{t(mutation.pending?"common.saving":mutation.uncertain?"success.retry":"common.save")}</button></div></form></AccessibleDrawer>;
}
