"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {hasCapability} from "@/lib/capabilities";
import {workflowTemplateActionSchema} from "@/lib/workflow-input";
import type {WorkflowTemplate,WorkflowTemplateDetail,WorkflowTemplatePage} from "@/lib/workflow-template-repository";
import {WorkflowTemplateEditor} from "./workflow-template-editor";
import {useI18n} from "./i18n-provider";
import {useAppUser} from "./app-user-context";
import {useUserPreferences} from "./user-preferences-context";
import {InlineMessage,StatusBadge} from "./ui";
export function WorkflowTemplatesWorkspace({initial}:{initial:WorkflowTemplatePage|null}){
 const {t,locale}=useI18n(),user=useAppUser(),{formatDate}=useUserPreferences(),[page,setPage]=useState(1),[data,setData]=useState<WorkflowTemplatePage>(initial??{items:[],page:1,pageSize:20,total:0}),[editor,setEditor]=useState<{record?:WorkflowTemplateDetail}|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(""),[uncertain,setUncertain]=useState(false),[notice,setNotice]=useState("");const attempt=useRef<ReturnType<typeof workflowTemplateActionSchema.parse>|null>(null),busy=useRef(false),canManage=hasCapability(user.role,"catalog.manage");
 const load=useCallback(async(signal?:AbortSignal)=>{try{const result=await apiFetch<WorkflowTemplatePage>(`/api/workflow-templates?page=${page}`,{signal});if(!signal?.aborted)setData(result);}catch(error){if(!signal?.aborted)setError(presentApiError(error,t,"workflow.loadFailed").message);}},[page,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const edit=async(row:WorkflowTemplate)=>{setPending(true);setError("");try{const result=await apiFetch<{item:WorkflowTemplateDetail}>(`/api/workflow-templates?id=${row.id}`);setEditor({record:result.item});}catch(error){setError(presentApiError(error,t,"workflow.loadFailed").message);}finally{setPending(false);}};
 const change=async(row?:WorkflowTemplate,operation?:"ACTIVATE"|"RETIRE"|"NEW_VERSION")=>{if(busy.current)return;if(!attempt.current){if(!row||!operation)return;attempt.current=workflowTemplateActionSchema.parse({id:row.id,expectedRevision:row.revision,requestKey:crypto.randomUUID(),operation,...(operation==="NEW_VERSION"?{newId:crypto.randomUUID()}:{})});}busy.current=true;setPending(true);setError("");let saved:WorkflowTemplate;try{saved=(await apiFetch<{item:WorkflowTemplate}>("/api/workflow-templates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)})).item;}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;setError(presentApiError(error,t,"workflow.saveFailed").message);busy.current=false;setPending(false);return;}const action=attempt.current.operation;attempt.current=null;setUncertain(false);setNotice(t("workflow.saved"));await load();if(action==="NEW_VERSION")await edit(saved);busy.current=false;setPending(false);};
 const disabled=pending||uncertain;
 return <div className="page-stack"><section className="page-heading-row"><div><h1>{t("workflow.templates")}</h1><p>{t("workflow.help")}</p></div>{canManage&&<button className="primary-button" disabled={disabled} onClick={()=>setEditor({})}>{t("workflow.create")}</button>}</section>{error&&<InlineMessage type="error">{error}</InlineMessage>}{notice&&<InlineMessage type="success">{notice}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}<button type="button" className="secondary-button" disabled={pending} onClick={()=>void change()}>{t("enrollments.retry")}</button></InlineMessage>}
 <section className="surface"><p className="field-help">{t("workflow.immutableHelp")}</p>{!data.items.length&&<p>{t("workflow.empty")}</p>}<div className="detail-record-list">{data.items.map(row=><article key={row.id}><div><b>{(locale==="en"?row.name_en:row.name_zh)||row.name_zh||row.name_en} · v{row.version}</b><p><StatusBadge tone={row.status==="ACTIVE"?"green":"gray"}>{t(`workflow.templateStatus.${row.status}`)}</StatusBadge> {row.used&&t("workflow.used")}</p><small>{(locale==="en"?row.product_name_en:row.product_name_zh)||t("workflow.generic")} · {t("workflow.steps")}: {row.step_count} · {formatDate(row.updated_at,{includeTime:true})}</small></div>{canManage&&row.can_edit&&<div className="detail-actions">{row.status==="DRAFT"&&!row.used&&<><button type="button" className="secondary-button" disabled={disabled} onClick={()=>void edit(row)}>{t("workflow.edit")}</button><button type="button" className="secondary-button" disabled={disabled} onClick={()=>void change(row,"ACTIVATE")}>{t("workflow.activate")}</button></>}{row.status==="ACTIVE"&&<button type="button" className="secondary-button" disabled={disabled} onClick={()=>void change(row,"RETIRE")}>{t("workflow.retire")}</button>}<button type="button" className="secondary-button" disabled={disabled} onClick={()=>void change(row,"NEW_VERSION")}>{t("workflow.newVersion")}</button></div>}</article>)}</div><div className="detail-actions"><button type="button" className="secondary-button" disabled={disabled||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button type="button" className="secondary-button" disabled={disabled||page*20>=data.total} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button><button type="button" className="secondary-button" disabled={disabled} onClick={()=>void load()}>{t("workflow.refresh")}</button></div></section>
 {editor&&<WorkflowTemplateEditor record={editor.record} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);setNotice(t("workflow.saved"));await load();}}/>}</div>;
}
