"use client";
import {useRef,useState} from "react";
import {isDefinitiveMutationFailure} from "@/lib/mutation-outcome";
import {apiFetch} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {workflowTemplateSaveSchema,workflowKinds,workflowBases,workflowCheckpoints,type WorkflowStep,type WorkflowTemplateData} from "@/lib/workflow-input";
import {workflowPresets,workflowPresetData} from "@/lib/workflow-presets";
import {milestoneTypes} from "@/lib/admission-milestone-input";
import type {WorkflowTemplateDetail} from "@/lib/workflow-template-repository";
import {useI18n} from "./i18n-provider";
import {AccessibleDrawer,InlineMessage} from "./ui";
import {EnrollmentRelation} from "./enrollment-relation";
export function newWorkflowStep(kind:WorkflowStep["step_kind"]="TASK",sequence=10):WorkflowStep{
 const base={id:crypto.randomUUID(),sequence,name_zh:"",name_en:"",required:true,default_owner_role:null,offset_basis:null,offset_days:null};
 return kind==="TASK"?{...base,step_kind:kind,task_config:{title_zh:"",title_en:"",description:"",priority:"NORMAL"},milestone_config:null,checkpoint_config:null}:kind==="MILESTONE"?{...base,step_kind:kind,task_config:null,milestone_config:{milestone_type:"INTERVIEW",default_status:"PENDING",application_scope:"ENROLLMENT"},checkpoint_config:null}:{...base,step_kind:kind,task_config:null,milestone_config:null,checkpoint_config:{checkpoint_type:"APPLICATION_SUBMITTED",application_scope:"APPLICATION"}};
}
export function WorkflowTemplateEditor({record,onClose,onSaved}:{record?:WorkflowTemplateDetail;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),[id]=useState(()=>record?.id??crypto.randomUUID()),[data,setData]=useState<WorkflowTemplateData>(()=>({name_zh:record?.name_zh??"",name_en:record?.name_en??"",product_id:record?.product_id??null,workflow_type:"ADMISSIONS",description:record?.description??"",steps:record?.steps??[newWorkflowStep()]})),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[accepted,setAccepted]=useState(false),[error,setError]=useState("");const attempt=useRef<ReturnType<typeof workflowTemplateSaveSchema.parse>|null>(null),busy=useRef(false);
 const step=(index:number,patch:Partial<WorkflowStep>)=>setData(previous=>({...previous,steps:previous.steps.map((s,i)=>i===index?{...s,...patch} as WorkflowStep:s)}));
 const move=(index:number,offset:number)=>setData(previous=>{const items=[...previous.steps];[items[index],items[index+offset]]=[items[index+offset],items[index]];return{...previous,steps:items.map((s,i)=>({...s,sequence:(i+1)*10}))};});
 const refreshAccepted=async()=>{try{await onSaved();}catch{setError(t("audit.savedRefreshFailed"));}};
 const save=async(event:React.FormEvent)=>{
  event.preventDefault();if(busy.current)return;
  if(accepted){busy.current=true;setPending(true);setError("");try{await refreshAccepted();}finally{busy.current=false;setPending(false);}return;}
  if(!attempt.current){const parsed=workflowTemplateSaveSchema.safeParse({id,expectedRevision:record?.revision??null,requestKey:crypto.randomUUID(),data});if(!parsed.success){setError(t("workflow.invalid"));return;}attempt.current=parsed.data;}
  busy.current=true;setPending(true);setError("");
  try{await apiFetch("/api/workflow-templates",{method:record?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}
  catch(error){const unknown=!isDefinitiveMutationFailure(error);setUncertain(unknown);if(!unknown)attempt.current=null;setError(presentApiError(error,t,"workflow.saveFailed").message);busy.current=false;setPending(false);return;}
  attempt.current=null;setUncertain(false);setAccepted(true);
  try{await refreshAccepted();}finally{busy.current=false;setPending(false);}
 };
 return <AccessibleDrawer title={t(record?"workflow.edit":"workflow.create")} description={t("workflow.immutableHelp")} pending={pending||uncertain} onClose={onClose}><form onSubmit={save}><fieldset className="follow-up-fields" disabled={pending||uncertain||accepted}>
 {!record&&<label className="field"><span>{locale==="en"?"Start from a preset":"从预设模板开始"}</span><select defaultValue="" onChange={event=>{setData(event.target.value?workflowPresetData(event.target.value):{name_zh:"",name_en:"",product_id:null,workflow_type:"ADMISSIONS",description:"",steps:[newWorkflowStep()]});}}><option value="">{locale==="en"?"Blank draft":"空白草稿"}</option>{workflowPresets.map(preset=><option key={preset.key} value={preset.key}>{locale==="en"?preset.nameEn:preset.nameZh}</option>)}</select><small>{locale==="en"?"Creates editable steps. Review before activating; no business record is completed automatically.":"预设步骤可修改。启用前请审核，不会自动完成业务记录。"}</small></label>}
 <div className="form-grid two-column">{(["name_zh","name_en"] as const).map(key=><label className="field" key={key}><span>{t(key==="name_zh"?"workflow.nameZh":"workflow.nameEn")}</span><input name={key} maxLength={160} value={data[key]} onChange={event=>setData(previous=>({...previous,[key]:event.target.value}))}/></label>)}</div>
 <EnrollmentRelation type="PRODUCT" label={t("products.product")} value={data.product_id??""} initialLabel={record?((locale==="en"?record.product_name_en:record.product_name_zh)||undefined):undefined} onChange={value=>setData(previous=>({...previous,product_id:value||null}))}/>
 <label className="field"><span>{t("workflow.description")}</span><textarea name="description" maxLength={2000} rows={2} value={data.description} onChange={event=>setData(previous=>({...previous,description:event.target.value}))}/></label>
 <h3>{t("workflow.steps")}</h3><p className="field-help">{t("workflow.ownerHelp")} {t("workflow.offsetHelp")}</p>
 {data.steps.map((s,index)=><section key={s.id} className="detail-section" data-workflow-step={index}><div className="detail-actions"><b>{s.sequence}</b><button type="button" className="secondary-button" disabled={index===0} onClick={()=>move(index,-1)}>{t("workflow.up")}</button><button type="button" className="secondary-button" disabled={index===data.steps.length-1} onClick={()=>move(index,1)}>{t("workflow.down")}</button><button type="button" className="text-button" disabled={data.steps.length===1} onClick={()=>setData(previous=>({...previous,steps:previous.steps.filter((_,i)=>i!==index).map((s,i)=>({...s,sequence:(i+1)*10}))}))}>{t("workflow.removeStep")}</button></div>
 <div className="form-grid two-column">{(["name_zh","name_en"] as const).map(key=><label className="field" key={key}><span>{t(key==="name_zh"?"workflow.nameZh":"workflow.nameEn")}</span><input name={`step_${index}_${key}`} maxLength={160} value={s[key]} onChange={event=>step(index,{[key]:event.target.value})}/></label>)}</div>
 <label className="field"><span>{t("workflow.kind")}</span><select name={`step_${index}_kind`} value={s.step_kind} onChange={event=>{const fresh=newWorkflowStep(event.target.value as WorkflowStep["step_kind"],s.sequence);step(index,{...fresh,id:s.id,name_zh:s.name_zh,name_en:s.name_en,required:s.required,default_owner_role:s.default_owner_role,offset_basis:s.offset_basis,offset_days:s.offset_days});}}>{workflowKinds.map(kind=><option key={kind} value={kind}>{t(`workflow.kind.${kind}`)}</option>)}</select></label>
 <label className="checkbox-field"><input type="checkbox" name={`step_${index}_required`} checked={s.required} onChange={event=>step(index,{required:event.target.checked})}/>{t("workflow.required")}</label>
 <label className="field"><span>{t("workflow.ownerRole")}</span><select name={`step_${index}_owner_role`} value={s.default_owner_role??""} onChange={event=>step(index,{default_owner_role:event.target.value as WorkflowStep["default_owner_role"]||null})}><option value="">{t("milestones.owner")}</option>{["SUPER_ADMIN","ADMIN","SALES_DIRECTOR","SALES_MANAGER","SALES_SPECIALIST","SALES_SUPPORT"].map(role=><option key={role} value={role}>{t(`workflow.role.${role}`)}</option>)}</select></label>
 <div className="form-grid two-column"><label className="field"><span>{t("workflow.basis")}</span><select name={`step_${index}_basis`} value={s.offset_basis??""} onChange={event=>step(index,{offset_basis:event.target.value as WorkflowStep["offset_basis"]||null,offset_days:event.target.value?s.offset_days??0:null})}><option value="">{t("business.unknown")}</option>{workflowBases.map(basis=><option value={basis} key={basis}>{t(`workflow.basis.${basis}`)}</option>)}</select></label><label className="field"><span>{t("workflow.offset")}</span><input name={`step_${index}_offset`} type="number" min={-3650} max={3650} disabled={!s.offset_basis} value={s.offset_days??""} onChange={event=>step(index,{offset_days:event.target.value===""?null:Number(event.target.value)})}/></label></div>
 {s.step_kind==="TASK"&&<>{(["title_zh","title_en","description"] as const).map(key=><label className="field" key={key}><span>{t(key==="title_zh"?"workflow.taskTitleZh":key==="title_en"?"workflow.taskTitleEn":"workflow.instructions")}</span><input name={`step_${index}_${key}`} maxLength={key==="description"?1000:160} value={s.task_config[key]} onChange={event=>step(index,{task_config:{...s.task_config,[key]:event.target.value}})}/></label>)}<p className="field-help">{t("workflow.instructionsHelp")}</p><label className="field"><span>{t("workflow.priority")}</span><select name={`step_${index}_priority`} value={s.task_config.priority} onChange={event=>step(index,{task_config:{...s.task_config,priority:event.target.value as "LOW"|"NORMAL"|"HIGH"|"URGENT"}})}>{["LOW","NORMAL","HIGH","URGENT"].map(p=><option key={p} value={p}>{t(`modules.priority.${p.toLowerCase()}`)}</option>)}</select></label></>}
 {s.step_kind==="MILESTONE"&&<><label className="field"><span>{t("milestones.type")}</span><select name={`step_${index}_milestone_type`} value={s.milestone_config.milestone_type} onChange={event=>step(index,{milestone_config:{...s.milestone_config,milestone_type:event.target.value as typeof s.milestone_config.milestone_type}})}>{milestoneTypes.map(type=><option value={type} key={type}>{t(`milestones.type.${type}`)}</option>)}</select></label><label className="field"><span>{t("workflow.scope")}</span><select name={`step_${index}_scope`} value={s.milestone_config.application_scope} onChange={event=>step(index,{milestone_config:{...s.milestone_config,application_scope:event.target.value as "ENROLLMENT"|"APPLICATION"}})}>{["ENROLLMENT","APPLICATION"].map(scope=><option key={scope} value={scope}>{t(`workflow.scope.${scope}`)}</option>)}</select></label></>}
 {s.step_kind==="CHECKPOINT"&&<><label className="field"><span>{t("workflow.checkpoint")}</span><select name={`step_${index}_checkpoint`} value={s.checkpoint_config.checkpoint_type} onChange={event=>step(index,{checkpoint_config:{checkpoint_type:event.target.value as typeof s.checkpoint_config.checkpoint_type,application_scope:"APPLICATION",...(event.target.value==="MILESTONE_COMPLETED"?{milestone_type:"INTERVIEW" as const}:{})}})}>{workflowCheckpoints.map(type=><option key={type} value={type}>{t(`workflow.checkpoint.${type}`)}</option>)}</select></label>{s.checkpoint_config.checkpoint_type==="MILESTONE_COMPLETED"&&<><label className="field"><span>{t("milestones.type")}</span><select name={`step_${index}_checkpoint_milestone`} value={s.checkpoint_config.milestone_type} onChange={event=>step(index,{checkpoint_config:{...s.checkpoint_config,milestone_type:event.target.value as NonNullable<typeof s.checkpoint_config.milestone_type>}})}>{milestoneTypes.map(type=><option key={type} value={type}>{t(`milestones.type.${type}`)}</option>)}</select></label><label className="field"><span>{t("workflow.scope")}</span><select value={s.checkpoint_config.application_scope} onChange={event=>step(index,{checkpoint_config:{...s.checkpoint_config,application_scope:event.target.value as "APPLICATION"|"ENROLLMENT"}})}>{["ENROLLMENT","APPLICATION"].map(scope=><option key={scope} value={scope}>{t(`workflow.scope.${scope}`)}</option>)}</select></label></>}</>}
 </section>)}<button type="button" className="secondary-button" disabled={data.steps.length>=40} onClick={()=>setData(previous=>({...previous,steps:[...previous.steps,newWorkflowStep("TASK",(previous.steps.length+1)*10)]}))}>{t("workflow.addStep")}</button>
 </fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={onClose}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":accepted?"ux.management.refresh":uncertain?"enrollments.retry":"common.save")}</button></div></form></AccessibleDrawer>;
}
