"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {apiFetch,ApiClientError} from "@/lib/api-client";
import {presentApiError} from "@/lib/api-error-presenter";
import {workflowStartSchema,workflowActionSchema} from "@/lib/workflow-input";
import type {WorkflowInstance,WorkflowPage,WorkflowStepInstance} from "@/lib/workflow-instance-repository";
import type {WorkflowTemplate,WorkflowTemplatePage} from "@/lib/workflow-template-repository";
import type {MilestoneRecord} from "@/lib/admission-milestone-repository";
import {useI18n} from "./i18n-provider";
import {useAppUser} from "./app-user-context";
import {useUserPreferences} from "./user-preferences-context";
import {InlineMessage,StatusBadge} from "./ui";
import {EnrollmentRelation} from "./enrollment-relation";
import {ApplicationSelector} from "./application-selector";
import {AdmissionMilestoneEditor} from "./admission-milestone-editor";
export function WorkflowsSection({enrollmentId,studentId,productId,cohortId,applicationId,ownerId,canEdit,onLock}:{enrollmentId:string;studentId:string;productId?:string;cohortId?:string;applicationId?:string;ownerId?:string|null;canEdit:boolean;onLock:(value:boolean)=>void}){
 const {t,locale}=useI18n(),{formatDate}=useUserPreferences(),[page,setPage]=useState(1),[data,setData]=useState<WorkflowPage>({items:[],page:1,pageSize:20,total:0}),[detail,setDetail]=useState<(WorkflowInstance&{steps:WorkflowStepInstance[]})|null>(null),[starting,setStarting]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(""),[uncertain,setUncertain]=useState(false),[operation,setOperation]=useState<{operation:"CANCEL"|"WAIVE"|"CANCEL_STEP";stepId?:string}|null>(null),[reason,setReason]=useState(""),[milestone,setMilestone]=useState<MilestoneRecord|null>(null);
 const attempt=useRef<ReturnType<typeof workflowActionSchema.parse>|null>(null),busy=useRef(false);
 const detailId=detail?.id;
 const load=useCallback(async(signal?:AbortSignal)=>{setError("");try{const result=await apiFetch<WorkflowPage>(`/api/workflows?enrollmentId=${enrollmentId}${applicationId?`&applicationId=${applicationId}`:""}&page=${page}`,{signal});if(!signal?.aborted)setData(result);if(detailId){const current=await apiFetch<{item:WorkflowInstance&{steps:WorkflowStepInstance[]}}>(`/api/workflows?id=${detailId}`,{signal});if(!signal?.aborted)setDetail(current.item);}}catch(error){if(!signal?.aborted)setError(presentApiError(error,t,"workflow.loadFailed").message);}},[enrollmentId,applicationId,page,detailId,t]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const open=async(id:string)=>{setPending(true);try{const result=await apiFetch<{item:WorkflowInstance&{steps:WorkflowStepInstance[]}}>(`/api/workflows?id=${id}`);setDetail(result.item);}catch(error){setError(presentApiError(error,t,"workflow.loadFailed").message);}finally{setPending(false);}};
 const operate=async(event:React.FormEvent)=>{event.preventDefault();if(busy.current||!detail||!operation)return;if(!attempt.current){const parsed=workflowActionSchema.safeParse({id:detail.id,expectedRevision:detail.revision,requestKey:crypto.randomUUID(),reason,...operation});if(!parsed.success){setError(t("workflow.invalid"));return;}attempt.current=parsed.data;}busy.current=true;setPending(true);onLock(true);setError("");try{await apiFetch("/api/workflows",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;onLock(unknown);setError(presentApiError(error,t,"workflow.saveFailed").message);busy.current=false;setPending(false);return;}attempt.current=null;setUncertain(false);onLock(false);setOperation(null);setReason("");await load();busy.current=false;setPending(false);};
 const openMilestone=async(id:string)=>{setPending(true);try{const result=await apiFetch<{item:MilestoneRecord}>(`/api/admission-milestones?id=${id}`);if(!result.item.can_edit){setError(t("workflow.forbidden"));return;}setMilestone(result.item);}catch(error){setError(presentApiError(error,t,"workflow.loadFailed").message);}finally{setPending(false);}};
 const locked=pending||uncertain;
 return <section className="detail-section" aria-label={t("workflow.workflow")}><h3>{t("workflow.workflow")}</h3><p className="field-help">{t("workflow.projectionHelp")}</p>{error&&<InlineMessage type="error">{error}</InlineMessage>}
 {starting?<WorkflowStartForm enrollmentId={enrollmentId} studentId={studentId} productId={productId} cohortId={cohortId} applicationId={applicationId} ownerId={ownerId} onLock={onLock} onCancel={()=>setStarting(false)} onSaved={async()=>{setStarting(false);await load();}}/>:milestone?<AdmissionMilestoneEditor key={milestone.id} record={milestone} enrollmentId={enrollmentId} studentId={studentId} applicationId={milestone.application_id??undefined} onLock={value=>{setPending(value);onLock(value);}} onCancel={()=>setMilestone(null)} onSaved={async()=>{setMilestone(null);await load();}}/>:operation?<form onSubmit={operate}><fieldset className="follow-up-fields" disabled={locked}><label className="field"><span>{t("workflow.reason")}</span><textarea name="workflow_reason" minLength={3} maxLength={500} required value={reason} onChange={event=>setReason(event.target.value)}/></label></fieldset>{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={locked} onClick={()=>setOperation(null)}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"enrollments.retry":"common.save")}</button></div></form>:detail?<>
 <button type="button" className="secondary-button" disabled={locked} onClick={()=>setDetail(null)}>{t("workflow.back")}</button><p><b>{(locale==="en"?detail.template_name_en:detail.template_name_zh)||detail.template_name_zh||detail.template_name_en} · v{detail.template_version}</b></p><StatusBadge tone={detail.projection.status==="COMPLETED"?"green":detail.projection.status==="BLOCKED"?"amber":"blue"}>{t(`workflow.status.${detail.projection.status}`)}</StatusBadge><p>{t("workflow.progress",{completed:detail.projection.completedOrWaivedSteps,total:detail.projection.totalSteps})}</p><p>{t("workflow.currentStep")}: {(()=>{const current=detail.steps.find(s=>["READY","IN_PROGRESS","BLOCKED"].includes(s.current_status));return current?((locale==="en"?current.name_en:current.name_zh)||current.name_en||current.name_zh):"—";})()}</p><div className="detail-record-list">{detail.steps.map(s=><article key={s.id}><div><b>{s.sequence} · {(locale==="en"?s.name_en:s.name_zh)||s.name_zh||s.name_en}</b><small>{t(`workflow.kind.${s.step_kind}`)} · {t(`workflow.stepStatus.${s.current_status}`)}</small><small>{t("milestones.due_at")}: {s.current_due_at?formatDate(s.current_due_at,{includeTime:true}):"—"} · {t("milestones.owner")}: {(locale==="en"?s.owner_name_en:s.owner_name_zh)||"—"}</small>{s.current_context_warning&&<p>{t(`workflow.warning.${s.current_context_warning}`)}</p>}{s.checkpoint_config&&<small>{t(`workflow.checkpoint.${s.checkpoint_config.checkpoint_type}`)}</small>}</div><div className="detail-actions">{s.task_id&&<Link className="secondary-button" href={`/tasks/${s.task_id}`}>{t("workflow.openTask")}</Link>}{s.milestone_id&&<button type="button" className="secondary-button" disabled={locked} onClick={()=>void openMilestone(s.milestone_id!)}>{t("workflow.openMilestone")}</button>}{detail.can_edit&&detail.projection.status!=="CANCELLED"&&!['COMPLETED','WAIVED'].includes(s.current_status)&&<><button type="button" className="secondary-button" disabled={locked} onClick={()=>{setReason("");setOperation({operation:"WAIVE",stepId:s.id});}}>{t("workflow.waive")}</button><button type="button" className="text-button" disabled={locked} onClick={()=>{setReason("");setOperation({operation:"CANCEL_STEP",stepId:s.id});}}>{t("workflow.cancelStep")}</button></>}</div></article>)}</div>{detail.can_edit&&detail.projection.status!=="CANCELLED"&&<button type="button" className="secondary-button" disabled={locked} onClick={()=>{setReason("");setOperation({operation:"CANCEL"});}}>{t("workflow.cancelWorkflow")}</button>}<button type="button" className="secondary-button" disabled={locked} onClick={()=>void load()}>{t("workflow.refresh")}</button></>:<>
 {canEdit&&<button type="button" className="secondary-button" disabled={locked} onClick={()=>setStarting(true)}>{t("workflow.start")}</button>}{!data.items.length&&<p>{t("workflow.noInstances")}</p>}<div className="detail-record-list">{data.items.map(w=><article key={w.id}><div><b>{(locale==="en"?w.template_name_en:w.template_name_zh)||w.template_name_zh||w.template_name_en} · v{w.template_version}</b><p><StatusBadge tone={w.projection.status==="COMPLETED"?"green":w.projection.status==="BLOCKED"?"amber":"blue"}>{t(`workflow.status.${w.projection.status}`)}</StatusBadge></p><small>{t("workflow.progress",{completed:w.projection.completedOrWaivedSteps,total:w.projection.totalSteps})} · {(locale==="en"?w.owner_name_en:w.owner_name_zh)||"—"}</small></div><button type="button" className="secondary-button" disabled={locked} onClick={()=>void open(w.id)}>{t("workflow.details")}</button></article>)}</div><div className="detail-actions"><button className="secondary-button" disabled={locked||page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button className="secondary-button" disabled={locked||page*20>=data.total} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button><button className="secondary-button" disabled={locked} onClick={()=>void load()}>{t("workflow.refresh")}</button></div></>}
 </section>;
}
function WorkflowStartForm({enrollmentId,studentId,productId,cohortId,applicationId,ownerId,onLock,onCancel,onSaved}:{enrollmentId:string;studentId:string;productId?:string;cohortId?:string;applicationId?:string;ownerId?:string|null;onLock:(value:boolean)=>void;onCancel:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),user=useAppUser(),[id]=useState(()=>crypto.randomUUID()),[page,setPage]=useState(1),[templates,setTemplates]=useState<WorkflowTemplatePage>({items:[],page:1,pageSize:20,total:0}),[selected,setSelected]=useState<WorkflowTemplate|null>(null),[app,setApp]=useState(applicationId??""),[owner,setOwner]=useState(ownerId??user.id),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState("");const attempt=useRef<ReturnType<typeof workflowStartSchema.parse>|null>(null),busy=useRef(false);
 useEffect(()=>{const controller=new AbortController();void (async()=>{const product=productId??(cohortId?(await apiFetch<{item:{product_id:string}}>(`/api/product-cohorts?id=${cohortId}`,{signal:controller.signal})).item.product_id:null);if(!product)throw Error("Missing product context");const value=await apiFetch<WorkflowTemplatePage>(`/api/workflow-templates?status=ACTIVE&productId=${product}&page=${page}`,{signal:controller.signal});if(!controller.signal.aborted)setTemplates(value);})().catch(error=>{if(!controller.signal.aborted)setError(presentApiError(error,t,"workflow.loadFailed").message);});return()=>controller.abort();},[productId,cohortId,page,t]);
 const start=async(event:React.FormEvent)=>{event.preventDefault();if(busy.current)return;if(!attempt.current){const parsed=workflowStartSchema.safeParse({id,templateId:selected?.id,templateVersion:selected?.version,enrollmentId,applicationId:app||null,ownerId:owner,requestKey:crypto.randomUUID()});if(!parsed.success){setError(t("workflow.invalid"));return;}attempt.current=parsed.data;}busy.current=true;setPending(true);onLock(true);setError("");try{await apiFetch("/api/workflows",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(attempt.current)});}catch(error){const unknown=!(error instanceof ApiClientError)||error.status===0||error.status>=500;setUncertain(unknown);if(!unknown)attempt.current=null;onLock(unknown);setError(presentApiError(error,t,"workflow.saveFailed").message);busy.current=false;setPending(false);return;}attempt.current=null;setUncertain(false);onLock(false);await onSaved();busy.current=false;setPending(false);};
 const options=selected&&!templates.items.some(w=>w.id===selected.id)?[selected,...templates.items]:templates.items;
 return <form onSubmit={start}><p className="field-help">{t("workflow.contextHelp")}</p><fieldset className="follow-up-fields" disabled={pending||uncertain}><label className="field"><span>{t("workflow.templateVersion")}</span><select name="workflow_template" required value={selected?.id??""} onChange={event=>setSelected(options.find(w=>w.id===event.target.value)??null)}><option value="">{t("business.unknown")}</option>{options.map(w=><option key={w.id} value={w.id}>{(locale==="en"?w.name_en:w.name_zh)||w.name_zh||w.name_en} · v{w.version}</option>)}</select></label><div className="detail-actions"><button type="button" className="secondary-button" disabled={page===1} onClick={()=>setPage(value=>value-1)}>{t("cohorts.previous")}</button><span>{page}</span><button type="button" className="secondary-button" disabled={page*20>=templates.total} onClick={()=>setPage(value=>value+1)}>{t("cohorts.next")}</button></div>{!applicationId&&<ApplicationSelector enrollmentId={enrollmentId} studentId={studentId} value={app} onChange={setApp}/>}
 <EnrollmentRelation type="USER" label={t("milestones.owner")} required value={owner} initialLabel={owner===user.id?user.displayName:undefined} onChange={setOwner}/>
 </fieldset>{error&&<InlineMessage type="error">{error}</InlineMessage>}{uncertain&&<InlineMessage type="warning">{t("enrollments.uncertain")}</InlineMessage>}<div className="drawer-actions"><button type="button" className="secondary-button" disabled={pending||uncertain} onClick={onCancel}>{t("common.cancel")}</button><button className="primary-button" disabled={pending}>{t(pending?"common.saving":uncertain?"enrollments.retry":"workflow.start")}</button></div></form>;
}
