import { ApiClientError } from "./api-client";

type Translator = (key: string, values?: Record<string, string | number>) => string;

const codeKeys: Record<string, string> = {
  SUCCESS_OUTCOME_VOIDED: "successOutcome.alreadyVoided",
  SUCCESS_VOID_REASON_REQUIRED: "successOutcome.invalid",
  SUCCESS_VERSION_CONFLICT: "success.conflict",
  SUCCESS_CASE_EXISTS: "success.caseExists",
  SUCCESS_REQUEST_CONFLICT: "success.requestConflict",
  SUCCESS_INPUT_INVALID: "success.invalid",
  SUCCESS_PARENT_IMMUTABLE: "success.parentImmutable",
  SUCCESS_OWNER_INVALID: "success.ownerInvalid",
  SUCCESS_ENROLLMENT_STATUS_INVALID: "success.enrollmentInvalid",
  SUCCESS_UPDATE_FORBIDDEN: "success.forbidden",
  SUCCESS_TASK_FORBIDDEN: "success.forbidden",
  SUCCESS_NOT_FOUND: "success.notFound",
  SUCCESS_CASE_NOT_FOUND: "success.notFound",
  SUCCESS_ENROLLMENT_NOT_FOUND: "success.notFound",
  SUCCESS_TASK_CONTEXT_MISMATCH: "success.taskMismatch",
  SUCCESS_GOAL_CONTEXT_MISMATCH: "success.taskMismatch",
  SUCCESS_CHECKIN_CONTEXT_MISMATCH: "successOps.contextMismatch",
  SUCCESS_RISK_CONTEXT_MISMATCH: "successOps.contextMismatch",
  SUCCESS_INTERVENTION_CONTEXT_MISMATCH: "successOps.contextMismatch",
  SUCCESS_TASK_ALREADY_LINKED: "success.taskAlreadyLinked",
  WORKFLOW_INPUT_INVALID: "workflow.invalid",
  WORKFLOW_FORBIDDEN: "workflow.forbidden",
  WORKFLOW_TEMPLATE_FORBIDDEN: "workflow.forbidden",
  WORKFLOW_REQUIRED_WAIVE_FORBIDDEN: "workflow.requiredWaive",
  WORKFLOW_NOT_FOUND: "workflow.notFound",
  WORKFLOW_VERSION_CONFLICT: "workflow.conflict",
  WORKFLOW_REQUEST_CONFLICT: "workflow.requestConflict",
  WORKFLOW_TEMPLATE_USED: "workflow.immutableHelp",
  WORKFLOW_TEMPLATE_IMMUTABLE: "workflow.immutableHelp",
  WORKFLOW_PARENT_IMMUTABLE: "workflow.immutableHelp",
  WORKFLOW_CONTEXT_REQUIRED: "workflow.contextRequired",
  WORKFLOW_OWNER_CONTEXT_REQUIRED: "workflow.ownerContext",
  WORKFLOW_OWNER_INVALID: "workflow.ownerContext",
  WORKFLOW_PRODUCT_MISMATCH: "workflow.productMismatch",
  WORKFLOW_STATE_INVALID: "workflow.stateInvalid",
  WORKFLOW_TEMPLATE_STATE_INVALID: "workflow.stateInvalid",
  WORKFLOW_APPLICATION_MISMATCH: "workflow.contextRequired",
  WORKFLOW_LINK_MISMATCH: "workflow.invalid",
  MILESTONE_INPUT_INVALID: "milestones.invalid",
  MILESTONE_DATES_INVALID: "milestones.invalid",
  MILESTONE_METADATA_INVALID: "milestones.invalid",
  MILESTONE_VERSION_CONFLICT: "milestones.versionConflict",
  MILESTONE_PARENT_IMMUTABLE: "milestones.parentImmutable",
  MILESTONE_REQUEST_CONFLICT: "milestones.requestConflict",
  MILESTONE_FORBIDDEN: "milestones.forbidden",
  MILESTONE_UPDATE_FORBIDDEN: "milestones.forbidden",
  MILESTONE_APPLICATION_FORBIDDEN: "milestones.forbidden",
  MILESTONE_APPLICATION_MISMATCH: "milestones.applicationMismatch",
  MILESTONE_OWNER_INVALID: "milestones.ownerInvalid",
  MILESTONE_NOT_FOUND: "milestones.notFound",
  MILESTONE_ENROLLMENT_NOT_FOUND: "milestones.notFound",
  APPLICATION_INPUT_INVALID: "applications.invalid",
  APPLICATION_LIFECYCLE_INVALID: "applications.invalid",
  APPLICATION_VERSION_CONFLICT: "applications.versionConflict",
  APPLICATION_PARENT_IMMUTABLE: "applications.parentImmutable",
  APPLICATION_REQUEST_CONFLICT: "applications.requestConflict",
  APPLICATION_ENROLLMENT_NOT_FOUND: "applications.notFound",
  APPLICATION_NOT_FOUND: "applications.notFound",
  APPLICATION_OWNER_INVALID: "applications.ownerInvalid",
  APPLICATION_UPDATE_FORBIDDEN: "applications.forbidden",
  APPLICATION_TARGET_FORBIDDEN: "applications.forbidden",
  APPLICATION_FORBIDDEN: "applications.forbidden",
  APPLICATION_TASK_STUDENT_MISMATCH: "applications.taskMismatch",
  COMMERCIAL_LINK_DUPLICATE: "commercial.duplicate",
  COMMERCIAL_LINK_FORBIDDEN: "commercial.forbidden",
  COMMERCIAL_QUOTE_FORBIDDEN: "permission.denied",
  COMMERCIAL_OPPORTUNITY_MISMATCH: "commercial.mismatch",
  COMMERCIAL_EVENT_MISMATCH: "commercial.mismatch",
  COMMERCIAL_CONTRACT_MISMATCH: "commercial.mismatch",
  COMMERCIAL_COHORT_MISMATCH: "commercial.mismatch",
  COMMERCIAL_VERSION_CONFLICT: "commercial.versionConflict",
  COMMERCIAL_REQUEST_CONFLICT: "commercial.requestConflict",
  COMMERCIAL_QUOTE_LOCKED: "commercial.quoteLocked",
  COMMERCIAL_INPUT_INVALID: "error.invalidInput",
  ENROLLMENT_INPUT_INVALID: "enrollments.invalid",
  ENROLLMENT_DUPLICATE: "enrollments.duplicate",
  ENROLLMENT_PRIMARY_CONFLICT: "enrollments.primaryConflict",
  ENROLLMENT_VERSION_CONFLICT: "enrollments.versionConflict",
  ENROLLMENT_PARENT_IMMUTABLE: "enrollments.parentImmutable",
  ENROLLMENT_REQUEST_CONFLICT: "enrollments.requestConflict",
  ENROLLMENT_COHORT_CLOSED: "enrollments.closed",
  ENROLLMENT_STUDENT_NOT_FOUND: "enrollments.notFound",
  ENROLLMENT_COHORT_NOT_FOUND: "enrollments.notFound",
  ENROLLMENT_NOT_FOUND: "enrollments.notFound",
  ENROLLMENT_UPDATE_FORBIDDEN: "permission.denied",
  ENROLLMENT_SOURCE_FORBIDDEN: "enrollments.sourceForbidden",
  ENROLLMENT_RELATED_FORBIDDEN: "enrollments.relatedForbidden",
  ENROLLMENT_OWNER_INVALID: "enrollments.ownerInvalid",
  ENROLLMENT_OPPORTUNITY_MISMATCH: "enrollments.opportunityMismatch",
  COHORT_CODE_CONFLICT: "cohorts.codeConflict",
  COHORT_VERSION_CONFLICT: "cohorts.versionConflict",
  COHORT_REQUEST_CONFLICT: "cohorts.requestConflict",
  COHORT_PARENT_IMMUTABLE: "cohorts.parentImmutable",
  COHORT_NOT_FOUND: "cohorts.notFound",
  COHORT_PRODUCT_NOT_FOUND: "cohorts.notFound",
  COHORT_UPDATE_FORBIDDEN: "permission.denied",
  COHORT_INPUT_INVALID: "cohorts.invalid",
  COHORT_OWNER_INVALID: "error.relatedConflict",
  EMAIL_TEMPLATE_VERSION_CONFLICT:"ux.templateConflict",
  EMAIL_TEMPLATE_IDEMPOTENCY_CONFLICT:"ux.templateCreateConflict",
  EMAIL_TEMPLATE_NOT_FOUND:"ux.templateNotFound",
  EMAIL_TEMPLATE_PUBLIC_FORBIDDEN:"permission.denied",
  EMAIL_PREVIEW_CHANGED:"customerOps.previewChanged",
  DATABASE_MIGRATION_REQUIRED:"customerOps.migrationRequired",
  CAPABILITY_FORBIDDEN: "permission.denied",
  DATABASE_PERMISSION_DENIED:"permission.denied",
  CRM_CREATE_FORBIDDEN:"permission.denied",
  CRM_UPDATE_FORBIDDEN:"permission.denied",
  CONTACT_OWNER_NOT_ASSIGNABLE:"customerOps.ownerNotAssignable",
  CONTACT_PROFILE_INVALID:"error.invalidInput",
  RELATED_RECORD_NOT_FOUND:"error.relatedConflict",
  FOLLOW_UP_IDEMPOTENCY_CONFLICT:"error.conflict",
  ROLE_FORBIDDEN: "permission.denied",
  MFA_REQUIRED: "permission.mfaRequired",
  INVALID_INPUT: "error.invalidInput",
  INVALID_LOCAL_TIME: "error.invalidLocalTime",
  INVALID_ID: "error.invalidInput",
  REQUEST_TIMEOUT: "error.timeout",
  NETWORK_ERROR: "error.network",
  SESSION_REFRESH_REQUIRED: "error.session",
  AUTH_REQUIRED: "error.session",
  RECORD_CONFLICT: "error.conflict",
  PRODUCT_CODE_CONFLICT: "products.codeConflict",
  PRODUCT_VERSION_CONFLICT: "products.versionConflict",
  PRODUCT_NOT_FOUND: "products.notFound",
  PRODUCT_ARCHIVED: "products.archived",
  PRODUCT_DELETE_NOT_AUTHORIZED: "permission.denied",
  PRODUCT_UPDATE_FORBIDDEN: "permission.denied",
  PRODUCT_UPDATE_NOT_AUTHORIZED: "permission.denied",
  PRODUCT_PRICE_NOT_AUTHORIZED: "permission.denied",
  DATABASE_SCHEMA_OUTDATED: "products.schemaOutdated",
  APPOINTMENT_IDEMPOTENCY_CONFLICT: "error.conflict",
  RELATED_RECORD_CONFLICT: "error.relatedConflict",
  CONSTRAINT_VIOLATION: "error.invalidInput",
  EDUCATION_VERSION_CONFLICT: "error.versionConflict",
  PROGRESSION_RULE_INVALID: "progression.ruleInvalid",
  PROGRESSION_ITEM_INVALID: "progression.itemInvalid",
  PROGRESSION_NOT_EDITABLE: "progression.notEditable",
  PROGRESSION_NOT_CANCELLABLE: "progression.notCancellable",
  STUDENT_VERSION_CONFLICT: "progression.studentConflict",
  LEAD_NOT_CONVERTIBLE: "leads.notConvertible",
  EDUCATION_RELATIONSHIP_SUBJECT_NOT_FOUND: "education.relationshipSubjectMissing",
  EDUCATION_RELATIONSHIP_NOT_FOUND: "education.relationshipMissing",
  EDUCATION_PRIMARY_REPLACEMENT_REQUIRED: "education.primaryReplacementRequired",
};

export type PresentedApiError = {
  message: string;
  code: string;
  field?: string;
  requestId?: string;
};

export function presentApiError(error: unknown, t: Translator, fallbackKey: string): PresentedApiError {
  if (!(error instanceof ApiClientError)) {
    return { message: t(fallbackKey), code: "UNKNOWN_ERROR" };
  }
  const base = t(codeKeys[error.code] ?? fallbackKey);
  const requestId = error.requestId;
  return {
    code: error.code,
    field: typeof error.details?.field === "string" ? error.details.field : undefined,
    requestId,
    message: `${base}${requestId ? ` · ${t("common.requestId")}: ${requestId}` : ""}`,
  };
}
