import type { AppRole } from "./roles";

export const CAPABILITIES = [
  "admin.access",
  "approvals.decide",
  "users.manage",
  "catalog.manage",
  "exchangeRates.manage",
  "finance.view",
  "finance.quote.create",
  "finance.payment.record",
  "finance.refund.complete",
  "finance.cashApplication.manage",
  "revenue.policy.view",
  "revenue.policy.manage",
  "revenue.policy.approve",
  "revenue.binding.manage",
  "revenue.configuration.view",
  "revenue.configuration.manage",
  "revenue.fulfillment.view",
  "revenue.fulfillment.manage",
  "revenue.fulfillment.verify",
  "revenue.recognition.view",
  "revenue.recognition.manage",
  "revenue.recognition.review",
  "revenue.recognition.post",
  "imports.view",
  "imports.execute",
  "dataQuality.manage",
  "performance.view",
  "performance.manage",
  "relationshipTargets.manage",
  "duplicates.manage",
  "privacyRequests.manage",
  "education.view",
  "education.manage",
  "progression.manage",
  "leads.view",
  "leads.manage",
  "opportunities.view",
  "opportunities.manage",
  "contracts.view",
  "contracts.manage",
  "calendar.view",
  "calendar.manage",
  "tasks.view",
  "tasks.manage",
  "messages.view",
  "messages.manage",
  "automation.manage",
  "portal.manage",
  "portal.decide",
  "ai.review",
  "exports.request",
  "workers.run",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

const administrator = new Set<Capability>(CAPABILITIES);
const roleCapabilities: Record<AppRole, ReadonlySet<Capability>> = {
  SUPER_ADMIN: administrator,
  ADMIN: administrator,
  FINANCE_MANAGER: new Set(["finance.view","finance.payment.record","contracts.view","calendar.view","calendar.manage","tasks.view","tasks.manage"]),
  FINANCE_SPECIALIST: new Set(["finance.view","contracts.view","calendar.view","calendar.manage","tasks.view","tasks.manage"]),
  OPERATIONS_MANAGER: new Set(["education.view","education.manage","calendar.view","calendar.manage","tasks.view","tasks.manage","messages.view"]),
  OPERATIONS_SPECIALIST: new Set(["education.view","education.manage","calendar.view","calendar.manage","tasks.view","tasks.manage"]),
  ACADEMIC_SPECIALIST: new Set(["education.view","education.manage","calendar.view","calendar.manage","tasks.view","tasks.manage"]),
  CUSTOMER_SUCCESS_SPECIALIST: new Set(["education.view","calendar.view","calendar.manage","tasks.view","tasks.manage","messages.view"]),
  SALES_DIRECTOR: new Set([
    "performance.view",
    "approvals.decide",
    "catalog.manage",
    "finance.view",
    "finance.quote.create",
    "imports.view",
    "imports.execute",
    "dataQuality.manage",
    "performance.manage",
    "relationshipTargets.manage",
    "duplicates.manage",
    "privacyRequests.manage",
    "education.view",
    "education.manage",
    "progression.manage",
    "leads.view",
    "leads.manage",
    "opportunities.view",
    "opportunities.manage",
    "contracts.view",
    "contracts.manage",
    "calendar.view",
    "calendar.manage",
    "tasks.view",
    "tasks.manage",
    "messages.view",
    "messages.manage",
    "automation.manage",
    "portal.manage",
    "portal.decide",
    "ai.review",
    "exports.request",
  ]),
  SALES_MANAGER: new Set([
    "performance.view",
    "approvals.decide",
    "finance.view",
    "finance.quote.create",
    "imports.view",
    "imports.execute",
    "dataQuality.manage",
    "performance.manage",
    "relationshipTargets.manage",
    "duplicates.manage",
    "education.view",
    "education.manage",
    "progression.manage",
    "leads.view",
    "leads.manage",
    "opportunities.view",
    "opportunities.manage",
    "contracts.view",
    "contracts.manage",
    "calendar.view",
    "calendar.manage",
    "tasks.view",
    "tasks.manage",
    "messages.view",
    "messages.manage",
    "automation.manage",
    "portal.manage",
    "portal.decide",
    "ai.review",
    "exports.request",
  ]),
  SALES_SPECIALIST: new Set([
    "performance.view",
    "finance.view",
    "finance.quote.create",
    "education.view",
    "education.manage",
    "leads.view",
    "leads.manage",
    "opportunities.view",
    "opportunities.manage",
    "contracts.view",
    "contracts.manage",
    "calendar.view",
    "calendar.manage",
    "tasks.view",
    "tasks.manage",
    "messages.view",
    "messages.manage",
    "portal.manage",
    "ai.review",
    "exports.request",
  ]),
  SALES_SUPPORT: new Set([
    "performance.view",
    "finance.view",
    "education.view",
    "education.manage",
    "leads.view",
    "opportunities.view",
    "contracts.view",
    "calendar.view",
    "calendar.manage",
    "tasks.view",
    "tasks.manage",
    "messages.view",
    "messages.manage",
    "portal.manage",
    "ai.review",
    "exports.request",
  ]),
};

export const aal2Capabilities = new Set<Capability>([
  "finance.cashApplication.manage",
  "revenue.recognition.post",
  "admin.access",
  "approvals.decide",
  "users.manage",
  "catalog.manage",
  "exchangeRates.manage",
  "finance.payment.record",
  "finance.refund.complete",
  "imports.execute",
  "dataQuality.manage",
  "performance.manage",
  "relationshipTargets.manage",
  "progression.manage",
  "privacyRequests.manage",
  "automation.manage",
  "portal.manage",
  "portal.decide",
  "workers.run",
]);

export function hasCapability(role: AppRole, capability: Capability) {
  return roleCapabilities[role].has(capability);
}

export function rolesForCapability(capability: Capability) {
  return (Object.keys(roleCapabilities) as AppRole[]).filter((role) => hasCapability(role, capability));
}
