import {databaseJson} from "./db/gateway";
import type {z} from "zod";
import type {Accrual,Eligibility,Settlement,accrualGenerateSchema,settlementSaveSchema,settlementTransitionSchema} from "./commission-input";
export function getCommissionEligibility(organizationId:string,enrollmentId:string|null=null,adapter=databaseJson){return adapter<{available:boolean;items:Eligibility[]}>("/db/rpc/commission_eligibility",{method:"POST",body:JSON.stringify({target_organization:organizationId,target_enrollment:enrollmentId})});}
export function listCommissionAccruals(organizationId:string,adapter=databaseJson){return adapter<Accrual[]>(`/db/table/commission_accrual_listing?${new URLSearchParams({organization_id:`eq.${organizationId}`,order:"accrued_at.desc,id.asc",limit:"100"})}`);}
export function listCommissionSettlements(organizationId:string,adapter=databaseJson){return adapter<Settlement[]>(`/db/table/commission_settlement_summary?${new URLSearchParams({organization_id:`eq.${organizationId}`,order:"created_at.desc,id.asc",limit:"100"})}`);}
export function generateCommissionAccrual(input:z.infer<typeof accrualGenerateSchema>,adapter=databaseJson){return adapter<Accrual>("/db/rpc/generate_commission_accrual",{method:"POST",body:JSON.stringify({target_rule:input.ruleId,target_enrollment:input.enrollmentId,target_payment:input.paymentId,p_request_key:input.requestKey})});}
export function saveCommissionSettlement(input:z.infer<typeof settlementSaveSchema>,adapter=databaseJson){return adapter<Settlement>("/db/rpc/save_commission_settlement",{method:"POST",body:JSON.stringify({target_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey})});}
export function changeCommissionSettlementStatus(id:string,input:z.infer<typeof settlementTransitionSchema>,adapter=databaseJson){return adapter<Settlement>("/db/rpc/change_commission_settlement_status",{method:"POST",body:JSON.stringify({target_id:id,expected_revision:input.expectedRevision,next_status:input.status,reference:input.reference,reason:input.reason,p_request_key:input.requestKey})});}
