import { supabaseAdminJson, supabaseJson, supabaseRequest } from "./supabase-server";

export type GeneratedJob={id:string;type:"CONTRACT_EXPORT"|"PERFORMANCE_SUMMARY"|"MARKETING_CONTACT_EXPORT"|"CRM_EXPORT";format:"CSV"|"XLSX"|"PDF";status:"QUEUED"|"PROCESSING"|"READY"|"FAILED"|"EXPIRED";createdAt:string;expiresAt:string|null;errorMessage:string|null};
export type GeneratedJobPage={items:GeneratedJob[];total:number;page:number;pageSize:number};

export async function listGeneratedJobs(options:{query?:string;status?:string;page?:number;pageSize?:number}={}):Promise<GeneratedJobPage>{const page=Math.max(1,Number(options.page??1));const pageSize=Math.max(1,Math.min(50,Number(options.pageSize??10)));const start=(page-1)*pageSize;const params=new URLSearchParams({select:"id,job_type,parameters,status,created_at,expires_at,error_message",order:"created_at.desc"});const query=(options.query??"").replace(/[*,()]/g," ").trim().slice(0,80);if(query)params.set("job_type",`ilike.*${query}*`);if(options.status&&options.status!=="all")params.set("status",`eq.${options.status}`);const response=await supabaseRequest(`/rest/v1/generated_jobs?${params}`,{headers:{Prefer:"count=exact",Range:`${start}-${start+pageSize-1}`}});const rows=await response.json() as Array<{id:string;job_type:GeneratedJob["type"];parameters:Record<string,unknown>;status:GeneratedJob["status"];created_at:string;expires_at:string|null;error_message:string|null}>;const total=Number((response.headers.get("content-range")??"*/0").split("/")[1]??rows.length);return{items:rows.map(row=>({id:row.id,type:row.job_type,format:["XLSX","PDF"].includes(String(row.parameters?.format))?String(row.parameters.format) as "XLSX"|"PDF":"CSV",status:row.status,createdAt:row.created_at,expiresAt:row.expires_at,errorMessage:row.error_message})),total,page,pageSize};}

export async function getGeneratedJob(id:string){const rows=await supabaseJson<Array<{id:string;status:GeneratedJob["status"];artifact_path:string|null;expires_at:string|null}>>(`/rest/v1/generated_jobs?select=id,status,artifact_path,expires_at&id=eq.${encodeURIComponent(id)}&limit=1`);return rows[0]??null;}

export async function signGeneratedJob(path:string){const encoded=path.split("/").map(encodeURIComponent).join("/");return supabaseAdminJson<{signedURL:string}>(`/storage/v1/object/sign/crm-exports/${encoded}`,{method:"POST",body:JSON.stringify({expiresIn:60})});}
