import {z} from "zod";
import {attentionHref,type AttentionItem} from "./management-metric-contract";
export const attentionReasons=["OVERDUE_RECEIVABLE","OVERDUE_MILESTONE","BLOCKED_WORKFLOW","HIGH_OPEN_RISK","STALE_CHECKIN","HIGH_QUALITY_FINDING"] as const;
export const attentionDomains=["FINANCE","ADMISSIONS","STUDENT_SUCCESS","DATA_QUALITY"] as const;
export const attentionFiltersSchema=z.object({page:z.coerce.number().int().min(1).max(100000).default(1),pageSize:z.coerce.number().int().refine(n=>[10,20,50,100].includes(n)).default(20),domain:z.enum(attentionDomains).optional(),reason:z.enum(attentionReasons).optional(),presentationSeverity:z.enum(["ATTENTION","CRITICAL"]).optional(),sort:z.enum(["PRIORITY","OLDEST","NEWEST"]).default("PRIORITY"),productId:z.uuid().optional(),cohortId:z.uuid().optional()}).strict();
export type AttentionFilters=z.input<typeof attentionFiltersSchema>;
type Contexts={OVERDUE_RECEIVABLE:{kind:"FINANCE";dueDate:string;daysOverdue:number;currency:string|null;outstandingAmount:string|null;moneyVisible:boolean};OVERDUE_MILESTONE:{kind:"MILESTONE";milestoneType:string;status:string;daysOverdue:number};BLOCKED_WORKFLOW:{kind:"WORKFLOW";status:string;templateId:string;templateVersion:number;startedAt:string};HIGH_OPEN_RISK:{kind:"RISK";riskType:string;sourceSeverity:string;status:string;observedAt:string;health:string;lastCheckinAt:string|null;activeInterventionCount:number};STALE_CHECKIN:{kind:"CASE";status:string;health:string;lastCheckinAt:string|null;nextReviewOn:string|null;openRiskCount:number;activeInterventionCount:number};HIGH_QUALITY_FINDING:{kind:"QUALITY";ruleKey:string;sourceSeverity:string;status:string;entityType:string;entityId:string}};
type Base={attentionKey:string;sourceDomain:typeof attentionDomains[number];sourceType:string;sourceId:string;contextId:string;presentationSeverity:"ATTENTION"|"CRITICAL";sourceDate:string|null;dueDate:string|null;canonicalRoute:string;canonicalReference:string;productId:string|null;cohortId:string|null};
export type AttentionRow={[K in keyof Contexts]:Base&{reasonCode:K;context:Contexts[K]}}[keyof Contexts];
export type AttentionPage={asOf:string;timezone:string;mode:"SNAPSHOT";page:number;pageSize:number;total:number;summary:{byDomain:Record<string,number>;byReason:Record<string,number>;bySeverity:Record<string,number>};filters:AttentionFilters;filterApplied:Record<string,string>;items:AttentionRow[]};
export type AttentionRawPage=Omit<AttentionPage,"items">&{items:Array<AttentionItem&{attention_key:string;product_id:string|null;cohort_id:string|null;due_at:string|null;context:AttentionRow["context"]}>};
export function attentionSourceRoute(item:AttentionRawPage["items"][number]){if(item.context.kind==="QUALITY")return attentionHref({...item,source_type:item.context.entityType,source_id:item.context.entityId});return attentionHref(item);}
export function projectAttention(raw:AttentionRawPage):AttentionPage{return {...raw,items:raw.items.map(item=>({attentionKey:item.attention_key,sourceDomain:item.source_domain,sourceType:item.source_type,sourceId:item.source_id,contextId:item.context_id,reasonCode:item.reason_code,presentationSeverity:item.severity,sourceDate:item.business_date,dueDate:item.due_at,canonicalRoute:attentionSourceRoute(item),canonicalReference:item.source_reference??item.source_id,productId:item.product_id,cohortId:item.cohort_id,context:item.context.kind==="FINANCE"&&!item.context.moneyVisible?{...item.context,currency:null,outstandingAmount:null}:item.context}) as AttentionRow)};}
export function attentionQueueHref(filters:{productId?:string;cohortId?:string}={}){const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined) as [string,string][]);return "/reports/executive/attention"+(q.size?"?"+q.toString():"");}
