import {z} from "zod";
import {metricDefinitions,type ManagementMetricKey,type ManagementModule,type MetricValue} from "./management-metric-contract";

const businessDate=z.iso.date();
const fields={from:businessDate.optional(),to:businessDate.optional(),productId:z.uuid().optional(),cohortId:z.uuid().optional()};
const validRange=(v:{from?:string;to?:string})=>!v.from||!v.to||(v.from<=v.to&&(Date.parse(v.to)-Date.parse(v.from))/86400000<730);
export const overviewFiltersSchema=z.object(fields).strict().refine(validRange);
export const trendFiltersSchema=z.object({...fields,granularity:z.enum(["DAY","WEEK","MONTH"]).optional()}).strict().refine(validRange);
export type TrendFilters=z.infer<typeof trendFiltersSchema>;
export function comparablePeriod(from:string,to:string){const days=(Date.parse(to)-Date.parse(from))/86400000+1;return{from:new Date(Date.parse(from)-days*86400000).toISOString().slice(0,10),to:new Date(Date.parse(from)-86400000).toISOString().slice(0,10)};}
export function effectiveGranularity(days:number,requested?:TrendFilters["granularity"]){const minimum=days<=45?"DAY":days<=180?"WEEK":"MONTH";return (["DAY","WEEK","MONTH"].indexOf(requested??minimum)<["DAY","WEEK","MONTH"].indexOf(minimum)?minimum:requested??minimum) as NonNullable<TrendFilters["granularity"]>;}
export type ManagementComparison={current:number|string;previous:number|string;absoluteChange:number|string;percentChange:number|string|null};
export type ManagementTrendPoint={bucketStart:string;bucketEnd:string;value:number|string};
export type ManagementTrendSeries={key:ManagementMetricKey;module:ManagementModule;unit:MetricValue["unit"];currency:string|null;comparison:ManagementComparison;points:ManagementTrendPoint[]};
export type ManagementTrends={asOf:string;period:{from:string;to:string;timezone:string};previousPeriod:{from:string;to:string};granularity:NonNullable<TrendFilters["granularity"]>;permissions:Record<ManagementModule|"commissionMoney",boolean>;series:ManagementTrendSeries[];filters:{productId:string|null;cohortId:string|null};filterApplied:Record<ManagementModule,string>};

// One typed route contract, reused by existing domain lists. URL filters grant no access.
export const exactDrills={openLeads:"/leads",qualifiedLeads:"/leads",leadsCreated:"/leads",leadsConverted:"/leads",openOpportunities:"/opportunities",opportunitiesWon:"/opportunities",opportunitiesLost:"/opportunities",activeEnrollments:"/enrollments",openEnrollments:"/enrollments",enrollmentsCreated:"/enrollments",enrollmentsActivated:"/enrollments",enrollmentsCompleted:"/enrollments",enrollmentsWithdrawn:"/enrollments",enrollmentsCancelled:"/enrollments",atRiskCases:"/student-success",activeCases:"/student-success",visibleCases:"/student-success",attentionCases:"/student-success",payments_in_period:"/finance",outcomesRecorded:"/student-success",recordedOutcomes:"/student-success"} as const;
export type ExactDrillKey=keyof typeof exactDrills;
export const reportFilterSchema=z.object({reportMetric:z.enum(Object.keys(exactDrills) as [ExactDrillKey,...ExactDrillKey[]]).optional(),from:businessDate.optional(),to:businessDate.optional(),productId:z.uuid().optional(),cohortId:z.uuid().optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional()}).refine(v=>!v.from||!v.to||(v.from<=v.to&&(Date.parse(v.to)-Date.parse(v.from))/86400000<730));
export type ReportFilter=z.infer<typeof reportFilterSchema>;
export function readReportFilter(params:Record<string,unknown>,route:string):ReportFilter{const filter=reportFilterSchema.parse(params);if(filter.reportMetric&&exactDrills[filter.reportMetric]!==route)throw new Error("MANAGEMENT_DRILL_INVALID");return filter;}
export function applyReportFilter(params:URLSearchParams,filter:ReportFilter){if(filter.reportMetric)params.set("report_filter",JSON.stringify(reportFilterSchema.parse(filter)));}
export function metricDrillHref(metric:Pick<MetricValue,"key"|"mode"|"currency">,filters:TrendFilters={},period?:{from:string;to:string}){if(!(metric.key in exactDrills))return null;const key=metric.key as ExactDrillKey;const args:ReportFilter={reportMetric:key,...(metric.mode==="PERIOD"?{from:period?.from??filters.from,to:period?.to??filters.to}:{}),...(metric.currency?{currency:metric.currency}:{}),...(exactDrills[key]!=="/leads"?{productId:filters.productId,cohortId:filters.cohortId}:{})};if(key==="outcomesRecorded"||key==="recordedOutcomes")return `/student-success?view=outcomes&${new URLSearchParams(Object.entries(args).filter(([,v])=>v!==undefined) as [string,string][])}`;return `${exactDrills[key]}?${new URLSearchParams(Object.entries(args).filter(([,v])=>v!==undefined) as [string,string][])}`;}
export const moduleDrillRoutes:Record<ManagementModule,string>={commercial:"/opportunities",delivery:"/enrollments",finance:"/finance",channel:"/reports/channels",admissions:"/applications",studentSuccess:"/student-success?view=analytics"};
export function metricContextHref(key:ManagementMetricKey,filters:TrendFilters){const domain=metricDefinitions[key][0],route=moduleDrillRoutes[domain],args=new URLSearchParams();if(domain==="channel"){if(filters.productId)args.set("product",filters.productId);if(filters.cohortId)args.set("cohort",filters.cohortId);}else if(domain!=="commercial"){if(filters.productId)args.set("productId",filters.productId);if(filters.cohortId)args.set("cohortId",filters.cohortId);}if(metricDefinitions[key][1]==="PERIOD"||domain==="studentSuccess"){if(filters.from)args.set("from",filters.from);if(filters.to)args.set("to",filters.to);}return route+(args.size?(route.includes("?")?"&":"?")+args.toString():"");}
export const metricTrendContract=Object.fromEntries(Object.entries(metricDefinitions).map(([key,definition])=>[key,{trend:definition[1]==="PERIOD",comparison:definition[1]==="PERIOD",bucketDate:definition[3],drilldown:key in exactDrills?exactDrills[key as ExactDrillKey]:moduleDrillRoutes[definition[0]],filters:definition[0]==="commercial"&&definition[2]==="leads"?[]:["productId","cohortId"],limitation:definition[1]==="SNAPSHOT"?"No historical-as-of snapshot; no comparison":key.startsWith("opportunities")||key==="won_value"?"Current WON/LOST with closed_at; not historical funnel":"Canonical business dates; visible records only"}])) as Record<ManagementMetricKey,{trend:boolean;comparison:boolean;bucketDate:string;drilldown:string|null;filters:string[];limitation:string}>;
