import {z} from "zod";
export const managementModules=["commercial","delivery","finance","channel","admissions","studentSuccess"] as const;
export type ManagementModule=typeof managementModules[number];
export type MetricMode="SNAPSHOT"|"PERIOD";
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
export const managementFiltersSchema=z.object({from:date.optional(),to:date.optional()}).strict().refine(v=>!v.from||!v.to||(v.from<=v.to&&Date.parse(v.to)-Date.parse(v.from)<=3660*86400000));
export type ManagementFilters=z.infer<typeof managementFiltersSchema>;
// Typed code registry; this is a read contract, never a business-fact registry.
export const metricDefinitions={
 openLeads:["commercial","SNAPSHOT","leads","current status"],qualifiedLeads:["commercial","SNAPSHOT","leads","current status"],openOpportunities:["commercial","SNAPSHOT","opportunities","current stage"],
 leadsCreated:["commercial","PERIOD","leads","created_at"],leadsConverted:["commercial","PERIOD","leads","converted_at"],opportunitiesWon:["commercial","PERIOD","opportunities","closed_at"],opportunitiesLost:["commercial","PERIOD","opportunities","closed_at"],open_value:["commercial","SNAPSHOT","opportunities","current stage"],won_value:["commercial","PERIOD","opportunities","closed_at"],
 activeProducts:["delivery","SNAPSHOT","products","current active"],recruitingCohorts:["delivery","SNAPSHOT","product_cohorts","current status"],activeCohorts:["delivery","SNAPSHOT","product_cohorts","current status"],completedCohorts:["delivery","SNAPSHOT","product_cohorts","current status"],openEnrollments:["delivery","SNAPSHOT","student_enrollments","current status"],activeEnrollments:["delivery","SNAPSHOT","student_enrollments","current status"],
 enrollmentsCreated:["delivery","PERIOD","student_enrollments","created_at"],enrollmentsActivated:["delivery","PERIOD","student_enrollment_status_history","changed_at"],enrollmentsCompleted:["delivery","PERIOD","student_enrollment_status_history","changed_at"],enrollmentsWithdrawn:["delivery","PERIOD","student_enrollment_status_history","changed_at"],enrollmentsCancelled:["delivery","PERIOD","student_enrollment_status_history","changed_at"],
 contracted:["finance","SNAPSHOT","contract_finance_snapshot","current contract"],receivable:["finance","SNAPSHOT","contract_finance_snapshot","current schedule"],collected:["finance","SNAPSHOT","contract_finance_snapshot","current net confirmed receipts"],netCollected:["finance","SNAPSHOT","contract_finance_snapshot","alias of collected"],refunded:["finance","SNAPSHOT","contract_finance_snapshot","current completed refund balance"],gross_confirmed:["finance","SNAPSHOT","contract_finance_snapshot","current confirmed gross receipts"],outstanding:["finance","SNAPSHOT","contract_finance_snapshot","current schedule balance"],overdue:["finance","SNAPSHOT","contract_finance_snapshot","workspace business date"],payments_in_period:["finance","PERIOD","payments","paid_at"],refunds_in_period:["finance","PERIOD","refunds","refunded_at"],
 visibleAccounts:["channel","SNAPSHOT","channel_analytics","current visible organizations"],availablePublicLeads:["channel","SNAPSHOT","channel_analytics","current pool availability"],channelOpenOpportunities:["channel","SNAPSHOT","channel_analytics","current stage"],primaryContributions:["channel","SNAPSHOT","channel_analytics","current explicit attribution"],assistContributions:["channel","SNAPSHOT","channel_analytics","current explicit attribution"],eventsHeld:["channel","PERIOD","channel_analytics","event starts_on"],commissionNet:["channel","SNAPSHOT","commission_accruals via channel_analytics","ledger entries"],commissionOpen:["channel","SNAPSHOT","commission_accruals via channel_analytics","noncancelled settlement reservation"],commissionPeriod:["channel","PERIOD","commission_accruals via channel_analytics","accrued_at"],commissionPaid:["channel","PERIOD","commission_settlements via channel_analytics","paid_at"],
 applicationsSubmitted:["admissions","PERIOD","student_applications","submitted_at"],applicationsDecided:["admissions","PERIOD","student_applications","decision_at"],milestonesCompleted:["admissions","PERIOD","admission_milestones","completed_at"],workflowsStarted:["admissions","PERIOD","workflow_instances","started_at"],workflowsCompleted:["admissions","PERIOD","workflow_instances","completed_at"],
 applicationsInProgress:["admissions","SNAPSHOT","student_applications","current status"],applicationsDueSoon:["admissions","SNAPSHOT","student_applications","deadline_on in next 7 calendar days"],applicationsPastDeadline:["admissions","SNAPSHOT","student_applications","deadline_on before business date"],openMilestones:["admissions","SNAPSHOT","admission_milestones","current nonterminal status"],overdueMilestones:["admissions","SNAPSHOT","admission_milestones","due_at before asOf"],activeWorkflows:["admissions","SNAPSHOT","workflow_instances","current status"],blockedWorkflows:["admissions","SNAPSHOT","workflow_instances","current status"],completedWorkflows:["admissions","SNAPSHOT","workflow_instances","current status"],
 visibleCases:["studentSuccess","SNAPSHOT","student_success_analytics","current visible cases"],activeCases:["studentSuccess","SNAPSHOT","student_success_analytics","current status"],attentionCases:["studentSuccess","SNAPSHOT","student_success_analytics","ATTENTION or AT_RISK"],atRiskCases:["studentSuccess","SNAPSHOT","student_success_analytics","current AT_RISK"],openRisks:["studentSuccess","SNAPSHOT","student_success_analytics","OPEN or MONITORING"],highOpenRisks:["studentSuccess","SNAPSHOT","student_success_analytics","HIGH and OPEN or MONITORING"],activeInterventions:["studentSuccess","SNAPSHOT","student_success_analytics","current status"],withoutRecentCheckin:["studentSuccess","SNAPSHOT","student_success_analytics","30 calendar day convention"],recordedOutcomes:["studentSuccess","SNAPSHOT","student_success_analytics","non-VOIDED"],goalAttainment:["studentSuccess","SNAPSHOT","student_success_analytics","ACHIEVED / (ACHIEVED + NOT_ACHIEVED); null denominator zero"],
 checkins:["studentSuccess","PERIOD","student_success_analytics","occurred_at"],healthAssessments:["studentSuccess","PERIOD","student_success_analytics","assessed_at"],risksObserved:["studentSuccess","PERIOD","student_success_analytics","observed_at"],risksResolved:["studentSuccess","PERIOD","student_success_analytics","resolved_at"],interventionsStarted:["studentSuccess","PERIOD","student_success_analytics","started_on"],interventionsCompleted:["studentSuccess","PERIOD","student_success_analytics","completed_at"],goalsAchieved:["studentSuccess","PERIOD","student_success_analytics","achieved_at"],outcomesRecorded:["studentSuccess","PERIOD","student_success_analytics","occurred_on"]
} as const satisfies Record<string,readonly[ManagementModule,MetricMode,string,string]>;
export type ManagementMetricKey=keyof typeof metricDefinitions;
export type MetricValue={key:ManagementMetricKey;value:number|string|null;unit:"COUNT"|"MONEY"|"RATIO";currency:string|null;mode:MetricMode;source:string;dateSemantics:string;asOf:string;period:{from:string;to:string;timezone:string}|null};
export type AttentionItem={source_domain:string;source_type:string;source_id:string;context_id:string;reason_code:string;severity:"ATTENTION"|"CRITICAL";business_date:string|null;source_reference?:string|null;context?:{kind:string;entityType?:string;entityId?:string}};
export type ManagementOverviewProjection={asOf:string;period:{from:string;to:string;timezone:string};filters?:{productId:string|null;cohortId:string|null};filterApplied?:Record<string,string>;permissions:Record<ManagementModule|"commissionMoney"|"quality",boolean>;modules:Record<ManagementModule,{available:boolean;metrics:MetricValue[];distributions:Record<string,Record<string,number>>}>;channelContributions:Array<{organizationId:string;nameZh:string;nameEn:string;primary:number;assist:number}>;attention:{total:number;limit:number;items:AttentionItem[]};quality:{count:number;distribution:Array<{entity_type:string;severity:string;count:number}>}};
export function attentionHref(item:AttentionItem):string{
 if(item.context?.kind==="QUALITY"&&item.context.entityType&&item.context.entityId)return attentionHref({...item,context:undefined,source_type:item.context.entityType,source_id:item.context.entityId});
 if(item.source_domain==="FINANCE"||item.source_type==="CONTRACT")return `/contracts?focus=${encodeURIComponent(item.context_id)}&query=${encodeURIComponent(item.source_reference??"")}`;
 if(item.source_domain==="ADMISSIONS")return `/enrollments?focus=${encodeURIComponent(item.context_id)}&tab=${item.source_type==="WORKFLOW"?"workflow":"admissions"}&source=${encodeURIComponent(item.source_id)}`;
 if(item.source_domain==="STUDENT_SUCCESS")return `/student-success?focus=${encodeURIComponent(item.context_id)}`;
 if(item.source_type.startsWith("STUDENT_SUCCESS_"))return `/student-success?focus=${encodeURIComponent(item.context_id)}`;
 if(["ENROLLMENT","ADMISSION_MILESTONE","WORKFLOW"].includes(item.source_type))return `/enrollments?focus=${encodeURIComponent(item.context_id)}`;
 if(item.source_type==="APPLICATION")return `/applications?focus=${encodeURIComponent(item.source_id)}`;
 if(item.source_type==="OPPORTUNITY")return `/opportunities?focus=${encodeURIComponent(item.source_id)}`;
 if(item.source_type==="CONTACT")return `/people/${encodeURIComponent(item.source_id)}`;
 if(item.source_type==="ORGANIZATION")return `/schools/${encodeURIComponent(item.source_id)}`;
 return "/data-quality";
}
