import type { Capability } from "./capabilities";

/** Canonical resource names, not client-supplied database identifiers. */
export const deletionResources = [
  { kind: "ORGANIZATION", label: "nav.schools", capability: "education.manage", table: "organizations" },
  { kind: "CONTACT", label: "ux.nav.contacts", capability: "education.manage", table: "contacts" },
  { kind: "STUDENT", label: "ux.nav.students", capability: "education.manage", table: "students" },
  { kind: "HOUSEHOLD", label: "ux.nav.families", capability: "education.manage", table: "households" },
  { kind: "TASK", label: "ux.nav.tasks", capability: "tasks.manage", table: "crm_tasks" },
  { kind: "PRODUCT", label: "nav.products", capability: "catalog.manage", table: "products" },
  { kind: "LEAD", label: "nav.leads", capability: "leads.manage", table: "leads" },
  { kind: "OPPORTUNITY", label: "nav.opportunities", capability: "opportunities.manage", table: "opportunities" },
  { kind: "CONTRACT", label: "nav.contracts", capability: "contracts.manage", table: "contracts" },
  { kind: "ENROLLMENT", label: "ux.nav.enrollments", capability: "education.manage", table: "student_enrollments" },
  { kind: "APPLICATION", label: "ux.nav.applications", capability: "education.manage", table: "student_applications" },
  { kind: "SUPPORT_CASE", label: "success.title", capability: "education.manage", table: "student_success_cases" },
  { kind: "SUPPORT_GOAL", label: "success.goals", capability: "education.manage", table: "student_success_goals" },
  { kind: "SUPPORT_CHECKIN", label: "successOps.checkins", capability: "education.manage", table: "student_success_checkins" },
  { kind: "SUPPORT_RISK", label: "successOps.risks", capability: "education.manage", table: "student_success_risk_signals" },
  { kind: "SUPPORT_INTERVENTION", label: "successOps.interventions", capability: "education.manage", table: "student_success_interventions" },
  { kind: "ORGANIZATION_PROFILE", label: "business.resource.organizations", capability: "education.manage", table: "organization_business_profiles" },
  { kind: "FAMILY_NEED", label: "business.resource.needs", capability: "education.manage", table: "family_education_needs" },
  { kind: "PATHWAY", label: "business.resource.pathways", capability: "education.manage", table: "student_pathways" },
  { kind: "OUTREACH_EVENT", label: "business.resource.events", capability: "education.manage", table: "education_outreach_events" },
  { kind: "REFERRAL", label: "business.resource.referrals", capability: "education.manage", table: "education_family_referrals" },
  { kind: "EVENT_PARTICIPATION", label: "business.resource.participations", capability: "education.manage", table: "education_event_participations" },
  { kind: "ACADEMIC_RECORD", label: "education.academic", capability: "education.manage", table: "student_academic_records" },
  { kind: "COHORT", label: "cohorts.title", capability: "catalog.manage", table: "product_cohorts" },
  { kind: "BUNDLE", label: "products.bundles", capability: "catalog.manage", table: "product_bundles" },
  { kind: "QUOTE", label: "finance.quotes", capability: "finance.quote.create", table: "quotes" },
  { kind: "CAMPAIGN", label: "growth.campaigns", capability: "leads.manage", table: "growth_campaigns" },
  { kind: "ADMISSION_JOURNEY", label: "growth.admissions", capability: "leads.manage", table: "admission_journeys" },
  { kind: "MILESTONE", label: "repair.milestones", capability: "education.manage", table: "admission_milestones" },
  { kind: "WORKFLOW_TEMPLATE", label: "ux.nav.workflowTemplates", capability: "catalog.manage", table: "workflow_templates" },
  { kind: "APPOINTMENT", label: "nav.calendar", capability: "calendar.manage", table: "appointments" },
  { kind: "EXCHANGE_RATE", label: "products.exchangeRates", capability: "exchangeRates.manage", table: "exchange_rate_snapshots" },
  { kind: "ADMISSION_OUTCOME", label: "repair.admissionOutcomes", capability: "education.manage", table: "organization_admission_outcomes" },
  { kind: "CONTACT_INTELLIGENCE", label: "repair.contactIntelligence", capability: "education.manage", table: "organization_contact_intelligence" },
  { kind: "CONTACT_RELATIONSHIP", label: "repair.contactRelationship", capability: "education.manage", table: "organization_contact_relationships" },
  { kind: "FOLLOWUP_PLAN", label: "repair.followupPlan", capability: "education.manage", table: "customer_follow_up_plans" },
  { kind: "FOLLOWUP_ENTRY", label: "repair.followupEntry", capability: "education.manage", table: "customer_follow_up_entries" },
  { kind: "ACTIVITY", label: "repair.activities", capability: "education.manage", table: "crm_activities" },
  { kind: "IMPORT_BATCH", label: "imports.batches", capability: "imports.execute", table: "import_batches" },
  { kind: "IMPORT_MAPPING", label: "imports.mappingProfile", capability: "imports.execute", table: "import_mapping_profiles" },
  { kind: "IMPORT_SET", label: "closure.importSets", capability: "imports.execute", table: "import_sets" },
  { kind: "PRODUCT_PRICE", label: "products.price", capability: "catalog.manage", table: "product_prices" },
  { kind: "CHANNEL_AGREEMENT", label: "commission.agreements", capability: "catalog.manage", table: "channel_agreements" },
  { kind: "CHANNEL_AGREEMENT_VERSION", label: "commission.version", capability: "catalog.manage", table: "channel_agreement_versions" },
] as const satisfies readonly { kind: string; label: string; capability: Capability; table: string }[];
export type DeletionKind = typeof deletionResources[number]["kind"];
export type DeletionItem = { id: string; label: string; status: string | null; revision: number | null; updatedAt: string | null; canDelete: boolean; blockedReason: "PROTECTED_STATE" | "REFERENCED" | null };
