import { NextResponse } from "next/server";
import { authorizeScim, scimErrorSchema } from "./scim";
import { SupabaseRequestError } from "./supabase-server";

export async function requireScim(request:Request){if(!await authorizeScim(request))throw new SupabaseRequestError(401,"SCIM_UNAUTHORIZED","Valid SCIM bearer authorization is required");}
export function scimJson(body:unknown,status=200,headers:HeadersInit={}){return NextResponse.json(body,{status,headers:{"content-type":"application/scim+json",...Object.fromEntries(new Headers(headers)),"cache-control":"no-store"}});}
const safeDetails:Record<string,string>={SCIM_UNAUTHORIZED:"Valid SCIM bearer authorization is required.",SCIM_FILTER_UNSUPPORTED:"The requested SCIM filter is unsupported.",SCIM_USER_NOT_FOUND:"The SCIM user was not found.",SCIM_VERSION_CONFLICT:"The SCIM user changed concurrently; reload and retry.",RECORD_CONFLICT:"The external ID or user name is already in use.",CONSTRAINT_VIOLATION:"The SCIM resource violates a lifecycle constraint.",SUPABASE_UNAVAILABLE:"The directory store is temporarily unavailable.",UPSTREAM_TIMEOUT:"The directory store timed out."};
const scimTypes:Record<string,string>={SCIM_FILTER_UNSUPPORTED:"invalidFilter",SCIM_USER_NOT_FOUND:"noTarget",SCIM_VERSION_CONFLICT:"mutability",RECORD_CONFLICT:"uniqueness",CONSTRAINT_VIOLATION:"invalidValue",INVALID_INPUT:"invalidValue"};
export function scimFailure(error:unknown){const known=error instanceof SupabaseRequestError;const status=known?error.status:500;const code=known&&/^[A-Z][A-Z0-9_]{2,80}$/.test(error.code)?error.code:"SCIM_FAILED";const detail=safeDetails[code]??"The SCIM request could not be completed.";const scimType=scimTypes[code];return scimJson({schemas:[scimErrorSchema],status:String(status),...(scimType?{scimType}:{}),detail},status,status===401?{"www-authenticate":"Bearer realm=\"Lumina CRM SCIM\""}:{});}
