import {applyReportFilter,type ReportFilter} from "./management-trend-contract";
import {databaseJson,databaseRequest} from "./db/gateway";
import type {z} from "zod";
import type {SuccessCaseData,SuccessGoalData,successFiltersSchema,successCaseSaveSchema,successGoalSaveSchema,successTaskLinkSchema} from "./student-success-input";
export type SuccessCase=SuccessCaseData&{id:string;workspace_id:string;revision:number;created_at:string;updated_at:string;student_id:string;cohort_id:string;product_id:string;enrollment_status:string;enrollment_owner_id:string;enrollment_owner_name_zh:string|null;enrollment_owner_name_en:string|null;student_name_zh:string;student_name_en:string;student_number:string|null;cohort_name_zh:string;cohort_name_en:string;product_name_zh:string;product_name_en:string;owner_name_zh:string|null;owner_name_en:string|null;active_goal_count:number;open_task_count:number;can_edit:boolean;last_checkin_at?:string|null;open_risk_count?:number;high_risk_count?:number;active_intervention_count?:number;recorded_outcome_count?:number;achieved_outcome_count?:number;partial_outcome_count?:number;not_achieved_outcome_count?:number;observed_outcome_count?:number};
export type SuccessGoal=SuccessGoalData&{owner_name_zh?:string|null;owner_name_en?:string|null;id:string;revision:number;created_at:string;updated_at:string};
export type SuccessHistory={id:string;from_status:SuccessCaseData["status"]|null;to_status:SuccessCaseData["status"];changed_at:string;reason:string;case_revision:number};
export type SuccessTask={id:string;task_id:string;case_id:string;goal_id:string|null;intervention_id?:string|null;revision:number;title_zh:string;title_en:string;status:string;priority:string;due_at:string|null;owner_id:string|null;can_edit:boolean};
export type SuccessPage={items:SuccessCase[];total:number;page:number;pageSize:number};
type Adapter={json:typeof databaseJson;request:typeof databaseRequest};const database:Adapter={json:databaseJson,request:databaseRequest};
export async function listSuccessCases(options:Partial<z.infer<typeof successFiltersSchema>>&{reportFilter?:ReportFilter},adapter=database):Promise<SuccessPage>{
 const page=options.page??1,pageSize=options.pageSize??20,params=new URLSearchParams({order:"updated_at.desc,id.asc"});
 for(const [column,key] of [["student_id","studentId"],["enrollment_id","enrollmentId"],["product_id","productId"],["cohort_id","cohortId"],["owner_id","ownerId"],["status","status"],["health_status","health"]] as const)if(options[key])params.set(column,`eq.${options[key]}`);
 if(options.reviewFrom&&options.reviewTo)params.set("and",`(next_review_on.gte.${options.reviewFrom},next_review_on.lte.${options.reviewTo})`);else if(options.reviewFrom)params.set("next_review_on",`gte.${options.reviewFrom}`);else if(options.reviewTo)params.set("next_review_on",`lte.${options.reviewTo}`);
 if(options.reportFilter)applyReportFilter(params,options.reportFilter);
 const response=await adapter.request(`/db/table/student_success_records?${params}`,{headers:{Prefer:"count=exact",Range:`${(page-1)*pageSize}-${page*pageSize-1}`}}),items=await response.json() as SuccessCase[];
 return{items,total:Number(response.headers.get("content-range")?.split("/")[1]??items.length),page,pageSize};
}
export async function getSuccessCase(id:string,adapter=database){return(await adapter.json<SuccessCase[]>(`/db/table/student_success_records?${new URLSearchParams({id:`eq.${id}`,limit:"1"})}`))[0]??null;}
export function listSuccessGoals(caseId:string,page=1,adapter=database){return adapter.json<SuccessGoal[]>(`/db/table/student_success_goal_records?${new URLSearchParams({case_id:`eq.${caseId}`,order:"created_at.asc,id.asc",limit:"50",offset:String((page-1)*50)})}`);}
export function listSuccessHistory(caseId:string,page=1,adapter=database){return adapter.json<SuccessHistory[]>(`/db/table/student_success_case_status_history?${new URLSearchParams({case_id:`eq.${caseId}`,order:"changed_at.asc,id.asc",limit:"50",offset:String((page-1)*50)})}`);}
export function listSuccessTasks(caseId:string,page=1,adapter=database,interventionId?:string){return adapter.json<SuccessTask[]>(`/db/table/student_success_task_records?${new URLSearchParams({case_id:`eq.${caseId}`,order:"created_at.asc,id.asc",limit:"50",offset:String((page-1)*50),...(interventionId?{intervention_id:`eq.${interventionId}`}:{})})}`);}
export function listSuccessTaskOptions(studentId:string,query="",adapter=database){const params=new URLSearchParams({related_type:"eq.STUDENT",related_id:`eq.${studentId}`,archived_at:"is.null",order:"updated_at.desc,id.asc",limit:"20",select:"id,title_zh,title_en"});const clean=query.replace(/[*,()%_]/g," ").trim();if(clean)params.set("or",`(title_zh.ilike.*${clean}*,title_en.ilike.*${clean}*)`);return adapter.json<Array<{id:string;title_zh:string;title_en:string}>>(`/db/table/crm_tasks?${params}`);}
export function saveSuccessCase(input:z.infer<typeof successCaseSaveSchema>,adapter=database){return adapter.json<SuccessCase>("/db/rpc/save_student_success_case",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey,status_reason:input.statusReason})});}
export function saveSuccessGoal(input:z.infer<typeof successGoalSaveSchema>,adapter=database){return adapter.json<SuccessGoal>("/db/rpc/save_student_success_goal",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey})});}
export function saveSuccessTaskLink(input:z.infer<typeof successTaskLinkSchema>,adapter=database){return adapter.json<SuccessTask>(input.interventionId?"/db/rpc/save_student_success_intervention_task_link":"/db/rpc/save_student_success_task_link",{method:"POST",body:JSON.stringify({record_id:input.id,target_case:input.caseId,target_task:input.taskId,target_goal:input.goalId,...(input.interventionId?{target_intervention:input.interventionId}:{}),expected_revision:input.expectedRevision,unlink:input.unlink,p_request_key:input.requestKey})});}
