import {databaseJson} from "./db/gateway";
import type {z} from "zod";
import type {successCheckinDataSchema,successRiskDataSchema,successInterventionDataSchema,successCheckinSaveSchema,successRiskSaveSchema,successInterventionSaveSchema} from "./student-success-operations-input";
type Identity={id:string;workspace_id:string;revision:number;created_at:string;updated_at:string};
export type SuccessCheckin=z.infer<typeof successCheckinDataSchema>&Identity&{conducted_name_zh:string|null;conducted_name_en:string|null;assessments:Array<{id:string;health_status:string;assessed_at:string}>|null};
export type SuccessRisk=z.infer<typeof successRiskDataSchema>&Identity&{owner_name_zh:string|null;owner_name_en:string|null;source_checkin_at?:string|null;active_intervention_count:number};
export type SuccessIntervention=z.infer<typeof successInterventionDataSchema>&Identity&{owner_name_zh:string|null;owner_name_en:string|null;risk_summary:string|null;visible_task_count:number};
export type SuccessOperationalHistory={id:string;case_id:string;source_type:"CASE"|"HEALTH"|"RISK"|"INTERVENTION";reference_id:string;from_status:string|null;to_status:string;changed_at:string;changed_by:string|null;reason:string|null;revision:number};
export type SuccessAssessment={id:string;case_id:string;checkin_id:string|null;health_status:string;assessed_at:string;assessed_by:string;rationale:string|null;case_revision:number};
export const successOperationResources={checkins:"student_success_checkin_records",assessments:"student_success_health_assessments",risks:"student_success_risk_records",interventions:"student_success_intervention_records",operationHistory:"student_success_operational_history"} as const;
export function listSuccessOperations(caseId:string,resource:keyof typeof successOperationResources,page=1,adapter=databaseJson){const date=resource==="checkins"?"occurred_at":resource==="assessments"?"assessed_at":resource==="operationHistory"?"changed_at":"created_at";return adapter<Array<SuccessCheckin|SuccessRisk|SuccessIntervention|SuccessOperationalHistory|SuccessAssessment>>(`/db/table/${successOperationResources[resource]}?${new URLSearchParams({case_id:`eq.${caseId}`,order:`${date}.desc,id.asc`,limit:"50",offset:String((page-1)*50)})}`);}
export function saveSuccessCheckin(input:z.infer<typeof successCheckinSaveSchema>,adapter=databaseJson){return adapter<SuccessCheckin>("/db/rpc/save_student_success_checkin",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey,options:input.options})});}
export function saveSuccessRisk(input:z.infer<typeof successRiskSaveSchema>,adapter=databaseJson){return adapter<SuccessRisk>("/db/rpc/save_student_success_risk",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey,status_reason:input.statusReason})});}
export function saveSuccessIntervention(input:z.infer<typeof successInterventionSaveSchema>,adapter=databaseJson){return adapter<SuccessIntervention>("/db/rpc/save_student_success_intervention",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey,status_reason:input.statusReason})});}
