import { createHash, randomBytes } from "node:crypto";
import { supabaseAdminJson, supabaseJson, supabaseRequest } from "./supabase-server";

export type AutomationRuleRecord={id:string;nameZh:string;nameEn:string;triggerKey:string;conditions:Record<string,unknown>;actionType:"TASK"|"NOTIFICATION";actionConfig:Record<string,unknown>;active:boolean;version:number;createdAt:string};
export type AutomationRunRecord={id:string;ruleId:string;status:string;resultType:string;errorCode:string;attemptCount:number;lastAttemptAt:string;createdAt:string;ruleNameZh:string;ruleNameEn:string};
export type AutomationPreview={ruleId:string;version:number;matches:boolean;trigger:string;conditions:Record<string,unknown>;actionType:string;actionConfig:Record<string,unknown>;sideEffects:false};
type AutomationRuleRow={id:string;name_zh:string;name_en:string;trigger_key:string;conditions:Record<string,unknown>;action_type:"TASK"|"NOTIFICATION";action_config:Record<string,unknown>;active:boolean;version:number;created_at:string};
export async function loadAutomationWorkspace(){
  const [rules,runs]=await Promise.all([
    supabaseJson<AutomationRuleRow[]>("/rest/v1/automation_rules?select=id,name_zh,name_en,trigger_key,conditions,action_type,action_config,active,version,created_at&order=created_at.desc"),
    supabaseJson<Array<{id:string;rule_id:string;status:string;result_type:string|null;error_code:string|null;attempt_count:number;last_attempt_at:string;created_at:string;automation_rules:{name_zh:string;name_en:string}|null}>>("/rest/v1/automation_runs?select=id,rule_id,status,result_type,error_code,attempt_count,last_attempt_at,created_at,automation_rules(name_zh,name_en)&order=created_at.desc&limit=30"),
  ]);
  return{rules:rules.map(row=>({id:row.id,nameZh:row.name_zh,nameEn:row.name_en,triggerKey:row.trigger_key,conditions:row.conditions,actionType:row.action_type,actionConfig:row.action_config,active:row.active,version:Number(row.version),createdAt:row.created_at})),runs:runs.map(row=>({id:row.id,ruleId:row.rule_id,status:row.status,resultType:row.result_type??"",errorCode:row.error_code??"",attemptCount:Number(row.attempt_count),lastAttemptAt:row.last_attempt_at,createdAt:row.created_at,ruleNameZh:row.automation_rules?.name_zh??"",ruleNameEn:row.automation_rules?.name_en??""}))};
}
export async function createAutomationRule(input:{nameZh:string;nameEn:string;triggerKey:string;conditionField?:string;conditionValue?:string;actionType:"TASK"|"NOTIFICATION";titleZh:string;titleEn:string;priority:string;dueHours:number}){
  const conditions=input.conditionField&&input.conditionValue?{[input.conditionField]:input.conditionValue}:{};
  return supabaseJson("/rest/v1/automation_rules",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({name_zh:input.nameZh,name_en:input.nameEn,trigger_key:input.triggerKey,conditions,action_type:input.actionType,action_config:{titleZh:input.titleZh,titleEn:input.titleEn,priority:input.priority,dueHours:input.dueHours}})});
}
export async function setAutomationRuleActive(id:string,active:boolean){return supabaseJson(`/rest/v1/automation_rules?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({active,updated_at:new Date().toISOString()})});}
export async function runAutomationEvent(input:{trigger:string;eventKey:string;payload:Record<string,unknown>}){return supabaseJson<Record<string,unknown>>("/rest/v1/rpc/run_automation_event",{method:"POST",body:JSON.stringify({target_trigger:input.trigger,target_event_key:input.eventKey,target_payload:input.payload})});}
export async function previewAutomationRule(id:string,payload:Record<string,unknown>){return supabaseJson<AutomationPreview>("/rest/v1/rpc/preview_automation_rule",{method:"POST",body:JSON.stringify({target_rule:id,target_payload:payload})});}
export async function retryAutomationRun(id:string){return supabaseJson<Record<string,unknown>>("/rest/v1/rpc/retry_automation_run",{method:"POST",body:JSON.stringify({target_run:id})});}

export type GrowthCampaign={id:string;code:string;nameZh:string;nameEn:string;channel:string;status:string;budget:number;currency:string;startsOn:string|null;endsOn:string|null;touches:number;leads:number;converted:number;pipelineByCurrency:Record<string,number>;wonByCurrency:Record<string,number>;enrolled:number};
export type AdmissionJourney={id:string;leadId:string|null;studentId:string|null;stage:string;probability:number;nextAction:string;nextActionAt:string|null;nameZh:string;nameEn:string};
export type GrowthSummary={activeCampaigns:number;attributedLeads:number;convertedLeads:number;pendingAdmissions:number};
export type GrowthSnapshot={campaigns:GrowthCampaign[];journeys:AdmissionJourney[];channels:Array<{channel:string;touches:number;leads:number}>;summary:GrowthSummary};
export async function loadGrowthPerformance(){return supabaseJson<{summary:GrowthSummary;campaigns:Array<{id:string;pipelineByCurrency:Record<string,number>;wonByCurrency:Record<string,number>;enrolled:number}>}>("/rest/v1/rpc/growth_performance_snapshot",{method:"POST",body:"{}"});}
export async function loadGrowthSnapshot(){const[snapshot,performance]=await Promise.all([supabaseJson<Omit<GrowthSnapshot,"summary">>("/rest/v1/rpc/growth_snapshot",{method:"POST",body:"{}"}),loadGrowthPerformance()]);const performanceMap=new Map(performance.campaigns.map(item=>[item.id,item]));return{...snapshot,summary:performance.summary,campaigns:snapshot.campaigns.map(campaign=>({...campaign,pipelineByCurrency:Object.fromEntries(Object.entries(performanceMap.get(campaign.id)?.pipelineByCurrency??{}).map(([currency,value])=>[currency,Number(value)])),wonByCurrency:Object.fromEntries(Object.entries(performanceMap.get(campaign.id)?.wonByCurrency??{}).map(([currency,value])=>[currency,Number(value)])),enrolled:Number(performanceMap.get(campaign.id)?.enrolled??0)}))};}
export async function createGrowthCampaign(input:{code:string;nameZh:string;nameEn:string;channel:string;status:string;budget:number;currency:string;startsOn?:string|null;endsOn?:string|null}){return supabaseJson("/rest/v1/growth_campaigns",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({code:input.code,name_zh:input.nameZh,name_en:input.nameEn,channel:input.channel,status:input.status,budget:input.budget,currency:input.currency,starts_on:input.startsOn||null,ends_on:input.endsOn||null})});}
export async function recordAttribution(input:{leadId:string;campaignId?:string|null;touchType:string;channel:string;source:string;medium:string;content:string}){return supabaseJson("/rest/v1/lead_attribution_touches",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({lead_id:input.leadId,campaign_id:input.campaignId||null,touch_type:input.touchType,channel:input.channel,source:input.source,medium:input.medium,content:input.content})});}
export async function saveAdmissionJourney(input:{leadId?:string|null;studentId?:string|null;stage:string;probability:number;nextAction:string;nextActionAt?:string|null}){
  const target=input.leadId?`lead_id=eq.${input.leadId}`:`student_id=eq.${input.studentId}`;
  const existing=await supabaseJson<Array<{id:string}>>(`/rest/v1/admission_journeys?select=id&${target}&limit=1`);
  const body={lead_id:input.leadId||null,student_id:input.studentId||null,stage:input.stage,probability:input.probability,next_action:input.nextAction,next_action_at:input.nextActionAt||null,updated_at:new Date().toISOString()};
  return existing[0]?supabaseJson(`/rest/v1/admission_journeys?id=eq.${existing[0].id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(body)}):supabaseJson("/rest/v1/admission_journeys",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(body)});
}

export type PortalInvitationRecord={id:string;householdId:string;householdZh:string;householdEn:string;email:string;status:string;expiresAt:string;lastAccessedAt:string|null;createdAt:string};
export type PortalUpdateRecord={id:string;invitationId:string;changes:Record<string,string>;appliedChanges:Record<string,string>;status:string;decisionNote:string;createdAt:string};
export async function loadPortalWorkspace(){
  const [invitations,updates]=await Promise.all([
    supabaseJson<Array<{id:string;household_id:string;invited_email:string;status:string;expires_at:string;last_accessed_at:string|null;created_at:string;households:{name_zh:string;name_en:string}|null}>>("/rest/v1/portal_invitations?select=id,household_id,invited_email,status,expires_at,last_accessed_at,created_at,households(name_zh,name_en)&order=created_at.desc"),
    supabaseJson<Array<{id:string;invitation_id:string;requested_changes:Record<string,string>;applied_changes:Record<string,string>;status:string;decision_note:string;created_at:string}>>("/rest/v1/portal_update_requests?select=id,invitation_id,requested_changes,applied_changes,status,decision_note,created_at&order=created_at.desc&limit=100"),
  ]);
  return{invitations:invitations.map(row=>({id:row.id,householdId:row.household_id,householdZh:row.households?.name_zh??"",householdEn:row.households?.name_en??"",email:row.invited_email,status:row.status,expiresAt:row.expires_at,lastAccessedAt:row.last_accessed_at,createdAt:row.created_at})),updates:updates.map(row=>({id:row.id,invitationId:row.invitation_id,changes:row.requested_changes,appliedChanges:row.applied_changes??{},status:row.status,decisionNote:row.decision_note,createdAt:row.created_at}))};
}
const portalDigest=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function createPortalInvitation(input:{householdId:string;guardianContactId?:string|null;email:string;expiresAt:string}){
  const token=randomBytes(32).toString("base64url");
  const row=await supabaseJson<{id:string}>("/rest/v1/rpc/create_guardian_portal_invitation",{method:"POST",body:JSON.stringify({target_household:input.householdId,target_email:input.email,target_digest:portalDigest(token),target_expires_at:input.expiresAt})});
  return{id:row.id,token};
}
export async function revokePortalInvitation(id:string){return supabaseJson("/rest/v1/rpc/revoke_guardian_portal_invitation",{method:"POST",body:JSON.stringify({target_invitation:id})});}
export async function decidePortalUpdate(id:string,status:"APPROVED"|"REJECTED",note:string){return supabaseJson("/rest/v1/rpc/decide_portal_update",{method:"POST",body:JSON.stringify({target_update:id,next_status:status,decision:note})});}
export type PublicPortalSnapshot={invitationId:string;expiresAt:string;consentRequired:boolean;household:{id:string;nameZh:string;nameEn:string;address:string};students:Array<{id:string;nameZh:string;nameEn:string;grade:string;academicYear:string;status:string}>;pendingUpdates:number};
export async function loadPublicPortal(token:string){return supabaseAdminJson<PublicPortalSnapshot>("/rest/v1/rpc/service_portal_snapshot",{method:"POST",body:JSON.stringify({target_digest:portalDigest(token)})});}
export async function submitPublicPortalUpdate(token:string,requestKey:string,changes:Record<string,string>){return supabaseAdminJson<string>("/rest/v1/rpc/service_submit_portal_update",{method:"POST",body:JSON.stringify({target_digest:portalDigest(token),target_request_key:requestKey,target_changes:changes})});}
export async function acceptPublicPortalConsent(token:string,requestKey:string){return supabaseAdminJson("/rest/v1/rpc/service_accept_portal_consent",{method:"POST",body:JSON.stringify({target_digest:portalDigest(token),target_request_key:requestKey,target_terms_version:"2026-07",target_privacy_version:"2026-07"})});}

export type CommunicationThreadRecord={id:string;contactId:string;contactZh:string;contactEn:string;email:string;subject:string;channel:string;purpose:string;status:string;lastMessageAt:string|null;messages:Array<{id:string;direction:string;body:string;deliveryStatus:string;lastError:string;attemptCount:number;createdAt:string}>};
export async function loadCommunications(query=""){return supabaseJson<CommunicationThreadRecord[]>("/rest/v1/rpc/communication_inbox_snapshot",{method:"POST",body:JSON.stringify({search_term:query,result_limit:100})});}
export async function createCommunicationThread(input:{contactId:string;subject:string;channel:string;purpose:string}){return supabaseJson<{id:string}>("/rest/v1/rpc/create_communication_thread",{method:"POST",body:JSON.stringify({target_contact:input.contactId,target_subject:input.subject,target_channel:input.channel,target_purpose:input.purpose})});}
export async function queueCommunicationMessage(threadId:string,body:string,idempotencyKey:string){return supabaseJson<{id:string}>("/rest/v1/rpc/queue_communication_message",{method:"POST",body:JSON.stringify({target_thread:threadId,target_body:body,target_idempotency_key:idempotencyKey})});}
export async function recordInboundCommunication(threadId:string,body:string,idempotencyKey:string){return supabaseJson<{id:string}>("/rest/v1/rpc/record_inbound_communication",{method:"POST",body:JSON.stringify({target_thread:threadId,target_body:body,target_idempotency_key:idempotencyKey})});}
export async function retryCommunicationMessage(id:string){return supabaseJson<{id:string;thread_id:string;body:string}>("/rest/v1/rpc/retry_communication_message",{method:"POST",body:JSON.stringify({target_message:id})});}
export async function communicationRecipient(threadId:string){const rows=await supabaseJson<Array<{subject:string;contacts:{email:string|null;name_zh:string;name_en:string}|null}>>(`/rest/v1/communication_threads?select=subject,contacts(email,name_zh,name_en)&id=eq.${threadId}&limit=1`);return rows[0];}
export async function completeCommunication(id:string,providerId:string){return supabaseAdminJson("/rest/v1/rpc/service_complete_communication",{method:"POST",body:JSON.stringify({target_message:id,target_provider_id:providerId})});}
export async function failCommunication(id:string,failure:string){return supabaseAdminJson("/rest/v1/rpc/service_fail_communication",{method:"POST",body:JSON.stringify({target_message:id,failure})});}

export async function loadQualityTrend(){return supabaseJson<Array<{snapshot_date:string;open_low:number;open_medium:number;open_high:number;resolved:number;dismissed:number;captured_at:string}>>("/rest/v1/data_quality_daily_snapshots?select=snapshot_date,open_low,open_medium,open_high,resolved,dismissed,captured_at&order=snapshot_date.asc&limit=90");}
export type QualityRuleConfig={id:string;ruleKey:string;enabled:boolean;severity:"LOW"|"MEDIUM"|"HIGH";updatedAt:string};
export async function loadQualityRules(){const rows=await supabaseJson<Array<{id:string;rule_key:string;enabled:boolean;severity:"LOW"|"MEDIUM"|"HIGH";updated_at:string}>>("/rest/v1/data_quality_rule_configs?select=id,rule_key,enabled,severity,updated_at&order=rule_key");return rows.map(row=>({id:row.id,ruleKey:row.rule_key,enabled:row.enabled,severity:row.severity,updatedAt:row.updated_at}));}
export async function configureQualityRule(ruleKey:string,enabled:boolean,severity:string){return supabaseJson("/rest/v1/rpc/configure_data_quality_rule",{method:"POST",body:JSON.stringify({target_rule:ruleKey,next_enabled:enabled,next_severity:severity})});}
export async function assignQualityIssue(id:string,userId:string){return supabaseJson("/rest/v1/rpc/assign_data_quality_issue",{method:"POST",body:JSON.stringify({target_issue:id,target_owner:userId})});}

export async function countRows(path:string){const response=await supabaseRequest(path,{headers:{Prefer:"count=exact",Range:"0-0"}});return Number((response.headers.get("content-range")??"*/0").split("/")[1]??0);}
