import {databaseJson,databaseRequest} from "./db/gateway";
import type {z} from "zod";
import type {WorkflowTemplateData,WorkflowStep,workflowTemplateSaveSchema,workflowTemplateActionSchema} from "./workflow-input";
export type WorkflowTemplate=Omit<WorkflowTemplateData,"steps">&{id:string;workspace_id:string;logical_id:string;version:number;revision:number;status:"DRAFT"|"ACTIVE"|"RETIRED";created_at:string;updated_at:string;can_edit:boolean;used:boolean;step_count:number;product_name_zh:string|null;product_name_en:string|null};
export type WorkflowTemplateDetail=WorkflowTemplate&{steps:WorkflowStep[]};
export type WorkflowTemplatePage={items:WorkflowTemplate[];page:number;pageSize:number;total:number};
type Adapter={json:typeof databaseJson;request:typeof databaseRequest};const db:Adapter={json:databaseJson,request:databaseRequest};
export async function listWorkflowTemplates(options:{status?:WorkflowTemplate["status"];productId?:string;page?:number}={},adapter=db):Promise<WorkflowTemplatePage>{const page=options.page??1,pageSize=20,params=new URLSearchParams({order:"updated_at.desc,id.asc"});if(options.status)params.set("status",`eq.${options.status}`);if(options.productId)params.set("or",`(product_id.is.null,product_id.eq.${options.productId})`);const response=await adapter.request(`/db/table/workflow_template_records?${params}`,{headers:{Prefer:"count=exact",Range:`${(page-1)*pageSize}-${page*pageSize-1}`}}),items=await response.json() as WorkflowTemplate[];return{items,page,pageSize,total:Number(response.headers.get("content-range")?.split("/")[1]??items.length)};}
export async function getWorkflowTemplate(id:string,adapter=db):Promise<WorkflowTemplateDetail|null>{const item=(await adapter.json<WorkflowTemplate[]>(`/db/table/workflow_template_records?${new URLSearchParams({id:`eq.${id}`,limit:"1"})}`))[0];if(!item)return null;const steps=await adapter.json<WorkflowStep[]>(`/db/table/workflow_template_steps?${new URLSearchParams({template_id:`eq.${id}`,order:"sequence.asc,id.asc",limit:"40",select:"id,sequence,name_zh,name_en,step_kind,required,default_owner_role,offset_basis,offset_days,task_config,milestone_config,checkpoint_config"})}`);return{...item,steps};}
export function saveWorkflowTemplate(input:z.infer<typeof workflowTemplateSaveSchema>,adapter=db){return adapter.json<WorkflowTemplate>("/db/rpc/save_workflow_template",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,data:input.data,p_request_key:input.requestKey})});}
export function changeWorkflowTemplate(input:z.infer<typeof workflowTemplateActionSchema>,adapter=db){return adapter.json<WorkflowTemplate>("/db/rpc/change_workflow_template",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,operation:input.operation,new_id:input.newId??null,p_request_key:input.requestKey})});}
