import {databaseJson,databaseRequest} from "./db/gateway";
import type {z} from "zod";
import type {workflowStartSchema,workflowActionSchema,WorkflowStep} from "./workflow-input";
export type WorkflowStatus="NOT_STARTED"|"ACTIVE"|"BLOCKED"|"COMPLETED"|"CANCELLED";
export type WorkflowInstance={id:string;enrollment_id:string;application_id:string|null;template_id:string;template_version:number;template_name_zh:string;template_name_en:string;owner_id:string;owner_name_zh:string|null;owner_name_en:string|null;status:WorkflowStatus;revision:number;started_at:string;completed_at:string|null;cancelled_at:string|null;projection:{status:WorkflowStatus;completedOrWaivedSteps:number;totalSteps:number};can_edit:boolean};
export type WorkflowStepInstance={id:string;workflow_instance_id:string;template_step_id:string;sequence:number;name_zh:string;name_en:string;step_kind:WorkflowStep["step_kind"];required:boolean;task_id:string|null;milestone_id:string|null;current_status:"PENDING"|"READY"|"IN_PROGRESS"|"BLOCKED"|"COMPLETED"|"WAIVED"|"CANCELLED";current_due_at:string|null;current_context_warning:string|null;current_owner_id:string|null;owner_name_zh:string|null;owner_name_en:string|null;checkpoint_config:WorkflowStep["checkpoint_config"];revision:number};
export type WorkflowPage={items:WorkflowInstance[];page:number;total:number;pageSize:number};
type Adapter={json:typeof databaseJson;request:typeof databaseRequest};const db:Adapter={json:databaseJson,request:databaseRequest};
export async function listWorkflows(options:{enrollmentId:string;applicationId?:string;page?:number},adapter=db):Promise<WorkflowPage>{const page=options.page??1,pageSize=20,params=new URLSearchParams({enrollment_id:`eq.${options.enrollmentId}`,order:"created_at.desc,id.asc"});if(options.applicationId)params.set("application_id",`eq.${options.applicationId}`);const response=await adapter.request(`/db/table/workflow_instance_records?${params}`,{headers:{Prefer:"count=exact",Range:`${(page-1)*pageSize}-${page*pageSize-1}`}}),items=await response.json() as WorkflowInstance[];return{items,page,pageSize,total:Number(response.headers.get("content-range")?.split("/")[1]??items.length)};}
export async function getWorkflow(id:string,adapter=db){const item=(await adapter.json<WorkflowInstance[]>(`/db/table/workflow_instance_records?${new URLSearchParams({id:`eq.${id}`,limit:"1"})}`))[0];if(!item)return null;const steps=await adapter.json<WorkflowStepInstance[]>(`/db/table/workflow_step_records?${new URLSearchParams({workflow_instance_id:`eq.${id}`,order:"sequence.asc,id.asc",limit:"40"})}`);return{...item,steps};}
export function instantiateWorkflow(input:z.infer<typeof workflowStartSchema>,adapter=db){return adapter.json<WorkflowInstance>("/db/rpc/instantiate_workflow",{method:"POST",body:JSON.stringify({record_id:input.id,template_id:input.templateId,template_version:input.templateVersion,enrollment_id:input.enrollmentId,application_id:input.applicationId,owner_id:input.ownerId,p_request_key:input.requestKey})});}
export function operateWorkflow(input:z.infer<typeof workflowActionSchema>,adapter=db){return adapter.json<WorkflowInstance>("/db/rpc/operate_workflow",{method:"POST",body:JSON.stringify({record_id:input.id,expected_revision:input.expectedRevision,operation:input.operation,step_id:input.stepId??null,reason:input.reason,p_request_key:input.requestKey})});}
