import { NextResponse } from "next/server";
import { z } from "zod";
import { apiRoute, requireApiCapability } from "@/lib/api";
import { importOperation,listImportBatches,listImportMappingProfiles,listImportRows,saveImportMappingProfile } from "@/lib/phase2-repository";
import { mutationIsTrusted } from "@/lib/request-security";
const create=z.object({operation:z.literal("create"),resource:z.enum(["ORGANIZATIONS","CONTACTS"]),filename:z.string().trim().min(1).max(180),content_hash:z.string().min(8).max(128),request_key:z.string().min(8).max(160),mapping:z.record(z.string(),z.string()),rows:z.array(z.record(z.string(),z.string())).min(1).max(10_000)});const decide=z.object({operation:z.literal("decide"),target_row:z.uuid(),chosen_action:z.enum(["CREATE","UPDATE","MERGE","SKIP"])});const repair=z.object({operation:z.literal("repair"),target_row:z.uuid(),replacement:z.object({nameZh:z.string().trim().max(120),nameEn:z.string().trim().max(160),email:z.string().trim().max(320),phone:z.string().trim().max(40),city:z.string().trim().max(80),title:z.string().trim().max(120)})});const process=z.object({operation:z.literal("process"),target_batch:z.uuid(),batch_size:z.number().int().min(1).max(100).default(50)});const rollback=z.object({operation:z.literal("rollback"),target_batch:z.uuid(),requestKey:z.string().trim().min(8).max(160)});const saveMapping=z.object({operation:z.literal("saveMapping"),resource:z.enum(["ORGANIZATIONS","CONTACTS"]),name:z.string().trim().min(1).max(80),mapping:z.record(z.string(),z.string())});const schema=z.discriminatedUnion("operation",[create,decide,repair,process,rollback,saveMapping]);
async function get(request:Request){await requireApiCapability("imports.view");const url=new URL(request.url);if(url.searchParams.get("mappingProfiles")==="true"){const resource=url.searchParams.get("resource");if(resource&&!["CONTACTS","ORGANIZATIONS"].includes(resource))return NextResponse.json({code:"INVALID_IMPORT_RESOURCE"},{status:400});return NextResponse.json(await listImportMappingProfiles(resource??undefined));}const batch=url.searchParams.get("batch");const parsedPage=Number(url.searchParams.get(batch?"rowPage":"page")??1);const parsedPageSize=Number(url.searchParams.get(batch?"rowPageSize":"pageSize")??(batch?50:10));if(!Number.isInteger(parsedPage)||parsedPage<1||![10,20,50].includes(parsedPageSize))return NextResponse.json({code:"INVALID_PAGINATION"},{status:400});try{return NextResponse.json(batch?await listImportRows(batch,parsedPage,parsedPageSize):await listImportBatches(parsedPage,parsedPageSize));}catch{return NextResponse.json({code:"IMPORT_LOAD_FAILED"},{status:500});}}
async function post(request:Request){if(!mutationIsTrusted(request))return NextResponse.json({code:"UNTRUSTED_ORIGIN"},{status:403});await requireApiCapability("imports.execute");const parsed=schema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({code:"INVALID_IMPORT_INPUT",field:String(parsed.error.issues[0]?.path[0]??"form")},{status:400});try{return NextResponse.json({item:parsed.data.operation==="saveMapping"?await saveImportMappingProfile(parsed.data):await importOperation(parsed.data as unknown as Record<string,unknown>)});}catch{return NextResponse.json({code:"IMPORT_OPERATION_FAILED"},{status:409});}}
export const GET=apiRoute(get,"IMPORT_LOAD_FAILED");
export const POST=apiRoute(post,"IMPORT_OPERATION_FAILED");
