import { NextResponse } from "next/server";
import { z } from "zod";
import { apiRoute, requireApiRole } from "@/lib/api";
import { importOperation,listImportBatches,listImportRows } from "@/lib/phase2-repository";
import { mutationIsTrusted } from "@/lib/request-security";
const create=z.object({operation:z.literal("create"),resource:z.enum(["ORGANIZATIONS","CONTACTS"]),filename:z.string().trim().min(1).max(180),content_hash:z.string().min(8).max(128),request_key:z.string().min(8).max(160),mapping:z.record(z.string(),z.string()),rows:z.array(z.record(z.string(),z.string())).min(1).max(500)});const decide=z.object({operation:z.literal("decide"),target_row:z.uuid(),chosen_action:z.enum(["CREATE","UPDATE","MERGE","SKIP"])});const process=z.object({operation:z.literal("process"),target_batch:z.uuid(),batch_size:z.number().int().min(1).max(100).default(50)});const rollback=z.object({operation:z.literal("rollback"),target_batch:z.uuid()});const schema=z.discriminatedUnion("operation",[create,decide,process,rollback]);
async function get(request:Request){await requireApiRole("SUPER_ADMIN","ADMIN","SALES_DIRECTOR","SALES_MANAGER");const url=new URL(request.url);const batch=url.searchParams.get("batch");const parsedPage=Number(url.searchParams.get(batch?"rowPage":"page")??1);const parsedPageSize=Number(url.searchParams.get(batch?"rowPageSize":"pageSize")??(batch?50:10));if(!Number.isInteger(parsedPage)||parsedPage<1||![10,20,50].includes(parsedPageSize))return NextResponse.json({code:"INVALID_PAGINATION"},{status:400});try{return NextResponse.json(batch?await listImportRows(batch,parsedPage,parsedPageSize):await listImportBatches(parsedPage,parsedPageSize));}catch{return NextResponse.json({code:"IMPORT_LOAD_FAILED"},{status:500});}}
async function post(request:Request){if(!mutationIsTrusted(request))return NextResponse.json({code:"UNTRUSTED_ORIGIN"},{status:403});await requireApiRole("SUPER_ADMIN","ADMIN","SALES_DIRECTOR","SALES_MANAGER");const parsed=schema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({code:"INVALID_IMPORT_INPUT",field:String(parsed.error.issues[0]?.path[0]??"form")},{status:400});try{return NextResponse.json({item:await importOperation(parsed.data as unknown as Record<string,unknown>)});}catch{return NextResponse.json({code:"IMPORT_OPERATION_FAILED"},{status:409});}}
export const GET=apiRoute(get,"IMPORT_LOAD_FAILED");
export const POST=apiRoute(post,"IMPORT_OPERATION_FAILED");
