import { z } from "zod";
import { getScimDirectoryUser, scimEnterpriseSchema, toScimUser, updateScimDirectoryUser } from "@/lib/scim";
import { requireScim, scimFailure, scimJson } from "@/lib/scim-http";
import { applicationOrigin } from "@/lib/application-origin.mjs";

type Context={params:Promise<{id:string}>};
const roles=["SALES_DIRECTOR","SALES_MANAGER","SALES_SPECIALIST","SALES_SUPPORT"] as const;
const replaceSchema=z.object({externalId:z.string().trim().min(1).max(255),userName:z.email().max(320),displayName:z.string().trim().max(160).optional(),name:z.object({formatted:z.string().trim().max(160).optional()}).optional(),active:z.boolean().default(true),[scimEnterpriseSchema]:z.object({displayNameZh:z.string().trim().max(80).default(""),displayNameEn:z.string().trim().max(80).optional(),role:z.enum(roles).default("SALES_SUPPORT"),team:z.string().trim().min(1).max(80).default("Enterprise directory")}).optional()});
const patchSchema=z.object({Operations:z.array(z.object({op:z.enum(["add","replace","remove"]),path:z.string().max(255).optional(),value:z.unknown().optional()})).min(1).max(20)});
function validId(id:string){return /^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id);}

export async function GET(request:Request,context:Context){try{await requireScim(request);const {id}=await context.params;if(!validId(id))return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"404",detail:"Not found"},404);const row=await getScimDirectoryUser(id);const resource=toScimUser(row,applicationOrigin(request.url));return scimJson(resource,200,{etag:resource.meta.version});}catch(error){return scimFailure(error);}}

export async function PUT(request:Request,context:Context){try{await requireScim(request);const {id}=await context.params;const parsed=replaceSchema.safeParse(await request.json().catch(()=>({})));if(!validId(id)||!parsed.success)return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"400",scimType:"invalidValue",detail:"Invalid SCIM user"},400);const extension=parsed.data[scimEnterpriseSchema];const english=extension?.displayNameEn??parsed.data.displayName??parsed.data.name?.formatted??parsed.data.userName.split("@")[0];const row=await updateScimDirectoryUser(id,{externalId:parsed.data.externalId,userName:parsed.data.userName,displayNameZh:extension?.displayNameZh??"",displayNameEn:english,role:extension?.role??"SALES_SUPPORT",team:extension?.team??"Enterprise directory",active:parsed.data.active});const resource=toScimUser(row,applicationOrigin(request.url));return scimJson(resource,200,{etag:resource.meta.version});}catch(error){return scimFailure(error);}}

export async function PATCH(request:Request,context:Context){try{await requireScim(request);const {id}=await context.params;const parsed=patchSchema.safeParse(await request.json().catch(()=>({})));if(!validId(id)||!parsed.success)return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"400",scimType:"invalidSyntax",detail:"Invalid PATCH request"},400);const changes:Record<string,unknown>={};for(const operation of parsed.data.Operations){const path=(operation.path??"").toLowerCase();if(operation.op==="remove"&&path==="active")changes.active=false;else if(path==="active"&&typeof operation.value==="boolean")changes.active=operation.value;else if(path==="username"&&typeof operation.value==="string")changes.userName=operation.value;else if(path==="externalid"&&typeof operation.value==="string")changes.externalId=operation.value;else if(path==="displayname"&&typeof operation.value==="string")changes.displayNameEn=operation.value;else if(path.endsWith(":role")&&typeof operation.value==="string"&&roles.includes(operation.value as typeof roles[number]))changes.role=operation.value;else if(path.endsWith(":team")&&typeof operation.value==="string")changes.team=operation.value;else if(path.endsWith(":displaynamezh")&&typeof operation.value==="string")changes.displayNameZh=operation.value;else return scimJson({schemas:["urn:ietf:params:scim:api:messages:2.0:Error"],status:"400",scimType:"invalidPath",detail:`Unsupported path: ${operation.path??""}`},400);}const row=await updateScimDirectoryUser(id,changes);const resource=toScimUser(row,applicationOrigin(request.url));return scimJson(resource,200,{etag:resource.meta.version});}catch(error){return scimFailure(error);}}

export async function DELETE(request:Request,context:Context){try{await requireScim(request);const {id}=await context.params;if(!validId(id))return new Response(null,{status:404});await updateScimDirectoryUser(id,{active:false});return new Response(null,{status:204,headers:{"cache-control":"no-store"}});}catch(error){return scimFailure(error);}}
