import { NextResponse } from "next/server";
import { z } from "zod";
import { apiRoute, parseUuid, requireApiUser } from "@/lib/api";
import { mutationIsTrusted } from "@/lib/request-security";
import { updateOpportunity } from "@/lib/sales-repository";
import { SupabaseRequestError } from "@/lib/supabase-server";

const schema=z.object({stage:z.enum(["DISCOVERY","EVALUATION","HESITATION","PAYMENT","WON","LOST"]),probability:z.number().int().min(0).max(100),expectedCloseDate:z.string().date().nullable().optional(),nextActionZh:z.string().trim().max(300).default(""),nextActionEn:z.string().trim().max(300).default(""),reason:z.string().trim().max(500).optional(),evidence:z.string().trim().max(1000).optional()}).superRefine((value,context)=>{if(!["WON","LOST"].includes(value.stage)&&(!value.expectedCloseDate||!value.nextActionZh||!value.nextActionEn))context.addIssue({code:"custom",message:"NEXT_ACTION_REQUIRED",path:["nextActionZh"]});if(value.stage==="WON"&&!value.evidence)context.addIssue({code:"custom",message:"WON_EVIDENCE_REQUIRED",path:["evidence"]});if(value.stage==="LOST"&&!value.reason)context.addIssue({code:"custom",message:"LOST_REASON_REQUIRED",path:["reason"]});});
async function patch(request:Request,context:{params:Promise<{id:string}>}){if(!mutationIsTrusted(request))return NextResponse.json({code:"UNTRUSTED_ORIGIN"},{status:403});const id=parseUuid((await context.params).id);const parsed=schema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({code:parsed.error.issues[0]?.message??"INVALID_INPUT",field:String(parsed.error.issues[0]?.path[0]??"form")},{status:400});await requireApiUser();try{return NextResponse.json({item:await updateOpportunity(id,parsed.data)});}catch(error){return NextResponse.json({code:error instanceof SupabaseRequestError?error.code:"OPPORTUNITY_OPERATION_FAILED"},{status:error instanceof SupabaseRequestError?error.status:500});}}
export const PATCH=apiRoute(patch,"OPPORTUNITY_OPERATION_FAILED");
