import type {Messages} from "../types";
const types = ["INTERVIEW","SUPPLEMENTARY_MATERIALS","PLACEMENT_TEST","I20_REQUESTED","I20_ISSUED","SEVIS_REQUIRED","SEVIS_COMPLETED","VISA_APPLICATION","VISA_APPOINTMENT","VISA_TRAINING","VISA_RESULT","FLIGHT_CONFIRMED","ORIENTATION","ARRIVAL","OTHER"];
const statuses = ["PENDING","SCHEDULED","IN_PROGRESS","COMPLETED","WAIVED","BLOCKED","CANCELLED"];
const results = ["PASS","FAIL","RESCHEDULE","NO_SHOW","UNKNOWN","APPROVED","REFUSED","ADMINISTRATIVE_PROCESSING","OTHER"];
function catalog(prefix:string,keys:string[],labels:string[]){return Object.fromEntries(keys.map((key,index)=>[`${prefix}.${key}`,labels[index]]));}
export const enMilestones:Messages={
 ...catalog("milestones.type",types,["Interview","Supplementary materials","Placement test","I-20 requested","I-20 issued","SEVIS required","SEVIS completed","Visa application","Visa appointment","Visa training","Visa result","Flight confirmed","Orientation","Arrival","Other"]),
 ...catalog("milestones.status",statuses,["Pending","Scheduled","In progress","Completed","Waived","Blocked","Cancelled"]),
 ...catalog("milestones.result",results,["Pass","Fail","Reschedule","No show","Unknown","Approved","Refused","Administrative processing","Other"]),
 "milestones.title":"Admission milestones","milestones.timeline":"Admissions timeline","milestones.create":"Create milestone","milestones.edit":"Edit milestone","milestones.type":"Type","milestones.due_at":"Due","milestones.scheduled_at":"Scheduled","milestones.completed_at":"Completed","milestones.outcome":"Outcome","milestones.owner":"Owner","milestones.sequence":"Sequence","milestones.external_reference":"External reference","milestones.note":"Note","milestones.history":"Milestone history","milestones.empty":"No admission milestones yet.","milestones.noTimeline":"No admissions events yet.","milestones.loadFailed":"Could not load admissions events.","milestones.saveFailed":"Could not save the milestone.","milestones.saved":"Milestone saved.","milestones.refreshFailed":"Saved. Reload the list to see the latest record.","milestones.invalid":"Check milestone fields, required dates and type-specific data.","milestones.versionConflict":"This milestone changed. Your draft is preserved; reload before editing again.","milestones.parentImmutable":"The enrollment cannot be changed.","milestones.requestConflict":"This save request conflicts with an earlier request.","milestones.forbidden":"You do not have access to this milestone or its context.","milestones.ownerInvalid":"Choose an assignable workspace member.","milestones.applicationMismatch":"The application must belong to this enrollment.","milestones.notFound":"The milestone or enrollment is unavailable.","milestones.contextHelp":"Enrollment is fixed. Application context is optional; milestones do not change application or financial facts.","milestones.metadataHelp":"Changing type clears the type-specific fields. Keep documents and sensitive identity information outside these fields.","milestones.summary":"Summary","milestones.result":"Result","milestones.interviewer":"Interviewer","milestones.score":"Score","milestones.scale":"Scale","milestones.reason":"Reason","milestones.label":"Label","milestones.overdue":"Overdue","milestones.enrollmentContext":"Enrollment-level milestone","milestones.source.APPLICATION":"Application","milestones.source.MILESTONE":"Milestone","milestones.event.SUBMITTED":"Application submitted","milestones.event.DECISION":"Admission decision","milestones.event.WITHDRAWN":"Application withdrawn","milestones.timelineHelp":"Application facts and milestone facts retain their source. Operation history is shown separately.",
 "quality.rule.MILESTONE_OVERDUE":"Overdue admission milestone","quality.rule.MILESTONE_BLOCKED":"Blocked admission milestone","quality.rule.VISA_RESULT_MISSING_OUTCOME":"Completed visa result without an outcome"
};
export const zhMilestones:Messages={
 ...catalog("milestones.type",types,["面试","补充材料","分班测试","I-20 已请求","I-20 已签发","需要 SEVIS","SEVIS 已完成","签证申请","签证预约","签证培训","签证结果","航班已确认","入学说明会","抵达","其他"]),
 ...catalog("milestones.status",statuses,["待处理","已安排","进行中","已完成","已豁免","受阻","已取消"]),
 ...catalog("milestones.result",results,["通过","未通过","重新安排","未出席","未知","获批","拒签","行政审查","其他"]),
 "milestones.title":"招生运营节点","milestones.timeline":"招生时间线","milestones.create":"新建节点","milestones.edit":"编辑节点","milestones.type":"节点类型","milestones.due_at":"截止时间","milestones.scheduled_at":"安排时间","milestones.completed_at":"完成时间","milestones.outcome":"结论","milestones.owner":"负责人","milestones.sequence":"顺序","milestones.external_reference":"外部编号","milestones.note":"备注","milestones.history":"节点状态历史","milestones.empty":"暂无招生运营节点。","milestones.noTimeline":"暂无招生事件。","milestones.loadFailed":"无法加载招生事件。","milestones.saveFailed":"无法保存节点。","milestones.saved":"节点已保存。","milestones.refreshFailed":"已保存，请重新加载列表查看最新记录。","milestones.invalid":"请检查节点字段、必要时间及该类型的专属信息。","milestones.versionConflict":"节点已被更新。草稿已保留，请重新加载后再编辑。","milestones.parentImmutable":"不能更换所属 Enrollment。","milestones.requestConflict":"本次保存请求与已有请求冲突。","milestones.forbidden":"无权访问该节点或关联上下文。","milestones.ownerInvalid":"请选择可分配的工作区成员。","milestones.applicationMismatch":"申请必须属于当前 Enrollment。","milestones.notFound":"节点或 Enrollment 不可用。","milestones.contextHelp":"所属 Enrollment 固定，申请上下文可选。节点不会自动更改申请或财务事实。","milestones.metadataHelp":"更换类型会清空专属字段。请勿在此保存文件或敏感身份信息。","milestones.summary":"摘要","milestones.result":"结果","milestones.interviewer":"面试官","milestones.score":"分数","milestones.scale":"评分标准","milestones.reason":"原因","milestones.label":"名称","milestones.overdue":"已逾期","milestones.enrollmentContext":"Enrollment 层节点","milestones.source.APPLICATION":"申请","milestones.source.MILESTONE":"运营节点","milestones.event.SUBMITTED":"申请已提交","milestones.event.DECISION":"录取决定","milestones.event.WITHDRAWN":"申请已撤回","milestones.timelineHelp":"申请事实与运营节点保留各自来源，操作历史单独展示。",
 "quality.rule.MILESTONE_OVERDUE":"招生运营节点逾期","quality.rule.MILESTONE_BLOCKED":"招生运营节点受阻","quality.rule.VISA_RESULT_MISSING_OUTCOME":"签证结果节点已完成但缺少结论"
};
