import type {Messages} from "../types";
const labels:Record<string,[string,string]>={
 title:["Applications","正式申请"],description:["Manage formal applications within existing enrollments.","管理现有 Enrollment 下的正式申请。"],create:["Create application","创建申请"],edit:["Edit application","编辑申请"],empty:["No applications in this scope.","当前范围暂无申请。"],enrollment:["Enrollment","报名记录"],target:["Target institution","目标机构"],externalId:["External application ID","外部申请编号"],deadline:["Application deadline","申请截止日期"],cohortDeadline:["Cohort deadline (context only)","批次截止日期（仅供参考）"],decision:["Admission decision","录取决定"],submitted_at:["Submitted at","提交时间"],decision_at:["Decision at","决定时间"],withdrawn_at:["Withdrawn at","撤回时间"],owner:["Application owner","申请负责人"],overview:["Overview","概览"],tasks:["Tasks","准备任务"],history:["Status history","状态历史"],identityHelp:["The enrollment is fixed after creation. Each enrollment can have multiple applications.","创建后不能更换报名记录。每个报名记录可对应多个申请。"],search:["Search student or external application ID…","搜索学生或外部申请编号…"],statusReason:["Status change reason","状态变更原因"],saved:["Application saved.","申请已保存。"],loadFailed:["Could not load applications.","无法加载申请。"],saveFailed:["Could not save. Your draft is preserved.","保存失败，草稿已保留。"],invalid:["Check the enrollment and lifecycle dates. Submitted requires a submission time; Decided requires a decision and its time; Withdrawn requires a withdrawal time.","请检查报名记录与日期。已提交需提交时间；已决定需录取决定和决定时间；已撤回需撤回时间。"],versionConflict:["This application changed. Cancel and reload before editing again; your draft is preserved.","此申请已被修改。草稿已保留，请取消并重新加载后编辑。"],parentImmutable:["An application's enrollment cannot be changed.","不能更换申请的报名记录。"],requestConflict:["The retry does not match the original request.","重试与原请求不一致。"],forbidden:["You cannot access this application or one of its related records.","无权访问此申请或关联记录。"],notFound:["Application or enrollment unavailable.","申请或报名记录不可用。"],ownerInvalid:["Select an authorized workspace member.","请选择可分配的工作区成员。"],historyHelp:["Real status changes form the operational admissions history. Decision edits are recorded in audit evidence.","真实状态变化构成招生运营历史，录取决定的修改记录在审计证据中。"],addTask:["Add application task","添加申请任务"],editTask:["Edit task","编辑任务"],noTasks:["No tasks linked to this application.","此申请暂无关联任务。"],noHistory:["No status history in this scope.","当前范围暂无状态历史。"],taskMismatch:["The task's student must match the application's student.","任务学生必须与申请的学生一致。"],deadlineFrom:["Deadline from","截止日期从"],deadlineTo:["Deadline through","截止日期至"],deadlineWarning:["Application deadline passed before submission","申请尚未提交且已过截止日期"],genericTask:["Unlinked tasks remain student preparation checklists.","未关联申请的任务仍是学生准备清单。"],created:["Created","已创建"],selectEnrollment:["Choose an existing enrollment before creating an application.","创建申请前请选择现有报名记录。"],
 "status.DRAFT":["Draft","草稿"],"status.PREPARING":["Preparing","准备中"],"status.SUBMITTED":["Submitted","已提交"],"status.UNDER_REVIEW":["Under review","审核中"],"status.DECIDED":["Decided","已决定"],"status.WITHDRAWN":["Withdrawn","已撤回"],"status.CLOSED":["Closed","已关闭"],
 "decision.ADMITTED":["Admitted","录取"],"decision.CONDITIONAL_ADMIT":["Conditional admit","有条件录取"],"decision.WAITLISTED":["Waitlisted","候补"],"decision.REJECTED":["Rejected","拒绝"],"decision.DEFERRED":["Deferred","延期决定"],"decision.OTHER":["Other","其他"],
};
export const enApplications:Messages=Object.fromEntries(Object.entries(labels).map(([key,value])=>[`applications.${key}`,value[0]]));
export const zhApplications:Messages=Object.fromEntries(Object.entries(labels).map(([key,value])=>[`applications.${key}`,value[1]]));
enApplications["quality.rule.APPLICATION_PAST_DEADLINE_NOT_SUBMITTED"]=labels.deadlineWarning[0];
zhApplications["quality.rule.APPLICATION_PAST_DEADLINE_NOT_SUBMITTED"]=labels.deadlineWarning[1];
