import type {Messages} from "../types";
const entries:Record<string,[string,string]>={
 "activation":["Channel activation","渠道运营进展"],"stage":["Partnership stage","合作阶段"],"stageSince":["Stage since","阶段变更时间"],"stageHistory":["Stage history","合作阶段历史"],"updateStage":["Update partnership stage","更新合作阶段"],
 "lead":["Open leads","开放线索"],"assignment":["Claimed leads","已领取线索"],"keyPeople":["Key contacts","关键联系人"],"decisionMakers":["Decision makers","决策者"],"opportunity":["Active opportunities","进行中商机"],"events":["Recent recruitment events (90 days)","近期招生活动（90天）"],"primary":["Primary attributed enrollments","主要归因报名"],"assist":["Assist attributed enrollments","协助归因报名"],
 "source.PROFILE":["Source: Organization profile","来源：机构业务档案"],"source.LEAD":["Source: Lead / assignment","来源：线索与分配"],"source.CONTACT":["Source: accessible Contact intelligence","来源：可访问联系人情报"],"source.OPPORTUNITY":["Source: Opportunity","来源：商机"],"source.EVENT":["Source: Outreach Event","来源：招生活动"],"source.ATTRIBUTION":["Source: Enrollment Attribution","来源：报名归因"],
 "view.pool":["Public pool","公共线索池"],"view.mine":["My leads","我的线索"],"view.all":["All leads","全部线索"],"internalHelp":["Internal workspace pool. Claim assigns responsibility without qualifying a lead.","工作区内部共享线索池。领取仅分配负责人，不自动确认线索资格。"],
 "claim":["Claim lead","领取线索"],"release":["Release lead","释放线索"],"reassign":["Reassign lead","转交线索"],"visibility":["Pool visibility","线索池可见性"],"create":["Create lead","创建线索"],"update":["Qualify / follow up","资格评估与跟进"],"convert":["Create opportunity","创建商机"],"history":["Assignment history","分配历史"],"qualify":["Qualify / follow up","资格评估与跟进"],"createOpportunity":["Create opportunity","创建商机"],"assignmentHistory":["Assignment history","分配历史"],
 "product":["Product","产品"],"owner":["Owner","负责人"],"you":["You","自己"],"unassigned":["Unassigned","未分配"],"reason":["Reason","原因"],"age":["Created at / lead age","创建时间 / 线索年龄"],"latestActivity":["Latest activity","最近活动"],"viewAccount":["View account / key people","查看机构与关键人"],"noHistory":["No recorded history; pre-existing dates are unknown.","暂无正式历史；旧记录的阶段时间未知。"],"claimed":["Lead claimed. Open the account to identify key people and plan your next action.","领取成功。请查看机构、确认关键人并安排下一步。"],"claimHelp":["This assigns the lead to you. Status, Organization and opportunities stay unchanged.","领取将把线索分配给自己，不自动改变资格、机构或创建商机。"],"alreadyClaimed":["This lead has already been claimed by a colleague. Refresh the pool.","该线索已被其他同事领取，请刷新公共池。"],"conflict":["The record has changed. Close and refresh before editing again.","记录已变更，请关闭并刷新后再编辑。"],"forbidden":["You do not have access to this operation.","你没有权限执行此操作。"],"invalid":["Check the values, assignment and related records.","请检查输入、分配与关联记录。"],"uncertain":["The save result is uncertain. Retry the same request to confirm.","保存结果尚未确认，请重试同一请求。"],"loadFailed":["Could not load channel operations. Retry.","无法加载渠道运营资料，请重试。"],"empty":["No available public school leads match these filters.","当前筛选下没有可领取的公共学校线索。"],"productOwnerRequired":["Choose a product and owner; clear or reselect an incompatible cohort.","请选择产品和负责人；不匹配的批次须明确清空或重新选择。"],
 "filter.q":["Search school / lead","搜索学校 / 线索"],"filter.city":["City / region","城市 / 地区"],"filter.schoolType":["School type","学校类型"],"filter.tier":["Commercial tier","商业等级"],"filter.keyContact":["Key contact assessment","关键联系人评估"],"filter.status":["Lead status","线索状态"],"filter.potentialMin":["Minimum partnership potential (10–100)","最低合作潜力（10–100）"],"filter.ageDays":["At least this many days old","最少线索年龄（天）"],"filter.sort":["Sort","排序"],
 "option.yes":["Has visible key contact","有可见关键联系人"],"option.no":["Missing visible key contact","无可见关键联系人"],"option.newest":["Newest","最新"],"option.oldest":["Oldest","最早"],"option.potential":["Highest potential","最高合作潜力"],"option.tier":["Commercial tier","商业等级"],"option.PRIVATE":["Private","私有"],"option.WORKSPACE_PUBLIC":["Workspace public","工作区公共池"],"event.CLAIMED":["Claimed","领取"],"event.RELEASED":["Released","释放"],"event.REASSIGNED":["Reassigned","转交"]
};
const stages:Record<string,[string,string]>={KEY_PERSON_ENGAGED:["Key person engaged","已接触关键人"],NEEDS_QUALIFIED:["Needs qualified","需求已确认"],SOLUTION_PROPOSED:["Solution proposed","方案已提出"],PARTNERSHIP_AGREED:["Partnership agreed","合作已达成"],RECRUITMENT_ACTIVATED:["Recruitment activated","招生已启动"],ONGOING_ENABLEMENT:["Ongoing enablement","持续赋能"]};
const rules:Record<string,[string,string]>={CLAIMED_LEAD_WITHOUT_NEXT_ACTION:["Claimed lead without next action","已领取线索缺少下一步"],QUALIFYING_SCHOOL_LEAD_WITHOUT_KEY_CONTACT:["Qualifying school lead without key contact","评估中的学校线索缺少关键联系人"],QUALIFIED_SCHOOL_LEAD_WITHOUT_ORGANIZATION_OWNER:["Qualified school lead without account owner","已确认学校线索缺少机构负责人"],RECRUITMENT_ACTIVATED_WITHOUT_KEY_CONTACT:["Recruitment activated without key contact","已启动招生但缺少关键联系人"],SOLUTION_PROPOSED_WITHOUT_OPPORTUNITY:["Solution proposed without active opportunity","已提出方案但缺少进行中商机"]};
function copy(index:0|1):Messages{return Object.fromEntries([...Object.entries(entries).map(([k,v])=>[`pool.${k}`,v[index]]),...Object.entries(stages).map(([k,v])=>[`business.option.${k}`,v[index]]),...Object.entries(rules).map(([k,v])=>[`quality.rule.${k}`,v[index]]),...["LEAD_CLAIMED","LEAD_RELEASED","CHANNEL_STAGE_CHANGED"].map((k,i)=>[`automation.trigger.${k}`,(index===0?["Lead claimed","Lead released","Channel stage changed"]:["线索领取","线索释放","渠道阶段变更"])[i]])]);}
export const enLeadPool=copy(0),zhLeadPool=copy(1);
