import type {Messages} from "../types";
export const enOperationalReadiness:Messages={
 "imports.operationalHelp":"Use existing product codes, unique cohort codes and student numbers. Missing, ambiguous or duplicate identities fail the row. These imports create neither Products nor Students and never overwrite existing enrollments.",
 "imports.identityMappingRequired":"Cohorts: map product code, cohort code and a name. Enrollments: map student number, cohort code and owner email. Names never identify Students.",
 "enrollmentFinance.title":"Financial summary","enrollmentFinance.contracted":"Contracted","enrollmentFinance.receivable":"Scheduled receivable","enrollmentFinance.collected":"Collected (net)","enrollmentFinance.refunded":"Refunded","enrollmentFinance.outstanding":"Scheduled outstanding","enrollmentFinance.overdue":"Overdue outstanding",
 "enrollmentFinance.scope":"Live contract-level facts. Net confirmed receipts exclude completed refunds. Outstanding covers scheduled installments only; amounts remain separate by currency.",
 "enrollmentFinance.allocation":"Allocation","enrollmentFinance.allocation.NONE":"No active contract","enrollmentFinance.allocation.EXCLUSIVE":"Exclusive","enrollmentFinance.allocation.PARTIAL_UNALLOCATED":"Partly unallocated","enrollmentFinance.allocation.SHARED_UNALLOCATED":"Shared · not allocated",
 "enrollmentFinance.exclusiveTotals":"Exclusive totals by currency","enrollmentFinance.sharedWarning":"{count} related contract(s) are shared. Their amounts are excluded from exclusive totals.","enrollmentFinance.noSchedule":"No receivable schedule. Scheduled outstanding does not describe the entire contract balance.","enrollmentFinance.none":"No visible active contract finance.","enrollmentFinance.unavailable":"Some financial information is unavailable under your current access.",
 "enrollmentFinance.filters":"Enrollment finance filters","enrollmentFinance.filterScope":"Filters apply through visible active enrollment links. Each finance record appears once. Student/enrollment filters exclude quotes, which can precede enrollment.","enrollmentFinance.applyFilters":"Apply filters",
 "cohortSnapshot.title":"Enrollment progress & channels","cohortSnapshot.scope":"Current facts for enrollment records you can access; no forecast or revenue allocation.","cohortSnapshot.totalRecords":"Total records","cohortSnapshot.currentOpen":"Current open","cohortSnapshot.currentOpenHelp":"Current open = Lead + Interested + Registering + Active; terminal records remain in total records.","cohortSnapshot.channels":"Organization attribution","cohortSnapshot.noChannels":"No organization attribution in this scope.","cohortSnapshot.channelCounts":"Primary {primary} · Assist {assist} · Active {active}",
 "automation.trigger.ENROLLMENT_CREATED":"Enrollment created","automation.trigger.ENROLLMENT_STATUS_CHANGED":"Enrollment status changed","automation.trigger.COHORT_APPLICATION_DEADLINE_APPROACHING":"Cohort application deadline approaching","automation.condition.daysUntilDeadline":"Days until deadline","automation.condition.status":"Status","automation.condition.source":"Source","automation.condition.stage":"Stage","automation.condition.currency":"Currency",
 "imports.field.productCode":"Existing product code","imports.field.cohortCode":"Cohort code","imports.field.intakeType":"Intake","imports.field.applicationOpenOn":"Applications open","imports.field.applicationDeadline":"Application deadline","imports.field.startOn":"Start date","imports.field.endOn":"End date","imports.field.targetEnrollment":"Target","imports.field.capacity":"Capacity","imports.field.currency":"Currency","imports.field.ownerEmail":"Owner email","imports.field.status":"Lifecycle status","imports.field.salesOwnerEmail":"Sales owner email","imports.field.householdReference":"Household UUID","imports.field.opportunityReference":"Opportunity UUID","imports.field.enrolledAt":"Enrolled at","imports.field.completedAt":"Completed at","imports.field.withdrawnAt":"Withdrawn at","imports.field.withdrawalReason":"Withdrawal reason","imports.field.row":"Row",
 "imports.error.domain_row_invalid":"Row validation failed","imports.reason.generic":"Check stable identities, access, lifecycle dates and capacity. Existing records are never overwritten.",
 "search.type.cohort":"Cohort","search.type.enrollment":"Enrollment",
};
export const zhOperationalReadiness:Messages={
 "imports.operationalHelp":"使用现有产品代码、唯一批次代码及学生编号。标识缺失、不唯一或重复时行失败；不会创建产品或学生，也不会覆盖现有报名记录。",
 "imports.identityMappingRequired":"批次需映射产品代码、批次代码及名称；报名需映射学生编号、批次代码及负责人邮箱。不会通过姓名识别学生。",
 "enrollmentFinance.title":"财务概览","enrollmentFinance.contracted":"合同金额","enrollmentFinance.receivable":"已计划应收","enrollmentFinance.collected":"净收款","enrollmentFinance.refunded":"已退款","enrollmentFinance.outstanding":"计划未收款","enrollmentFinance.overdue":"逾期未收款",
 "enrollmentFinance.scope":"实时合同财务事实。净收款为已确认付款减去已完成退款；未收款仅覆盖应收分期，不同币种分别展示。",
 "enrollmentFinance.allocation":"金额归属","enrollmentFinance.allocation.NONE":"无有效合同","enrollmentFinance.allocation.EXCLUSIVE":"独占合同","enrollmentFinance.allocation.PARTIAL_UNALLOCATED":"部分未分配","enrollmentFinance.allocation.SHARED_UNALLOCATED":"共享合同 · 尚未分配",
 "enrollmentFinance.exclusiveTotals":"按币种汇总独占合同","enrollmentFinance.sharedWarning":"{count} 份相关合同覆盖多个 Enrollment，金额不计入独占汇总。","enrollmentFinance.noSchedule":"尚无应收计划，计划未收款不能代表整个合同余额。","enrollmentFinance.none":"暂无可查看的有效合同财务。","enrollmentFinance.unavailable":"当前权限下部分财务信息不可查看。",
 "enrollmentFinance.filters":"报名财务筛选","enrollmentFinance.filterScope":"通过可查看的有效报名合同关系筛选，每条财务记录只显示一次。学生及报名筛选不包含可先于报名创建的报价。","enrollmentFinance.applyFilters":"应用筛选",
 "cohortSnapshot.title":"报名进度与渠道","cohortSnapshot.scope":"仅统计权限范围内的真实报名记录，不预测或分配收入。","cohortSnapshot.totalRecords":"全部记录","cohortSnapshot.currentOpen":"当前进行中","cohortSnapshot.currentOpenHelp":"当前进行中 = 潜在线索 + 有意向 + 报名中 + 已参与；终止状态仍计入全部记录。","cohortSnapshot.channels":"机构来源归因","cohortSnapshot.noChannels":"此范围内暂无机构归因。","cohortSnapshot.channelCounts":"主要 {primary} · 协助 {assist} · 已参与 {active}",
 "automation.trigger.ENROLLMENT_CREATED":"报名记录创建","automation.trigger.ENROLLMENT_STATUS_CHANGED":"报名状态变化","automation.trigger.COHORT_APPLICATION_DEADLINE_APPROACHING":"批次申请截止日期临近","automation.condition.daysUntilDeadline":"距离截止日期天数","automation.condition.status":"状态","automation.condition.source":"来源","automation.condition.stage":"阶段","automation.condition.currency":"币种",
 "imports.field.productCode":"现有产品代码","imports.field.cohortCode":"批次代码","imports.field.intakeType":"入学季","imports.field.applicationOpenOn":"申请开放日期","imports.field.applicationDeadline":"申请截止日期","imports.field.startOn":"开始日期","imports.field.endOn":"结束日期","imports.field.targetEnrollment":"目标人数","imports.field.capacity":"容量","imports.field.currency":"币种","imports.field.ownerEmail":"负责人邮箱","imports.field.status":"生命周期状态","imports.field.salesOwnerEmail":"销售负责人邮箱","imports.field.householdReference":"家庭 UUID","imports.field.opportunityReference":"机会 UUID","imports.field.enrolledAt":"正式参与时间","imports.field.completedAt":"完成时间","imports.field.withdrawnAt":"退出时间","imports.field.withdrawalReason":"退出原因","imports.field.row":"行",
 "imports.error.domain_row_invalid":"行验证失败","imports.reason.generic":"检查稳定标识、访问权限、生命周期日期及容量；不会覆盖现有记录。",
 "search.type.cohort":"批次","search.type.enrollment":"报名记录",
};
const qualityRules:Record<string,[string,string]>={
 COHORT_MISSING_APPLICATION_DEADLINE:["Recruiting/draft cohort has no application deadline","招生或草稿批次缺少申请截止日期"],
 COHORT_MISSING_OWNER:["Operational cohort has no owner","运营批次缺少负责人"],
 COHORT_RECRUITING_AFTER_DEADLINE:["Cohort is recruiting after its deadline","批次截止日期已过仍在招生"],
 COHORT_ACTIVE_WITHOUT_START_DATE:["Active cohort has no start date","进行中批次缺少开始日期"],
 COHORT_COMPLETED_WITHOUT_END_DATE:["Completed cohort has no end date","已完成批次缺少结束日期"],
 ENROLLMENT_MISSING_HOUSEHOLD:["Registering/active enrollment has no household context","报名中或已参与记录缺少家庭上下文"],
 ENROLLMENT_WITHOUT_PRIMARY_ATTRIBUTION:["Interested/registering/active enrollment has no primary source","有意向、报名中或已参与记录缺少主要来源"],
 ENROLLMENT_ACTIVE_WITHOUT_CONTRACT:["Active enrollment has no active contract link (warning)","已参与报名尚无有效合同关系（提醒）"],
};
const importReasons:Record<string,[string,string]>={
 import_owner_not_found:["Owner email must identify one active member in this workspace","负责人邮箱必须对应当前工作区唯一有效成员"],import_owner_required:["Owner email is required","负责人邮箱必填"],import_product_identity_invalid:["Product code does not identify one existing product","产品代码未对应唯一现有产品"],import_cohort_duplicate:["Cohort code already exists","批次代码已存在"],import_date_invalid:["Use a valid YYYY-MM-DD date","使用有效的 YYYY-MM-DD 日期"],import_capacity_invalid:["Capacity and target must be nonnegative integers","容量及目标必须为非负整数"],import_student_identity_required:["Student number is required; names cannot identify a student","学生编号必填，不可通过姓名匹配学生"],import_student_identity_invalid:["Student number is unknown or ambiguous","学生编号不存在或不唯一"],import_cohort_not_found:["Cohort code does not exist in this workspace","当前工作区不存在该批次代码"],import_enrollment_duplicate:["Student already has an enrollment in this cohort","该学生在此批次已有报名记录"],import_duplicate_in_batch:["Repeated identity in this import batch","同一导入批次出现重复标识"],cohort_update_forbidden:["Catalog permission is required to import cohorts","导入批次需要产品目录管理权限"],enrollment_cohort_closed:["Cohort does not accept new enrollments","此批次不接受新的报名记录"],enrollment_lifecycle_invalid:["Lifecycle status requires valid dates and a withdrawal reason when applicable","生命周期状态要求相应有效日期，退出时还需要原因"],enrollment_update_forbidden:["You cannot save this enrollment","无权保存此报名记录"],enrollment_related_forbidden:["Related records or owner are outside your access","关联记录或负责人超出权限范围"],
};
for(const [key,[en,zh]] of Object.entries(qualityRules)){enOperationalReadiness[`quality.rule.${key}`]=en;zhOperationalReadiness[`quality.rule.${key}`]=zh;}
for(const [key,[en,zh]] of Object.entries(importReasons)){enOperationalReadiness[`imports.reason.${key}`]=en;zhOperationalReadiness[`imports.reason.${key}`]=zh;}
