import type { Messages } from "../types";

export const zhSalesPlaybook: Messages = {
  "sales.keyAccounts":"重点客户","sales.matrix.contact":"联系方式","sales.matrix.meal":"共进餐","sales.matrix.family":"家长里短","sales.matrix.advocacy":"校内宣传","sales.pendingAdvance":"待推进",
  "sales.relationshipPlaybook.title":"客户关系推进建议","sales.relationshipPlaybook.description":"根据当前关系阶段选择低压力、可验证的下一步；每次只推进一到两项。",
  "sales.relationshipPlaybook.contact.verifyChannel":"确认客户偏好的联系渠道、频率和可联系时段。","sales.relationshipPlaybook.contact.shareValue":"先发送一份与客户当前需求直接相关的简短资料。","sales.relationshipPlaybook.contact.askPreference":"询问客户更愿意讨论学校合作、学生服务还是家庭需求。","sales.relationshipPlaybook.contact.setNextStep":"结束沟通前约定一个具体且轻量的下一步。",
  "sales.relationshipPlaybook.meal.inviteMeal":"以项目复盘或交流为由发出清晰、无压力的用餐邀请。","sales.relationshipPlaybook.meal.chooseContext":"选择方便、适度且符合双方机构合规要求的场合。","sales.relationshipPlaybook.meal.listenMore":"少做推销，多了解客户的工作重点和现实难题。","sales.relationshipPlaybook.meal.followUp":"餐后 24 小时内致谢，并落实席间约定的事项。",
  "sales.relationshipPlaybook.family.startEveryday":"从通勤、城市生活或教育观察等日常话题自然展开。","sales.relationshipPlaybook.family.rememberBoundaries":"记住客户主动分享的公开偏好，但不追问敏感私事。","sales.relationshipPlaybook.family.connectNeeds":"把家庭近况与客户明确表达的服务需求连接起来。","sales.relationshipPlaybook.family.respectPrivacy":"只在客户愿意时继续，不在 CRM 中记录具体私生活内容。",
  "sales.relationshipPlaybook.advocacy.confirmValue":"先确认客户已真实获得并认可可说明的服务价值。","sales.relationshipPlaybook.advocacy.offerMaterial":"提供可由客户审阅、修改的校内介绍材料或活动方案。","sales.relationshipPlaybook.advocacy.makeEasy":"把协助动作缩小为一次引荐、一次转发或一次活动邀请。","sales.relationshipPlaybook.advocacy.askPermission":"明确征得同意后再使用客户姓名、学校名称或推荐内容。",
  "sales.closingPlaybook.title":"付款与关单推进建议","sales.closingPlaybook.description":"按客户决策阶段推荐下一步，减少不确定性并让付款流程清楚可控。","sales.closingStage":"第 {stage} 阶段",
  "sales.closingPlaybook.discovery.title":"初步了解","sales.closingPlaybook.discovery.clarifyNeed":"复述客户目标、范围和成功标准，请客户确认。","sales.closingPlaybook.discovery.mapDecision":"确认实际使用者、决策人、付款人和审批流程。","sales.closingPlaybook.discovery.confirmBudget":"用价格区间确认预算匹配度，避免过早制作完整方案。","sales.closingPlaybook.discovery.agreeNext":"约定下一次会议的主题、参与人和时间。",
  "sales.closingPlaybook.evaluation.title":"方案评估","sales.closingPlaybook.evaluation.tailorProposal":"用客户的目标和时间表组织方案，不堆砌无关功能。","sales.closingPlaybook.evaluation.showEvidence":"提供相似场景案例、交付样例和明确限制。","sales.closingPlaybook.evaluation.compareOptions":"给出 2–3 个范围清晰的方案并解释取舍。","sales.closingPlaybook.evaluation.reviewTogether":"安排共同评审，现场记录异议、负责人和截止时间。",
  "sales.closingPlaybook.hesitation.title":"决策犹豫","sales.closingPlaybook.hesitation.surfaceConcern":"直接询问阻碍决定的是预算、风险、时机还是内部共识。","sales.closingPlaybook.hesitation.reduceRisk":"用试点、阶段验收或明确退出条件降低可逆风险。","sales.closingPlaybook.hesitation.bringDecisionMaker":"邀请决策人与交付负责人参加一次针对性答疑。","sales.closingPlaybook.hesitation.setDecisionDate":"共同确定合理决策日期，不制造虚假稀缺或倒计时。",
  "sales.closingPlaybook.payment.title":"付款执行","sales.closingPlaybook.payment.confirmTerms":"在开票前书面确认范围、金额、税务信息和付款节点。","sales.closingPlaybook.payment.simplifyPayment":"提供清晰发票、收款账户和合规的分期选择。","sales.closingPlaybook.payment.sendChecklist":"发送一页付款清单并标明双方经办人与预计到账时间。","sales.closingPlaybook.payment.confirmKickoff":"付款后立即确认收款、启动日期和首次交付安排。","sales.closingPlaybook.ethics":"不得使用虚假折扣、伪造稀缺、隐瞒条款或持续施压。所有建议都应以客户知情同意和真实价值为前提。",
};

export const enSalesPlaybook: Messages = {
  "sales.keyAccounts":"Key accounts","sales.matrix.contact":"Contact details","sales.matrix.meal":"Shared meal","sales.matrix.family":"Everyday life","sales.matrix.advocacy":"School advocacy","sales.pendingAdvance":"To advance",
  "sales.relationshipPlaybook.title":"Customer relationship suggestions","sales.relationshipPlaybook.description":"Choose low-pressure, verifiable next steps for the current relationship stage; advance only one or two at a time.",
  "sales.relationshipPlaybook.contact.verifyChannel":"Confirm the customer's preferred channel, frequency, and contact times.","sales.relationshipPlaybook.contact.shareValue":"Send one concise resource directly relevant to the customer's current need.","sales.relationshipPlaybook.contact.askPreference":"Ask whether they prefer to discuss school partnerships, student services, or household needs.","sales.relationshipPlaybook.contact.setNextStep":"Agree on one specific, lightweight next step before ending the conversation.",
  "sales.relationshipPlaybook.meal.inviteMeal":"Offer a clear, no-pressure meal invitation around a project review or exchange.","sales.relationshipPlaybook.meal.chooseContext":"Choose a convenient, moderate setting that meets both organizations' compliance rules.","sales.relationshipPlaybook.meal.listenMore":"Sell less and learn more about the customer's priorities and practical constraints.","sales.relationshipPlaybook.meal.followUp":"Thank them within 24 hours and complete anything agreed during the meal.",
  "sales.relationshipPlaybook.family.startEveryday":"Begin naturally with commuting, city life, or observations about education.","sales.relationshipPlaybook.family.rememberBoundaries":"Remember preferences the customer volunteers, but do not probe sensitive private matters.","sales.relationshipPlaybook.family.connectNeeds":"Connect family context only to service needs the customer has explicitly expressed.","sales.relationshipPlaybook.family.respectPrivacy":"Continue only when welcomed and never record detailed private life in the CRM.",
  "sales.relationshipPlaybook.advocacy.confirmValue":"First confirm that the customer has received and recognizes real, explainable value.","sales.relationshipPlaybook.advocacy.offerMaterial":"Offer school-facing materials or an event proposal the customer can review and edit.","sales.relationshipPlaybook.advocacy.makeEasy":"Reduce the ask to one introduction, one share, or one event invitation.","sales.relationshipPlaybook.advocacy.askPermission":"Get explicit permission before using the customer's name, school, or endorsement.",
  "sales.closingPlaybook.title":"Payment and closing suggestions","sales.closingPlaybook.description":"Recommend next steps by decision stage to reduce uncertainty and make payment clear and controllable.","sales.closingStage":"Stage {stage}",
  "sales.closingPlaybook.discovery.title":"Initial discovery","sales.closingPlaybook.discovery.clarifyNeed":"Restate goals, scope, and success criteria and ask the customer to confirm.","sales.closingPlaybook.discovery.mapDecision":"Identify users, decision makers, payers, and the approval process.","sales.closingPlaybook.discovery.confirmBudget":"Use a price range to test budget fit before building a full proposal.","sales.closingPlaybook.discovery.agreeNext":"Agree on the topic, participants, and time for the next meeting.",
  "sales.closingPlaybook.evaluation.title":"Solution evaluation","sales.closingPlaybook.evaluation.tailorProposal":"Organize the proposal around customer goals and timing, without irrelevant feature padding.","sales.closingPlaybook.evaluation.showEvidence":"Provide comparable cases, delivery examples, and explicit limitations.","sales.closingPlaybook.evaluation.compareOptions":"Offer two or three clearly scoped options and explain the trade-offs.","sales.closingPlaybook.evaluation.reviewTogether":"Review together and record objections, owners, and due dates live.",
  "sales.closingPlaybook.hesitation.title":"Decision hesitation","sales.closingPlaybook.hesitation.surfaceConcern":"Ask directly whether budget, risk, timing, or internal alignment blocks the decision.","sales.closingPlaybook.hesitation.reduceRisk":"Use a pilot, staged acceptance, or clear exit terms to reduce reversible risk.","sales.closingPlaybook.hesitation.bringDecisionMaker":"Invite the decision maker and delivery owner to a focused Q&A.","sales.closingPlaybook.hesitation.setDecisionDate":"Agree on a reasonable decision date without fake scarcity or countdown pressure.",
  "sales.closingPlaybook.payment.title":"Payment execution","sales.closingPlaybook.payment.confirmTerms":"Confirm scope, amount, tax details, and payment milestones in writing before invoicing.","sales.closingPlaybook.payment.simplifyPayment":"Provide a clear invoice, payment account, and compliant installment choices.","sales.closingPlaybook.payment.sendChecklist":"Send a one-page checklist with owners and expected settlement timing.","sales.closingPlaybook.payment.confirmKickoff":"After payment, confirm receipt, kickoff date, and first delivery immediately.","sales.closingPlaybook.ethics":"Never use fake discounts, fabricated scarcity, hidden terms, or persistent pressure. Every suggestion depends on informed consent and real customer value.",
};
