import type {Messages} from "../types";
export const enSuccessOperations:Messages={
 "successOps.contextMismatch":"The linked record must belong to this support record.","search.type.student_success_risk":"Success risk signal","search.type.student_success_intervention":"Success intervention",
 "successOps.checkins":"Check-ins","successOps.risks":"Risk signals","successOps.interventions":"Interventions","successOps.assessments":"Health assessments","successOps.lastCheckin":"Last check-in","successOps.openRisks":"Open / monitoring risks","successOps.highRisks":"High open / monitoring risks","successOps.activeInterventions":"Active interventions","successOps.create.checkin":"Record check-in","successOps.create.risk":"Record confirmed risk","successOps.create.intervention":"Plan intervention","successOps.edit":"Edit record","successOps.noRecords":"No visible records yet.","successOps.independence":"Risk, intervention and overall delivery status are independent. Changes require explicit confirmation.","successOps.notesHelp":"Record necessary delivery support notes. Avoid diagnoses, identity documents and unrelated sensitive information.","successOps.assessHealth":"Update overall health assessment","successOps.healthOptional":"Recording a check-in does not update delivery status unless you select an assessment.","successOps.updateReview":"Explicitly update next review","successOps.rationale":"Assessment rationale","successOps.noContext":"Case-level / no link","successOps.viewTasks":"View linked tasks","successOps.allTasks":"All case tasks","successOps.activeInterventionCount":"Active interventions","successOps.taskCount":"Visible linked tasks","successOps.noAssessment":"No health assessment","successOps.historySource":"Source","successOps.source.CASE":"Case","successOps.source.HEALTH":"Health assessment","successOps.source.RISK":"Risk signal","successOps.source.INTERVENTION":"Intervention","successOps.started":"Created","successOps.invalid":"Check required fields, dates and completion times.",
 "successOps.field.checkin_type":"Check-in type","successOps.field.occurred_at":"Occurred at","successOps.field.conducted_by":"Conducted by","successOps.field.summary":"Operational summary","successOps.field.next_steps":"Next steps","successOps.field.source_checkin_id":"Source check-in","successOps.field.risk_type":"Risk type","successOps.field.severity":"Risk severity","successOps.field.status":"Status","successOps.field.observed_at":"Observed at","successOps.field.owner_id":"Owner","successOps.field.resolution_note":"Resolution / dismissal note","successOps.field.resolved_at":"Resolved at","successOps.field.risk_signal_id":"Linked risk","successOps.field.intervention_type":"Support type","successOps.field.started_on":"Start date","successOps.field.target_end_on":"Target end date","successOps.field.completed_at":"Completed at","successOps.field.outcome_note":"Support outcome note","successOps.field.intervention_id":"Intervention",
 "successOps.checkinType.ROUTINE":"Routine","successOps.checkinType.ACADEMIC":"Academic review","successOps.checkinType.ENGAGEMENT":"Engagement","successOps.checkinType.TRANSITION":"Transition","successOps.checkinType.FAMILY_COORDINATION":"Family coordination","successOps.checkinType.OTHER":"Other",
 "successOps.riskType.ACADEMIC":"Academic","successOps.riskType.ATTENDANCE":"Attendance","successOps.riskType.ENGAGEMENT":"Engagement","successOps.riskType.LANGUAGE":"Language","successOps.riskType.TRANSITION":"Transition","successOps.riskType.SUPPORT_NEED":"Support need","successOps.riskType.LOGISTICS":"Logistics","successOps.riskType.OTHER":"Other",
 "successOps.severity.LOW":"Low","successOps.severity.MEDIUM":"Medium","successOps.severity.HIGH":"High","successOps.riskStatus.OPEN":"Open","successOps.riskStatus.MONITORING":"Monitoring","successOps.riskStatus.RESOLVED":"Resolved","successOps.riskStatus.DISMISSED":"Dismissed",
 "successOps.interventionType.ACADEMIC_SUPPORT":"Academic support","successOps.interventionType.LANGUAGE_SUPPORT":"Language support","successOps.interventionType.ENGAGEMENT_SUPPORT":"Engagement support","successOps.interventionType.ATTENDANCE_SUPPORT":"Attendance support","successOps.interventionType.MENTORING":"Mentoring","successOps.interventionType.TRANSITION_SUPPORT":"Transition support","successOps.interventionType.FAMILY_COORDINATION":"Family coordination","successOps.interventionType.OTHER":"Other",
 "successOps.interventionStatus.PLANNED":"Planned","successOps.interventionStatus.ACTIVE":"Active","successOps.interventionStatus.COMPLETED":"Completed","successOps.interventionStatus.CANCELLED":"Cancelled",
 "quality.rule.ACTIVE_CASE_WITHOUT_RECENT_CHECKIN":"Active case has no check-in in the last 30 calendar days","quality.rule.AT_RISK_CASE_WITHOUT_OPEN_RISK":"At-risk case has no open or monitoring risk","quality.rule.HIGH_RISK_WITHOUT_ACTIVE_INTERVENTION":"High risk has no active intervention","quality.rule.ACTIVE_INTERVENTION_PAST_TARGET_DATE":"Active intervention is past its target end date","quality.rule.OPEN_RISK_WITHOUT_OWNER":"Open or monitoring risk has no owner"
};
export const zhSuccessOperations:Messages={
 "successOps.contextMismatch":"关联记录必须属于当前学生服务与跟进案例。","search.type.student_success_risk":"学生服务与跟进风险信号","search.type.student_success_intervention":"学生服务与跟进支持措施",
 "successOps.checkins":"跟进记录","successOps.risks":"风险信号","successOps.interventions":"支持措施","successOps.assessments":"交付状态评估","successOps.lastCheckin":"最近跟进","successOps.openRisks":"未解决／观察中风险","successOps.highRisks":"未解决／观察中高风险","successOps.activeInterventions":"进行中支持措施","successOps.create.checkin":"记录跟进","successOps.create.risk":"记录已确认风险","successOps.create.intervention":"制定支持措施","successOps.edit":"编辑记录","successOps.noRecords":"暂无可见记录。","successOps.independence":"风险、支持措施和整体交付状态相互独立，变更需要明确确认。","successOps.notesHelp":"仅记录必要的交付支持信息，请勿填写诊断、身份文件或无关敏感信息。","successOps.assessHealth":"更新整体交付状态评估","successOps.healthOptional":"记录跟进不会更新交付状态，除非明确选择评估。","successOps.updateReview":"明确更新下次回顾日期","successOps.rationale":"评估依据","successOps.noContext":"案例级／不关联","successOps.viewTasks":"查看关联任务","successOps.allTasks":"案例全部任务","successOps.activeInterventionCount":"进行中支持措施","successOps.taskCount":"可见关联任务","successOps.noAssessment":"未进行交付状态评估","successOps.historySource":"来源","successOps.source.CASE":"案例","successOps.source.HEALTH":"交付状态评估","successOps.source.RISK":"风险信号","successOps.source.INTERVENTION":"支持措施","successOps.started":"已建立","successOps.invalid":"请检查必填字段、日期和完成时间。",
 "successOps.field.checkin_type":"跟进类型","successOps.field.occurred_at":"实际发生时间","successOps.field.conducted_by":"跟进人","successOps.field.summary":"运营摘要","successOps.field.next_steps":"后续动作","successOps.field.source_checkin_id":"来源跟进","successOps.field.risk_type":"风险类型","successOps.field.severity":"风险严重程度","successOps.field.status":"状态","successOps.field.observed_at":"发现时间","successOps.field.owner_id":"负责人","successOps.field.resolution_note":"解决／撤销说明","successOps.field.resolved_at":"解决时间","successOps.field.risk_signal_id":"关联风险","successOps.field.intervention_type":"支持类型","successOps.field.started_on":"开始日期","successOps.field.target_end_on":"目标结束日期","successOps.field.completed_at":"完成时间","successOps.field.outcome_note":"支持结果说明","successOps.field.intervention_id":"支持措施",
 "successOps.checkinType.ROUTINE":"常规跟进","successOps.checkinType.ACADEMIC":"学业复盘","successOps.checkinType.ENGAGEMENT":"参与度跟进","successOps.checkinType.TRANSITION":"衔接跟进","successOps.checkinType.FAMILY_COORDINATION":"家庭协同","successOps.checkinType.OTHER":"其他",
 "successOps.riskType.ACADEMIC":"学业","successOps.riskType.ATTENDANCE":"出勤","successOps.riskType.ENGAGEMENT":"参与度","successOps.riskType.LANGUAGE":"语言","successOps.riskType.TRANSITION":"衔接","successOps.riskType.SUPPORT_NEED":"支持需求","successOps.riskType.LOGISTICS":"行程安排","successOps.riskType.OTHER":"其他",
 "successOps.severity.LOW":"低","successOps.severity.MEDIUM":"中","successOps.severity.HIGH":"高","successOps.riskStatus.OPEN":"未解决","successOps.riskStatus.MONITORING":"观察中","successOps.riskStatus.RESOLVED":"已解决","successOps.riskStatus.DISMISSED":"已撤销",
 "successOps.interventionType.ACADEMIC_SUPPORT":"学业支持","successOps.interventionType.LANGUAGE_SUPPORT":"语言支持","successOps.interventionType.ENGAGEMENT_SUPPORT":"参与度支持","successOps.interventionType.ATTENDANCE_SUPPORT":"出勤支持","successOps.interventionType.MENTORING":"导师支持","successOps.interventionType.TRANSITION_SUPPORT":"衔接支持","successOps.interventionType.FAMILY_COORDINATION":"家庭协同","successOps.interventionType.OTHER":"其他",
 "successOps.interventionStatus.PLANNED":"计划中","successOps.interventionStatus.ACTIVE":"进行中","successOps.interventionStatus.COMPLETED":"已完成","successOps.interventionStatus.CANCELLED":"已取消",
 "quality.rule.ACTIVE_CASE_WITHOUT_RECENT_CHECKIN":"进行中的案例最近30个日历日缺少跟进","quality.rule.AT_RISK_CASE_WITHOUT_OPEN_RISK":"存在风险的案例缺少未解决或观察中风险","quality.rule.HIGH_RISK_WITHOUT_ACTIVE_INTERVENTION":"高风险缺少进行中的支持措施","quality.rule.ACTIVE_INTERVENTION_PAST_TARGET_DATE":"进行中的支持措施已超过目标结束日期","quality.rule.OPEN_RISK_WITHOUT_OWNER":"未解决或观察中风险缺少负责人"
};
