import type { Messages } from "../types";

export const zhV220:Messages={
  "common.disabled":"已停用","common.enable":"启用","common.disable":"停用","common.copy":"复制","common.approve":"批准","common.reject":"拒绝","common.none":"无","common.notAvailable":"不可用",
  "meta.automation":"自动化规则","meta.growth":"增长与招生归因","meta.portal":"家长门户",
  "nav.automation":"自动化","nav.growth":"增长与归因","nav.guardianPortal":"家长门户",
  "automation.eyebrow":"确定性工作流","automation.title":"自动化规则","automation.help":"用可解释的条件自动创建任务或站内通知，并保留每次执行记录。","automation.deterministic":"规则只执行已配置的确定性动作；不会自动作出录取、签约或其他高风险决定。","automation.new":"新建规则","automation.active":"启用规则","automation.succeeded":"成功执行","automation.failedRuns":"失败执行","automation.rules":"规则","automation.rulesHelp":"规则按事件幂等执行，同一事件不会重复创建动作。","automation.history":"最近执行","automation.noCondition":"无条件","automation.test":"测试","automation.empty":"尚未配置自动化规则。","automation.failed":"自动化操作失败，请检查权限或规则字段。","automation.created":"自动化规则已创建。","automation.createHelp":"选择业务事件、可选精确条件以及需要创建的动作。","automation.trigger":"触发事件","automation.conditionField":"条件字段","automation.conditionValue":"条件值","automation.action":"动作","automation.taskTitleZh":"任务标题（中文）","automation.taskTitleEn":"任务标题（英文）","automation.dueHours":"到期小时数",
  "automation.trigger.LEAD_CREATED":"线索创建","automation.trigger.LEAD_STATUS_CHANGED":"线索状态变化","automation.trigger.OPPORTUNITY_STAGE_CHANGED":"商机阶段变化","automation.trigger.CONTRACT_RENEWAL_DUE":"合同续约到期","automation.trigger.MANUAL":"人工事件","automation.action.TASK":"创建任务","automation.action.NOTIFICATION":"发送站内通知","automation.notification.title":"自动化规则已触发","automation.notification.body":"规则 {ruleZh} 已执行，请查看相关业务记录。",
  "automation.preview":"预览","automation.run":"执行","automation.previewMatch":"规则 v{version} 将匹配；预览不会产生任务或通知。","automation.previewMiss":"规则 v{version} 不匹配；未产生任何副作用。","automation.attempts":"尝试 {count} 次",
  "growth.eyebrow":"增长闭环","growth.title":"增长与招生归因","growth.help":"追踪活动、首次/辅助/末次触点，以及从线索到录取的招生旅程。","growth.newCampaign":"新建活动","growth.recordTouch":"记录触点","growth.journey":"招生旅程","growth.campaigns":"活动","growth.attributedLeads":"归因线索","growth.converted":"已转化","growth.campaignMetrics":"{touches} 次触点 · {leads} 条线索 · {converted} 条转化","growth.journeys":"招生旅程","growth.empty":"尚未创建增长活动。","growth.saved":"增长记录已保存。","growth.failed":"增长数据未能保存或加载。","growth.drawer.campaign":"新建增长活动","growth.drawer.attribution":"记录归因触点","growth.drawer.journey":"更新招生旅程","growth.code":"活动代码","growth.channel":"渠道","growth.budget":"预算","growth.lead":"线索","growth.campaign":"关联活动","growth.touchType":"触点类型","growth.source":"来源","growth.medium":"媒介","growth.content":"内容标识","growth.stage":"招生阶段","growth.probability":"成功概率","growth.nextAction":"下一步行动",
  "growth.activeCampaigns":"进行中活动","growth.pendingAdmissions":"待推进招生","growth.pipeline":"管线金额","growth.won":"已赢金额","growth.enrolled":"已入读","growth.roi":"活动 ROI",
  "portal.eyebrow":"安全的家庭协作","portal.title":"家长门户","portal.help":"创建限时邀请，让家庭查看最小必要信息并提交更正申请。","portal.invite":"创建邀请","portal.security":"收件邮箱必须属于该家庭的成员或学生监护人；授权前隐藏地址与学生资料。系统只存储令牌摘要，链接可随时撤销。","portal.linkOnce":"请立即安全交付此一次性显示的访问链接：","portal.copied":"邀请链接已复制。","portal.invitations":"邀请记录","portal.invitationHelp":"访问范围固定为单一家庭；过期或撤销后立即失效。","portal.expires":"到期 {date}","portal.lastAccess":"最近访问 {date}","portal.neverAccessed":"尚未访问","portal.revoke":"撤销","portal.updateRequests":"资料更新申请","portal.review":"复核","portal.noUpdates":"暂无待处理资料更新。","portal.inviteHelp":"只能邀请已记录在该家庭中的邮箱，有效期最长 30 天；原始链接不会写入日志或数据库。","portal.householdRequired":"请选择邀请对应的家庭。","portal.expiry":"失效时间","portal.createLink":"创建安全链接","portal.created":"安全邀请已创建。","portal.decided":"资料更新申请已处理。","portal.failed":"门户操作失败，请检查收件人是否属于该家庭、权限、有效期或输入。","portal.decisionNote":"处理依据","portal.appliedChanges":"已应用字段","portal.field.address":"家庭地址","portal.field.preferredContact":"偏好联系方式","portal.field.note":"补充说明",
  "portal.public.eyebrow":"家庭安全访问","portal.public.title":"学生与家庭门户","portal.public.expires":"此链接有效至 {date}","portal.public.noAddress":"暂未记录地址","portal.public.students":"学生资料","portal.public.requestUpdate":"申请更新资料","portal.public.requestHelp":"工作人员会复核每项申请；批准的受支持字段将写入 CRM，并保留应用回执。","portal.public.changeRequired":"请至少填写一项需要更新的内容。","portal.public.submitted":"资料更新申请已安全提交。","portal.public.failed":"申请未能提交；链接可能已过期或请求过于频繁。","portal.public.submit":"提交更新申请",
  "portal.public.consentTitle":"授权后查看家庭资料","portal.public.consentHelp":"为保护学生与家庭资料，请先确认本次访问及数据处理授权。授权前不会显示地址或学生记录。","portal.public.consentAgreement":"我确认自己是获邀的家庭成员或监护人，并同意为本次服务访问处理必要资料。","portal.public.consentRequired":"必须确认授权后才能继续。","portal.public.consentSaved":"访问授权已记录。","portal.public.continue":"授权并继续",
  "communications.eyebrow":"经同意的沟通","communications.title":"沟通收件箱","communications.help":"在一个线程中保留主题、正文、投递状态与失败原因。","communications.new":"新建会话","communications.governance":"发送前会实时检查联系人渠道同意、处理限制和勿扰状态；不满足时不会投递。","communications.empty":"尚无沟通会话。","communications.choose":"请选择一个会话。","communications.message":"消息正文","communications.send":"发送邮件","communications.subject":"主题","communications.purpose":"处理目的","communications.contactRequired":"请选择联系人。","communications.created":"沟通会话已创建。","communications.sent":"消息已发送并记录回执。","communications.consentRequired":"联系人未授权此渠道与处理目的，消息未发送。","communications.deliveryMissing":"邮件投递服务尚未配置；消息已记录为失败。","communications.failed":"沟通操作失败，请检查输入或稍后重试。",
  "communications.search":"搜索联系人、主题或正文","communications.noResults":"没有匹配的会话。","communications.recordInbound":"记录来信","communications.recorded":"来信已记录。","communications.retry":"重试投递","communications.retryQueued":"消息已重新投递并更新状态。","communications.attempts":"尝试次数",
  "operations.provider.PAYMENT":"支付平台","operations.webhooksEnabled":"Webhook 已启用且已配置","operations.webhooksDisabled":"Webhook 可选功能未启用","operations.integrationsEnabled":"集成同步已启用且已配置","operations.integrationsDisabled":"集成同步可选功能未启用","operations.optionalWorkerHelp":"未启用的可选 Worker 不参与发布就绪判定；启用后必须具备凭据、心跳和健康队列。","quality.trend":"质量趋势","quality.trendHelp":"每日记录开放问题的严重度和已解决数量，用于衡量规则效果。",
  "quality.rules":"质量规则","quality.rulesHelp":"可按工作区启停规则并设置严重度；扫描会自动关闭已修复的问题。","quality.enabled":"启用","quality.severityLabel":"严重度","quality.ruleSaved":"规则配置已保存。","quality.assignToMe":"分配给我","quality.assigned":"问题已分配给你。","quality.rule.contactMethodMissing":"联系人缺少有效沟通方式","quality.rule.opportunityNextActionMissing":"活跃商机缺少下一步行动","quality.rule.organizationOwnerMissing":"机构缺少负责人","quality.rule.studentGuardianMissing":"学生缺少监护人关系","quality.rule.consentExpired":"联系人授权已过期","quality.rule.opportunityExchangeRateMissing":"外币商机缺少汇率快照","quality.rule.leadAttributionMissing":"线索缺少归因触点","quality.rule.contactDuplicate":"发现重复联系人","quality.rule.guardianMissing":"学生缺少监护人关系","quality.rule.exchangeRateMissing":"外币商机缺少汇率快照","quality.rule.attributionMissing":"线索缺少归因触点","quality.rule.duplicateContact":"发现重复联系人",
  "dashboard.attributedLeads":"归因线索","dashboard.pendingAdmissions":"待推进招生"
};

export const enV220:Messages={
  "common.disabled":"Disabled","common.enable":"Enable","common.disable":"Disable","common.copy":"Copy","common.approve":"Approve","common.reject":"Reject","common.none":"None","common.notAvailable":"N/A",
  "meta.automation":"Automation rules","meta.growth":"Growth and admissions attribution","meta.portal":"Guardian portal",
  "nav.automation":"Automation","nav.growth":"Growth & attribution","nav.guardianPortal":"Guardian portal",
  "automation.eyebrow":"DETERMINISTIC WORKFLOWS","automation.title":"Automation rules","automation.help":"Create tasks or in-app notifications from explainable conditions, with a run record for every event.","automation.deterministic":"Rules execute configured deterministic actions only; they never make admission, contract, or other high-risk decisions.","automation.new":"New rule","automation.active":"Active rules","automation.succeeded":"Successful runs","automation.failedRuns":"Failed runs","automation.rules":"Rules","automation.rulesHelp":"Events are idempotent, so the same event never creates duplicate actions.","automation.history":"Recent runs","automation.noCondition":"No condition","automation.test":"Test","automation.empty":"No automation rules are configured.","automation.failed":"The automation operation failed. Check permissions and rule fields.","automation.created":"Automation rule created.","automation.createHelp":"Choose a business event, an optional exact condition, and the action to create.","automation.trigger":"Trigger event","automation.conditionField":"Condition field","automation.conditionValue":"Condition value","automation.action":"Action","automation.taskTitleZh":"Task title (Chinese)","automation.taskTitleEn":"Task title (English)","automation.dueHours":"Hours until due",
  "automation.trigger.LEAD_CREATED":"Lead created","automation.trigger.LEAD_STATUS_CHANGED":"Lead status changed","automation.trigger.OPPORTUNITY_STAGE_CHANGED":"Opportunity stage changed","automation.trigger.CONTRACT_RENEWAL_DUE":"Contract renewal due","automation.trigger.MANUAL":"Manual event","automation.action.TASK":"Create task","automation.action.NOTIFICATION":"Send in-app notification","automation.notification.title":"Automation rule triggered","automation.notification.body":"Rule {ruleEn} ran. Review the related business record.",
  "automation.preview":"Preview","automation.run":"Run","automation.previewMatch":"Rule v{version} will match; the preview creates no tasks or notifications.","automation.previewMiss":"Rule v{version} does not match; no side effects were created.","automation.attempts":"{count} attempts",
  "growth.eyebrow":"GROWTH LOOP","growth.title":"Growth & admissions attribution","growth.help":"Track campaigns, first/assist/last touches, and the admissions journey from inquiry to enrolment.","growth.newCampaign":"New campaign","growth.recordTouch":"Record touch","growth.journey":"Admissions journey","growth.campaigns":"Campaigns","growth.attributedLeads":"Attributed leads","growth.converted":"Converted","growth.campaignMetrics":"{touches} touches · {leads} leads · {converted} converted","growth.journeys":"Admissions journeys","growth.empty":"No growth campaigns yet.","growth.saved":"Growth record saved.","growth.failed":"Growth data could not be saved or loaded.","growth.drawer.campaign":"New growth campaign","growth.drawer.attribution":"Record attribution touch","growth.drawer.journey":"Update admissions journey","growth.code":"Campaign code","growth.channel":"Channel","growth.budget":"Budget","growth.lead":"Lead","growth.campaign":"Campaign","growth.touchType":"Touch type","growth.source":"Source","growth.medium":"Medium","growth.content":"Content identifier","growth.stage":"Admissions stage","growth.probability":"Success probability","growth.nextAction":"Next action",
  "growth.activeCampaigns":"Active campaigns","growth.pendingAdmissions":"Pending admissions","growth.pipeline":"Pipeline","growth.won":"Won revenue","growth.enrolled":"Enrolled","growth.roi":"Campaign ROI",
  "portal.eyebrow":"SECURE FAMILY COLLABORATION","portal.title":"Guardian portal","portal.help":"Create time-limited invitations so families can view minimum necessary data and request corrections.","portal.invite":"Create invitation","portal.security":"The recipient email must belong to a household member or student guardian. Address and student data stay hidden until consent; only a revocable token digest is stored.","portal.linkOnce":"Securely deliver this one-time displayed access link now:","portal.copied":"Invitation link copied.","portal.invitations":"Invitations","portal.invitationHelp":"Access is fixed to one household and stops immediately after expiry or revocation.","portal.expires":"Expires {date}","portal.lastAccess":"Last access {date}","portal.neverAccessed":"Never accessed","portal.revoke":"Revoke","portal.updateRequests":"Data update requests","portal.review":"Review","portal.noUpdates":"No pending data updates.","portal.inviteHelp":"Only an email already linked to the household can be invited, for no more than 30 days. The raw link is never stored in logs or the database.","portal.householdRequired":"Select the household for this invitation.","portal.expiry":"Expiry time","portal.createLink":"Create secure link","portal.created":"Secure invitation created.","portal.decided":"Data update request decided.","portal.failed":"The portal operation failed. Check that the recipient belongs to the household, permission, expiry, or input.","portal.decisionNote":"Decision evidence","portal.appliedChanges":"Applied fields","portal.field.address":"Household address","portal.field.preferredContact":"Preferred contact method","portal.field.note":"Additional note",
  "portal.public.eyebrow":"SECURE FAMILY ACCESS","portal.public.title":"Student & family portal","portal.public.expires":"This link is valid until {date}","portal.public.noAddress":"No address is currently recorded","portal.public.students":"Student records","portal.public.requestUpdate":"Request a data update","portal.public.requestHelp":"Staff review every request. Approved supported fields are applied to CRM with an application receipt.","portal.public.changeRequired":"Enter at least one change to request.","portal.public.submitted":"The data update request was securely submitted.","portal.public.failed":"The request could not be submitted. The link may be expired or rate-limited.","portal.public.submit":"Submit update request",
  "portal.public.consentTitle":"Authorise access to family data","portal.public.consentHelp":"To protect student and family data, confirm this access and necessary processing. Address and student records remain hidden until consent.","portal.public.consentAgreement":"I confirm I am the invited household member or guardian and consent to necessary data processing for this service access.","portal.public.consentRequired":"Confirm consent before continuing.","portal.public.consentSaved":"Access consent recorded.","portal.public.continue":"Consent and continue",
  "communications.eyebrow":"CONSENT-GOVERNED COMMUNICATION","communications.title":"Communications inbox","communications.help":"Keep subject, content, delivery state, and failures in one conversation thread.","communications.new":"New conversation","communications.governance":"Before sending, the system checks channel consent, processing restrictions, and do-not-contact state in real time.","communications.empty":"No communication threads yet.","communications.choose":"Choose a conversation.","communications.message":"Message body","communications.send":"Send email","communications.subject":"Subject","communications.purpose":"Processing purpose","communications.contactRequired":"Select a contact.","communications.created":"Communication thread created.","communications.sent":"Message sent and receipt recorded.","communications.consentRequired":"The contact has not granted this channel and purpose; no message was sent.","communications.deliveryMissing":"Email delivery is not configured; the message was recorded as failed.","communications.failed":"The communication operation failed. Check the input or try again.",
  "communications.search":"Search contact, subject, or message","communications.noResults":"No matching conversations.","communications.recordInbound":"Record inbound","communications.recorded":"Inbound message recorded.","communications.retry":"Retry delivery","communications.retryQueued":"Message redelivered and status updated.","communications.attempts":"Attempts",
  "operations.provider.PAYMENT":"Payment platform","operations.webhooksEnabled":"Webhooks enabled and configured","operations.webhooksDisabled":"Optional webhooks are disabled","operations.integrationsEnabled":"Integration sync enabled and configured","operations.integrationsDisabled":"Optional integration sync is disabled","operations.optionalWorkerHelp":"Disabled optional workers do not block release readiness. Once enabled, credentials, heartbeats, and healthy queues are required.","quality.trend":"Quality trend","quality.trendHelp":"Daily open issues by severity and resolved counts show whether quality rules are effective.",
  "quality.rules":"Quality rules","quality.rulesHelp":"Enable rules and set severity per workspace. Scans automatically close issues whose sources are fixed.","quality.enabled":"Enabled","quality.severityLabel":"Severity","quality.ruleSaved":"Rule configuration saved.","quality.assignToMe":"Assign to me","quality.assigned":"Issue assigned to you.","quality.rule.contactMethodMissing":"Contact has no valid communication method","quality.rule.opportunityNextActionMissing":"Active opportunity has no next action","quality.rule.organizationOwnerMissing":"Organization has no owner","quality.rule.studentGuardianMissing":"Student has no guardian relationship","quality.rule.consentExpired":"Contact consent has expired","quality.rule.opportunityExchangeRateMissing":"Foreign-currency opportunity lacks an exchange-rate snapshot","quality.rule.leadAttributionMissing":"Lead has no attribution touch","quality.rule.contactDuplicate":"Possible duplicate contact","quality.rule.guardianMissing":"Student has no guardian relationship","quality.rule.exchangeRateMissing":"Foreign-currency opportunity lacks an exchange-rate snapshot","quality.rule.attributionMissing":"Lead has no attribution touch","quality.rule.duplicateContact":"Possible duplicate contact",
  "dashboard.attributedLeads":"Attributed leads","dashboard.pendingAdmissions":"Pending admissions"
};
