import type { Messages } from "../types";
export const zhV250:Messages={
  "nav.actionCenter":"我的行动中心","meta.actionCenter":"我的行动中心","meta.actionCenter.description":"按当前角色汇总需要处理的真实业务工作。",
  "actionCenter.eyebrow":"角色工作台","actionCenter.title":"我的行动中心","actionCenter.description":"为{role}汇总当前权限范围内可执行的真实工作，不自动修改任何业务记录。","actionCenter.summary":"行动摘要","actionCenter.total":"待处理事项","actionCenter.urgent":"紧急事项","actionCenter.workstreams":"工作流数量","actionCenter.urgentCount":"{count} 项紧急","actionCenter.clear":"没有紧急事项","actionCenter.filters":"按业务类型筛选","actionCenter.category.all":"全部","actionCenter.category.work":"个人工作","actionCenter.category.sales":"销售","actionCenter.category.service":"客户服务","actionCenter.category.governance":"治理","actionCenter.source":"来源：实时角色权限聚合","actionCenter.empty":"当前分区已清空","actionCenter.emptyHelp":"没有权限范围内的待处理项目；新的真实事项出现后会自动显示。",
  "actionCenter.item.overdueTasks":"{count} 项任务已逾期","actionCenter.item.overdueTasksHelp":"打开任务列表，重新确认负责人、截止时间与下一步。","actionCenter.item.todayTasks":"今天有 {count} 项任务","actionCenter.item.todayTasksHelp":"按优先级完成今天到期的真实工作。","actionCenter.item.approvals":"{count} 项审批待处理","actionCenter.item.approvalsHelp":"核对业务证据并执行 Maker-Checker 决策。","actionCenter.item.renewals":"{count} 份合同即将续约","actionCenter.item.renewalsHelp":"确认续约意向、负责人和下一次联系。","actionCenter.item.riskContracts":"{count} 份合同需要关注","actionCenter.item.riskContractsHelp":"处理风险合同及相关收款或交付问题。","actionCenter.item.newLeads":"{count} 条新线索待跟进","actionCenter.item.newLeadsHelp":"完成线索资格判断并安排下一步。","actionCenter.item.progression":"{count} 项升学进度待处理","actionCenter.item.progressionHelp":"更新里程碑证据和客户服务动作。","actionCenter.item.admissions":"{count} 项申请决定待处理","actionCenter.item.admissionsHelp":"核对材料和权限后完成申请流程。","actionCenter.item.notifications":"{count} 条未读通知","actionCenter.item.notificationsHelp":"查看任务、审批和安全通知。","actionCenter.item.privacy":"{count} 项隐私请求待处理","actionCenter.item.privacyHelp":"核对身份、法定期限、审批与执行凭证。","actionCenter.item.operations":"{count} 项后台任务异常","actionCenter.item.operationsHelp":"检查失败或卡死任务，修正原因后执行已审计重试。",
  "operations.validateConnector":"验证连接器","operations.validationPassed":"连接器沙箱验证已通过，并保存了有效期 24 小时的验证凭证。","operations.validationFailed":"连接器验证失败；同步未排队，请检查适配器配置。","operations.validationCurrent":"验证有效 · {date}","operations.validationExpired":"验证失败或已过期 · {date}","operations.validationMissing":"尚无验证凭证；同步保持禁用。","operations.validationCapabilities":"已验证 {count} 项适配器能力",
  "operations.observabilityEnabled":"遥测已启用","operations.observabilityDisabled":"遥测未启用","operations.ssoEnabled":"企业 SSO 已启用","operations.ssoDisabled":"企业 SSO 未启用","operations.scimEnabled":"SCIM 已启用","operations.scimDisabled":"SCIM 未启用","admin.technicalDetails":"技术详情"
};
export const enV250:Messages={
  "nav.actionCenter":"My action center","meta.actionCenter":"My action center","meta.actionCenter.description":"Review real work requiring action in your current role.",
  "actionCenter.eyebrow":"ROLE WORKSPACE","actionCenter.title":"My action center","actionCenter.description":"Real, actionable work visible to {role}. This view never changes business records automatically.","actionCenter.summary":"Action summary","actionCenter.total":"Items requiring action","actionCenter.urgent":"Urgent items","actionCenter.workstreams":"Active workstreams","actionCenter.urgentCount":"{count} urgent","actionCenter.clear":"No urgent items","actionCenter.filters":"Filter by business area","actionCenter.category.all":"All","actionCenter.category.work":"Personal work","actionCenter.category.sales":"Sales","actionCenter.category.service":"Customer service","actionCenter.category.governance":"Governance","actionCenter.source":"Source: live role-scoped aggregates","actionCenter.empty":"This area is clear","actionCenter.emptyHelp":"There are no actionable items in your current access scope. New real work appears automatically.",
  "actionCenter.item.overdueTasks":"{count} overdue tasks","actionCenter.item.overdueTasksHelp":"Open tasks and reconfirm owner, deadline, and next step.","actionCenter.item.todayTasks":"{count} tasks due today","actionCenter.item.todayTasksHelp":"Work through today's real tasks in priority order.","actionCenter.item.approvals":"{count} approvals awaiting action","actionCenter.item.approvalsHelp":"Review evidence and make a Maker-Checker decision.","actionCenter.item.renewals":"{count} contracts approaching renewal","actionCenter.item.renewalsHelp":"Confirm renewal intent, owner, and next contact.","actionCenter.item.riskContracts":"{count} contracts need attention","actionCenter.item.riskContractsHelp":"Resolve risk, payment, or delivery issues.","actionCenter.item.newLeads":"{count} new leads to follow up","actionCenter.item.newLeadsHelp":"Qualify each lead and schedule its next step.","actionCenter.item.progression":"{count} progression items need action","actionCenter.item.progressionHelp":"Update milestone evidence and customer-service work.","actionCenter.item.admissions":"{count} admissions decisions pending","actionCenter.item.admissionsHelp":"Review evidence and permissions before completing the workflow.","actionCenter.item.notifications":"{count} unread notifications","actionCenter.item.notificationsHelp":"Review task, approval, and security notices.","actionCenter.item.privacy":"{count} privacy requests need action","actionCenter.item.privacyHelp":"Review identity evidence, statutory deadlines, approvals, and execution receipts.","actionCenter.item.operations":"{count} background jobs need attention","actionCenter.item.operationsHelp":"Inspect failed or stuck jobs, correct the cause, and use the audited retry action.",
  "operations.validateConnector":"Validate connector","operations.validationPassed":"Connector sandbox validation passed and a 24-hour receipt was stored.","operations.validationFailed":"Connector validation failed. Sync was not queued; check the adapter configuration.","operations.validationCurrent":"Validation current · {date}","operations.validationExpired":"Validation failed or expired · {date}","operations.validationMissing":"No validation receipt; sync remains disabled.","operations.validationCapabilities":"{count} adapter capabilities verified",
  "operations.observabilityEnabled":"Telemetry enabled","operations.observabilityDisabled":"Telemetry disabled","operations.ssoEnabled":"Enterprise SSO enabled","operations.ssoDisabled":"Enterprise SSO disabled","operations.scimEnabled":"SCIM enabled","operations.scimDisabled":"SCIM disabled","admin.technicalDetails":"Technical details"
};
