import type {Messages} from "../types";

export const zhV270:Messages={
  "nav.recycleBin":"回收站",
  "recycle.eyebrow":"可恢复删除","recycle.title":"回收站","recycle.description":"查看超级管理员权限范围内已移除的核心业务记录，并在保留期内恢复。","recycle.retention":"记录移入回收站后保留 30 天；到期后由后台清理任务永久删除。","recycle.itemsEyebrow":"待清理记录","recycle.items":"回收站中的记录（{count}）","recycle.removedAt":"移入时间：{date}","recycle.expiresAt":"计划永久删除：{date}","recycle.restore":"恢复","recycle.restoreTitle":"恢复业务记录","recycle.restoreConfirm":"确认恢复“{name}”？记录将重新出现在业务列表中。","recycle.restored":"记录已从回收站恢复。","recycle.restoreFailed":"记录未能恢复，请确认它仍在 30 天保留期内。","recycle.empty":"回收站当前为空。","recycle.loadFailed":"无法载入回收站，请检查超级管理员权限和数据库连接。",
  "recycle.kind.organization":"学校/机构","recycle.kind.contact":"联系人","recycle.kind.task":"任务","recycle.kind.student":"学生","recycle.kind.household":"家庭",
  "crm.archive":"移入回收站","crm.archiveConfirm":"确认将这条记录移入回收站？它会从活动列表隐藏，可由超级管理员在 30 天内恢复。","crm.archived":"记录已移入回收站，并将保留 30 天。",
  "education.archiveStudent":"将学生移入回收站","education.archiveHousehold":"将家庭移入回收站","education.studentArchived":"学生记录已移入回收站，并将保留 30 天。","education.householdArchived":"家庭记录已移入回收站，并将保留 30 天。","education.recycleConfirm":"记录将移入回收站，可由超级管理员在 30 天内恢复。"
  ,"settings.passwordSame":"新密码不能与当前密码相同。","settings.passwordRateLimited":"尝试次数过多，请稍后再更新密码。","settings.passwordServiceUnavailable":"登录验证服务暂时不可用，密码没有改变，请稍后重试。","settings.passwordReauthentication":"当前登录验证已过期，请重新登录后修改密码。"
  ,"communications.purposeHelp":"处理目的会用于实时匹配联系人授权范围，请选择最贴近本次会话的类别。","communications.purposeClassification":"现有四类已覆盖服务跟进、申请/合同/付款、活动预约和营销推广；新增目的前必须同步扩展联系人同意记录。","communications.purpose.service":"服务与个案跟进","communications.purpose.transactional":"申请、合同与付款通知","communications.purpose.event":"活动与预约","communications.purpose.marketing":"营销与推广","communications.status.open":"进行中","communications.status.closed":"已结束","communications.delivery.queued":"等待投递","communications.delivery.sending":"投递中","communications.delivery.processing":"投递中","communications.delivery.sent":"已发送","communications.delivery.delivered":"已送达","communications.delivery.failed":"投递失败","communications.delivery.uncertain":"结果待人工确认","communications.delivery.received":"已接收"
};

export const enV270:Messages={
  "nav.recycleBin":"Recycle bin",
  "recycle.eyebrow":"RECOVERABLE DELETION","recycle.title":"Recycle bin","recycle.description":"Review removed core business records within super-admin scope and restore them during retention.","recycle.retention":"Records remain in the recycle bin for 30 days, then a background cleanup permanently deletes them.","recycle.itemsEyebrow":"PENDING CLEANUP","recycle.items":"Records in recycle bin ({count})","recycle.removedAt":"Removed: {date}","recycle.expiresAt":"Permanent deletion scheduled: {date}","recycle.restore":"Restore","recycle.restoreTitle":"Restore business record","recycle.restoreConfirm":"Restore “{name}”? It will reappear in active business lists.","recycle.restored":"Record restored from the recycle bin.","recycle.restoreFailed":"The record could not be restored. Confirm that it remains within the 30-day retention period.","recycle.empty":"The recycle bin is empty.","recycle.loadFailed":"The recycle bin could not be loaded. Check super-admin access and the database connection.",
  "recycle.kind.organization":"School / organization","recycle.kind.contact":"Contact","recycle.kind.task":"Task","recycle.kind.student":"Student","recycle.kind.household":"Household",
  "crm.archive":"Move to recycle bin","crm.archiveConfirm":"Move this record to the recycle bin? It will be hidden from active lists and a super administrator can restore it for 30 days.","crm.archived":"Record moved to the recycle bin and retained for 30 days.",
  "education.archiveStudent":"Move student to recycle bin","education.archiveHousehold":"Move household to recycle bin","education.studentArchived":"Student moved to the recycle bin and retained for 30 days.","education.householdArchived":"Household moved to the recycle bin and retained for 30 days.","education.recycleConfirm":"The record will move to the recycle bin and a super administrator can restore it for 30 days."
  ,"settings.passwordSame":"The new password must differ from the current password.","settings.passwordRateLimited":"Too many attempts. Wait before updating the password again.","settings.passwordServiceUnavailable":"The sign-in verification service is temporarily unavailable. The password was not changed.","settings.passwordReauthentication":"Your sign-in verification expired. Sign in again before changing the password."
  ,"communications.purposeHelp":"The processing purpose is matched against the contact's live consent scope. Choose the closest category for this conversation.","communications.purposeClassification":"These four categories cover service follow-up, applications/contracts/payments, events/appointments, and marketing. Adding another purpose also requires a matching contact-consent category.","communications.purpose.service":"Service & case follow-up","communications.purpose.transactional":"Application, contract & payment notices","communications.purpose.event":"Events & appointments","communications.purpose.marketing":"Marketing & promotions","communications.status.open":"Open","communications.status.closed":"Closed","communications.delivery.queued":"Queued","communications.delivery.sending":"Sending","communications.delivery.processing":"Processing","communications.delivery.sent":"Sent","communications.delivery.delivered":"Delivered","communications.delivery.failed":"Failed","communications.delivery.uncertain":"Outcome requires review","communications.delivery.received":"Received"
};
