import type { Messages } from "../types";
const entries:Record<string,[string,string]>={
  "nav.adminOverview":["系统管理概况","Administration overview"],
  "nav.schools":["学校和机构","Schools & institutions"],"nav.people":["客户管理","Customer management"],"nav.households":["家庭客户管理","Family customers"],"nav.students":["孩子与学生","Children & students"],"nav.relationships":["客户关系","Customer relationships"],"nav.sales":["销售拓展","Sales development"],"nav.business":["合同与财务","Contracts & finance"],"nav.customerService":["客户服务","Customer service"],"nav.messages":["客户通信","Customer communications"],"nav.guardianPortal":["家庭自助门户","Family self-service portal"],"nav.data":["数据治理","Data governance"],"nav.reports":["分析与报告","Analytics & reports"],"nav.progression":["学业升年","Academic progression"],
  "modules.schools.title":["学校和机构","Schools & institutions"],"modules.schools.add":["新建学校或机构","New school or institution"],"modules.schools.search":["搜索名称、简称、城市或课程…","Search names, aliases, cities or curricula…"],"modules.people.title":["客户管理","Customer management"],"modules.people.add":["新建客户","New customer"],"modules.people.description":["统一客户档案、跟进目标、业务关联和通信授权。","Manage customer profiles, follow-up goals, business links and communication consent."],"meta.people":["客户管理","Customer management"],"meta.schools":["学校和机构","Schools & institutions"],"meta.households":["家庭客户管理","Family customers"],
  "customerOps.title":["客户运营工作台","Customer operations"],"customerOps.sections":["工作区栏目","Workspace sections"],"customerOps.shortName":["简称","Short name"],"customerOps.entries":["跟进记录","Follow-up entries"],"customerOps.tab.overview":["信息概况","Overview"],"customerOps.tab.followUp":["跟进与目标","Follow-up & goals"],"customerOps.tab.business":["合同与产品","Contracts & products"],"customerOps.tab.people":["客户与家庭成员","Customers & family members"],"customerOps.tab.privacy":["权限与通信","Access & communication"],
  "customerOps.goal":["运营目标","Objective"],"customerOps.targetLevel":["目标关系级别","Target relationship level"],"customerOps.targetCount":["关键结果：联系次数","Key result: contact count"],"customerOps.startDate":["开始日期（UTC）","Start date (UTC)"],"customerOps.dueDate":["目标期限（UTC）","Due date (UTC)"],"customerOps.editPlan":["设置或调整跟进目标","Set or adjust follow-up goals"],"customerOps.record":["记录实际跟进","Record a follow-up"],"customerOps.summary":["沟通内容与证据","Summary & evidence"],"customerOps.nextStep":["下一步行动","Next action"],"customerOps.overdue":["目标已逾期，建议调整计划并联系负责人。","This objective is overdue. Review the plan with the owner."],"customerOps.limited":["关联列表显示最近 50 条，完整内容请到相应业务页面查看。","Related lists show up to 50 records. Open the relevant workspace for the complete list."],"customerOps.recent":["最近 {count} 条跟进记录 · 总计 {total} 条；目标统计使用全量记录。","Latest {count} entries · {total} total. Goal counts include all entries."],"customerOps.linkContract":["关联已有合同","Link an existing contract"],"customerOps.relationshipEvidence":["记录并审核组织关系里程碑","Record and review relationship evidence"],"customerOps.evidenceHelp":["建议不会自动提升级别；级别须依据实际证据更新。","Suggestions do not upgrade levels automatically; update levels only with evidence."],
  "customerOps.suggestion.1":["建议：确认客户角色、需求和首个有效联系。","Suggestion: confirm the customer's role, needs and first useful contact."],"customerOps.suggestion.2":["建议：安排自愿的深入沟通，明确双方下一步。","Suggestion: arrange a voluntary deeper conversation and agree on next steps."],"customerOps.suggestion.3":["建议：持续服务、确认长期需求并尊重家庭隐私。","Suggestion: provide ongoing service, confirm long-term needs and respect family privacy."],"customerOps.suggestion.4":["建议：持续维护合作；引荐必须出于客户自愿。","Suggestion: maintain the relationship; referrals must always be voluntary."],
  "customerOps.ownerNotAssignable":["当前角色不能分配该负责人，请选择自己或联系管理员。","Your role cannot assign this owner. Select yourself or contact an administrator."],"customerOps.migrationRequired":["数据库结构未更新，请由管理员执行本版本迁移后重试。","The database schema is outdated. Ask an administrator to apply this release's migrations."],
  "customerOps.field.city":["城市","City"],"customerOps.field.curriculum":["课程","Curriculum"],"customerOps.field.website":["网站","Website"],"customerOps.field.email":["邮箱","Email"],"customerOps.field.phone":["电话","Phone"],"customerOps.field.title":["职位","Title"],"customerOps.field.preferred_language":["首选语言","Preferred language"],"customerOps.field.next_follow_up_at":["下次跟进","Next follow-up"],
  "customerOps.previousMonth":["上个月","Previous month"],"customerOps.nextMonth":["下个月","Next month"],
  "customerOps.inbox":["通信收件箱","Communications inbox"],"customerOps.templates":["模板发信与群发","Templates & bulk email"],"customerOps.email":["使用模板联系客户","Contact with a template"],"customerOps.template":["邮件模板","Email template"],"customerOps.template.FOLLOW_UP":["服务跟进","Service follow-up"],"customerOps.template.MEETING":["预约沟通","Arrange a conversation"],"customerOps.template.PROGRAM":["课程推广（需营销同意）","Program promotion (marketing consent required)"],"customerOps.recipients":["添加收件客户（最多 50 位）","Add customer recipients (up to 50)"],"customerOps.preview":["生成个性化预览","Generate personalized previews"],"customerOps.blocked":["不可发送：无邮箱、不可访问或禁止联系","Blocked: missing email, inaccessible or do-not-contact"],"customerOps.bulkHelp":["每位客户独立发信，不会暴露其他收件人。姓名和负责人自动替换；群发最多 50 位，授权与退订规则逐人检查。","Each customer receives a separate email without other recipients exposed. Names and owners are filled automatically. Up to 50 recipients; consent and suppression are checked individually."],"customerOps.sendConfirm":["请核对所有预览。确认后仅进入发送队列，不代表邮件已投递。","Review all previews. Confirmation queues delivery; it does not mean the email has been delivered."],"customerOps.queue":["确认并入队（{count} 位）","Confirm & queue ({count} recipients)"],"customerOps.queuedResult":["已入队 {queued} 位，未入队 {failed} 位。","Queued: {queued}; not queued: {failed}."],"customerOps.queued":["已入队，查看通信记录","Queued — view thread"],"customerOps.retryBatch":["重试本批次（已入队项目不会重复）","Retry this batch (queued items are not duplicated)"],"customerOps.newBatch":["开始新批次","Start a new batch"],"customerOps.previewChanged":["客户资料发生变化，请重新生成预览后发送。","Customer details changed. Generate a new preview before sending."],"customerOps.providerHelp":["邮件通过现有 Worker 投递。默认 Resend；腾讯、阿里、Outlook、Gmail、Zoho 可通过受控 HTTPS 邮件中继接入，需管理员配置真实授权。尚未启用邮箱双向同步。","Delivery uses the existing Worker. Resend is the default; Tencent, Alibaba, Outlook, Gmail and Zoho can use an authenticated HTTPS mail relay configured by an administrator. Bidirectional mailbox sync is not enabled."],
  "customerOps.delivery.RECIPIENT_UNAVAILABLE":["客户不可发送或未提供邮箱","Recipient unavailable or missing email"],"customerOps.delivery.COMMUNICATION_CONSENT_REQUIRED":["缺少有效通信授权","Valid communication consent is required"],"customerOps.delivery.COMMUNICATION_QUEUE_FAILED":["入队失败，请重试或联系管理员","Queue failed; retry or contact an administrator"],
};
export const zhV3120:Messages=Object.fromEntries(Object.entries(entries).map(([key,value])=>[key,value[0]]));
export const enV3120:Messages=Object.fromEntries(Object.entries(entries).map(([key,value])=>[key,value[1]]));
