import type { Messages } from "../types";

export const zhV390:Messages={
  "products.introduction":"产品介绍","products.introductionZh":"中文详细介绍","products.introductionEn":"英文详细介绍","products.introductionEmpty":"尚未填写产品介绍。","products.purchasers":"购买此产品的客户","products.noPurchasers":"尚无客户购买记录。",
  "contact.profileEyebrow":"联系人资料","contact.profile":"详细资料","contact.familyEyebrow":"家庭关系","contact.notesEyebrow":"业务备注","contact.type":"联系人类型","contact.contactStatus":"联络状态","contact.communicationLevel":"客户沟通级别","contact.notes":"联系人备注","contact.notesEmpty":"尚未填写联系人备注。","contact.households":"所属家庭","contact.noHouseholds":"尚未关联家庭；可在家庭资料中添加成员关系。",
  "contact.type.contact":"一般联系人","contact.type.parent":"家长","contact.type.student":"学生","contact.type.school_staff":"学校员工","contact.type.payer":"付款人",
  "contact.status.new":"新联系人","contact.status.attempting":"尝试联络","contact.status.connected":"已建立联络","contact.status.follow_up":"持续跟进","contact.status.dormant":"暂时沉寂",
  "contact.communication.level1":"第 1 级 · 已取得联系方式","contact.communication.level2":"第 2 级 · 正式场景外交流","contact.communication.level3":"第 3 级 · 建立可信业务语境","contact.communication.level4":"第 4 级 · 愿意倡导／引荐",
  "admin.teams.leads":"团队负责人（可多选）","admin.teams.multiLeadHelp":"同一员工可领导多个团队；每个被选中的负责人也会成为该团队成员。","admin.teams.leadBadge":"负责人","admin.teams.unassigned":"未分配团队","admin.teams.adjustMemberships":"调整归属团队","admin.teams.adjustFor":"调整 {name} 的归属团队","admin.teams.multiMembershipHelp":"员工和负责人都可同时属于多个团队。负责人身份请在团队编辑中维护。","admin.teams.assignmentsSaved":"员工归属团队已更新。","admin.teams.assignmentsFailed":"无法更新员工归属团队。","admin.teams.myTeams":"我的团队","admin.teams.requestHelp":"可申请加入其他团队；管理员审核或直接调整后生效。","admin.teams.requestJoin":"申请加入","admin.teams.requestFailed":"团队加入申请未能提交。","admin.teams.membershipsLoadFailed":"无法读取团队归属。","admin.teams.membership.active":"已加入","admin.teams.membership.pending":"待审批",
};

export const enV390:Messages={
  "products.introduction":"Product introduction","products.introductionZh":"Detailed introduction (Chinese)","products.introductionEn":"Detailed introduction (English)","products.introductionEmpty":"No product introduction has been added.","products.purchasers":"Customers who purchased this product","products.noPurchasers":"No customer purchase records yet.",
  "contact.profileEyebrow":"CONTACT PROFILE","contact.profile":"Detailed profile","contact.familyEyebrow":"FAMILY LINKS","contact.notesEyebrow":"BUSINESS NOTES","contact.type":"Contact type","contact.contactStatus":"Contact status","contact.communicationLevel":"Customer communication level","contact.notes":"Contact notes","contact.notesEmpty":"No contact notes have been added.","contact.households":"Linked households","contact.noHouseholds":"No household is linked. Add the member relationship from the household record.",
  "contact.type.contact":"General contact","contact.type.parent":"Parent","contact.type.student":"Student","contact.type.school_staff":"School staff","contact.type.payer":"Payer",
  "contact.status.new":"New contact","contact.status.attempting":"Contact attempt","contact.status.connected":"Connected","contact.status.follow_up":"Follow-up","contact.status.dormant":"Dormant",
  "contact.communication.level1":"Level 1 · Contact details obtained","contact.communication.level2":"Level 2 · Informal business interaction","contact.communication.level3":"Level 3 · Trusted business context","contact.communication.level4":"Level 4 · Willing to advocate or introduce",
  "admin.teams.leads":"Team leads (multiple allowed)","admin.teams.multiLeadHelp":"A staff member may lead several teams. Every selected lead is also an active member of this team.","admin.teams.leadBadge":"Lead","admin.teams.unassigned":"No team assigned","admin.teams.adjustMemberships":"Adjust team memberships","admin.teams.adjustFor":"Adjust teams for {name}","admin.teams.multiMembershipHelp":"Staff and team leads may belong to several teams. Maintain lead responsibility from the team editor.","admin.teams.assignmentsSaved":"Staff team memberships updated.","admin.teams.assignmentsFailed":"Staff team memberships could not be updated.","admin.teams.myTeams":"My teams","admin.teams.requestHelp":"Request another team membership. It becomes active after an administrator reviews or assigns it.","admin.teams.requestJoin":"Request to join","admin.teams.requestFailed":"The team membership request could not be submitted.","admin.teams.membershipsLoadFailed":"Team memberships could not be loaded.","admin.teams.membership.active":"Active","admin.teams.membership.pending":"Pending approval",
};
