import { NextResponse } from "next/server";
import { z } from "zod";
import { apiRoute, parsePagination, requireApiAal2, requireApiRole, requireApiUser } from "@/lib/api";
import { financeOperation,loadFinanceOverview } from "@/lib/phase2-repository";
import { mutationIsTrusted } from "@/lib/request-security";
import { SupabaseRequestError } from "@/lib/supabase-server";
const createQuote=z.object({operation:z.literal("createQuote"),quote_no:z.string().trim().min(1).max(60),target_organization:z.uuid(),target_opportunity:z.uuid().nullable().optional(),target_product:z.uuid().nullable().optional(),target_bundle:z.uuid().nullable().optional(),target_exchange_rate:z.uuid().nullable().optional(),quote_currency:z.string().regex(/^[A-Z]{3}$/),quote_subtotal:z.number().nonnegative(),quote_discount:z.number().nonnegative(),valid_through:z.string().date(),terms_zh:z.string().max(2000).default(""),terms_en:z.string().max(2000).default("")}).refine(v=>v.quote_discount<=v.quote_subtotal,{path:["quote_discount"]}).refine(v=>Boolean(v.target_product)!==Boolean(v.target_bundle),{path:["target_product"]});
const submit=z.object({operation:z.literal("submitQuote"),target_quote:z.uuid(),business_reason:z.string().trim().min(3).max(500)});const accept=z.object({operation:z.literal("acceptQuote"),target_quote:z.uuid()});const convert=z.object({operation:z.literal("convertQuote"),target_quote:z.uuid(),contract_no:z.string().trim().min(1).max(60),period_start:z.string().date(),period_end:z.string().date()});const schedule=z.object({operation:z.literal("saveReceivables"),target_contract:z.uuid(),installments:z.array(z.object({dueDate:z.string().date(),amount:z.number().positive()})).min(1).max(24)});const payment=z.object({operation:z.literal("recordPayment"),target_contract:z.uuid(),target_schedule:z.uuid(),payment_amount:z.number().positive(),payment_currency:z.string().regex(/^[A-Z]{3}$/),payment_reference:z.string().trim().min(1).max(120),paid_on:z.string().datetime()});const refund=z.object({operation:z.literal("requestRefund"),target_payment:z.uuid(),refund_amount:z.number().positive(),refund_reason:z.string().trim().min(3).max(500)});const complete=z.object({operation:z.literal("completeRefund"),target_refund:z.uuid(),receipt:z.string().trim().min(1).max(200)});const schema=z.discriminatedUnion("operation",[createQuote,submit,accept,convert,schedule,payment,refund,complete]);
const fail=(error:unknown)=>error instanceof SupabaseRequestError?NextResponse.json({code:error.code},{status:error.status}):NextResponse.json({code:"FINANCE_OPERATION_FAILED"},{status:500});
async function get(request:Request){await requireApiUser();const url=new URL(request.url);const{page,pageSize}=parsePagination(url.searchParams,10);try{return NextResponse.json(await loadFinanceOverview({query:url.searchParams.get("q")??"",page,pageSize}));}catch(error){return fail(error);}}
async function post(request:Request){if(!mutationIsTrusted(request))return NextResponse.json({code:"UNTRUSTED_ORIGIN"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({code:"INVALID_FINANCE_INPUT",field:String(parsed.error.issues[0]?.path[0]??"form")},{status:400});if(["recordPayment","completeRefund"].includes(parsed.data.operation)){await requireApiRole("SUPER_ADMIN","ADMIN");await requireApiAal2();}else await requireApiRole("SUPER_ADMIN","ADMIN","SALES_DIRECTOR","SALES_MANAGER","SALES_SPECIALIST");try{return NextResponse.json({item:await financeOperation(parsed.data as unknown as Record<string,unknown>)});}catch(error){return fail(error);}}
export const GET=apiRoute(get,"FINANCE_LOAD_FAILED");
export const POST=apiRoute(post,"FINANCE_OPERATION_FAILED");
