main = "src/index.js"
compatibility_date = "2026-07-30"
workers_dev = false
keep_vars = true

[[routes]]
pattern = "mail-api.ewaya.com"
custom_domain = true

[vars]
EMAIL_FROM = "Lumina CRM <notifications@notify.ewaya.com>"
CRM_APP_URL = "https://crm.ewaya.com"
LUMINA_BRAND_NAME = "Lumina Education CRM"
