import crypto from "node:crypto";

const required=["NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"];
const missing=required.filter(key=>!process.env[key]);if(missing.length)throw new Error(`Missing smoke variables: ${missing.join(", ")}`);
const base=process.env.NEXT_PUBLIC_SUPABASE_URL.replace(/\/$/,"");const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;const service=process.env.SUPABASE_SERVICE_ROLE_KEY;const suffix=Date.now().toString(36);const email=`phase2-${suffix}@example.invalid`;const password=`P2!${crypto.randomBytes(18).toString("base64url")}aA1`;
const serviceHeaders={apikey:service,authorization:`Bearer ${service}`,"content-type":"application/json"};let userId="",token="",organizationId="",contactId="",productId="",quoteId="",batchId="",appointmentId="";const approvals=[];
async function request(path,{method="GET",body,serviceRole=false,headers={}}={}){const userHeaders={apikey:anon,"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})};const response=await fetch(`${base}${path}`,{method,headers:{...(serviceRole?serviceHeaders:userHeaders),...headers},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(`${method} ${path} failed (${response.status}: ${result?.message??result?.msg??result?.error_description??result?.error_code??result?.code??"unknown"})`);return result;}
async function rpc(name,body){return request(`/rest/v1/rpc/${name}`,{method:"POST",body});}
try{
  const created=await request("/auth/v1/admin/users",{method:"POST",serviceRole:true,body:{email,password,email_confirm:true,app_metadata:{role:"SALES_DIRECTOR",workspace_id:process.env.CRM_WORKSPACE_ID??"00000000-0000-4000-8000-000000000001"},user_metadata:{username:`phase2.${suffix}`,display_name_zh:"阶段测试",display_name_en:"Phase Two Test"}}});userId=created.id;
  const signed=await request("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password},headers:{apikey:anon},serviceRole:false});token=signed.access_token;
  const organizations=await request("/rest/v1/organizations?select=id",{method:"POST",body:{name_zh:`测试机构${suffix}`,name_en:`Test Organization ${suffix}`,city:"Taipei",status:"UNVERIFIED",owner_id:userId},headers:{Prefer:"return=representation"}});organizationId=organizations[0].id;
  const contacts=await request("/rest/v1/contacts?select=id",{method:"POST",body:{organization_id:organizationId,name_zh:"测试联系人",name_en:"Test Contact",email,status:"UNVERIFIED",owner_id:userId},headers:{Prefer:"return=representation"}});contactId=contacts[0].id;
  await rpc("save_contact_consent",{target_contact:contactId,target_channel:"EMAIL",target_purpose:"MARKETING",target_status:"GRANTED",consent_source:"SIGNED_FORM",evidence:"phase-two smoke",retained_until:null,quiet_start:null,quiet_end:null});
  await rpc("save_contact_consent",{target_contact:contactId,target_channel:"EMAIL",target_purpose:"EVENT",target_status:"GRANTED",consent_source:"MEETING_REQUEST",evidence:"phase-two smoke",retained_until:null,quiet_start:null,quiet_end:null});
  if(await rpc("contact_channel_allowed",{target_contact:contactId,target_channel:"EMAIL",target_purpose:"MARKETING"})!==true)throw new Error("Consent gate did not allow a granted record");
  const product=await rpc("create_product_with_price",{product_code:`P2-${suffix}`,product_name_zh:"阶段测试产品",product_name_en:"Phase Two Product",product_billing:"PROJECT",product_duration_zh:"一个项目周期",product_duration_en:"One project cycle",price_currency:"CNY",price_amount:100000});productId=product.id;
  const quote=await rpc("create_quote_v100",{quote_no:`Q-${suffix}`,target_organization:organizationId,target_opportunity:null,target_product:productId,target_bundle:null,target_exchange_rate:null,quote_currency:"CNY",quote_subtotal:100000,quote_discount:5000,valid_through:new Date(Date.now()+86400000*30).toISOString().slice(0,10),terms_zh:"测试条款",terms_en:"Test terms"});quoteId=quote.id;
  const submitted=await rpc("submit_quote",{target_quote:quoteId,business_reason:"Smoke-test discount approval"});if(submitted.status!=="PENDING_DISCOUNT_APPROVAL")throw new Error("Discount quote did not enter approval");approvals.push(submitted.discount_approval_id);
  const exportApproval=await rpc("request_marketing_contact_export",{export_channel:"EMAIL",business_reason:"Smoke-test consent-gated export"});approvals.push(exportApproval.id);
  const rows=[{nameZh:`导入${suffix}`,nameEn:`Imported ${suffix}`,email:`import-${suffix}@example.invalid`,phone:"",city:"",title:"Coordinator"}];const contentHash=crypto.createHash("sha256").update(JSON.stringify(rows)).digest("hex");const batch=await rpc("create_import_batch",{resource:"CONTACTS",filename:"phase2.csv",content_hash:contentHash,request_key:`smoke:${contentHash}`,mapping:{nameZh:"nameZh",nameEn:"nameEn",email:"email"},rows});batchId=batch.id;const repeated=await rpc("create_import_batch",{resource:"CONTACTS",filename:"phase2.csv",content_hash:contentHash,request_key:`smoke:${contentHash}`,mapping:{nameZh:"nameZh",nameEn:"nameEn",email:"email"},rows});if(repeated.id!==batchId)throw new Error("Import idempotency failed");const processed=await rpc("process_import_batch",{target_batch:batchId,batch_size:50});if(processed.status!=="COMPLETED")throw new Error("Import did not complete");const rolledBack=await rpc("rollback_import_batch",{target_batch:batchId});if(rolledBack.status!=="ROLLED_BACK")throw new Error("Import rollback failed");
  const starts=new Date(Date.now()+86400000*5);const appointment=await rpc("create_appointment_with_delivery",{title_zh:"客户回访",title_en:"Customer follow-up",event_type:"MEETING",relation_type:"ORGANIZATION",relation_id:organizationId,relation_label:"Smoke",starts:starts.toISOString(),ends:new Date(starts.getTime()+3600000).toISOString(),event_channel:"Teams",reminders:[60],attendees:[{contactId,email,name:"Test Contact",consentConfirmed:true}]});appointmentId=appointment.id;const deliveries=await request(`/rest/v1/calendar_deliveries?select=status&appointment_id=eq.${appointmentId}`);if(deliveries[0]?.status!=="QUEUED")throw new Error("Calendar invite was not queued");
  const timeline=await rpc("customer_timeline",{target_organization:organizationId,page_number:1,page_size:20,event_types:null});if(!timeline.items?.some(item=>item.type==="APPOINTMENT")||!timeline.items?.some(item=>item.type==="CONTACT"))throw new Error("Customer timeline is incomplete");
  await rpc("save_contact_consent",{target_contact:contactId,target_channel:"EMAIL",target_purpose:"MARKETING",target_status:"REVOKED",consent_source:"CONTACT_REQUEST",evidence:"phase-two smoke",retained_until:null,quiet_start:null,quiet_end:null});if(await rpc("contact_channel_allowed",{target_contact:contactId,target_channel:"EMAIL",target_purpose:"MARKETING"})!==false)throw new Error("Consent withdrawal did not block marketing");
  process.stdout.write("Phase-two business smoke passed: consent, approval, import rollback, calendar delivery, and customer timeline.\n");
}finally{
  if(appointmentId)await request(`/rest/v1/appointments?id=eq.${appointmentId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(quoteId)await request(`/rest/v1/quotes?id=eq.${quoteId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(productId)await request(`/rest/v1/products?id=eq.${productId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  for(const id of approvals.filter(Boolean))await request(`/rest/v1/approval_requests?id=eq.${id}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(batchId)await request(`/rest/v1/import_batches?id=eq.${batchId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(contactId)await request(`/rest/v1/contacts?id=eq.${contactId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(organizationId)await request(`/rest/v1/organizations?id=eq.${organizationId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
  if(userId)await request(`/auth/v1/admin/users/${userId}`,{method:"DELETE",serviceRole:true}).catch(()=>undefined);
}
