import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { createContractDraft,createContractRenewal,listContracts } from "@/lib/contract-repository";
import { mutationIsTrusted } from "@/lib/request-security";
import { SupabaseRequestError } from "@/lib/supabase-server";
const createSchema=z.object({operation:z.literal("create"),contractNumber:z.string().trim().min(2).max(80),organizationId:z.string().uuid(),productId:z.string().uuid().nullable().optional(),startDate:z.string().date(),endDate:z.string().date(),currency:z.string().regex(/^[A-Z]{3}$/),value:z.number().nonnegative(),relationshipLevel:z.number().int().min(1).max(4)}).refine(value=>value.endDate>=value.startDate,{path:["endDate"]});const renewalSchema=z.object({operation:z.literal("renewal"),id:z.string().uuid()});const mutationSchema=z.discriminatedUnion("operation",[createSchema,renewalSchema]);
export async function GET(request:Request){await requireUser();const url=new URL(request.url);try{return NextResponse.json(await listContracts({page:Number(url.searchParams.get("page")??1),pageSize:Number(url.searchParams.get("pageSize")??5),query:url.searchParams.get("query")??"",status:url.searchParams.get("status")??"all"}));}catch{return NextResponse.json({code:"CONTRACTS_LOAD_FAILED"},{status:500});}}
export async function POST(request:Request){if(!mutationIsTrusted(request))return NextResponse.json({code:"UNTRUSTED_ORIGIN"},{status:403});const parsed=mutationSchema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({code:"INVALID_INPUT",field:String(parsed.error.issues[0]?.path[0]??"form")},{status:400});try{await requireUser();const item=parsed.data.operation==="create"?await createContractDraft(parsed.data):await createContractRenewal(parsed.data.id);return NextResponse.json({item});}catch(error){return NextResponse.json({code:error instanceof SupabaseRequestError?error.code:"CONTRACT_OPERATION_FAILED"},{status:error instanceof SupabaseRequestError?error.status:500});}}
